QwikDev/qwik

README.md
Add a "made by Builder.io" at the bottom of the readme
=> Add a "made by Builder.io" at the bottom of the readme

README.md
=> chore: Add logo to readme

integration/README.md
I never heard of Bazel, & I suspect many if not most of the non-Angular non-mega-enterprise non-C/Java programmers have not either.
I had to do a double-take when I saw it was written in Java....
=> + Bazel link

README.md, cypress/integration/todo_spec.ts, integration/todo/server_index.tsx, src/core/render/jsx/attributes.ts, src/qwikloader.ts
=> fix(core): Correctly deal with user input

src/optimizer/core/src/collector.rs, src/optimizer/core/src/parse.rs, src/optimizer/core/src/snapshots/qwik_core__test__issue_117.snap, src/optimizer/core/src/test.rs, src/optimizer/core/src/transform.rs
=> fix: fix wrong js generation

src/optimizer/core/src/code_move.rs, src/optimizer/core/src/collector.rs, src/optimizer/core/src/parse.rs, src/optimizer/core/src/snapshots/qwik_core__test__issue_118.snap, src/optimizer/core/src/test.rs, src/optimizer/core/src/transform.rs
=> fix(optimizer): minification breaks imports and exports

src/bootloader-shared.ts, src/core/props/props-on.ts
=> feat: add qSymbols event

docs/functions/[[path]].ts, docs/src/entry.cloudflare.tsx, docs/src/layouts/builder/builder.tsx
=> docs: update headers

scripts/release.ts
=> chore: fix version in package build

docs/src/components/content-nav/content-nav.tsx, docs/src/components/footer/footer.tsx, docs/src/components/on-this-page/on-this-page.tsx, docs/src/components/sidebar/sidebar.tsx, docs/src/layouts/builder/builder.tsx, docs/src/layouts/docs/docs.tsx
=> docs: inline styles

docs/src/components/head/head.tsx
=> docs: SEO update

scripts/build.ts, scripts/submodule-optimizer.ts, src/optimizer/src/rollup/index.ts, src/optimizer/src/scripts.ts, starters/README.md, starters/apps/base/index.html
=> fix: inject qwikloader into dev client index

docs/src/components/head/head.tsx
=> docs: add site attribution

.github/workflows/ci.yml, CONTRIBUTING.md
=> chore: release workflow dist-tag options

docs/functions/[[path]].ts
=> docs: redirect homepage to the overview page

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/docs_suggestion.md, .github/ISSUE_TEMPLATE/feature_request.md, docs/src/components/header/header.tsx, docs/src/components/on-this-page/on-this-page.tsx, docs/src/components/svgs/edit-icon.tsx
=> docs: create an issue link

docs/pages/guide/overview.mdx
Update overview.mdx to be more value-oriented
Make it more clear to people **why** to use Qwik more than **what** Qwik is
=> Update overview.mdx to be more value-oriented

docs/pages/guide/overview.mdx
=> Minor grammar

docs/pages/guide/lazy-loading.mdx, docs/pages/guide/philosophy.mdx, docs/pages/guide/rendering.mdx, docs/qwest/src/vite/rehype.ts
=> docs: allow hrefs to sourc md files

docs/src/layouts/docs/docs.css
=> docs: table css

docs/src/components/header/header.css, docs/src/components/sidebar/sidebar.css, docs/src/components/sidebar/sidebar.tsx, docs/src/global.css, docs/src/layouts/docs/docs.css
=> docs: improve scroll css

docs/index.html, docs/src/components/content-nav/content-nav.css, docs/src/components/content-nav/content-nav.tsx, docs/src/layouts/docs/docs.css, starters/apps/base/index.html
=> docs: update mobile paginate btns

docs/pages/guide/components/host-element.mdx, docs/pages/guide/components/lite-components.mdx, docs/pages/guide/components/overview.mdx, docs/pages/guide/components/projection.mdx, docs/pages/guide/components/props.mdx, docs/pages/guide/components/qrl.mdx, docs/pages/guide/events/component.mdx, docs/pages/guide/events/on-window.mdx, docs/pages/guide/events/overview.mdx, docs/pages/guide/getting-started.mdx, docs/pages/guide/lazy-loading.mdx, docs/pages/guide/optimizer/lexical-scope.mdx, docs/pages/guide/optimizer/overview.mdx, docs/pages/guide/optimizer/rules.mdx, docs/pages/guide/qwikloader.mdx, docs/pages/guide/reactivity/overview.mdx, docs/pages/guide/rendering.mdx, docs/pages/guide/resumable.mdx, docs/pages/guide/server-side-rendering/overview.mdx
=> docs: update component syntax

README.md, docs/pages/guide/README.md, docs/src/components/footer/footer.tsx, docs/src/components/on-this-page/on-this-page.tsx, src/cli/README.md, starters/apps/base/README.md
Changed discord links to only use Welcome channel for better clarity
https://discord.gg/bNVSQmPzqy
=> update discrod to welcome channel

docs/src/components/head/head.tsx
Changed default Open Graph Image
=> docs: change og image

src/core/component/component.unit.tsx, src/core/render/render.unit.tsx, src/core/util/dom.unit.ts, src/server/api.md, src/server/document.ts, src/server/index.ts, src/server/types.ts, src/server/utils.unit.ts, src/testing/api.md, src/testing/document.ts, src/testing/document.unit.ts, src/testing/element-fixture.ts, src/testing/index.ts, src/testing/jsx.ts, src/testing/types.ts
=> refactor: server/testing qwik document

docs/functions/[[path]].ts
=> docs: add coep/coop headers for partytown

docs/pages/tutorial/basics.mdx, docs/pages/tutorial/introduction/basics/app/main.tsx, docs/pages/tutorial/introduction/basics/index.mdx, docs/pages/tutorial/introduction/lazy-loading/app/main.tsx, docs/pages/tutorial/introduction/lazy-loading/index.mdx, docs/pages/tutorial/reactivity/basics/app/main.tsx, docs/pages/tutorial/reactivity/basics/index.mdx, docs/qwest/src/runtime/page.ts, docs/src/layouts/tutorial/tutorial-menu.ts
=> docs: init tutorial content

src/core/object/q-object.ts
=> fix: do not wrap noSerialize() values

packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/render/notify-render.ts
=> fix: clear state.watchStaging

packages/docs/package.json, packages/docs/src/components/header/header.tsx, packages/qwik-city/src/vite/code-generation.ts, yarn.lock
=> docs: enable playground link

packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/props/props.ts, packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/render/render.public.ts, packages/qwik/src/core/render/render.unit.tsx, packages/qwik/src/core/use/use-context.ts, packages/qwik/src/core/use/use-subscriber.ts, packages/qwik/src/core/watch/watch.public.ts, packages/qwik/src/qwikloader.ts, packages/qwik/src/testing/expect-dom.unit.tsx, starters/apps/e2e/src/components/watch/watch.tsx, starters/e2e/e2e.spec.ts
=> feat: useCleanup()

packages/docs/pages/guide/components/props.mdx
No functional changes.
Add line break to improve props list readability. This is a docs-only change (though it changes a code sample).
N/A
=> Add line break to improve props list readability

packages/docs/pages/docs/components/hooks.mdx
The `interface User` and `function User` are repeated without any change in the same example.
=> Delete extra code in the example

packages/qwik/src/core/api.md, packages/qwik/src/core/index.ts, packages/qwik/src/core/object/q-object.ts
=> feat: add immutable api

packages/docs/src/components/repl/repl-tab-button.tsx, packages/docs/src/components/repl/repl.tsx, packages/docs/src/components/repl/types.ts, packages/qwik/src/core/render/notify-render.ts, starters/dev-server.ts
=> perf: little fixes to improve perf

scripts/cli.ts
=> fix: skip test apps in the CLI

packages/docs/src/components/header/header.tsx
=> fix: disable examples

packages/qwik/src/core/api.md, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/import/qrl-class.ts, packages/qwik/src/core/import/qrl.public.ts, packages/qwik/src/core/import/qrl.ts, packages/qwik/src/core/platform/types.ts, packages/qwik/src/optimizer/src/types.ts, packages/qwik/src/server/api.md, packages/qwik/src/server/platform.ts, packages/qwik/src/server/prefetch-strategy.ts, packages/qwik/src/server/render.ts, packages/qwik/src/testing/api.md, starters/dev-server.ts
=> fix: implement correct symbol mapper

package.json, packages/create-qwik/package.json, packages/docs/package.json, packages/docs/pages/docs/overview.mdx, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik-city/src/runtime/api.md, packages/qwik-city/src/runtime/page.ts, packages/qwik-city/src/runtime/types.ts, packages/qwik/package.json, packages/qwik/src/server/prefetch-strategy.ts, yarn.lock
=> perf: improve prefetching and immutable state

.github/workflows/ci.yml, package.json, packages/create-qwik/package.json, packages/docs/package.json, packages/docs/src/entry.ssr.tsx, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/qwikloader.ts, packages/qwik/src/server/api.md, packages/qwik/src/server/render.ts, packages/qwik/src/server/types.ts, packages/qwik/src/testing/api.md, starters/apps/base/.vscode/qwik.code-snippets, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/starter-builder/src/entry.ssr.tsx, starters/apps/starter-partytown/src/entry.ssr.tsx, starters/apps/starter/src/entry.ssr.tsx, starters/apps/todo/src/entry.ssr.tsx, yarn.lock
=> perf docs update

packages/docs/package.json, packages/qwik-city/package.json, packages/qwik-city/src/runtime/page.ts, starters/apps/qwik-city/package.json, yarn.lock
=> perf: dont cause rerender

packages/docs/pages/docs/getting-started.mdx, packages/docs/pages/docs/overview.mdx, packages/docs/public/banner.svg, packages/docs/tailwind.config.js
=> docs: improve docs

packages/docs/pages/examples/visibility/clock/root.tsx
=> chore(examples): fix typo

starters/apps/qwik-city/pages/index.mdx
=> docs: correct typos

packages/docs/src/pages/docs/components/hooks.mdx
Remove misleading comment from the useServerMount$ example
=> docs: remove misleading comment

packages/docs/package.json, packages/qwik-city/package.json, yarn.lock
=> chore: update deps docs

packages/docs/src/pages/docs/components/hooks.mdx
=> docs: fix wrong docs

package.json, packages/create-qwik/package.json, packages/docs/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, starters/apps/qwik-city/package.json, yarn.lock
=> fix: Fix qwik city deps

packages/qwik/src/core/component/component-ctx.ts, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/component/qrl-styles.ts, packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/use/use-core.ts, packages/qwik/src/core/use/use-store.public.ts, packages/qwik/src/core/watch/watch.public.ts, starters/apps/e2e/src/components/styles/child.css, starters/apps/e2e/src/components/styles/child2.css, starters/apps/e2e/src/components/styles/parent.css, starters/apps/e2e/src/components/styles/styles.tsx, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/e2e/src/root.tsx
=> fix: dont download serialized styles

packages/docs/package.json, packages/qwik-city/package.json, yarn.lock
=> chore: update deps

packages/docs/src/components/repl/worker/app-bundle-ssr.ts, packages/qwik/src/core/render/notify-render.ts, packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/optimizer/src/plugins/plugin.unit.ts, packages/qwik/src/optimizer/src/plugins/rollup.unit.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts
=> fix: mutation while rendering in server

packages/docs/package.json, packages/qwik-city/package.json, yarn.lock
=> chore: update docs 0.0.25

package.json, packages/create-qwik/package.json, packages/docs/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, packages/qwik/src/core/import/qrl.ts, packages/qwik/src/core/object/q-object.ts, yarn.lock
=> fix: noSerialize()

packages/docs/src/pages/docs/overview.mdx
A trivial typo.
_P.S.
I just stumbled upon this framework. Nice work!
Btw. it looks like the example from your front page isn't working. The `on$:click` handler should be replaced with `onClick`, I think._
=> trivial: typo

package.json, packages/eslint-plugin-qwik/file.tsx, packages/eslint-plugin-qwik/index.ts, packages/eslint-plugin-qwik/lib/validLexicalScope.ts, packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/tsconfig-tests.json, starters/features/eslint/.eslintrc.js, yarn.lock
=> feat: New eslint lexical scope

packages/docs/src/pages/docs/components/rendering.mdx
=> trivial: typos

packages/docs/src/pages/docs/components/events.mdx
Fixed a few typos as well as some of the code examples. Nothing of big importance, just a few variables.
=> fix typos and code examples

packages/docs/src/pages/docs/advanced/optimizer.mdx
Added link to serialization paragraph.
=> add link to serialization

packages/qwik/src/core/api.md, packages/qwik/src/core/index.ts, packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/render/notify-render.ts, packages/qwik/src/core/render/render-component.ts, packages/qwik/src/core/render/render.public.ts, packages/qwik/src/core/use/use-context.ts, starters/apps/e2e/src/components/context/context.tsx, starters/e2e/e2e.spec.ts
Fixes https://github.com/BuilderIO/qwik/issues/599
=> fix: content projection can inject contexts

packages/docs/package.json, packages/qwik-city/package.json, yarn.lock
=> chore: update docs 0.0.26

packages/docs/src/layouts/examples/examples.tsx
=> docs(examples): fix broken link

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json, packages/qwik/src/optimizer/core/src/package_json.rs, packages/qwik/src/optimizer/src/platform.ts, packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts, yarn.lock
vite plugin can build ssr, dev, client and prod builds with external deps
=> fix: fix external deps

packages/docs/src/pages/tutorial/introduction/listeners/solution/app.tsx, starters/apps/starter-partytown/src/components/app/app.tsx, starters/apps/todo-old.test/src/components/header/header.tsx, starters/apps/todo-old.test/src/components/item/item.tsx, starters/apps/todo/src/components/header/header.tsx, starters/apps/todo/src/components/item/item.tsx
=> fix: example use correct event names

packages/qwik/src/core/render/cursor.ts
=> fix(render): dont remove nodes in <head>

packages/docs/package.json, packages/qwik-city/package.json, packages/qwik-react/package.json, yarn.lock
=> chore: update versions

packages/docs/src/entry.cloudflare.tsx
=> fix: redirect old /guide URLs to new content

packages/docs/src/pages/docs/cheat-sheet.mdx
=> fix(docs): update state in counter example

packages/docs/src/pages/docs/cheat-sheet.mdx
=> Fix syntax errors for React example code

packages/docs/src/pages/examples/examples-menu.json, packages/docs/src/pages/examples/reactivity/auto-complete/app.tsx, packages/docs/src/pages/examples/reactivity/auto-complete/entry.server.tsx, packages/docs/src/pages/examples/reactivity/auto-complete/root.tsx
=> docs(example): add auto-complete

packages/docs/src/pages/docs/components/context.mdx
=> docs(context): fix Children template recursion

packages/docs/src/pages/examples/partial/hackernews-index/app.tsx
=> fixed typo

packages/docs/src/pages/examples/partial/hackernews-index/root.tsx
=> added conrespondant title

packages/qwik/src/optimizer/core/src/errors.rs, packages/qwik/src/optimizer/core/src/lib.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_capturing_fn_class.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_invalid_hook_expr1.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_invalid_references.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_missing_custom_inlined_functions.snap, packages/qwik/src/optimizer/core/src/transform.rs
=> fix: improve optimizer errors

packages/qwik/src/core/object/q-object.ts, starters/apps/e2e/src/components/render/render.tsx
=> fix: infinite loop in verifySerializable

packages/qwik/src/optimizer/src/plugins/vite.ts
=> fix(vite): handle global css correctly

packages/qwik/src/core/api.md, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/error/error.ts, packages/qwik/src/core/props/props.ts, packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/render/jsx/factory.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/render/render-component.ts, packages/qwik/src/core/render/render.unit.tsx, starters/apps/e2e/src/components/toggle/toggle.tsx
=> fix: rendering of root elements

packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_default_export.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_default_export_index.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/core/src/transform.rs
=> feat: better symbol names for default exports

packages/qwik/src/optimizer/src/plugins/plugin.ts
=> fix: vite transform .mjs and .cjs

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json, packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/render/jsx/slot.public.ts, packages/qwik/src/core/util/markers.ts, packages/qwik/src/testing/expect-dom.unit.tsx
=> fix: <html> auto projects

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-react/src/index.ts, packages/qwik-react/src/vite/index.ts, packages/qwik/package.json, packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts
=> fix: vite react plugin

packages/qwik/src/core/error/error.ts, packages/qwik/src/core/object/store.ts, starters/apps/base/gitignore
=> fix: pause container at runtime

packages/docs/src/pages/docs/components/hooks.mdx
according to see Miško#9885
https://discord.com/channels/842438759945601056/992449727994011759/992470886554812429
=> added docs about useMount$

packages/docs/src/pages/docs/cheat-sheet.mdx
update button-div tag in "button click handler"
=> Update button-div tag

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts, packages/qwik/src/core/api.md, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/render/render.public.ts, packages/qwik/src/core/render/render.unit.tsx, packages/qwik/src/core/util/log.ts, packages/qwik/src/server/render.ts, starters/apps/e2e/src/components/lexical-scope/lexicalScope.tsx, starters/e2e/e2e.spec.ts
=> feat: serialize promises

packages/qwik/src/core/api.md, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/render/notify-render.ts, packages/qwik/src/core/render/render-component.ts, packages/qwik/src/core/render/render.public.ts, packages/qwik/src/server/render.ts, starters/apps/e2e/src/entry.ssr.tsx
=> fix: first render state

packages/docs/src/pages/docs/advanced/prefetching.mdx
=> docs: correct typo

packages/qwik/src/core/api.md, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/render/notify-render.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-watch.ts, starters/apps/e2e/src/components/resource/resource.tsx, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/e2e/src/root.tsx, starters/e2e/e2e.spec.ts
=> fix: execution order of watches

packages/qwik/src/optimizer/cli/src/main.rs, packages/qwik/src/optimizer/core/benches/transform.rs, packages/qwik/src/optimizer/core/src/filter_exports.rs, packages/qwik/src/optimizer/core/src/lib.rs, packages/qwik/src/optimizer/core/src/parse.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_exports_unused.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_exports_used.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/src/optimizer.ts
=> feat: stripExports option in compiler

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json
=> chore: revert to 0.0.35

README.md
Suggestion to fine-tune the introductory paragraphs in the README.
n/a
=> docs: update introductory paragraph in README

packages/qwik/src/core/assert/assert.ts, packages/qwik/src/core/error/error.ts, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/props/props.ts, packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/render/notify-render.ts, packages/qwik/src/core/render/render-component.ts, packages/qwik/src/core/use/use-core.ts, packages/qwik/src/core/use/use-host-element.public.ts, packages/qwik/src/core/use/use-lexical-scope.public.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-watch.ts, packages/qwik/src/core/util/dom.ts
=> fix: improve asserts and errors

packages/docs/src/pages/tutorial/introduction/ssr/index.mdx
Editorial edit pass for SSR tutorial.
Suggested changes to SSR tutorial to strengthen the prose.
n/a
=> docs: SSR Tutorial - editorial pass

packages/docs/src/pages/tutorial/component/basic/index.mdx
=> docs: Basic Component tutorial - fix typos

packages/docs/src/pages/tutorial/component/binding/index.mdx
=> docs: Binding Expressions tutorial - refine text

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/buildtime/vite/plugin.ts, packages/qwik-city/package.json, packages/qwik-city/runtime/vite.config.ts, packages/qwik-react/package.json, packages/qwik-react/vite.config.ts, packages/qwik/package.json, packages/qwik/src/optimizer/src/optimizer.ts, packages/qwik/src/optimizer/src/platform.ts, packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/server/platform.ts, scripts/qwik-city.ts, starters/apps/qwik-city/package.json, starters/apps/qwik-city/src/components/body/body.tsx, starters/apps/qwik-city/src/root.tsx, yarn.lock
=> fix: third party libs

packages/docs/src/pages/tutorial/component/composition/index.mdx
=> docs: Composing Components - edit pass

packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/app/routes/products/[id].tsx, packages/qwik/src/core/api.md, packages/qwik/src/core/index.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-watch.ts, starters/apps/e2e/src/components/resource/resource.tsx, starters/apps/e2e/src/components/resource/weather.tsx, tsconfig.json
=> refactor: rename <Async> to <Resource>

packages/docs/src/pages/docs/cheat/components.mdx
People copy pasting might have unnecessary errors with this typo.
=> Typo in useClientEffect

packages/docs/src/pages/tutorial/events/basic/index.mdx
I have a few questions about some of the content. See in-line for details.
n/a
=> docs: Event Listeners - edit pass

packages/docs/src/pages/qwikcity/content/component.mdx
- Fixes a sentence that I felt was clunky.
- Changes the reference to other_component to sub_component as mentioned early in the Doc.
=> Fix reference to _sub-component file. Fix some clunky language.

packages/docs/src/pages/qwikcity/middleware/overview.mdx
Adds the Netlify middleware to the Qwik City middleware list.
=> Add Netlify Middleware link

packages/docs/src/pages/tutorial/events/synchronous/index.mdx
=> docs: Synchronous Event Processing - edit pass

packages/docs/src/pages/tutorial/events/programmatic/index.mdx
=> doc: Programmatic Listeners - edit pass

packages/docs/package.json, packages/qwik-city/middleware/request-handler/utils.ts, packages/qwik-city/package.json, packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/app/components/breadcrumbs/breadcrumbs.tsx, packages/qwik-city/runtime/src/app/components/menu/menu.tsx, packages/qwik-city/runtime/src/app/routes/index.tsx, packages/qwik-city/runtime/src/index.ts, packages/qwik-city/runtime/src/library/content.ts, packages/qwik-city/runtime/src/library/contexts.ts, packages/qwik-city/runtime/src/library/html.tsx, packages/qwik-city/runtime/src/library/link.tsx, packages/qwik-city/runtime/src/library/types.ts, packages/qwik-city/runtime/src/library/use-functions.ts, packages/qwik-react/package.json, packages/qwik/src/core/api.md, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/use/use-store.public.ts, packages/qwik/src/server/api.md, packages/qwik/src/server/render.ts, packages/qwik/src/server/types.ts, packages/qwik/src/testing/api.md, starters/apps/base/package.json, starters/apps/e2e/src/components/treeshaking/treeshaking.tsx, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/qwik-city/package.json, starters/apps/qwik-city/src/components/menu/menu.tsx, tsconfig.json, yarn.lock
=> feat: advanced data treeshaking

packages/qwik/src/core/api.md, packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/render/jsx/host.public.ts, packages/qwik/src/core/render/render.ts, packages/qwik/src/core/render/render.unit.tsx
=> fix(render): render projected <Host> attributes

packages/qwik/src/core/render/cursor.ts, packages/qwik/src/core/render/render.public.ts
=> fix: <head> rerendering

packages/qwik/src/core/props/props.ts, packages/qwik/src/core/render/render.unit.tsx, packages/qwik/src/core/use/use-on.ts, packages/qwik/src/qwikloader.ts, starters/apps/e2e/src/components/broadcast-events/broadcast-event.tsx
=> fix: capture from document and window independently

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json
=> Release 0.0.38

packages/docs/src/pages/tutorial/props/basic/index.mdx
=> docs: Component Props - edit pass

packages/qwik/src/optimizer/src/plugins/vite.ts
Adds the fix Manu figured out on stream with Ryan.
Closes: #808
=> Add the fetch fix Manu figured out on stream with Ryan

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/object/serializers.ts, packages/qwik/src/core/object/store.unit.tsx, starters/apps/e2e/src/components/lexical-scope/lexicalScope.tsx, starters/e2e/e2e.spec.ts
Add serialization for:
- URL
- Date
- RegExpr
=> feat: add more serializers

packages/qwik/src/core/api.md, packages/qwik/src/core/index.ts
=> fix: expose PropFnInterface

CONTRIBUTING.md, package.json, packages/qwik/src/optimizer/src/plugins/plugin.unit.ts, packages/qwik/src/optimizer/src/plugins/rollup.unit.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts, packages/qwik/src/testing/util.ts, tsm.cjs, yarn.lock
Add prerequisites on Windows to CONTRIBUTING.md, and fix tests on Windows
Build & test the framework on Windows machines (#794)
=> Windows support

packages/qwik-city/buildtime/build.ts, packages/qwik-city/buildtime/routing/resolve-source-file.ts, packages/qwik-city/buildtime/routing/source-file.unit.ts, packages/qwik-city/buildtime/routing/walk-routes-dir.ts, packages/qwik-city/buildtime/vite/dev-server.ts, packages/qwik-city/buildtime/vite/plugin.ts, packages/qwik-city/middleware/cloudflare-pages/api.md, packages/qwik-city/middleware/cloudflare-pages/index.ts, packages/qwik-city/middleware/express/api.md, packages/qwik-city/middleware/express/index.ts, packages/qwik-city/middleware/netlify-edge/api.md, packages/qwik-city/middleware/netlify-edge/index.ts, packages/qwik-city/middleware/request-handler/request-handler.ts, packages/qwik-city/middleware/request-handler/types.ts, packages/qwik-city/middleware/request-handler/user-response.ts, packages/qwik-city/package.json, packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/app/components/content-nav/content-nav.css, packages/qwik-city/runtime/src/app/components/content-nav/content-nav.tsx, packages/qwik-city/runtime/src/app/routes/docs/_layout!/index.tsx, packages/qwik-city/runtime/src/app/routes/products/[id].tsx, packages/qwik-city/runtime/src/entry.express.tsx, packages/qwik-city/runtime/src/library/types.ts, scripts/qwik-city.ts
- Removed need for `@qwik-city-plan` import
- Refactored express middleware
- Added `setRenderBlocking()` option to reques event
=> fix: qwik-city build plan

packages/docs/src/routes/tutorial/store/no-serialize/index.mdx
Co-Authored-By: Craig Shoemaker <craig@craigshoemaker.net>
=> docs: Non-serializable Properties

packages/docs/src/routes/tutorial/props/mutable/index.mdx
Co-Authored-By: Craig Shoemaker <craig@craigshoemaker.net>
=> docs: Mutable props

packages/docs/src/routes/docs/cheat/serialization.mdx
Co-Authored-By: David Zearing <dzearing@microsoft.com>
=> docs: fix serialization.mdx typos

packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/util/types.ts, starters/apps/e2e/src/components/lexical-scope/lexicalScope.tsx, starters/e2e/e2e.spec.ts
=> fix(runtime): serialize null prototype objects

packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/render/types.ts, packages/qwik/src/core/use/use-context.ts, starters/apps/e2e/src/components/slot/slot.tsx, starters/e2e/e2e.spec.ts
=> fix: streaming render fixes

packages/qwik/src/core/api.md, packages/qwik/src/core/component/qrl-styles.ts, packages/qwik/src/core/index.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/props/props-on.ts, packages/qwik/src/core/props/props.ts, packages/qwik/src/core/render/container.ts, packages/qwik/src/core/render/dom/render-dom.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/jsx/host.public.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/use/use-core.ts, packages/qwik/src/core/use/use-styles.ts, packages/qwik/src/core/util/markers.ts, starters/apps/e2e/src/components/styles/styles.tsx
=> fix: scoped styles

packages/docs/src/components/body/body.tsx, packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/app/components/body/body.tsx, packages/qwik-city/runtime/src/index.ts, packages/qwik-city/runtime/src/library/router-outlet.ts, starters/apps/qwik-city/src/components/body/body.tsx
=> refactor: qwik-city rename Content to RouterOutlet

packages/docs/src/routes/qwikcity/endpoint/data.mdx, packages/docs/src/routes/qwikcity/endpoint/modify.mdx, packages/docs/src/routes/qwikcity/endpoint/non-200.mdx
- Updates the Qwik City Docs endpoint examples to the correct return types. 
- Updates examples to use response status and headers
=> Docs: Update Qwik City endpoint examples

packages/docs/src/routes/docs/cheat-sheet.mdx
No need for the context in the change background color example
=> docs: Update cheat-sheet.mdx

starters/apps/qwik-city/src/routes/api/[org]/[user].json/index.ts, starters/apps/qwik-city/src/routes/api/data.json.ts, starters/apps/qwik-city/src/routes/products/[id].tsx
Removes os and process calls in the Qwik City starter that are causing build errors.
Closes: #686
=> Remove node apis from Qwik City starter

packages/qwik-city/buildtime/routing/sort-routes.ts, packages/qwik-city/buildtime/routing/sort-routes.unit.ts
=> fix: route sorting

package.json, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/component/component.unit.tsx, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/effect-client/effect-client.tsx, starters/apps/e2e/src/components/slot/slot.tsx, starters/apps/e2e/src/components/two-listeners/twolisteners.tsx
=> fix(host): Set host to `<q:host>` and `display: contents`

packages/docs/src/routes/docs/advanced/custom-build-dir.mdx
Solving so many beta-tester issues to change build directory like #567 
- 1. Unique development workflow
- 2. Custom software architecture
=> Create custom build directory setting documentation

packages/docs/public/_redirects
=> docs: fix /docs/ redirect

packages/docs/src/routes/docs/overview.mdx
It is better to know what it means directly. In this case, it means the web.dev case study. (#407)
- 1. Docs readers can directly read the entire case studies
- 2. Docs readers can understand deeper what those metrics mean
=> link web.dave to its case study page

packages/docs/src/routes/docs/cheat/components.mdx
Removed unused imports, added space lines for dividing the code and used prop destructuring instead of using a props object
=> docs: Update components.mdx

packages/docs/vite.config.ts, packages/qwik-city/package.json, packages/qwik-city/runtime/src/library/html.tsx, packages/qwik-city/runtime/src/library/router-outlet.ts, packages/qwik-city/runtime/src/library/types.ts, packages/qwik/src/core/util/qdev.ts
=> fix: qtest in prod mode

packages/docs/src/routes/examples/[...id]!.tsx, packages/docs/tailwind.config.js
Fixes some broken paths after the upgrade.
Closes #966
=> Fix broken links and broken tailwind config

package.json, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/component/component.unit.tsx, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/effect-client/effect-client.tsx, starters/apps/e2e/src/components/slot/slot.tsx, starters/apps/e2e/src/components/two-listeners/twolisteners.tsx
=> Revert "fix(host): Set host to `<q:host>` and `display: contents`"

packages/qwik/src/core/api.md, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/props/props.ts
=> fix: `_useMutableProps`

packages/docs/src/routes/docs/concepts/progressive/index.mdx
Small fix to make a paragraph more cohesive
Co-Authored-By: Gil Fink <1590253+gilf@users.noreply.github.com>
=> docs: Update progressive.mdx

packages/docs/src/routes/docs/components/hooks/index.mdx
Co-Authored-By: Forresst <163352+forresst@users.noreply.github.com>
=> docs: replace obs function by track function

packages/docs/src/routes/docs/overview/index.mdx
Fix broken link in the intro docs
=> fix link to resumable concept docs

packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/index.ts
Related #968
Co-Authored-By: Félix Sanz <felixsanz@users.noreply.github.com>
=> feat: Expose types related to head function in endpoints

packages/qwik-city/middleware/request-handler/user-response.ts
fixed https://github.com/BuilderIO/qwik/issues/981
- 1. run website in netlify edge function mode, and need to read cookies
=> Patch req headers

packages/docs/src/routes/docs/components/projection/index.mdx
Fixes an inconsistency between code-result and fixes a typo
Nope
=> docs: Projection fixes typo

packages/docs/src/routes/playground/playground.css, packages/docs/src/routes/qwikcity/middleware/netlify-edge/index.mdx, packages/docs/src/routes/qwikcity/middleware/overview/index.mdx, packages/docs/src/routes/tutorial/tutorial.css, starters/servers/netlify-edge/README.md, starters/servers/netlify-edge/netlify.toml, starters/servers/netlify-edge/package.json
add setup guide for netlify middleware
- 1. maybe someone want to know how to add middleware or migrate from others
=> Docs netlify

packages/docs/src/routes/docs/components/rendering/index.mdx
Rendering: a few presentation improvements
Nope
=> docs: Rendering, a few presentation improvements

packages/docs/src/routes/qwikcity/layout/named/index.mdx, packages/docs/src/routes/qwikcity/layout/nested/index.mdx, packages/docs/src/routes/qwikcity/layout/overview/index.mdx, packages/docs/src/routes/qwikcity/layout/top/index.mdx
=> Docs: Layout fixups

packages/docs/src/routes/qwikcity/middleware/overview/index.mdx
=> Docs: Middleware fixups

packages/qwik-city/middleware/request-handler/endpoint-handler.ts, packages/qwik/src/core/api.md, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/server/api.md, packages/qwik/src/server/render.ts, packages/qwik/src/server/types.ts
=> feat: better streaming strategy

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, starters/apps/qwik-city/package.json, yarn.lock
=> chore: release 0.0.100

packages/qwik-city/package.json, starters/apps/qwik-city/package.json, starters/apps/qwik-city/src/components/footer/footer.tsx
=> release qwik-city

README.md
=> docs: Update README.md - Fix broken links

packages/qwik/src/core/api.md, packages/qwik/src/core/import/qrl-class.ts, packages/qwik/src/core/import/qrl.ts, packages/qwik/src/core/import/qrl.unit.ts, packages/qwik/src/core/object/serializers.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/render/dom/render-dom.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/use/use-core.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-watch.ts, starters/apps/e2e/src/components/lexical-scope/lexicalScope.tsx, starters/apps/e2e/src/components/resource/resource-serialization.tsx, starters/apps/e2e/src/components/resource/resource.tsx, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/e2e/src/root.tsx, starters/dev-server.ts, starters/e2e/e2e.spec.ts
=> fix: properly serialize resources

packages/qwik/src/core/api.md, packages/qwik/src/core/render/dom/render.public.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/server/api.md, packages/qwik/src/server/render.ts, packages/qwik/src/server/types.ts
=> feat: containerAttributes

packages/qwik/src/core/platform/platform.ts, packages/qwik/src/core/render/dom/notify-render.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-watch.ts, packages/qwik/src/core/util/qdev.ts, scripts/submodule-core.ts, starters/apps/e2e/src/components/effect-client/effect-client.tsx, starters/e2e/e2e.spec.ts
Fixes https://github.com/BuilderIO/qwik/issues/1056
=> fix: useClientEffect() runs in client-side mounted cmps

packages/docs/src/routes/docs/components/hooks/index.mdx, packages/docs/src/routes/tutorial/reactivity/explicit/problem/app.tsx, starters/apps/base/.vscode/qwik.code-snippets
=> docs: clarify useEffect usage a bit that can watch

packages/qwik/src/core/render/dom/notify-render.ts, packages/qwik/src/core/render/dom/render.public.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/render/types.ts
Fixes https://github.com/BuilderIO/qwik/issues/1093
=> fix: root styles rendering

packages/docs/src/routes/qwikcity/middleware/cloudflare-pages/index.mdx, starters/servers/cloudflare-pages/functions/[[path]].ts, starters/servers/cloudflare-pages/src/entry.cloudflare.tsx
=> fix: cloudflare pages starter

packages/qwik/src/core/style/scoped-stylesheet.ts, packages/qwik/src/core/style/scoped-stylesheet.unit.ts
=> fix(css): correctly process vendor prefix and animation

packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/broadcast-events/broadcast-event.tsx, starters/apps/e2e/src/components/ref/ref.tsx, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/e2e/src/root.tsx, starters/e2e/e2e.spec.ts
=> fix: useOn() on client bootstrapping

packages/docs/algolia.json, packages/docs/src/routes/docs/docs.css, packages/docs/src/routes/docs/layout!.tsx, packages/docs/src/routes/examples/[...id]/index!.tsx, packages/docs/src/routes/qwikcity/layout!.tsx, packages/docs/src/routes/tutorial/layout!.tsx
=> fix: improve seo layout

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json, packages/qwik/src/core/component/component.unit.tsx, packages/qwik/src/core/import/qrl.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/object/store.unit.tsx, packages/qwik/src/core/render/dom/render.public.ts, packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/util/qdev.ts, packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/server/render.ts, packages/qwik/src/testing/element-fixture.ts, scripts/submodule-core.ts, starters/dev-server.ts, tsm.cjs, yarn.lock
=> fix: qDev in prod build

packages/docs/src/routes/index.tsx, packages/docs/src/routes/qwikcity/routing/data/index.mdx, packages/docs/src/routes/qwikcity/routing/error-responses/index.mdx, packages/docs/src/routes/tutorial/introduction/resource/index.mdx, packages/docs/src/routes/tutorial/introduction/resource/problem/app.tsx, packages/docs/src/routes/tutorial/introduction/resource/solution/app.tsx, packages/docs/src/routes/tutorial/reactivity/resource/index.mdx, packages/docs/src/routes/tutorial/reactivity/resource/problem/app.tsx, packages/docs/src/routes/tutorial/reactivity/resource/solution/app.tsx, packages/qwik-city/runtime/src/app/routes/blog/[...slug]/index.tsx, packages/qwik-city/runtime/src/app/routes/products/[id]/index.tsx, packages/qwik/src/core/api.md, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/use/use-resource.ts, starters/apps/e2e/src/components/resource/resource-serialization.tsx, starters/apps/e2e/src/components/resource/resource.tsx, starters/apps/e2e/src/components/resource/weather.tsx, starters/apps/e2e/src/components/streaming/streaming.tsx, starters/apps/qwik-city/src/routes/blog/[...slug]/index.tsx, starters/apps/qwik-city/src/routes/products/[id]/index.tsx
=> refactor(resource): rename prop to value

packages/docs/package.json, yarn.lock
=> chore: update qwik

packages/docs/package.json, yarn.lock
=> chore: update docs

packages/docs/package.json, packages/qwik-city/package.json, yarn.lock
=> chore: update docs to latest qwikcity

packages/docs/src/routes/docs/cheat-sheet/index.mdx
I think you have mistaken jsx with template strings:)
=> docs: remove unnecessary $ signs

packages/docs/package.json, packages/docs/src/routes/docs/docs.css
=> fix(docs): h1 anchoring

packages/qwik-city/buildtime/vite/dev-server.ts, packages/qwik-city/buildtime/vite/plugin.ts, packages/qwik-city/middleware/request-handler/user-response.ts, packages/qwik-city/middleware/request-handler/user-response.unit.ts
=> fix: dev.ssr 404 handling

packages/docs/src/routes/docs/components/hooks/index.mdx
=> Update 1 line of wording in Docs for clarity -> Component API -> Hooks -> useClientEffect$

packages/docs/src/routes/docs/cheat/serialization/index.mdx
then of scope is the end of the serialization boundary (found when reading docs)
correct docs
=> Doc: fix comment annotating serialization boundaries

packages/qwik-city/package.json, packages/qwik-city/runtime/src/library/router-outlet-component.ts, packages/qwik-react/src/react/qwikify.tsx, packages/qwik/src/core/api.md, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/component/component.unit.tsx, packages/qwik/src/core/index.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/props/props-on.ts, packages/qwik/src/core/props/props.ts, packages/qwik/src/core/render/dom/render-dom.ts, packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/jsx/host.public.ts, packages/qwik/src/core/render/jsx/slot.public.ts, packages/qwik/src/core/render/jsx/utils.public.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/use/use-on.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-sequential-scope.ts, packages/qwik/src/core/use/use-watch.ts, packages/qwik/src/qwikloader.ts, packages/qwik/src/testing/element-fixture.ts, starters/apps/e2e/src/components/render/render.tsx, starters/apps/e2e/src/components/streaming/streaming.tsx, starters/apps/qwik-city/package.json, starters/e2e/e2e.spec.ts
=> feat: <SSRStream>

packages/docs/src/routes/docs/components/lite-components/index.mdx
Fixed a sentence in the lite component doc.
=> updated lite component doc

packages/docs/package.json, packages/docs/src/routes/index.tsx, packages/qwik/src/core/api.md, packages/qwik/src/core/render/jsx/types/jsx-generated.ts, yarn.lock
=> feat(docs): integrate Qwik SDK to homepage using `?render=sdk`

packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/resource/resource.tsx, starters/apps/e2e/src/components/styles/child.css, starters/apps/e2e/src/components/styles/child2.css, starters/apps/e2e/src/components/styles/parent.css, starters/apps/e2e/src/components/styles/styles.tsx, starters/dev-server.ts, starters/e2e/e2e.spec.ts
Fixes https://github.com/BuilderIO/qwik/issues/1229
=> fix: fix className rendering

packages/qwik/src/core/import/qrl-class.ts, packages/qwik/src/optimizer/cli/src/main.rs, packages/qwik/src/optimizer/core/src/entry_strategy.rs, packages/qwik/src/optimizer/core/src/lib.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_manual_chunks.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/core/src/transform.rs, packages/qwik/src/optimizer/src/api.md, packages/qwik/src/optimizer/src/index.ts, packages/qwik/src/optimizer/src/optimizer.ts, packages/qwik/src/optimizer/src/types.ts, packages/qwik/src/qwikloader.ts
=> perf: docs perf of algolia

packages/docs/src/components/footer/footer.css, packages/docs/src/components/footer/footer.tsx
Update docs site footer: Use Qwik accounts, backlink to Builder on Builder logo, add a max width for large screens, add Discord link
To spark joy
- [n/a] I have made corresponding changes to the documentation
- [n/a] Added new tests to cover the fix / functionality
=> chore: update docs site footer

packages/qwik-city/middleware/request-handler/request-handler.ts, packages/qwik-city/middleware/request-handler/types.ts, packages/qwik-city/middleware/request-handler/user-response.ts
=> fix: propagate aborted status to the middlware

packages/docs/public/robots.txt, packages/docs/src/components/footer/footer.tsx, packages/docs/src/components/header/header.tsx, packages/docs/src/components/sidebar/sidebar.tsx, packages/docs/src/global.css, packages/docs/src/root.tsx, packages/docs/vite.config.ts
=> perf: docs

packages/docs/src/components/footer/footer.tsx
=> chore: improve docs footer CSS for mobile

packages/qwik/src/core/props/props.ts, packages/qwik/src/optimizer/src/plugins/vite-server.ts, packages/qwik/src/optimizer/src/plugins/vite.ts
=> chore: add ssr dev logs

packages/create-qwik/create-interactive.ts, packages/docs/src/components/header/header.css, packages/qwik/src/cli/types.ts, packages/qwik/src/cli/utils/utils.ts
=> Pr qwik node version

packages/docs/src/routes/tutorial/hooks/use-cleanup/index.mdx, packages/docs/src/routes/tutorial/hooks/use-client-effect/index.mdx, packages/docs/src/routes/tutorial/qrl/data/index.mdx, packages/docs/src/routes/tutorial/style/scoped/solution/app.tsx
=> fix: Fixed some tutorial typos

packages/docs/src/components/sidebar/sidebar.tsx, packages/docs/src/routes/docs/faq/index.mdx, packages/docs/src/routes/docs/menu.md, packages/docs/src/routes/docs/think-qwik/index.mdx, packages/docs/src/routes/qwikcity/overview/index.mdx, packages/qwik-city/buildtime/markdown/menu.ts
=> docs: add FAQ

packages/docs/src/routes/docs/faq/index.mdx
=> docs: add more FAQs

packages/docs/src/routes/qwikcity/prefetching/overview/index.mdx
=> docs: fix typos

packages/docs/src/routes/qwikcity/prefetching/service-worker-prefetching/index.mdx
Another typo fix and grammar update to prefetch docs
=> docs: typos and grammar

packages/qwik/src/core/import/qrl-class.ts, packages/qwik/src/core/object/q-object.ts, starters/apps/e2e/src/components/styles/styles.tsx, starters/e2e/e2e.spec.ts
=> fix: crash when empty style

packages/qwik/src/optimizer/core/src/collector.rs, packages/qwik/src/optimizer/core/src/parse.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_ts_enums.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_ts_enums_issue_1341.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_ts_enums_no_transpile.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/core/src/transform.rs
=> fix: optimizer with enums

packages/docs/src/routes/docs/concepts/reactivity/index.mdx
=> docs: fixed typo

packages/docs/src/routes/docs/faq/index.mdx
=> Fixed typos

packages/docs/src/routes/tutorial/reactivity/explicit/problem/app.tsx, packages/docs/src/routes/tutorial/reactivity/resource/index.mdx, packages/docs/src/routes/tutorial/reactivity/template/problem/app.tsx
- added the Type for the Implicit template updates example under the Reactivity tutorial.
- also fixed a typo in the tutorial
- [ n/a ] I have made corresponding changes to the documentation
- [ n/a ] Added new tests to cover the fix / functionality
=> tutorial: Add type to useStore and fix typo

starters/features/qwik-react/src/routes/react/index.tsx
=> fix(qwik-react): add `client:visible` to the starter

packages/docs/src/routes/docs/faq/index.mdx
=> fix typo (splitted -> split) in FAQ

packages/docs/src/routes/qwikcity/overview/index.mdx
The title does not match the content
Nope
=> docs: improve title Quick City Overview

packages/docs/src/routes/tutorial/component/basic/index.mdx
=> Clarify tutorial

.gitignore, starters/apps/base/README.md, starters/apps/basic/src/components/header/header.css
Small updates to the starter/apps/base and project level .gitignore.
There was some grammatical errors in the starter readme, also an undeclared .CSS variable being used.
Added .idea to the project level .gitignore for contributors using webstorm or other JB IDEs.
=> Starter basic updates

packages/docs/src/routes/qwikcity/overview/index.mdx
some typos and grammar
- [] Bug
fix some typos, improve grammar, add a link.
=> Improve documentation

packages/qwik/src/core/api.md, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/object/store.ts, packages/qwik/src/core/props/props.ts, packages/qwik/src/core/readme.md, packages/qwik/src/core/render/dom/notify-render.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/util/implicit_dollar.ts, packages/qwik/src/core/util/log.ts, packages/qwik/src/server/render.ts
=> docs: fix old API name in docs

packages/docs/src/routes/docs/cheat/serialization/index.mdx, packages/docs/src/routes/docs/faq/index.mdx
Fix a small typo that I found reading the documentation.
=> docs: fix typo

packages/docs/src/routes/docs/think-qwik/index.mdx
Change "left of" to "left off".
=> docs: fix minor typo

packages/qwik/src/core/import/qrl-class.ts, packages/qwik/src/core/props/props-on.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/ssr/render-ssr.ts
=> fix: add container to event QRLs

packages/docs/src/routes/docs/advanced/containers/index.mdx
=> fixed minor typos

starters/apps/basic/package.json
Fix confusion around Qwik City in the starters
Fix #1423
=> feat: Update basic starter description

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts, starters/apps/base/.vscode/extensions.json
=> feat(eslint): detect identifier mutations

packages/docs/src/routes/docs/cheat/qwik-react/index.mdx
- [ x ] Feature / enhancement
- [ y ] Bug
- [ y ] Docs / tests
fixed #1435
=> fix a small bug in debounced input example

packages/docs/src/routes/docs/advanced/optimizer/index.mdx, packages/docs/src/routes/docs/components/events/index.mdx
=> docs: fixed minor typos and grammar

packages/docs/package.json, yarn.lock
=> upgrade sdk-qwik

packages/docs/src/routes/docs/advanced/qrl/index.mdx
=> docs(qrl): fix typos

packages/docs/src/routes/docs/components/rendering/index.mdx
=> docs: minor changes

packages/docs/src/routes/qwikcity/overview/index.mdx
Docs
Change incorrect spelling: from **opiniated** to **opinionated** .
=> Docs: Fix spelling: ( from `opiniated` to `opinionated`)

packages/docs/src/routes/docs/cheat/qwik-react/index.mdx, packages/docs/src/routes/docs/components/state/index.mdx
=> docs: fixed typos and changed components names (Cheat Sheet)

packages/docs/src/routes/qwikcity/api/use-content/index.mdx, packages/docs/src/routes/qwikcity/api/use-location/index.mdx, packages/docs/src/routes/qwikcity/content/component/index.mdx, packages/docs/src/routes/qwikcity/content/menu/index.mdx, packages/docs/src/routes/qwikcity/routing/endpoints/index.mdx, packages/docs/src/routes/qwikcity/routing/overview/index.mdx
=> docs: corrected url paths

packages/docs/src/routes/media/index.tsx
=> fix: enable algolia crawling

packages/docs/src/routes/docs/concepts/reactivity/index.mdx
The code is missing a function headers for callbacks and that's both confusing and wrong
=> docs reactivity: add missing function definitions

packages/docs/src/routes/media/index.tsx
Adds a `youtube` helper function to generate a Media Entry.
=> Add youtube helper

packages/docs/src/routes/tutorial/component/inline/index.mdx, packages/docs/src/routes/tutorial/context/basic/problem/app.tsx, packages/docs/src/routes/tutorial/events/basic/index.mdx, packages/docs/src/routes/tutorial/events/programmatic/index.mdx, packages/docs/src/routes/tutorial/hooks/use-client-effect/index.mdx, packages/docs/src/routes/tutorial/props/closures/index.mdx, packages/docs/src/routes/tutorial/store/serialization/index.mdx, packages/docs/src/routes/tutorial/welcome/overview/index.md, packages/eslint-plugin-qwik/src/noUseAfterAwait.ts, packages/qwik/src/cli/utils/log.ts
=> Docs: Updated URLs, fixed typos and minor changes.

packages/docs/src/routes/docs/components/lifecycle/index.mdx, packages/docs/src/routes/docs/components/resource/index.mdx
… in the Resource docs.
Adds the hook rules documented in #652
=> docs: Hook rules

packages/docs/src/routes/docs/components/state/index.mdx
I've answered this question ~1000 times on Discord. Figured it was time to document recursive tracking for useStore :laughing:
=> docs: Recursion in UseStore

packages/docs/src/routes/tutorial/props/closures/index.mdx, packages/docs/src/routes/tutorial/props/closures/problem/app.tsx, packages/docs/src/routes/tutorial/props/closures/solution/app.tsx
Hello I was doing the tutorial and notice (imo) a typo between "hello" and "good-bye".
If it's done one purpose, i'll close the PR ^^
=> docs(closures): fix typo

packages/docs/src/routes/media/index.tsx
Added two Spanish Video
- [ x] Docs / tests
Added two videos Spanish
=> [docs] Added Spain Videos

packages/docs/src/routes/qwikcity/middleware/netlify-edge/index.mdx
=> docs: change middleware docs to be more clear

packages/qwik-city/middleware/node/api.md, packages/qwik-city/middleware/node/index.ts
BREAKING CHANGE: Typescript public interface changed
=> fix: typo in public interface

packages/docs/src/routes/qwikcity/data/redirects/index.mdx
Fix good status for 302 HTTP response status code
Nope
=> Docs: Redirects fix name status 302

packages/docs/src/routes/qwikcity/static-assets/index.mdx
=> docs: typo

packages/docs/vite.config.ts
fix #1421, fix #1438, fix #1565
Algolia search file was included in repl section in vite conf.
=> fix(vite.config.ts): fix code highlighting for docs

packages/docs/src/components/docsearch/doc-search.tsx, packages/docs/src/components/docsearch/result.tsx, packages/docs/src/components/docsearch/search-box.tsx, packages/docs/src/routes/playground/index!.tsx, packages/docs/src/routes/tutorial/events/document/problem/app.tsx, packages/docs/src/routes/tutorial/qrl/closures/problem/app.tsx, packages/docs/src/routes/tutorial/qrl/closures/solution/app.tsx, packages/qwik/src/core/api.md, packages/qwik/src/core/render/jsx/types/jsx-generated.ts, packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts, packages/qwik/src/core/render/jsx/types/jsx-qwik-elements.ts, packages/qwik/src/core/render/jsx/types/jsx-qwik-events.ts
Improve types - especially Event types
Fixes: https://github.com/BuilderIO/qwik/issues/1483
=> Event types

packages/docs/src/routes/docs/faq/index.mdx
Fix a typo in the following FAQ question :
> Why does Qwik use JSX? it it React under the hood?
- Fix typo
=> docs: fix typo in FAQ

starters/features/tailwind/package.json
Fix issue afeter execute `npm run qwik add tailwind` 
- [ x] Bug
Not found dependencies 
- [ x] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [ x] I have made corresponding changes to the documentation
- [ x] Added new tests to cover the fix / functionality
=> fix autoprefixer error

packages/qwik/src/core/object/q-object.ts, starters/apps/e2e/src/components/lexical-scope/lexicalScope.tsx
=> fix: freeze of stores

packages/qwik/src/core/object/serializers.ts, packages/qwik/src/core/render/container.ts, starters/apps/e2e/src/components/ref/ref.tsx
=> fix: track signals in useClientEffect()

packages/qwik/src/core/use/use-resource.ts
=> fix: resource pending in ssr

packages/docs/src/routes/docs/advanced/containers/index.mdx, packages/docs/src/routes/docs/advanced/optimizer/index.mdx, packages/docs/src/routes/docs/advanced/prefetching/index.mdx, packages/docs/src/routes/docs/components/resource/index.mdx, packages/docs/src/routes/docs/concepts/reactivity/index.mdx
=> corrected docs path urls

packages/docs/src/routes/docs/components/overview/index.mdx
=> docs: Added example link

packages/docs/src/routes/qwikcity/menu.md, packages/docs/src/routes/qwikcity/starters/partytown/index.mdx, packages/qwik/src/cli/add/run-add-interactive.ts, packages/qwik/src/cli/types.ts, packages/qwik/src/cli/utils/log.ts, packages/qwik/src/core/api.md, packages/qwik/src/core/use/use-ref.ts, starters/features/partytown/package.json, starters/features/tailwind/package.json
Added new section for explained the difference starters scripts
- [x ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [x ] I have made corresponding changes to the documentation
- [x ] Added new tests to cover the fix / functionality
=> Docs: add partytown starter doc

packages/docs/src/routes/qwikcity/starters/partytown/index.mdx
=> docs: fix typo and added export

packages/docs/src/routes/docs/components/projection/index.mdx, packages/docs/src/routes/docs/components/rendering/index.mdx, packages/docs/src/routes/docs/components/state/index.mdx, packages/docs/src/routes/docs/concepts/progressive/index.mdx, packages/docs/src/routes/docs/concepts/reactivity/index.mdx
=> docs: export components

packages/qwik/src/core/render/dom/signals.ts, packages/qwik/src/core/render/dom/virtual-element.ts, packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/attributes/attributes.tsx, starters/e2e/e2e.spec.ts
=> fix: svg attribute rendering

packages/qwik/src/core/component/component.public.ts, starters/apps/e2e/src/components/slot/slot.tsx, starters/e2e/e2e.spec.ts
=> fix(): project named slot components

packages/qwik/src/core/render/dom/operations.ts, packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/slot/slot.tsx, starters/e2e/e2e.spec.ts
=> fix: nested slot projection

packages/docs/src/routes/media/index.tsx
Added Qwik Core Training
- [x ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [x ] I have made corresponding changes to the documentation
- [x ] Added new tests to cover the fix / functionality
=> Qwik Core Developers Training added

packages/docs/src/routes/qwikcity/routing/route-parameters/index.mdx
=> docs: limit catch-all routes

packages/docs/src/routes/tutorial/introduction/resource/index.mdx
Fix Resource onError in onRejected
Nope
=> Docs: Fix Resource onError in onRejected

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json, yarn.lock
=> Release 0110

packages/qwik/src/core/api.md, packages/qwik/src/core/object/q-object.ts, packages/qwik/src/core/render/container.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: signals in lite components

packages/docs/src/repl/editor.tsx, packages/docs/src/repl/repl.tsx, packages/docs/src/routes/docs/cheat/qwik-react/index.mdx, packages/docs/src/routes/examples/[...id]/index!.tsx, packages/docs/src/routes/examples/apps/reactivity/auto-complete/app.tsx, packages/docs/src/routes/examples/apps/reactivity/watch/app.tsx, packages/docs/src/routes/playground/index!.tsx, packages/docs/src/routes/tutorial/hooks/use-watch/problem/app.tsx, packages/docs/src/routes/tutorial/hooks/use-watch/solution/app.tsx, packages/docs/src/routes/tutorial/introduction/resource/index.mdx, packages/docs/src/routes/tutorial/introduction/resource/problem/app.tsx, packages/docs/src/routes/tutorial/introduction/resource/solution/app.tsx, packages/docs/src/routes/tutorial/layout!.tsx, packages/docs/src/routes/tutorial/reactivity/explicit/solution/app.tsx, packages/docs/src/routes/tutorial/reactivity/resource/index.mdx, packages/docs/src/routes/tutorial/reactivity/resource/problem/app.tsx, packages/docs/src/routes/tutorial/reactivity/resource/solution/app.tsx
Update example usage of `track` to the new non-deprecated API.
So people will learn the new syntax
=> docs: update usage of `track` to new API

package.json, packages/qwik/src/core/render/dom/operations.ts, scripts/package-json.ts, scripts/qwik-city.ts, scripts/submodule-build.ts, scripts/submodule-qwikloader.ts, scripts/submodule-testing.ts, starters/apps/basic/src/components/router-head/router-head.tsx, starters/apps/documentation-site/src/components/router-head/router-head.tsx, starters/e2e/e2e.attributes.spec.ts, starters/e2e/e2e.context.spec.ts, starters/e2e/e2e.effect-client.spec.ts, starters/e2e/e2e.events.spec.ts, starters/e2e/e2e.factory.spec.ts, starters/e2e/e2e.lexical-scope.spec.ts, starters/e2e/e2e.mount.spec.ts, starters/e2e/e2e.ref.spec.ts, starters/e2e/e2e.render.spec.ts, starters/e2e/e2e.resource.spec.ts, starters/e2e/e2e.signals.spec.ts, starters/e2e/e2e.slot.spec.ts, starters/e2e/e2e.streaming.spec.ts, starters/e2e/e2e.style.spec.ts, starters/e2e/e2e.toggle.spec.ts, starters/e2e/e2e.watch.spec.ts, starters/e2e/todo-old.spec.ts, starters/e2e/todo.spec.ts, starters/playwright.config.ts, yarn.lock
=> chore: improve starters

packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/util/promises.ts, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> Fix async render

.prettierignore
Remove duplicate settings in .prettierignore
=> chore: Remove duplicate settings in .prettierignore

CONTRIBUTING.md
CodeflowApp is a friendly bot, which provides a one-click link that spins up the whole environment for pull requests and issues. No more context-switching or branch-checkouts, just a new browser tab with a full IDE and a dev server running.
1. Development in browser
2. Creating PR 
3. Reviewing PR
=> docs: Added Stackblitz codeflow to CONTRIBUTING

packages/docs/src/routes/media/index.tsx
Added new videos and blog posts related to qwik.
=> docs: added videos and blog posts related to qwik

packages/docs/src/routes/media/index.tsx
- [ •] Feature / enhancement
New video for the media page 
- [• ] My code follows the [developer guidelines of this project](../CONTRIBUTING.md)
- [• ] I have performed a self-review of my own code
=> New media (YouTube video)

packages/qwik/src/core/render/dom/render-dom.ts, packages/qwik/src/core/render/dom/signals.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: boolean signals

packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/state/listeners.ts, packages/qwik/src/core/use/use-on.ts, packages/qwik/src/core/use/use-watch.ts, starters/apps/e2e/src/components/effect-client/effect-client.tsx, starters/apps/e2e/src/components/signals/signals.tsx, starters/apps/e2e/src/components/two-listeners/twolisteners.tsx, starters/e2e/e2e.effect-client.spec.ts, starters/e2e/e2e.two-listeners.spec.ts
=> fix: qrl rendering override

packages/docs/src/routes/media/index.tsx
=> add new presentation

.github/PULL_REQUEST_TEMPLATE.md
- From `../CONTRIBUTING.md`
- To `https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md`
- Before
- After
=> docs: fix pull request developer guidelines broken link

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json, yarn.lock
=> Release 0111

packages/qwik/src/core/container/container.ts, scripts/package-json.ts
=> fix: client-side qwikevents

packages/docs/src/routes/tutorial/hooks/use-mount/index.mdx
"and but" should be just "but"
=> docs: Additional word grammar fix

packages/docs/src/routes/media/index.tsx
=> docs: added new videos

packages/docs/src/routes/docs/components/state/index.mdx
=> docs: fixing typo/wording issue

packages/docs/src/routes/docs/advanced/optimizer/index.mdx
=> docs: removed unnecessary closing bracket

packages/docs/src/routes/qwikcity/content/component/index.mdx, packages/qwik-react/README.md
=> docs: minor changes.

packages/qwik/src/core/api.md, packages/qwik/src/core/container/serializers.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-watch.ts, starters/apps/e2e/src/components/resource/resource.tsx, starters/apps/e2e/src/components/resource/weather.tsx
=> fix: reduce Resource api surface

packages/docs/src/routes/docs/components/overview/index.mdx
=> docs: added urls in note && added exports.

packages/docs/src/routes/qwikcity/static-site-generation/static-site-config/index.mdx
=> docs: remove unnecessary npm run

packages/docs/src/routes/qwikcity/menu.md, packages/docs/src/routes/qwikcity/starters/tailwind/index.mdx
add documentation for starter tailwind
- [x ] I have made corresponding changes to the documentation
- [ x] Added new tests to cover the fix / functionality
=> doc tailwind

packages/docs/src/routes/qwikcity/routing/overview/index.mdx
Typo? Remove an extra 'a' in "you must a define".
=> Fix: index.mdx

packages/qwik/src/core/readme.md
- [] I have performed a self-review of my own code
=> docs: fix incorrect usemount description

packages/docs/src/routes/docs/faq/index.mdx, packages/docs/src/routes/media/index.tsx
=> docs: fix FAQ h2s

packages/qwik-city/package.json, starters/apps/base/package.json, yarn.lock
=> chore: release qwik-city

packages/qwik/src/cli/add/update-app.ts, packages/qwik/src/cli/add/update-vite-config.ts, packages/qwik/src/cli/code-mod/code-mod.ts, packages/qwik/src/cli/code-mod/code-mod.unit.ts, packages/qwik/src/cli/types.ts, scripts/create-qwik-cli.ts, scripts/submodule-cli.ts
Add back the ability for the cli to code mod `vite.confi.ts`
=> fix: vite.config.ts cli code mod

packages/docs/src/routes/qwikcity/data/endpoints/index.mdx
Added an extension to apply a coloring.
=> docs: typo in Qwikcity data endpoints example

packages/docs/src/routes/docs/cheat/qwik-react/index.mdx
=> docs: added react examples in qwik vs react

packages/docs/src/routes/qwikcity/integrations/react/index.mdx
Replacing the absolute path with a relative.
=> docs(QwikCity): integrations react typo

packages/create-qwik/create-app.ts, packages/qwik/src/cli/add/run-add-interactive.ts, packages/qwik/src/cli/utils/install-deps.ts, packages/qwik/src/cli/utils/log.ts, starters/apps/base/package.json, starters/features/react/package.json, starters/features/tailwind/package.json
=> chore: fixes

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/adaptors/cloudflare-pages/vite/index.ts, packages/qwik-city/adaptors/express/vite/index.ts, packages/qwik-city/adaptors/netlify-edge/vite/index.ts, packages/qwik-city/adaptors/static/vite/index.ts, packages/qwik/package.json, packages/qwik/src/optimizer/src/plugins/vite.ts
=> chore: Fix generate release

.github/PULL_REQUEST_TEMPLATE.md, packages/docs/src/routes/docs/faq/index.mdx, packages/docs/src/routes/docs/getting-started/index.mdx, packages/docs/src/routes/qwikcity/integrations/react/index.mdx
=> docs: update urls && minor changes

.gitignore, package.json
=> chore: add eslint cache

packages/docs/src/routes/docs/components/resource/index.mdx, packages/docs/src/routes/docs/components/state/index.mdx
=> docs: updated track usage.

packages/docs/src/routes/docs/advanced/optimizer/index.mdx, packages/docs/src/routes/docs/advanced/qrl/index.mdx, packages/docs/src/routes/docs/components/events/index.mdx, packages/docs/src/routes/docs/components/lite-components/index.mdx
=> docs: added exports.

packages/docs/src/routes/tutorial/qrl/data/index.mdx
=> docs: fix typo tutorial

packages/docs/src/components/docsearch/start-screen.tsx, packages/docs/src/repl/repl-output-panel.tsx, starters/apps/e2e/src/components/lexical-scope/lexicalScope.tsx
=> fix: remove `mutable()` references

packages/docs/src/routes/tutorial/introduction/resource/index.mdx, packages/docs/src/routes/tutorial/reactivity/resource/index.mdx
=> docs: fix closing tag

packages/qwik/src/core/render/ssr/render-ssr.ts
=> Typo: useStyleStyle -> useStyles

.github/workflows/bench.yml, .github/workflows/ci.yml, packages/qwik-city/static/main-thread.ts, packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts, starters/adaptors/static/package.json, starters/adaptors/static/src/entry.static.tsx
=> chore: update ci actions

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts, packages/qwik-city/package.json, packages/qwik-react/package.json, packages/qwik/package.json, packages/qwik/src/optimizer/core/src/package_json.rs, packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts, yarn.lock
=> fix: regressions

packages/docs/src/routes/docs/components/resource/index.mdx
=> docs: updates examples format and grammar changes.

packages/docs/src/routes/tutorial/hooks/use-mount/index.mdx
=> docs: update useMount$() bocs

packages/docs/src/routes/docs/faq/index.mdx
=> docs: spelling fix (fixes #1893)

packages/docs/src/routes/tutorial/hooks/use-watch/problem/app.tsx
=> docs: update app.tsx

packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_preserve_filenames_hooks.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/src/optimizer.ts, packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/server/prefetch-strategy.ts
=> perf: vite plugin

packages/docs/src/routes/qwikcity/integrations/react/index.mdx
useSignal()
From: useSignal$
To: useSignal
=> docs: useSignal$ typo

packages/docs/src/routes/qwikcity/integrations/tailwind/index.mdx
Update tailwind text.
- From: Website Tailwind
- To: Tailwind Website
=> doc: update tailwind link text

starters/apps/basic/src/global.css, starters/apps/basic/src/routes/index.tsx
Fix SEO audit with chrome lighthouse test for mobile and desktop devices...
---
Before - 83% coverage:
After - 100% coverage for mobile and desktop devices:
- 1. increase core web vitals for SEO ranking
=> fix(SEO audit): 100% for mobile and desktop device

packages/qwik-city/package.json, packages/qwik-react/package.json, packages/qwik/package.json, packages/qwik/src/optimizer/src/plugins/vite.ts, scripts/package-json.ts, scripts/qwik-city.ts, starters/apps/library/package.json
=> perf: fix minification regression

packages/qwik/src/core/typings.d.ts, scripts/api.ts
=> fix: .css types

packages/docs/src/routes/qwikcity/data/endpoints/index.mdx
=> docs: enhanced endpoint docs (fixes #1944)

packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/styles/styles.tsx, starters/e2e/e2e.style.spec.ts
=> fix: scoped styles with slot

packages/docs/src/repl/worker/repl-plugins.ts
=> fix: docs repl

packages/qwik-city/middleware/netlify-edge/index.ts
Netlify uses a special path `/.netlify/*` for platform specific features. We should skip any url paths that start with this segment.
Fixes: #1929
=> fix: Netlify git gateway

packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/optimizer/src/plugins/rollup.ts, packages/qwik/src/optimizer/src/plugins/vite.ts
=> fix(vite): ensure correct mod invalidation

packages/qwik-react/src/react/qwikify.tsx
=> fix(react): support client:only

packages/docs/src/routes/media/index.tsx
=> docs: Add the first YouTube Tutorial in Portuguese about Qwik

packages/qwik/src/core/container/container.ts, packages/qwik/src/core/container/index.html, packages/qwik/src/core/container/pause.ts, packages/qwik/src/core/container/resume.ts, packages/qwik/src/core/render/dom/notify-render.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/error-handling.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/render/types.ts, packages/qwik/src/core/state/context.ts, packages/qwik/src/core/use/use-context.ts, packages/qwik/src/core/use/use-lexical-scope.public.ts, packages/qwik/src/core/use/use-on.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-sequential-scope.ts, packages/qwik/src/core/use/use-signal.ts, packages/qwik/src/core/use/use-store.public.ts, packages/qwik/src/core/use/use-styles.ts, packages/qwik/src/core/use/use-watch.ts, packages/qwik/src/server/render.ts, packages/qwik/src/testing/element-fixture.ts, starters/apps/e2e/src/components/context/context.tsx, starters/e2e/e2e.context.spec.ts
Fixes https://github.com/BuilderIO/qwik/issues/1971
Fixes https://github.com/BuilderIO/qwik/issues/1648
=> fix(context): contexts gets propogated through slots

scripts/qwik-save-artifacts.ts
=> chore: add `qwik-city-build` into artifacts

packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts
Adds support for HTML5 Audio and Video events.
Closes #2010
=> feat: Add Audio and Video Events

packages/qwik/src/core/render/ssr/render-ssr.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: textarea with signals

starters/features/react/src/integrations/react/mui.tsx, starters/features/react/src/routes/react/index.tsx
=> fix: remove confusing example

packages/docs/src/routes/docs/components/resource/index.mdx
Also update examples to use a live REST API.
=> docs: update resource docs to reflect current api

packages/qwik-city/package.json, packages/qwik/src/core/render/dom/notify-render.ts, starters/apps/e2e/src/components/effect-client/effect-client.tsx, starters/e2e/e2e.effect-client.spec.ts
=> fix: consistent useClientEffect order

packages/docs/src/routes/docs/components/styles/index.mdx, packages/docs/src/routes/docs/menu.md
=> docs: enhance styles section (fixes: #1907)

packages/qwik-city/adaptors/cloudflare-pages/vite/index.ts, packages/qwik-city/adaptors/express/vite/index.ts, packages/qwik-city/adaptors/netlify-edge/vite/index.ts, packages/qwik-city/adaptors/static/vite/index.ts, packages/qwik-city/buildtime/vite/plugin.ts, packages/qwik-city/buildtime/vite/types.ts, packages/qwik-city/static/api.md, packages/qwik-city/static/main-thread.ts, packages/qwik-city/static/node/node-system.ts, packages/qwik-city/static/types.ts
=> fix: ssg basePathname

packages/qwik/src/core/render/ssr/render-ssr.ts
=> fix: noscript is not a textonly element

packages/qwik-city/runtime/src/library/types.ts
=> fix: export StaticGenerate

packages/qwik-city/buildtime/vite/plugin.ts
=> fix: build.server error and sw build

packages/qwik/src/core/container/container.ts, packages/qwik/src/core/render/dom/notify-render.ts, packages/qwik/src/core/render/dom/render-dom.ts, starters/apps/e2e/src/components/resource/resource-serialization.tsx, starters/e2e/e2e.resource.spec.ts
=> fix: mixed render with signals

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json, packages/qwik/src/qwikloader.ts, yarn.lock
=> Prepare 0.13.0 release

scripts/qwik-save-artifacts.ts
=> chore: don't try to push to build repo if artifacts did not build

packages/docs/src/routes/qwikcity/static-site-generation/static-site-config/index.mdx
I've encountered an [issue](https://github.com/BuilderIO/qwik/issues/1998) with `qwik-city`. It's related to the docs that are not up-to-date. This PR is an update to the docs.
I'm not a native English speaker so feel free to rephrase everything☺️
- 1. Current docs will cause the project to not run
=> updated qwik-city SSG docs according to new usage with an adaptor

packages/docs/src/routes/qwikcity/static-site-generation/static-site-config/index.mdx
improve and fix typo static-site-config
Nope
=> docs: improve and fix typo static-site-config

packages/docs/src/routes/qwikcity/adaptors/cloudflare-pages/index.mdx
Added a markdown extension to apply a coloring.
=> docs(QwikCity): cloudflare-pages

packages/qwik-city/buildtime/vite/dev-server.ts, packages/qwik-city/middleware/request-handler/page-handler.ts, packages/qwik/src/core/api.md, packages/qwik/src/core/index.ts, packages/qwik/src/core/render/jsx/utils.public.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/server/api.md, packages/qwik/src/server/render.ts, packages/qwik/src/server/types.ts
=> feat: add <SSRHint>

packages/docs/src/routes/qwikcity/adaptors/cloudflare-pages/index.mdx, packages/docs/src/routes/qwikcity/adaptors/netlify-edge/index.mdx
Fix typo and improve adaptators
Nope
=> docs: fix typo and improve adaptators

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts
=> fix(eslint): correct detect usage of unexported root

scripts/submodule-core.ts
- Docs / tests
Deleting a single line which has code that was commented out 8 months ago.
See this old PR for reference:
https://github.com/BuilderIO/qwik/commit/0b247ca0a2708c804ac5a469814d68e97f54c60a
For cleaner, more professional code.
- [N/A (Stackblitz not working for me)] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [Y] I have performed a self-review of my own code
- [N/A] I have made corresponding changes to the documentation
=> Removing commented out code

packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/container/pause.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/state/context.ts, starters/apps/e2e/src/components/context/context.tsx, starters/e2e/e2e.context.spec.ts
=> fix: context treeshaking with slot

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, starters/apps/base/package.json
=> Release 0 13 1

packages/qwik/src/optimizer/src/plugins/rollup.ts
=> fix: rollup plugin

packages/qwik/src/core/container/resume.ts, packages/qwik/src/core/qrl/qrl.ts, packages/qwik/src/qwikloader.ts
=> fix: handle default exports of QRL

packages/docs/src/routes/docs/advanced/dollar/index.mdx
=> docs: dollar explanation

packages/docs/src/routes/tutorial/events/synchronous/solution/app.tsx
=> docs: update example to use useSignal

packages/docs/src/routes/docs/components/lite-components/index.mdx
This PR mentions some of the limitations present with lite components.
=> docs(lite-components): lite components limitations

CONTRIBUTING.md
=> docs: Updated CONTRIBUTING.md from yarn to pnpm

packages/qwik/src/server/render.ts
=> chore: update manifest warning msg

packages/docs/src/routes/media/index.tsx
Added videos and docs
I have added new videos to the media page and changed the position of a few videos.
=> docs: Add new videos to the media page

packages/docs/src/routes/docs/components/projection/index.mdx
=> docs: fix typo projection

packages/docs/src/routes/docs/advanced/dollar/index.mdx
=> docs: fix typo advanced dollar

packages/docs/src/routes/docs/components/lifecycle/index.mdx
=> docs: fix lifecycle typo

packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
https://github.com/BuilderIO/qwik/issues/2142
=> fix: correct css variable rendering

packages/qwik/src/core/container/pause.ts, packages/qwik/src/core/state/context.ts, packages/qwik/src/core/state/store.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: computed prop signals

packages/docs/package.json, starters/adaptors/cloudflare-pages/package.json, starters/adaptors/express/package.json, starters/adaptors/netlify-edge/package.json, starters/adaptors/vercel-edge/package.json, starters/apps/base/package.json
=> feat: use deploy instead of serve

packages/qwik/src/core/component/component.unit.tsx, packages/qwik/src/core/render/dom/operations.ts, packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
=> fix: add [hidden] to qwik styles

packages/docs/src/routes/qwikcity/adaptors/cloudflare-pages/index.mdx
Remove references to Netlify in Cloudflare Pages adapter documentation. And some other general improvements to the Cloudflare docs. Resolves #2186
=> Remove references to Netlify in Cloudflare Pages adapter documentation

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CONTRIBUTING.md
=> fix: devcontainer

packages/qwik-react/package.json, packages/qwik/src/cli/build/run-build-command.ts, starters/apps/base/package.json, starters/apps/library/package.json
=> fix: use pkg manager to run scripts

packages/docs/src/routes/docs/advanced/dollar/index.mdx
=> docs: maintain heading hierarchy

packages/docs/src/routes/docs/advanced/dollar/index.mdx
=> docs: fix "it" -> "that"

packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/index.ts, packages/qwik-city/runtime/src/qwik-city-component.tsx
=> feat: add QwikCityMockProvider

packages/qwik-city/buildtime/vite/dev-server.ts, starters/apps/basic/src/routes/index.tsx, starters/apps/qwikcity-test/src/routes/[catchall]/index.tsx, starters/apps/qwikcity-test/src/routes/about-us/index.tsx
Closes https://github.com/BuilderIO/qwik/issues/2205
=> fix: dev-server w/ catchall

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, pnpm-lock.yaml, starters/apps/base/package.json
=> chore: Prepare release

CONTRIBUTING.md
=> docs: updated contributing.md

packages/qwik-city/buildtime/vite/plugin.ts, packages/qwik-city/package.json, starters/apps/base/package.json
=> fix: qwikcity vite dev server order

packages/docs/src/routes/docs/faq/index.mdx
FAQ : fix doubled sentences
Nope
=> docs: FAQ fix doubled sentences

packages/docs/src/routes/docs/faq/index.mdx
=> docs: fix typo in faq/index.mdx

packages/docs/src/routes/qwikcity/integrations/react/index.mdx
=> Rephrase a paragraph

packages/qwik/src/core/api.md, packages/qwik/src/core/index.ts, packages/qwik/src/core/qrl/qrl.ts, packages/qwik/src/optimizer/cli/src/main.rs, packages/qwik/src/optimizer/core/benches/transform.rs, packages/qwik/src/optimizer/core/src/lib.rs, packages/qwik/src/optimizer/core/src/parse.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_client_code.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_server_code.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/core/src/transform.rs, packages/qwik/src/optimizer/core/src/words.rs, packages/qwik/src/optimizer/src/api.md, packages/qwik/src/optimizer/src/optimizer.ts, packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/optimizer/src/types.ts
<a href="https://www.loom.com/share/cded0a4c4d754550bde6ec8a61603a2d">
</a>
=> perf/fix: strong partially guaranties 

packages/docs/src/routes/qwikcity/static-site-generation/static-site-config/index.mdx
This pull request is to fix the spelling
=> docs: fix typo in static-site-config/index.mdx

packages/qwik-city/runtime/src/client-navigate.ts, packages/qwik-city/runtime/src/client-navigate.unit.ts, packages/qwik-city/runtime/src/constants.ts, packages/qwik-city/runtime/src/link-component.tsx
=> fix: back button w/ SPA link and reload

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, starters/apps/base/package.json
=> chore: Release 0.14.1

packages/qwik/src/core/api.md, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/render/dom/signals.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/render/jsx/types/jsx-generated.ts, packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/signals/signals.tsx, starters/apps/e2e/src/components/signals/test/test.tsx, starters/apps/e2e/src/components/signals/utils/utils.tsx, starters/e2e/e2e.signals.spec.ts, starters/features/styled-vanilla-extract/package.json, starters/features/styled-vanilla-extract/src/routes/styled-flower/index.tsx, starters/features/vitest/src/components/example/example.tsx
=> fix: signal rendering of classes

packages/docs/src/routes/docs/components/resource/index.mdx
=> Fix a typo

packages/qwik/src/core/container/container.ts, packages/qwik/src/core/render/dom/notify-render.ts, packages/qwik/src/core/render/dom/render.public.ts, packages/qwik/src/core/render/error-handling.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/use/use-context.ts, packages/qwik/src/core/use/use-mount.ts, packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-sequential-scope.ts, packages/qwik/src/core/use/use-signal.ts, packages/qwik/src/core/use/use-store.public.ts, packages/qwik/src/core/use/use-styles.ts, packages/qwik/src/core/use/use-watch.ts
Make sure errors are not hidden during rendering in production mode
=> fix: not silent error during rendering

packages/qwik/src/core/api.md, packages/qwik/src/core/render/jsx/types/jsx-generated.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/attributes/attributes.tsx, starters/e2e/e2e.attributes.spec.ts
=> fix: correctly handle draggable and spellcheck

packages/qwik-city/buildtime/vite/dev-server.ts
=> fix: dev server 302 error

packages/qwik/src/optimizer/src/optimizer.ts
Wasm was not getting all the params required!
=> fix(optimizer): missing args passed to wasm fallback

packages/docs/src/routes/tutorial/component/binding/problem/app.tsx, packages/docs/src/routes/tutorial/component/binding/solution/app.tsx, packages/qwik/src/core/render/jsx/types/jsx-generated.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/signals/signals.tsx
fixes https://github.com/BuilderIO/qwik/issues/2235
=> fix: textarea value rendering in SSR

packages/qwik/src/core/container/container.ts, packages/qwik/src/core/render/dom/notify-render.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: render toggle + signal

packages/qwik-city/runtime/src/routing.ts, packages/qwik-city/runtime/src/routing.unit.ts, packages/qwik-city/utils/fs.ts, packages/qwik-city/utils/fs.unit.ts, starters/apps/qwikcity-test/src/routes/docs/menu.md
=> fix: useContent menu lookup

packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/optimizer/src/plugins/vite-server.ts
Fixes: https://github.com/BuilderIO/qwik/issues/2252
=> "Click to Component"

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json
=> chore: prepare 0.15.0

packages/docs/src/routes/docs/components/state/index.mdx
While reading the documentation I noticed some typos and wanted to suggest some improvements to the content.
=> docs: fix typos and improve explanations

packages/qwik/src/optimizer/src/plugins/vite-server.ts, packages/qwik/src/optimizer/src/plugins/vite.ts
Minor fixes to click to component
=> fix: click-to-component

packages/docs/src/routes/docs/components/overview/index.mdx
While reading the documentation I noticed a couple of minor typos and some improvements to the explanations.
=> Fix some typos and align explanations

.npmrc, package.json, scripts/tsc.ts, tsconfig.json
Add scripts for vite-ecosystem testing
=> chore: add vite ecosystem scripts

packages/docs/src/routes/docs/components/lifecycle/index.mdx
=> docs: fix typo lifecycle

packages/qwik/src/core/state/common.ts
=> fix: detect and error on array holes

packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
Fixes https://github.com/BuilderIO/qwik/issues/2344
=> fix: textarea vdom patching

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/singleJsxRoot.ts
=> fix: jsx rule with fragment

packages/qwik/src/core/qrl/qrl.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, starters/apps/e2e/src/components/effect-client/effect-client.tsx, starters/e2e/e2e.effect-client.spec.ts
fixes https://github.com/BuilderIO/qwik/issues/1955
fixes https://github.com/BuilderIO/qwik/issues/2329
fixes #1062
fixes #1413
fixes #1446
=> fix: useClientEffect() in empty components

packages/qwik/src/core/state/common.ts
=> fix: make array hole test more readable

packages/docs/src/routes/docs/components/lifecycle/index.mdx
=> docs: removed unnecessary fragments

packages/docs/src/routes/docs/components/rendering/index.mdx
Provided a small guide on using array mapping functions in JSX and the required `key` prop.
- 1. Mapping an array of data in JSX
=> docs: Add Guide On Using Map Functions In JSX

packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/optimizer/src/plugins/vite-utils.ts, starters/apps/e2e/src/components/events/events.tsx, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/starter-partytown-test/src/root.tsx, starters/apps/todo-old-test/src/root.tsx, starters/apps/todo-test/src/root.tsx
https://github.com/BuilderIO/qwik/issues/1794
=> feat: detect invalid HTML

starters/apps/basic/src/components/header/header.tsx, starters/apps/basic/src/global.css
Fix link accessibility
- Mobile
- Desktop
=> chore: fix link accessibility

packages/docs/src/routes/media/index.tsx
Add latest 'Qwik City for Resumable, Dynamic Apps' interview with Misko to Media page
=> docs: Add latest 'Qwik City for Resumable, Dynamic Apps' interview with Misko

packages/docs/package.json, packages/docs/src/components/builder-content/index.tsx, packages/docs/src/components/docsearch/search-box.tsx, packages/docs/src/constants.ts, packages/docs/src/repl/repl-output-panel.tsx, packages/docs/src/root.tsx, packages/docs/src/routes/index.tsx, packages/docs/src/routes/layout.tsx, packages/docs/src/routes/tutorial/layout!.tsx, packages/docs/src/routes/tutorial/qrl/closures/problem/app.tsx, packages/docs/src/routes/tutorial/qrl/closures/solution/app.tsx, packages/docs/src/routes/tutorial/reactivity/resource/problem/app.tsx, packages/qwik-city/runtime/vite.config.ts, pnpm-lock.yaml, tsconfig.json
=> docs: add builder.io OSS header bar

packages/qwik/src/core/error/error.ts
=> fix: error messages typos

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik-city/runtime/src/qwik-city-component.tsx, packages/qwik-react/package.json, packages/qwik/package.json, pnpm-lock.yaml
=> Release 0 16 0

packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
=> fix: number values for style

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik-city/package.json, packages/qwik/package.json, packages/qwik/src/core/container/serializers.ts, pnpm-lock.yaml, starters/apps/qwikcity-test/src/routes/(common)/streaming/index.tsx
=> fix: form data crash

packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
Co-Authored-By: OhB00 <43827372+ohb00@users.noreply.github.com>
=> fix: cleanse ssr attribute name and class value

packages/docs/src/routes/qwikcity/layout!.tsx
=> docs: remove duplicate builder bar

packages/docs/src/routes/media/index.tsx
=> docs(media): `Qwik: The Lightest, Fastest Way to Build Web Apps`

packages/docs/src/components/builder-content/index.tsx, packages/docs/src/components/header/header.css
=> docs: update builder content site and margin

packages/docs/public/_redirects, packages/docs/src/routes/docs/faq/index.mdx, packages/docs/src/routes/docs/getting-started/index.mdx, starters/adaptors/azure-swa/package.json, starters/adaptors/cloud-run/package.json, starters/adaptors/cloud-run/src/entry.cloud-run.tsx, starters/adaptors/cloudflare-pages/package.json, starters/adaptors/cloudflare-pages/src/entry.cloudflare-pages.tsx, starters/adaptors/express/package.json, starters/adaptors/express/src/entry.express.tsx, starters/adaptors/netlify-edge/package.json, starters/adaptors/netlify-edge/src/entry.netlify-edge.tsx, starters/adaptors/vercel-edge/package.json, starters/apps/documentation-site/src/routes/about-us/index.md, starters/apps/documentation-site/src/routes/docs/index.md
modify the docs link that shows on terminal after `npm run qwik add express`
=> modify the docs link 

packages/docs/src/components/header/header.tsx, packages/docs/src/routes/docs/components/styles/index.mdx, packages/docs/src/routes/docs/faq/index.mdx, packages/docs/src/routes/docs/getting-started/index.mdx, packages/docs/src/routes/docs/overview/index.mdx, packages/docs/src/routes/integrations/integration/overview/index.mdx
- fixes #2505
- fixes #2506 
- updated getting started page (added yarn and pnpm, fixed broken links and updated default ports)
- fixed 404 links
- changed main navigation link target of `integrations` to `integrations` instead of `deployments`
- updated list of available integrations and aligned them with the CLI prompt
=> docs: several improvements

packages/docs/src/routes/docs/components/overview/index.mdx
=> docs: added ref attrib to component docs

packages/docs/src/routes/integrations/integration/overview/index.mdx, packages/docs/src/routes/integrations/integration/playwright/index.mdx, packages/docs/src/routes/integrations/menu.md
- added playwright integration page
- linked from overview page
- changed sidebar menu order (integration before deployment)
=> docs: added playwright integration section

starters/features/partytown/package.json, starters/features/react/package.json, starters/features/tailwind/package.json, starters/features/vitest/package.json
=> docs: change links

packages/docs/src/routes/integrations/integration/partytown/index.mdx
Removed extra semicolon in Partytown section.
Nope
=> docs: remove extra code (Partytown)

packages/docs/scripts/pages.json
- ✅ Feature / enhancement
Adds https://shaunchander.me to the showcase.
Adds my personal website to the showcase to show what's possible with Qwik!
- ✅ My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- ✅ I have performed a self-review of my own code
- ✅ I have made corresponding changes to the documentation
- ✅ Added new tests to cover the fix / functionality
=> ⚡️ add my personal site to the showcase

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts
=> fix(eslint): allow any as $ attribute

.github/ISSUE_TEMPLATE/bug.yaml, packages/create-qwik/create-interactive.ts, packages/create-qwik/index.ts, packages/qwik-city/middleware/node/http.ts, packages/qwik-city/middleware/node/node-fetch.ts, packages/qwik/package.json, scripts/package-json.ts, starters/dev-server.ts, tsm.cjs
=> fix: undici as peerDependency

package.json, packages/create-qwik/package.json, packages/eslint-plugin-qwik/package.json, packages/qwik/package.json, pnpm-lock.yaml
=> Release 16 2

scripts/qwik-save-artifacts.ts
=> ci: add better console.log

packages/docs/src/routes/docs/advanced/dollar/index.mdx, packages/docs/src/routes/docs/advanced/qrl/index.mdx
The main changes are in the "dollar" docs page to update some mentions of an API that I don't believe is exported anymore.
I also did some little fixes in other places to make the language a little more natural.
Open to any suggestions if I misunderstood anything!
=> docs: update out-of-date documentation

packages/qwik-city/adaptors/shared/vite/post-build.ts, packages/qwik-city/middleware/cloudflare-pages/index.ts, packages/qwik-city/middleware/netlify-edge/index.ts, packages/qwik-city/middleware/node/index.ts, packages/qwik-city/middleware/request-handler/generated/static-paths.ts, packages/qwik-city/middleware/vercel-edge/index.ts
=> fix: treat non `GET` methods as always dynamic.

packages/docs/src/routes/docs/overview/index.mdx, packages/qwik/src/core/component/component.public.ts, packages/qwik/src/core/qrl/qrl-class.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/state/common.ts, packages/qwik/src/core/util/log.ts
=> feat: improve non-serializable error

.github/workflows/ci.yml, packages/qwik-city/adaptors/shared/vite/post-build.ts, scripts/qwik-save-artifacts.ts
=> ci: Create build artifacts per commit.

packages/docs/src/routes/media/index.tsx
=> add new video Qwik Spanish

scripts/qwik-save-artifacts.ts
=> fix: git builds

packages/qwik-city/middleware/request-handler/generated/static-paths.ts
=> docs: add docs

packages/docs/src/routes/media/index.tsx
=> add more video spanish

packages/docs/src/routes/docs/advanced/prefetching/index.mdx, packages/docs/src/routes/docs/advanced/qwikloader/index.mdx, packages/docs/src/routes/docs/components/state/index.mdx, packages/docs/src/routes/docs/components/styles/index.mdx, packages/docs/src/routes/docs/faq/index.mdx, packages/docs/src/routes/docs/getting-started/index.mdx, packages/docs/src/routes/docs/think-qwik/index.mdx, packages/docs/src/routes/integrations/integration/styled-vanilla-extract/index.mdx, packages/docs/src/routes/qwikcity/api/index.mdx, packages/docs/src/routes/tutorial/projection/basic/index.mdx
Random wording changes and updates that I think make things more natural/correct.
=> Docs improvements

packages/docs/scripts/pages.json
=> added website

packages/docs/scripts/pages.json
Add portfolio page in showcase page
https://amirhbeigi.ir/
=> Add portfolio in showcase page

packages/docs/src/routes/qwikcity/api/index.mdx
=> chore: fix typo in api/index.mdx

starters/apps/base/src/entry.dev.tsx, starters/apps/base/src/entry.ssr.tsx
=> fixed consistent type imports warning

packages/docs/src/components/builder-content/index.tsx, packages/docs/src/root.tsx
=> fix: cache multiple requests to builder.io

packages/qwik/src/core/state/signal.ts, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> fix: string wrapSignal()

packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_capturing_fn_class.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_custom_inlined_functions.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_default_export.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_explicit_ext_transpile.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_functional_component_2.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_functional_component_capture_props.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_jsx.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_jsx_listeners.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_manual_chunks.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_missing_custom_inlined_functions.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_mutable_children.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_qwik_conflict.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_renamed_exports.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_skip_transform.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_client_code.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_server_code.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_use_client_effect.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_use_server_mount.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__issue_150.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__issue_964.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__relative_paths.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/core/src/transform.rs, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> fix: add key to root jsx nodes

CONTRIBUTING.md
Improving CONTRIBUTING file with missing sections
=> update CONTRIBUTING file

packages/docs/src/routes/integrations/deployments/node/index.mdx
=> remove a wrong letter

CONTRIBUTING.md
Inputs to discuss on discord: https://discord.com/channels/842438759945601056/940654245265436732/1063181106557485096
=> fixes(docs): contributing file updates

starters/apps/library/src/entry.dev.tsx, starters/apps/library/src/entry.ssr.tsx
=> fix:consistent type imports warning

packages/docs/src/routes/qwikcity/data/overview/index.mdx
This is the matching `getAll` cookies document change, if PR #2477 is accepted.
This is the matching `getAll` cookies document change, if PR https://github.com/BuilderIO/qwik/pull/2477 is accepted.
- [√] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [√] I have performed a self-review of my own code
- [√] I have made corresponding changes to the documentation
- [√] Added new tests to cover the fix / functionality
=> docs: Add getAll() cookies documentation

packages/docs/src/routes/qwikcity/content/menu/index.mdx
I found a problem with the menu explanation.
=> docs: fix wrong sample about menu

.github/PULL_REQUEST_TEMPLATE.md, packages/docs/src/routes/docs/components/overview/index.mdx
=> docs: removed useMount link and updated links

packages/docs/scripts/pages.json
I created Puzzledbycsharp.com using Qwik and it's a lot faster now with great page speed.
- [ x] Docs / tests
Adding new site puzzledbysharp.com to showcase. 
- [x ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
=> docs: Update pages.json

packages/qwik-city/adaptors/cloudflare-pages/vite/index.ts
fixes #2575
fixes #2575 by doing the mentioned revert since the new implemented solution causes other issues and we should find a general solution.
=> fixes(qwik-city): revert cloudflare q-data.json fix

packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
=> feat: CSRF protection

packages/docs/src/routes/qwikcity/content/head/index.mdx
i followed code in this page, but not works without useDocumentHead() code i found that qwik site github
=> [Doc] QwikCity <head> page need info about RouterHead

packages/docs/src/routes/docs/components/state/index.mdx
=> docs: updated example

packages/qwik/src/core/use/use-resource.ts, packages/qwik/src/core/use/use-task.ts, starters/apps/e2e/src/components/resource/resource-serialization.tsx, starters/e2e/e2e.resource.spec.ts
=> fix: useResource$() race condition

packages/docs/src/routes/qwikcity/api/index.mdx
There was an error in the example, I already modified it, check.
=> Label modification

packages/docs/src/routes/docs/components/resource/index.mdx
=> docs: update url

packages/qwik/src/core/error/error.ts, packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/use/use-core.ts
=> feat: improve error messages

packages/docs/src/routes/docs/components/overview/index.mdx
=> docs: Fix state api signature

CONTRIBUTING.md
This PR wants to describe how to configure the environment to be able to contribute.
=> docs(contributing): improve Getting started section

packages/qwik-city/buildtime/runtime-generation/generate-routes.ts, packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts, packages/qwik-city/runtime/src/qwik-city-component.tsx, packages/qwik-city/runtime/src/types.ts, packages/qwik-city/runtime/src/use-endpoint.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts, starters/apps/qwikcity-test/src/routes/(common)/api/data.json/index.ts, starters/apps/qwikcity-test/src/routes/layout.tsx, starters/e2e/qwikcity/api.spec.ts
=> fix: execute layouts with endpoints

packages/qwik-city/adaptors/cloudflare-pages/vite/index.ts
=> fix: cloudflare use worker conditionals

packages/qwik-city/buildtime/markdown/mdx.ts, packages/qwik-city/buildtime/markdown/rehype.ts
=> fix: qwikcity id links

packages/docs/src/routes/docs/components/events/index.mdx
=> docs: improve component event doc

packages/qwik-city/middleware/request-handler/request-event.ts, packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
=> fix: trailingSlash option

packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/types.ts
=> fix: action.run is a QRL

.github/workflows/ci.yml
=> fix: CI for external PRs

packages/qwik-city/buildtime/vite/dev-server.ts, packages/qwik-city/buildtime/vite/plugin.ts, packages/qwik/src/optimizer/src/plugins/vite.ts
fixes https://github.com/BuilderIO/qwik/issues/2787
=> fix: vite proxy support 

packages/eslint-plugin-qwik/src/loaderLocation.ts
=> fix: loader$() eslint rule in windows

packages/docs/scripts/pages.json
Hello again :) Recently I made my own website with Qwik.js and results are wonderful! I got a perfect score in both desktop and mobile versions. I would love to see this cutie in the showcase of Qwik docs :)
https://necatikcl.dev/
https://twitter.com/i/status/1621565438990901250
=> Add a website with perfect score to the showcase (docs/showcase)

packages/docs/src/routes/media/index.tsx
=> add new video qwik spanish (2 hours)

packages/docs/src/routes/docs/faq/index.mdx
=> docs: fixing landing page typos

packages/qwik/src/core/state/store.ts, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> fix: reactivity of store keys

packages/qwik/src/optimizer/core/src/props_destructuring.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap, packages/qwik/src/optimizer/core/src/test.rs
=> fix: optimize prop shorthand

packages/qwik-city/runtime/src/router-outlet-component.ts, starters/apps/qwikcity-test/src/components/provider/provider.tsx, starters/apps/qwikcity-test/src/components/router-head/router-head.tsx, starters/apps/qwikcity-test/src/root.tsx, starters/apps/qwikcity-test/src/routes/(common)/index.tsx, starters/apps/qwikcity-test/src/routes/issue2829/a/index.tsx, starters/apps/qwikcity-test/src/routes/issue2829/b/index.tsx, starters/e2e/qwikcity/nav.spec.ts
=> fix: spa context serialization

packages/docs/src/routes/docs/components/rendering/index.mdx
=> docs:  add `dangerouslySetInnerHTML`

packages/qwik-city/middleware/azure-swa/index.ts
This adds the support to send binary data in the response from Azure Static Web Apps.
The current implementation used a `TextDecoder` to convert the data sent to the `WritableStream` to strings. 
If you want to send binary data like images from a handler it did not work on Azure Static Web Apps. With this change you can send any data as the response.
=> feat(azure-swa): support binary data in the response

packages/docs/src/routes/qwikcity/project-structure/index.mdx
=> docs(qwik-city): project-structure typo

packages/qwik-city/adapters/static/vite/index.ts
=> fix: ssg config options

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts
fixes https://github.com/BuilderIO/qwik/issues/2881
=> fix: eslint prop interface

starters/apps/documentation-site/src/routes/docs/layout.tsx, starters/apps/documentation-site/src/routes/index.tsx
Fixes table tag structure. The lack of tbody in the table tag will cause vite compilation to fail.
Fix the imported doc.css stylesheet
=> Fix create qwik documentation site

packages/qwik/src/core/state/store.ts, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> fix: deep store tracking with complex objects

packages/qwik/src/core/render/dom/operations.ts, packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/context/context.tsx, starters/e2e/e2e.context.spec.ts
=> fix: context for unprojected content

packages/qwik-city/runtime/src/client-navigate.ts, packages/qwik-city/runtime/src/client-navigate.unit.ts, packages/qwik-city/runtime/src/qwik-city-component.tsx, starters/apps/qwikcity-test/src/routes/issue2890/a/index.tsx, starters/apps/qwikcity-test/src/routes/issue2890/b/index.tsx, starters/e2e/qwikcity/nav.spec.ts
=> fix(qwikcity): nav() respects query and hash

packages/docs/src/root.tsx, packages/docs/src/routes/community/groups/index.mdx, packages/docs/src/routes/community/projects/index.mdx, packages/docs/src/routes/community/values/index.mdx, packages/docs/src/routes/docs/components/rendering/index.mdx
=> docs: use QwikCityProvider api

packages/qwik-city/static/main-thread.ts, packages/qwik-city/static/node/node-system.ts, packages/qwik-city/static/not-found.ts, packages/qwik-city/static/types.ts, packages/qwik-city/static/worker-thread.ts
=> fix: write static endpoints during ssg

packages/docs/src/routes/docs/components/projection/index.mdx, packages/docs/src/routes/docs/components/state/index.mdx
=> docs: fix ie to i.e.

packages/docs/src/routes/docs/cheat/best-practices/index.mdx, packages/docs/src/routes/docs/getting-started/index.mdx, packages/docs/src/routes/qwikcity/project-structure/index.mdx
docs: fix some error
e.g. 
* node => Node;
* code highlight failed;
* qwik version error;
=> docs: fix some error

packages/docs/src/routes/qwikcity/pages/index.mdx
In the Documentation was not the correct function Name used, to recieve the product data.
=> docs: fix Typo in documentation

packages/docs/src/routes/docs/advanced/vite/index.mdx, packages/docs/src/routes/docs/menu.md, packages/docs/src/routes/docs/overview/index.mdx, packages/qwik-city/middleware/node/api.md, packages/qwik/src/optimizer/src/api.md, packages/qwik/src/optimizer/src/plugins/vite.ts
Added docs for vite within the advanced section covering configuration options for the `qwikVite()` and `qwikCity()` plugins along with a short troubleshooting block.
fixes #1885 (https://github.com/BuilderIO/qwik/issues/1885#issuecomment-1420022458)
=> docs: added vite docs

packages/docs/src/routes/docs/concepts/progressive/index.mdx
I made some  changes to the "progressive" doc
=> Made some small fixes on the "progressive" doc

packages/qwik-auth/README.md
=> docs: update to correct package name

CONTRIBUTING.md
Fix typo in :warning: Troubleshooting PR build issues on CI
=> docs: fix CONTRIBUTING typo

packages/qwik/src/core/render/dom/operations.ts, packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/slot/slot.tsx, starters/e2e/e2e.slot.spec.ts
=> fix: slot switching

packages/qwik/src/optimizer/src/plugins/plugin.ts
=> chore: word spelling error

packages/qwik/src/core/readme.md, packages/qwik/src/optimizer/src/plugins/vite-server.ts
chore: for better accesibility
=> chore: for better accesibility

packages/create-qwik/create-app.ts, packages/create-qwik/create-interactive.ts, packages/create-qwik/index.ts, packages/create-qwik/package.json, packages/qwik/src/cli/utils/install-deps.ts, packages/qwik/src/cli/utils/log.ts, pnpm-lock.yaml
Updated the `create-qwik` CLI to give it a bit fresher look'n'feel.
Let me know what you think about it.
https://user-images.githubusercontent.com/3241476/219188336-c379d3bd-403a-4c45-bcb6-6d9a3a6041d0.mp4
some gathered feedback:
=> refactor(create-qwik): enhanced create qwik cli

packages/qwik/src/cli/utils/integrations.ts, packages/qwik/src/cli/utils/utils.ts
fix: dashToTitlelCase to dashToTitleCase
=> fix: dashToTitlelCase to dashToTitleCase

packages/qwik/src/cli/add/run-add-command.ts, packages/qwik/src/cli/utils/log.ts
fix: delete unnecessary eslint disable rule no-console
=> fix: delete unnecessary eslint disable rule no-console

packages/docs/scripts/pages.json
I added my new portfolio to the pages list.
Thx for all Builder.IO!
=> Docs(pages.json): add new site to showcase room

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts, packages/qwik/src/optimizer/core/src/errors.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_invalid_references.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_ts_enums_issue_1341.snap, packages/qwik/src/optimizer/core/src/transform.rs
=> feat: allows referencing of module variables

packages/docs/src/routes/qwikcity/routing/index.mdx
Improve link nested-layout
Nope
=> docs: Improve link nested-layout

packages/eslint-plugin-qwik/src/validLexicalScope.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts
=> fix typo in eslint message

packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
=> fix: trailing slash with Link

packages/qwik/src/optimizer/core/src/parse.rs, starters/apps/e2e/src/components/effect-client/effect-client.tsx
=> fix: deprecated useClientEffect

packages/docs/src/routes/docs/components/lifecycle/index.mdx
NOTE in "When to use `useBrowserVisibleTask$()`" section at the end of the previous section
=> Remove duplicate NOTE

packages/qwik/src/core/render/ssr/render-ssr.unit.tsx, packages/qwik/src/core/state/context.ts, packages/qwik/src/core/style/qrl-styles.ts, starters/apps/e2e/src/components/styles/parent.css, starters/apps/e2e/src/components/styles/parent2.css, starters/apps/e2e/src/components/styles/styles.tsx, starters/e2e/e2e.style.spec.ts
=> fix: multiple styles scoped

packages/docs/src/routes/docs/components/lifecycle/index.mdx
=> typo: non -> not

packages/docs/src/routes/docs/components/lifecycle/index.mdx
=> changed useClientEffect$ -> useBrowserVisibleTask$

packages/qwik/src/core/container/store.unit.tsx, packages/qwik/src/core/render/dom/signals.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/state/common.ts, packages/qwik/src/core/state/signal.ts, starters/apps/e2e/src/components/signals/signals.tsx
=> fix: reactivity issue

packages/docs/src/routes/docs/components/context/index.mdx
=> Docs: Improved Context

packages/docs/src/routes/qwikcity/action/index.mdx
fixed statement import on code sample.
Fixed import on sample code.
=> docs: fixed typo on import statement

packages/docs/src/routes/docs/advanced/vite/index.mdx
=> docs: update vite docs

packages/docs/scripts/pages.json
Just learned Qwik JS and want to share my result using Qwik+React, Partytown and Qwik Speak.
Thank you.
=> Add keyboardz to Qwik showcases

packages/docs/src/routes/docs/concepts/reactivity/index.mdx, packages/docs/src/routes/docs/menu.md
Minor changes to the reactivity doc
=> Rective doc

packages/qwik/src/optimizer/src/plugins/plugin.ts
=> fix: test mode

packages/docs/src/routes/qwikcity/endpoints/index.mdx, packages/docs/src/routes/qwikcity/loader/index.mdx
Typo in the docs from `cookies` to `cookie` per type spec.
fixes #3053 
It was confusing to to use the code in the docs and have it error immediately. If not using TS with hints in your IDE, this could be a confusing problem to solve.
=> docs: renamed cookies to cookie

packages/docs/scripts/pages.json
Travelcalc is a web-application for travelers. It is a simpliefied currency converter, where user can set his country and where he is, and then convert foreign prices into the currency, which is understandable for user. It is also possible to set hourly rate to be able to convert some prices to working time.
* Qwik 0.17.5
* Qwik City 0.1.0
* Qwik Speak 0.5.1
* Tailwind 3.2.6
* FontAwesome 6.3.0
* Headless UI / React 1.7.10
* Sweetalert2 11.7.1
* Tippy 6.3.7
=> Add Travelcalc to showcase

packages/qwik-city/buildtime/context.ts, packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/optimizer/src/plugins/vite-server.ts, packages/qwik/src/optimizer/src/plugins/vite.ts
=> fix: custom srcDir

packages/qwik/src/core/container/pause.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: reactivity issue with deep: true

packages/qwik/src/core/qrl/qrl-class.ts, packages/qwik/src/core/use/use-core.ts, starters/apps/e2e/src/components/watch/watch.tsx, starters/e2e/e2e.watch.spec.ts
=> feat: support this in QRLs

packages/docs/src/routes/qwikcity/guides/mdx/index.mdx
=> docs: remove unused useStyle$

packages/docs/src/routes/examples/apps/visibility/clock/app.tsx
docs: useClientEffect to useBrowserVisibleTask
=> docs: useClientEffect to useBrowserVisibleTask

packages/docs/src/routes/docs/components/context/index.mdx
=> docs: fix typo Caveats

packages/docs/src/routes/qwikcity/api/index.mdx
docs: update RouteLocation type, add url field
=> docs: update RouteLocation type

packages/docs/src/routes/qwikcity/guides/static-site-generation/index.mdx
docs: modify visitors to visitor's
=> docs: visitors to visitor's

packages/docs/src/routes/qwikcity/api/index.mdx
docs: add code demo for api `useDocumentHead`
=> docs: add code demo for api useDocumentHead

packages/docs/src/routes/qwikcity/action/index.mdx
Fix bad link and remove unused headings
Nope
=> docs: fix bad link and remove unused headings

packages/qwik-city/middleware/request-handler/request-event.ts, starters/apps/qwikcity-test/src/routes/layout.tsx
=> fix: set locale regression

packages/qwik-dom/lib/DOMImplementation.js
=> chore: fix typo in DOMImplementation.js

packages/qwik/src/optimizer/src/plugins/plugin.ts
fixes #3160
fixes #3158
fixes #1901
=> fix: deps tracking

README.md
This PR add `yarn` and `pnpm` to sync with the web docs?
To ensure clarity about whether `yarn` and `pnpm` is supported or not.
=> docs(README): add `yarn` and `pnpm`

packages/qwik-city/middleware/request-handler/api.md, packages/qwik-city/middleware/request-handler/request-event.ts, packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts, packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/index.ts, packages/qwik-city/runtime/src/server-functions.ts, packages/qwik-city/runtime/src/types.ts, starters/apps/qwikcity-test/src/routes/(common)/actions/validated/index.ts, starters/apps/qwikcity-test/src/routes/(common)/actions/validated/index.tsx, starters/apps/qwikcity-test/src/routes/(common)/issue2644/index.tsx, starters/apps/qwikcity-test/src/routes/(common)/issue2644/other/index.tsx, starters/apps/qwikcity-test/src/routes/(common)/loaders/[id]/index.tsx, starters/apps/qwikcity-test/src/routes/issue-loader-serialization/action.tsx, starters/apps/qwikcity-test/src/routes/issue-loader/action.tsx
=> fix: action types

packages/docs/src/routes/qwikcity/menu.md
fixes: https://github.com/BuilderIO/qwik/issues/3157
=> docs: remove empty pages from qwik-city

packages/docs/src/routes/tutorial/hooks/use-signal/index.mdx
Updated spelling
Extremely Minor Spelling Mistake, which was spelled `fruite` in the tutorials
- 1. None Major, could cause confusion for non English Individuals.
=> docs: removed typo

packages/qwik-auth/src/index.ts
Added support for passing a callbackUrl to signing and signout.  Defaults to the current page.  This follows other @auth/core framework designs.
=> feat(qwik-auth): support callbackUrl for signin and signout

packages/docs/src/routes/docs/getting-started/index.mdx
avoids further situations like this: https://github.com/BuilderIO/qwik/issues/318
=> docs: remove `@latest` from yarn install cmd

packages/docs/src/routes/docs/getting-started/index.mdx
fix(docs): modify prerequisites to Node16.8
=> fix(docs): modify prerequisites to Node16.8

packages/qwik/src/core/api.md, packages/qwik/src/core/internal.ts, packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts, packages/qwik/src/core/state/signal.ts, packages/qwik/src/optimizer/core/src/collector.rs, packages/qwik/src/optimizer/core/src/props_destructuring.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_getter_generation.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_use_optimization.snap, packages/qwik/src/optimizer/core/src/transform.rs, packages/qwik/src/optimizer/core/src/words.rs, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: signal props passing

starters/features/auth/package.json
Add optimizeDeps to vite for @auth/core, fixes an error about cookie module not being optimized.
I'm not sure if this is the write way to do it, so opening this PR as a draft.
=> fix(qwik-auth): add @auth/core dep optimization

packages/docs/src/routes/qwikcity/routing/index.mdx
There is no mention of `skuId` in the entire section.
- 1. Fix docs by using existing example.
=> docs: update "Directory-based routing" section example

packages/docs/src/routes/qwikcity/advanced/speculative-module-fetching/index.mdx
=> docs: speculative module fetching (#3239)

packages/docs/src/routes/tutorial/introduction/resource/problem/app.tsx
In the tutorial Resource section, the initial problem's code is similar to the solution. This PR replaces the solution parts with placeholders.
=> docs: problem and solution on resource tutorial are no longer equal

packages/docs/src/components/builder-content/index.tsx, packages/docs/src/components/footer/footer.tsx, packages/docs/src/components/header/header.tsx, packages/docs/src/constants.ts, packages/docs/src/global.css
Move the docs footer to Builder for easier updating
=> docs: Manage docs site footer in Builder

packages/docs/src/routes/docs/getting-started/index.mdx
=> docs: fix component link

packages/qwik/src/qwikloader.ts
=> chore: make statement smooth

packages/docs/src/components/docsearch/doc-search-modal.tsx, packages/docs/src/components/docsearch/search-box.tsx, packages/docs/src/components/header/header.tsx, packages/docs/src/repl/editor.tsx, packages/docs/src/repl/repl.tsx, packages/docs/src/routes/examples/apps/visibility/clock/app.tsx, packages/docs/src/routes/playground/index!.tsx
fix(docs): replace useBrowserVisibleTask$ to useVisibleTask$
=> fix(docs): replace useBrowserVisibleTask$ to useVisibleTask$

packages/docs/src/routes/docs/components/overview/index.mdx, packages/docs/src/routes/tutorial/events/synchronous/index.mdx
fix(docs): two error reference to usebrowservisibletask
=> fix(docs): two error reference to usebrowservisibletask

packages/docs/src/routes/qwikcity/route-loader/index.mdx
=> docs: fix title for routeLoader$

packages/docs/src/routes/integrations/integration/react/index.mdx
=> docs: fix missing arrow

packages/docs/src/routes/docs/components/context/index.mdx, packages/docs/src/routes/docs/components/events/index.mdx, packages/docs/src/routes/docs/components/lifecycle/index.mdx, packages/docs/src/routes/docs/components/lite-components/index.mdx, packages/docs/src/routes/docs/components/overview/index.mdx, packages/docs/src/routes/docs/components/projection/index.mdx, packages/docs/src/routes/docs/components/rendering/index.mdx, packages/docs/src/routes/docs/components/resource/index.mdx, packages/docs/src/routes/docs/components/state/index.mdx, packages/docs/src/routes/docs/components/styles/index.mdx
docs: add missing import statement, for better ux.
=> docs: add missing import statement

packages/docs/scripts/pages.json
Hello there, we've written our landing page, https://wope.com/ in Qwik.js and proud of the results we've gotten a perfect performance score (most of time, though). We would love to show it in the showcase on Qwik docs. :)
https://twitter.com/i/status/1621301824090259462
=> docs: add Wope to showcase

packages/docs/src/routes/media/index.tsx
https://docs.google.com/presentation/d/1q0eILmAAdFyE0tHkvd_fSuFtcHsHzUn0nZnz5FDgU4k/edit#slide=id.g13225ffe116_6_234
=> docs: add qwik city presentation example

packages/docs/src/routes/qwikcity/routing/index.mdx
modify solidStart routing link
=> fix(docs): modify solidStart routing link

packages/qwik-city/static/index.ts
chore: remove unnecessary  eslint-disable no-console
=> chore: remove unnecessary  eslint-disable no-console

packages/docs/public/_redirects, packages/docs/src/routes/community/groups/index.mdx
=> docs: update discord link

packages/qwik/src/optimizer/src/plugins/vite-utils.ts
=> fix: findLocation

packages/qwik/src/core/container/serializers.ts, starters/apps/qwikcity-test/src/routes/issue-loader-serialization/index.tsx, starters/e2e/qwikcity/loaders.spec.ts
=> fix: serialize state with multiple subscribers

packages/qwik/src/core/render/dom/operations.ts, packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> fix: vdom reordering

packages/qwik/src/core/api.md, packages/qwik/src/core/container/container.ts, packages/qwik/src/core/container/resume.ts, packages/qwik/src/core/render/dom/notify-render.ts, packages/qwik/src/core/render/dom/operations.ts, packages/qwik/src/core/render/dom/render-dom.ts, packages/qwik/src/core/render/dom/signals.ts, packages/qwik/src/core/render/dom/virtual-element.ts, packages/qwik/src/core/render/dom/visitor.ts, packages/qwik/src/core/render/jsx/jsx-runtime.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/state/common.ts, packages/qwik/src/core/state/context.ts, packages/qwik/src/core/util/element.ts, packages/qwik/src/jsx-runtime/api.md, starters/apps/e2e/src/components/render/render.tsx, starters/apps/e2e/src/components/slot/slot-remove.tsx, starters/apps/e2e/src/components/slot/slot.tsx, starters/apps/e2e/src/components/styles/styles.tsx, starters/apps/e2e/src/root.tsx, starters/apps/qwikcity-test/src/components/menu/menu.tsx, starters/apps/qwikcity-test/src/routes/(common)/actions/index.tsx, starters/dev-server.ts, starters/e2e/e2e.render.spec.ts, starters/e2e/e2e.slot.spec.ts, starters/e2e/qwikcity/auth.spec.ts, starters/e2e/qwikcity/nav.spec.ts
fixes #3219
fixes #3178
fixes #2751
=> fix: render bugs

packages/eslint-plugin-qwik/src/loaderLocation.ts
=> fix(eslint): allow plugin for loaders

packages/qwik-city/middleware/request-handler/api.md, packages/qwik-city/middleware/request-handler/index.ts, packages/qwik-city/middleware/request-handler/types.ts, packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/index.ts, packages/qwik-city/runtime/src/types.ts
=> fix: reduce API surface of server$

packages/qwik-city/runtime/src/server-functions.ts
=> fix: allow calling server$ within the server

packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
=> fix: compare host instead of origin in dev mode

packages/docs/src/entry.dev.tsx, packages/docs/src/routes/playground/index!.tsx
fix(docs): merge duplicate import statement
=> fix(docs): merge duplicate import statement

packages/docs/src/routes/integrations/deployments/azure-swa/index.mdx
- Add missing information for GitHub deployment.
- Add docs how to deploy with other CI systems
=> docs: Improve deployment documentation for Azure SWA

packages/docs/src/routes/media/index.tsx
fix(docs): correct Youtube to YouTube
=> fix(docs): correct Youtube to YouTube

packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts, packages/qwik-city/runtime/src/server-functions.ts
routeAction$() was not working when it was the only action in the whole app.
=> fix: routeAction

packages/docs/src/routes/qwikcity/routing/index.mdx
=> fix(docs):add missing json fn

packages/qwik/src/core/render/jsx/jsx-runtime.ts, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.attributes.spec.ts, starters/e2e/e2e.computed.spec.ts, starters/e2e/e2e.containers.spec.ts, starters/e2e/e2e.context.spec.ts, starters/e2e/e2e.effect-client.spec.ts, starters/e2e/e2e.events.spec.ts, starters/e2e/e2e.factory.spec.ts, starters/e2e/e2e.lexical-scope.spec.ts, starters/e2e/e2e.mount.spec.ts, starters/e2e/e2e.noresume.spec.ts, starters/e2e/e2e.ref.spec.ts, starters/e2e/e2e.render.spec.ts, starters/e2e/e2e.resource.spec.ts, starters/e2e/e2e.resuming.spec.ts, starters/e2e/e2e.signals.spec.ts, starters/e2e/e2e.slot.spec.ts, starters/e2e/e2e.streaming.spec.ts, starters/e2e/e2e.style.spec.ts, starters/e2e/e2e.toggle.spec.ts, starters/e2e/e2e.two-listeners.spec.ts, starters/e2e/e2e.use-id.spec.ts, starters/e2e/e2e.watch.spec.ts, starters/e2e/starter-partytown.spec.ts, starters/e2e/todo-old.spec.ts, starters/e2e/todo.spec.ts
=> fix: dynamic tag name rendering

packages/docs/src/routes/qwikcity/pages/index.mdx
=> fix(docs): add missing import statement

packages/qwik/src/core/render/ssr/render-ssr.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: signal rendering of innerHTML

packages/eslint-plugin-qwik/index.ts, packages/eslint-plugin-qwik/src/unusedServer.ts
=> feat: add eslint rule for unused server$

packages/create-qwik/create-interactive.ts
Some styling changes and improvements on the create CLI 🎉
=> fix(cli): minore CLI adjustments

packages/qwik/src/core/render/jsx/types/jsx-generated.ts, packages/qwik/src/optimizer/core/src/is_immutable.rs, packages/qwik/src/optimizer/core/src/props_destructuring.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_children.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_multiple_children.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_input_bind.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_mutable_children.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__relative_paths.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/optimizer/core/src/transform.rs, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
```tsx
export default component$(() => {
const value = useSignal('');
return (
<>
<input bind:value={value} />
<div>Value: {value}</div>
</>
);
});
```
=> feat: bind:value for input

packages/qwik-city/buildtime/markdown/mdx.ts, packages/qwik-city/buildtime/vite/plugin.ts
=> fix: base64url is not supported

starters/apps/basic/src/routes/demo/todolist/index.tsx
Do not allow empty data loading.
If the required one is disabled in html, validate
Current behavior: Allows input to be loaded with whitespace.
Result behavior:
=> feat(starters-todolist): Add validation to text

packages/qwik/src/build/index.ts, starters/features/vitest/package.json
=> fix: isDev in external library

packages/docs/src/components/docsearch/handleSearch.ts, packages/docs/src/routes/(ecosystem)/ecosystem/index.tsx
temp ecosystem page on mobile is not usable. till we have the final designs, this should fix the most important things.
=> fix: ecosystem page for mobile

packages/qwik/src/optimizer/src/manifest.ts
=> fix: do not include \u paths in q-manifest

starters/apps/base/.vscode/qwik-city.code-snippets
=> chore: fix starter code snippet

packages/qwik-city/runtime/src/routing.unit.ts
=> test: add pathname matching tests with a period

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
=> docs: typos

packages/docs/src/routes/deployments/node/index.mdx, packages/docs/src/routes/docs/(qwik)/advanced/vite/index.mdx, packages/docs/src/routes/docs/(qwik)/faq/index.mdx, packages/docs/src/routes/integrations/integration/overview/index.mdx, packages/qwik/src/optimizer/src/platform.ts, packages/qwik/src/optimizer/src/plugins/vite-server.ts, packages/qwik/src/optimizer/src/plugins/vite.ts, scripts/index.ts, scripts/package-json.ts, scripts/submodule-optimizer.ts, scripts/submodule-server.ts, scripts/util.ts, starters/apps/documentation-site/src/routes/index.tsx
=> docs: Node.js typos

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx, starters/apps/base/.vscode/qwik-city.code-snippets
=> docs: fix code snippet on page `routeLoader$()`

packages/docs/src/routes/docs/(qwik)/cheat/best-practices/index.mdx
=> docs: update links

packages/docs/src/routes/docs/(qwik)/components/resource/index.mdx
found a couple more minor things to get in
cc @zanettin
=> docs: fix and simplify resource example

packages/docs/src/components/code-block/code-block.tsx, packages/docs/src/components/code-example/index.css, packages/docs/src/components/code-example/index.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/example/counter/index!.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/example/lazy/index!.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/example/props/index!.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/example/ref/index!.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/example/simple-component/index!.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/example/two-components/index!.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx, packages/docs/src/routes/docs/(qwik)/components/resource/index.mdx, packages/docs/vite.config.ts, packages/docs/vite.source-resolver.ts
=> docs: add live examples

packages/docs/src/global.css
fixed header height on desktop
=> make header smaller on desktop.

starters/README.md, starters/apps/library/README.md, starters/apps/library/src/components/counter/counter.tsx, starters/apps/library/src/components/logo/logo.tsx
=> Starter-fixes

packages/docs/src/components/builder-content/index.tsx, packages/docs/src/components/header/header.css, packages/docs/src/components/header/header.tsx, packages/docs/src/components/panel-toggle/panel-toggle.css, packages/docs/src/components/sidebar/sidebar.css, packages/docs/src/components/sidebar/sidebar.tsx, packages/docs/src/global.css, packages/docs/src/repl/repl.css, packages/docs/src/routes/docs/docs.css, packages/docs/src/routes/docs/layout.tsx, packages/docs/src/routes/examples/[...id]/examples.css, packages/docs/src/routes/playground/playground.css, packages/docs/src/routes/tutorial/tutorial.css
- better sizing of the header and logo
- sticky scrolling
- general cleanup
https://user-images.githubusercontent.com/844291/228934676-2423483c-4b66-444b-b58c-de7ab2145934.mov
=> header styling fixes

packages/docs/src/components/builder-content/index.tsx, packages/docs/src/repl/repl.css
seems tailwind classes not working there, this change was not critical so lets just roll it back to fix stuff
=> docs: fix for cloudflare build

packages/docs/src/routes/docs/(qwik)/index.mdx
=> docs: Improved docs overview page

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx
Route loaders are for fetching data, so lets use real world examples so people properly understand
=> docs: More real world examples for route loader

packages/create-qwik/create-interactive.ts
=> fix: cli background install

packages/docs/src/routes/docs/(qwik)/components/context/index.mdx, packages/docs/src/routes/docs/(qwik)/index.mdx
current ones are quite complex immediately, lets make it easier like react's context docs
=> docs: Make the intro to context simpler and easier to mentally parse

packages/docs/src/routes/docs/(qwik)/faq/index.mdx
=> docs: misspelling fixes

packages/docs/src/routes/(ecosystem)/media/index.tsx, packages/docs/src/routes/(ecosystem)/media/media.css
Add resources links (youtube, blogs, podcasts)
=> Ecosystem-add

packages/docs/scripts/pages.json
This PR adds upester to the Showcase of apps built with Qwik.
The upester app was initially built with Angular, then we decided to port it to Qwik for the superior SSR/SSG capabilities. It's been fun and educational, and upester is now 100% Qwik.
A big "Thank you!" to the Qwik maintainers!
Asking to add upester to the Showcase of apps made with Qwik.
No particular use case. If accepted, upester will be featured on the Showcase page.
- [n/a] I have made corresponding changes to the documentation
- [n/a] Added new tests to cover the fix / functionality
=> docs: Add upester to the Showcase

packages/docs/scripts/pages.json
=> Revert "docs: Add upester to the Showcase"

packages/docs/src/routes/demo/tasks/cleanup/index.tsx, packages/docs/src/routes/demo/tasks/track-fn/index.tsx, packages/docs/src/routes/demo/tasks/track-server-guard/index.tsx, packages/docs/src/routes/demo/tasks/track/index.tsx, packages/docs/src/routes/demo/tasks/use-task/index.tsx, packages/docs/src/routes/demo/tasks/use-visible-task-eager/index.tsx, packages/docs/src/routes/demo/tasks/use-visible-task/index.tsx, packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx
=> docs: flushed out tasks docs

packages/docs/adapters/cloudflare-pages/vite.config.ts, packages/docs/src/routes/demo/api/add/index.tsx, packages/docs/src/routes/demo/tasks/resource/index.tsx, packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx, packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
=> Pr docs cleanup

packages/docs/src/routes/integrations/postcss/index.mdx
=> docs: update PostCSS integration docs

packages/docs/src/routes/docs/(qwik)/faq/index.mdx
=> docs: update FAQ for qwik

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx
I think it should be `important` rather than `import` 🤔.
=> docs: fix a typo in the `noSerialize()` section

packages/docs/src/components/on-this-page/on-this-page.tsx
=> fix: Edit this Page

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx
Fix example.
https://discord.com/channels/842438759945601056/843151429479956510/1092117432832892969
=> Fix routeLoader doc mistake

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx
=> docs: update failure docs.

starters/apps/base/README.md
=> Fixed typo in README.md

packages/qwik/src/core/render/dom/operations.ts, packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/attributes/attributes.tsx, starters/e2e/e2e.attributes.spec.ts
=> feat: select value rendering

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx
=> docs: Fixed QRL link

packages/qwik-auth/package.json, starters/features/auth/package.json
=> chore: release qwik auth

starters/apps/base/.vscode/qwik.code-snippets
=> starters: code snippets useBrowserVisibleTask -> useVisibleTask

.vscode/qwik.code-snippets
=> docs: added code snippets

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx
=> docs: small changes

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
=> docs: improved folder structure

packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx, packages/docs/src/routes/docs/(qwik)/advanced/optimizer/index.mdx, packages/docs/src/routes/docs/(qwik)/advanced/qrl/index.mdx, packages/docs/src/routes/docs/(qwik)/advanced/vite/index.mdx, packages/docs/src/routes/docs/(qwik)/components/events/index.mdx, packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx, packages/docs/src/routes/docs/(qwik)/components/styles/index.mdx, packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx, packages/docs/src/routes/docs/(qwik)/faq/index.mdx, packages/docs/src/routes/docs/(qwikcity)/advanced/menu/index.mdx, packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx, packages/docs/src/routes/docs/(qwikcity)/advanced/static-assets/index.mdx, packages/docs/src/routes/docs/(qwikcity)/api/index.mdx, packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx, packages/docs/src/routes/docs/(qwikcity)/guides/mdx/index.mdx, packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx, packages/docs/src/routes/docs/(qwikcity)/layout/index.mdx, packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx, packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx, packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
=> docs: add title in code block

packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts
fixes #3641
fixes #3483
fixes #3297
=> fix: node bundling

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-react/index.mdx
=> docs: onInput$ -> bind:value

packages/qwik-city/runtime/src/api.md, packages/qwik-city/runtime/src/types.ts, packages/qwik/src/core/state/signal.ts, packages/qwik/src/core/use/use-task.ts
it always return the awaited value
fixes #3528
=> fix: types useComputed

packages/docs/src/routes/docs/(qwik)/components/context/index.mdx
=> docs: small typo

packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx
=> docs: update optimizer example

packages/docs/src/routes/deployments/azure-swa/index.mdx, packages/docs/src/routes/deployments/cloudflare-pages/index.mdx, packages/docs/src/routes/deployments/gcp-cloud-run/index.mdx, packages/docs/src/routes/deployments/netlify-edge/index.mdx, packages/docs/src/routes/deployments/vercel-edge/index.mdx, packages/docs/src/routes/docs/(qwik)/advanced/custom-build-dir/index.mdx, packages/docs/src/routes/docs/(qwik)/advanced/vite/index.mdx, packages/docs/src/routes/integrations/partytown/index.mdx, packages/docs/src/routes/integrations/postcss/index.mdx, packages/docs/src/routes/integrations/react/index.mdx, packages/docs/src/routes/integrations/styled-vanilla-extract/index.mdx, packages/docs/src/routes/integrations/tailwind/index.mdx, packages/docs/src/routes/integrations/vitest/index.mdx
=> docs: added more titles

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
=> docs: add asterisk to 'use' for more clarity

packages/docs/src/routes/docs/(qwikcity)/api/index.mdx, packages/docs/src/routes/docs/(qwikcity)/endpoints/index.mdx
=> docs: added onGet

packages/docs/src/routes/community/projects/index.mdx, packages/docs/src/routes/docs/menu.md
=> docs: Improve projects

.vscode/extenstions.json
=> added recommeded extenstion.json

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
=> docs(file name): it corrects the English of the sentence. Precisely the tense used in this sentence

packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx
- [x ] Docs
Streamline Best Practices.
Streamline the docs. 
- [x ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
=> Docs: Best Practices

packages/docs/src/components/code-sandbox/index.css, packages/docs/src/components/code-sandbox/index.tsx, packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
and clean up some styles, like add a max width to some of the huge code examples that you don't need to even see the whole thing - similar to react docs
=> docs: add code highlights to getting started

packages/docs/src/routes/docs/(qwik)/faq/index.mdx
=> Update link in FAQ

packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> fix: reorder children issue

README.md, packages/docs/README.md
I meant to update the main readme in a previous PR but accidentally updated the docs site readme
this revers the docs readme and applies the changes to the main readme
=> docs: readme fixes

packages/qwik-city/runtime/src/server-functions.ts, packages/qwik/src/core/state/store.ts, starters/apps/qwikcity-test/src/routes/(common)/treeshaking/index.tsx, starters/apps/qwikcity-test/src/routes/issue2890/b/index.tsx
=> fix: routeLoader can return undefined

packages/qwik/src/core/api.md, packages/qwik/src/core/use/use-task.ts, starters/apps/e2e/src/components/resource/resource-fn.tsx
=> fix: useResource type

packages/docs/src/components/docsearch/doc-search-modal.tsx, packages/docs/src/components/docsearch/doc-search.css, packages/docs/src/components/docsearch/doc-search.tsx, packages/docs/src/components/docsearch/result.tsx, packages/docs/src/global.css
show the AI results side by side to our normal search results so you can look at both together
https://user-images.githubusercontent.com/844291/232127889-ab53a3a9-17d9-46c7-bb44-977237c943f0.mov
=> docs: UX improvements for AI search

packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx
=> fix `Implantation` typo all over the file

packages/docs/src/components/home-page-v2/callout.tsx
=> docs: fix typo in callout.tsx

packages/eslint-plugin-qwik/src/validLexicalScope.ts
=> fix(eslint-plugin-qwik): remove warning for bigint now that it can be serialized

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/useMethodUsage.ts
=> fix(eslint): allow use method inside other use methods

Cargo.lock, packages/qwik/src/optimizer/core/Cargo.toml, packages/qwik/src/optimizer/core/src/parse.rs, packages/qwik/src/optimizer/core/src/props_destructuring.rs, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_exports.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_functional_component_2.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_invalid_references.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_optimization_issue_3795.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_qwik_conflict.snap, packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_reg_ctx_name_hooks_hoisted.snap, packages/qwik/src/optimizer/core/src/test.rs, packages/qwik/src/wasm/Cargo.lock, starters/apps/e2e/src/components/render/render.tsx, starters/e2e/e2e.render.spec.ts
=> fix: agressive optimizer inlining

packages/qwik/src/core/render/dom/visitor.ts, starters/apps/e2e/src/components/slot/slot.tsx, starters/e2e/e2e.slot.spec.ts
=> fix: slot creation forgets vdom

packages/qwik/src/core/render/dom/render.unit.tsx, packages/qwik/src/core/render/jsx/types/jsx-qwik-elements.ts, starters/apps/e2e/src/components/render/render.tsx
=> fix: children types

scripts/package-json.ts
=> fix: default prod build for node

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx, packages/qwik-city/middleware/request-handler/response-page.ts, packages/qwik-city/runtime/src/server-functions.ts, packages/qwik-city/runtime/src/types.ts, packages/qwik/src/core/render/dom/render-dom.ts, packages/qwik/src/core/render/execute-component.ts, packages/qwik/src/core/render/ssr/render-ssr.ts, packages/qwik/src/core/use/use-env-data.ts, packages/qwik/src/core/use/use-task.ts
=> feat: server$ this will be defined most of the times

packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/validLexicalScope.ts
=> fix: allow enum literals

packages/docs/src/components/docsearch/doc-search.css, packages/docs/src/components/header/header.css
make search available for mobile users as well as requested by Steve (https://discord.com/channels/842438759945601056/1041016608946135161/1096813726285439017)
https://user-images.githubusercontent.com/3241476/232256022-423a7e4e-7185-4f14-881c-2d67acb34c4a.mp4
=> docs: add mobile search

packages/qwik/src/core/render/jsx/jsx-runtime.ts
=> fix: remove jsx warning

packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts, packages/qwik-city/runtime/src/server-functions.ts
=> feat: serialize server$ exceptions

packages/docs/src/routes/demo/demo-reset.css, packages/docs/src/routes/demo/getting-started/03-posting-data/index.tsx, packages/docs/src/routes/demo/getting-started/04-state/index.tsx, packages/docs/src/routes/demo/getting-started/05-tasks/index.tsx, packages/docs/src/routes/demo/getting-started/06-styling/index.tsx, packages/docs/src/routes/demo/slot/advanced/index.tsx, packages/docs/src/routes/demo/slot/basic/index.tsx, packages/docs/src/routes/demo/slot/named/index.css, packages/docs/src/routes/demo/slot/named/index.tsx, packages/docs/src/routes/demo/slot/unprojected/index.tsx, packages/docs/src/routes/demo/state/no-serialize/index.tsx, packages/docs/src/routes/demo/state/no-serialize/monaco.tsx, packages/docs/src/routes/docs/(qwik)/components/slots/index.mdx, packages/docs/src/routes/docs/(qwik)/components/state/index.mdx, packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
=> docs: update slot

packages/qwik/src/core/state/common.ts, starters/apps/e2e/src/components/signals/signals.tsx, starters/e2e/e2e.signals.spec.ts
=> fix: treshaking signals crash

packages/eslint-plugin-qwik/src/useMethodUsage.ts, packages/qwik/src/core/api.md, packages/qwik/src/core/use/use-on.ts
=> feat: allow undefined useOn QRLs

packages/qwik-city/adapters/shared/vite/index.ts
=> fix: always generate 404.html

packages/qwik/src/optimizer/src/plugins/plugin.ts, packages/qwik/src/optimizer/src/plugins/plugin.unit.ts, packages/qwik/src/optimizer/src/plugins/vite.ts, packages/qwik/src/optimizer/src/plugins/vite.unit.ts, starters/apps/e2e/src/components/build-variables/build.tsx, starters/apps/e2e/src/entry.ssr.tsx, starters/apps/e2e/src/root.tsx, starters/e2e/e2e.build-variables.spec.ts
=> fix: build variables

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
=> docs: correct typos and update import statements

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx
=> docs: correct typos for route loader

packages/docs/src/routes/docs/(qwik)/concepts/reactivity/index.mdx
closes https://github.com/BuilderIO/qwik/issues/3823
=> docs: typo fix

packages/docs/src/routes/docs/(qwikcity)/endpoints/index.mdx
=> docs: correct typos and ensure consistency

packages/qwik-city/runtime/src/qwik-city-component.tsx, starters/apps/qwikcity-test/src/routes/(common)/loaders/[id]/index.tsx
=> fix: recursive tracking loaders

packages/docs/src/routes/demo/component/lazy/index.tsx, packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
=> docs: fix 404 on lazy example

packages/docs/src/routes/docs/(qwikcity)/guides/react-cheat-sheet/index.mdx
I added it because I thought the advantages would be more highlighted if there was an example like this.
=> Docs: Add "Props Use Example" to react vs qwik page

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx
=> docs: correct typos for env variables

.github/PULL_REQUEST_TEMPLATE.md
With new contributors excited to see their work acknowledged and valued, this sets community expectations and path forward.
**Future Steps** -- We need to provide a process and landing spot to submit 3rd Party Community Add-Ons for inclusion in a library (possibly with stars / up-votes).
=> Update PR template to set community expectations

packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx
=> docs: add missing import for Slot

packages/docs/src/routes/docs/(qwik)/advanced/optimizer/index.mdx
=> docs: replace store with count

.github/PULL_REQUEST_TEMPLATE.md
=> docs: update PR template for types / typos

package.json, packages/eslint-plugin-qwik/qwik.unit.ts, packages/eslint-plugin-qwik/src/useMethodUsage.ts, pnpm-lock.yaml
=> fix(eslint): allow use inside objects

packages/docs/public/ecosystem/qwik-amsterdam.svg, packages/docs/src/routes/(ecosystem)/ecosystem.json, packages/docs/src/routes/community/groups/index.mdx
Add Qwik Amsterdam Community link
=> docs: add qwik amsterdam community link

packages/docs/src/routes/docs/integrations/authjs/index.mdx, starters/features/auth/src/routes/plugin@auth.ts
Revert environment variable changes that were introduced in #3712 that contradict best practices.
=> fix(docs/auth): revert env variable changes

packages/docs/package.json, packages/docs/src/routes/demo/integration/img/qwik-image/index.tsx, packages/docs/src/routes/docs/integrations/image-optimization/index.mdx, pnpm-lock.yaml
I create the [Qwik Image](https://github.com/qwikifiers/qwik-image) component inside the qwikifiers GitHub account.
This component follow the Qwik APIs guidelines and I think this is a great plus.
This PR is to add qwik-image library inside the Image Optimisation section.
=> docs: add qwik-image inside the Image Optimisation section

packages/docs/src/routes/(ecosystem)/ecosystem/ecosystem-menu.tsx, packages/docs/src/routes/(ecosystem)/ecosystem/index.tsx, packages/docs/src/routes/(ecosystem)/media/index.tsx, packages/docs/src/routes/docs/(qwik)/index.mdx
=> docs: adde courses section

packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx
tiny docs adjustments. great article btw @adamdbradley 🙏
=> docs: tiny adjustments
