QwikDev/qwik

packages/qwik/src/core/container/container.ts
packages/qwik/src/core/render/dom/visitor.ts
packages/qwik/src/core/render/ssr/render-ssr.ts
starters/apps/e2e/src/components/events/events.tsx
starters/e2e/e2e.events.spec.ts

fix: dynamic rendering on window listeners

---

packages/docs/src/components/builder-content/index.tsx

docs: allow rendering any Builder content with both SDK or REST

---

packages/docs/src/routes/docs/integrations/modular-forms/index.mdx
packages/docs/src/routes/docs/integrations/prisma/index.mdx
packages/docs/src/routes/docs/menu.md

At @mhevery's  request, I wrote a Modular Forms integration guide for Qwik and added it to the docs. Thank you for this opportunity!

Add Modular Forms integration guide to docs

---

starters/adapters/azure-swa/src/entry.azure-swa.tsx
starters/adapters/cloudflare-pages/src/entry.cloudflare-pages.tsx
starters/adapters/deno/src/entry.deno.tsx
starters/adapters/express/src/entry.express.tsx
starters/adapters/fastify/src/entry.fastify.tsx
starters/adapters/netlify-edge/src/entry.netlify-edge.tsx
starters/adapters/vercel-edge/src/entry.vercel-edge.tsx

@adamdbradley I've noticed you fixed the comments in https://github.com/BuilderIO/qwik/pull/3959 (I was about to do it as well but you beat me to it! 😁)
I think you've missed a broken URL, also a couple of the adapters don't have the comment (which they should I guess for consistency sake)
Opening this PR with such minor changes 🙂 
PS: unimportant but I've also added the `/docs/` path to all the urls just for consistency sake (if the version without the `docs` is preferred let me know and I can update the url to be consistent with that)

chore(adapters entry file comments): slightly update/fix the adapters entry file initial comments

---

packages/docs/src/routes/docs/integrations/index.mdx
packages/docs/src/routes/docs/integrations/integrations-list.tsx
packages/docs/src/routes/docs/integrations/nx/index.mdx
packages/docs/src/routes/docs/menu.md

Qwik and nx integration
plus improved the integration overview

docs: added nx and qwik-nx integration

---

packages/docs/src/routes/docs/menu.md

docs: add deno in deployments section

---

packages/qwik-city/runtime/src/server-functions.ts

fix: pass this in server$

---

packages/docs/src/routes/docs/(qwik)/index.mdx

docs: added space between sentences.

---

packages/docs/functions/[[path]].ts
packages/docs/src/routes/docs/deployments/cloudflare-pages/index.mdx
packages/qwik-city/adapters/cloudflare-pages/vite/index.ts
packages/qwik-city/middleware/cloudflare-pages/api.md
packages/qwik-city/middleware/cloudflare-pages/index.ts
starters/adapters/cloudflare-pages/functions/[[path]].ts
starters/adapters/cloudflare-pages/src/entry.cloudflare-pages.tsx

update the cloudflare pages adapter to use the _worker.js (the preferred advanced mode), this will allow various improvements in the future

feat(cloudflare-pages-adapter): refactor the cloudflare pages adapter to use _worker.js

---

packages/qwik-city/runtime/src/api.md
packages/qwik-city/runtime/src/types.ts
packages/supabase-auth-helpers-qwik/package.json
packages/supabase-auth-helpers-qwik/src/utils/createSupabaseClient.ts
starters/apps/qwikcity-test/src/routes/(common)/actions/validated/index.tsx
starters/apps/qwikcity-test/src/routes/(common)/loaders/[id]/index.tsx

fix: routeAction types

---

packages/qwik-city/runtime/src/api.md
packages/qwik-city/runtime/src/link-component.tsx
packages/qwik-city/runtime/src/qwik-city-component.tsx
packages/qwik-city/runtime/src/types.ts
packages/qwik/src/core/api.md
packages/qwik/src/core/internal.ts
packages/qwik/src/core/render/dom/visitor.ts
packages/qwik/src/core/use/use-core.ts

Feat / fix for view transition api

feat: view transition api

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

Docs: remove non-inclusive language.

---

packages/docs/src/routes/docs/integrations/supabase/index.mdx

use inclusive language: remove the word "simple" (according to [Google Documentation style guide](https://developers.google.com/style/word-list)):
- add link to client example + note.
- add missing `$` for `routeAction$`

docs: Supabase inclusive language + add link to client example

---

packages/docs/src/routes/docs/(qwik)/index.mdx

All other sections use emoji, so lets be consistent

docs: Use an emoji for courses, to be consistent with other sections

---

packages/docs/src/routes/(ecosystem)/media/index.tsx

docs:  could I add course spanish edition

---

packages/docs/src/components/header/header.css
packages/docs/vite.config.ts

links were not centered the way the are supposed to be

docs: fix header positioning

---

packages/docs/src/components/header/header.css
packages/docs/src/components/header/header.tsx

docs: fix header styles

---

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

docs: add limitation to inline components

---

packages/qwik-city/middleware/deno/index.ts

fix: remove Deno.version since it's not available in Deno Deploy

---

packages/docs/src/routes/docs/integrations/image-optimization/index.mdx

chore: add missing contributor

---

packages/docs/src/routes/docs/integrations/tailwind/index.mdx

The current documentations claims that there are required extra steps, which no longer appears to be the case. Some other details updated as well.

Update Tailwind documentation

---

packages/qwik-city/adapters/cloudflare-pages/vite/index.ts
packages/qwik-city/utils/fs.ts

fix: cloudflare worker deploy from windows

---

packages/docs/src/routes/docs/(qwikcity)/guides/react-cheat-sheet/index.mdx

There is a typo in one of the code examples.

docs: change state to count

---

packages/docs/src/routes/docs/(qwikcity)/guides/mdx/index.mdx

Info about how to access frontmatter data.
Fixes #1930

docs: extend mdx section with reading frontmatter

---

packages/docs/scripts/pages.json

docs: add showcase

---

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx

docs: remove empty line

---

packages/docs/src/routes/docs/integrations/supabase/index.mdx

Fix docs on how to access env vars for Supabase.

Fix Supabase docs

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: added titles

---

packages/docs/src/routes/docs/(qwikcity)/guides/react-cheat-sheet/index.mdx

docs: update code snippet

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

Add a missing export in the documentation, in the example for the style section.

docs: fix export of hook useJokeVoteAction

---

packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx

Added one line for the easy reference of Angular Developers.

Update index.mdx for an easy reference to Angular Developers

---

packages/qwik-city/runtime/src/init-popstate.txt
starters/apps/qwikcity-test/src/routes/issue4100/index.tsx
starters/e2e/qwikcity/nav.spec.ts

fix: hash navigation

---

starters/apps/base/src/entry.ssr.tsx
starters/apps/library/src/entry.ssr.tsx

Simple typo fix on description of entry ssr starter app

Fix typo in entry ssr starter app

---

packages/docs/src/routes/docs/(qwikcity)/project-structure/index.mdx

docs: modify link to prevent redirection.

---

packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx

docs: code highlight 

---

packages/qwik/src/core/state/store.ts
starters/apps/e2e/src/components/signals/signals.tsx
starters/e2e/e2e.signals.spec.ts

fix: adding props to store

---

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx

docs: fix typo in useVisibleTask

---

packages/docs/src/routes/api/qwik/api.json
packages/docs/src/routes/api/qwik/index.md
packages/qwik/src/core/api.md
packages/qwik/src/core/component/component.public.ts
packages/qwik/src/core/qrl/qrl.public.ts

fix: allow async functions for any $ prop

---

packages/docs/src/routes/(ecosystem)/media/index.tsx

I have added my new free qwik course
Also my Podcast episode 113, which is about qwik v1.0
- [ X ] Docs / tests / types / typos
I have finished my new free course about qwik which contains more than 8 hours of video, homework and almost 100 videos—everything's qwik related.
This is a Spanish course by the way.
- [ X ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ X ] I have performed a self-review of my own code
- [ X ] I have made corresponding changes to the documentation

New Course and Podcast

---

packages/docs/src/routes/docs/integrations/tauri/index.mdx
packages/docs/src/routes/docs/menu.md

docs: add tauri to integrations

---

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx

https://github.com/BuilderIO/qwik/issues/4179#issuecomment-1546099581

docs: :memo: add class prop showcase

---

packages/create-qwik/create-interactive.ts

cli: created app -> app created

---

scripts/api.ts
tsconfig.json

fix: add frontmatter named export

---

packages/qwik/src/core/container/resume.ts
packages/qwik/src/core/render/dom/virtual-element.ts
packages/qwik/src/core/render/dom/visitor.ts
starters/apps/e2e/src/components/slot/slot.tsx
starters/e2e/e2e.slot.spec.ts

fix: rendering content projection inside svg

---

packages/docs/package.json
starters/adapters/cloudflare-pages/package.json

fix# https://github.com/cloudflare/workers-sdk/issues/3220

fix: correct cloudflare starter (#4232)

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

docs: state: add types for method example

---

packages/docs/src/routes/docs/(qwikcity)/guides/react-cheat-sheet/index.mdx

docs: update react code snippets

---

packages/docs/src/routes/docs/menu.md

adjust sort order of integrations and deployments

docs: menu sort order

---

packages/qwik/src/core/render/dom/signals.ts
packages/qwik/src/core/state/common.ts
starters/apps/e2e/src/components/render/render.tsx
starters/apps/e2e/src/components/signals/signals.tsx
starters/apps/e2e/src/components/slot/slot.tsx
starters/e2e/e2e.signals.spec.ts

fix: variable subscription signals

---

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx

docs: Fix typo on (qwik)/components/events/index.mdx

---

packages/docs/src/routes/tutorial/events/programmatic/index.mdx

docs: add link & standardize description on https://qwik.builder.io/tutorial/events/programmatic/

docs: add link & standardize description

---

packages/docs/scripts/pages.json

docs: add seifen.vercel.app to showcase

---

packages/docs/public/_redirects

docs: add inline components redirect

---

.vscode/launch.json
starters/apps/base/.vscode/launch.json

feat(cli): add vscode launch configuration for `dev.debug`

---

packages/docs/src/routes/tutorial/events/preventdefault/index.mdx

docs: improve language on 'Preventing default behavior'

---

packages/docs/vite.config.ts

docs: update symbol colocation

---

packages/docs/src/root.tsx
packages/docs/src/routes/docs/(qwikcity)/guides/bundle/index.mdx
packages/docs/src/routes/docs/menu.md
packages/docs/vite.config.ts

docs: add bundle optimization

---

packages/docs/src/routes/docs/(qwikcity)/guides/bundle/index.mdx

docs(bundle): fix some typos

---

packages/docs/scripts/pages.json

Add a new project to list of showcase projects. It's web BuiltWithAppwrite, which uses Qwik and Pink Design.
x

Add BuiltWithAppwrite to pages.json

---

packages/docs/scripts/pages.json

and add the repo for burgers on fleek
Adding SimplyMC and the repo for Burgers on Fleek's website

docs: add SimplyMC to showcase

---

packages/qwik/src/core/render/dom/operations.ts
packages/qwik/src/core/render/ssr/render-ssr.ts
packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
starters/apps/e2e/src/components/slot/slot.tsx
starters/e2e/e2e.slot.spec.ts

fix(slot): duplicated ssr content projection

---

packages/docs/src/routes/(ecosystem)/ecosystem/index.tsx
packages/docs/src/routes/(ecosystem)/media/index.tsx
packages/docs/src/routes/(ecosystem)/media/media.css

Create a sub section for all non english content on the media view.

feat: media pages separated by language

---

packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx

docs: Update (qwik)/components/tasks/index.mdx

---

packages/qwik/src/qwikloader.ts

fix: non passive event listeners

---

packages/docs/src/routes/demo/getting-started/06-styling/index.tsx
packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

Deprecated full capitalized import
Deprecated import from index.mdx at Styles chapter.

Import styles naming fixing

---

packages/eslint-plugin-qwik/src/jsxImg.ts

Fix noWidthHeight example typo

fix(jsxImg): noWidthHeight example

---

packages/qwik/src/optimizer/src/plugins/vite.ts

fix: hot module reloading for server$

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

docs: routing added titles

---

packages/qwik/src/optimizer/core/src/props_destructuring.rs
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_optimization_issue_4386.snap
packages/qwik/src/optimizer/core/src/test.rs
starters/apps/e2e/src/components/render/render.tsx
starters/e2e/e2e.render.spec.ts

fix(optimizer): missing const inline

---

packages/docs/src/routes/api/qwik-city/api.json
packages/docs/src/routes/api/qwik-city/index.md
packages/qwik-city/runtime/src/api.md
packages/qwik-city/runtime/src/types.ts

fix: missing media type in DocumentMeta

---

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx

docs: env small typos

---

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx

docs(qwik in a nutshell docs): fix grammar

---

packages/docs/src/routes/docs/(qwik)/advanced/eslint/index.mdx
packages/eslint-plugin-qwik/src/useMethodUsage.ts

Adjustment based on conversation on #4376

docs: eslint page adjustment

---

packages/docs/src/routes/docs/integrations/authjs/index.mdx

Add an example of how to provide route protection

docs: add qwik-auth route protection example

---

packages/qwik/src/optimizer/core/src/props_destructuring.rs
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap
packages/qwik/src/optimizer/core/src/test.rs

fix(optimizer): handle assign + default

---

packages/qwik-city/buildtime/vite/dev-server.ts

fix: use levenshtein distance to provide even better 404

---

packages/docs/package.json
packages/docs/src/routes/demo/demo-reset.css
packages/docs/src/routes/demo/integration/modular-forms/index.tsx
packages/docs/src/routes/demo/state/counter-store-deep/index.tsx
packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
packages/docs/src/routes/docs/(qwik)/components/state/index.mdx
packages/docs/src/routes/docs/integrations/image-optimization/index.mdx
packages/docs/src/routes/docs/integrations/modular-forms/index.mdx
pnpm-lock.yaml

I added a CodeSandbox demo to the Modular Forms guide and syncronized the demo code of other guides.

docs: add CodeSandbox demo to Modular Forms guide

---

packages/docs/src/routes/docs/menu.md

fix link to `Bundle Optimization`

docs: fix link to `Bundle Optimization`

---

packages/docs/src/components/header/header.tsx
packages/docs/src/global.css
starters/e2e/qwikcity/nav.spec.ts

https://twitter.com/erikras/status/1666361545629024256

docs: qwiksand-box

---

packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx

docs: fix example to match

---

packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_cmp.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_div.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_getter_generation.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_immutable_analysis.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_input_bind.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_jsx_listeners.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_spread_jsx.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_client_code.snap
packages/qwik/src/optimizer/core/src/transform.rs
starters/apps/e2e/src/components/render/render.tsx
starters/e2e/e2e.render.spec.ts

fix: jsx rendering order

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

It seems here the proper function is `useLocation` instead of `getLocation`

docs: Routing - Change getLocation() to useLocation()

---

packages/qwik/src/core/render/dom/notify-render.ts
starters/apps/e2e/src/components/effect-client/effect-client.tsx
starters/e2e/e2e.effect-client.spec.ts

fix: visible task execution after removal

---

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx

docs: routeLoader adjustment

---

.gitignore

The [reorganized](https://github.com/BuilderIO/qwik/pull/4456) `.gitignore` file did no longer cover nested `node_modules` or `dist` directories.

fix: root gitignore file

---

packages/docs/src/routes/docs/(qwik)/index.mdx

Just a little dash of inclusivity that costs nothing.
Look at the "rich" diff to confirm that it's really the four-person-in-one emoji.

Include a woman in the "community" emoji

---

packages/qwik/src/optimizer/src/plugins/plugin.ts
starters/adapters/deno/src/entry.deno.ts

fix: bundling for testing

---

packages/qwik-city/buildtime/vite/api.md
packages/qwik-city/buildtime/vite/plugin.ts
packages/qwik-city/package.json
pnpm-lock.yaml
scripts/api.ts
scripts/qwik-city.ts

- Zero runtime, zero JS
- Simplest API surface possible (zero props by default)
- Strongly typed (You cant referenced 404 images)
- Autocompletion supported by typescript
- Immutable cached images (hashed files)
- Optimized to webp
- Automatic width/height (prevent layout reflows)
- Automated srcSet generation (ideal image size)
- Extendable (add any `<img>` attribute)
- Loading lazy and async decoding
- Lightweight, a single `<img>` node in the HTML
https://www.loom.com/share/23c21ef8d4be464dab59eae6064c918a
```tsx
import { component$ } from '@builder.io/qwik';
import Image from '~/media/image2.jpg?jsx';
export default component$(() => {
return (
<div>
<Image alt='Unsplash image' />
</div>
);
});
```
Output:

feat: image vite transform

---

packages/qwik/src/core/render/dom/notify-render.ts
scripts/submodule-cli.ts
starters/e2e/e2e.effect-client.spec.ts

refactor: visible tasks can run in parallel

---

packages/docs/src/routes/api/qwik-city/api.json
packages/docs/src/routes/api/qwik-city/index.md
packages/qwik-city/runtime/src/api.md
packages/qwik-city/runtime/src/client-navigate.ts
packages/qwik-city/runtime/src/client-navigate.unit.ts
packages/qwik-city/runtime/src/qwik-city-component.tsx
packages/qwik-city/runtime/src/types.ts

This could fix: https://github.com/BuilderIO/qwik/issues/4487

Allow replace state when navigating

---

packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_issue_4438.snap
packages/qwik/src/optimizer/core/src/test.rs
packages/qwik/src/optimizer/core/src/transform.rs

fix: $localize optimizer bug

---

packages/docs/adapters/cloudflare-pages/vite.config.ts
packages/docs/src/routes/demo/qwikcity/middleware/getWritableStream/index.tsx
packages/docs/src/routes/demo/qwikcity/middleware/layout.tsx
packages/docs/src/routes/demo/qwikcity/middleware/proxy/index.tsx

Pr docs qwik city

---

packages/qwik-city/middleware/request-handler/request-event.ts
packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
packages/qwik-city/middleware/request-handler/user-response.ts
packages/qwik-city/runtime/src/use-endpoint.ts
starters/apps/basic/src/routes/demo/todolist/index.tsx
starters/apps/qwikcity-test/src/routes/issue4502/broken/index.tsx
starters/apps/qwikcity-test/src/routes/issue4502/broken/route/index.tsx
starters/apps/qwikcity-test/src/routes/issue4502/index.tsx

fix: spa redirects from non-pages

---

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx
packages/docs/src/routes/docs/(qwikcity)/api/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx
packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx
packages/docs/src/routes/docs/integrations/authjs/index.mdx
starters/e2e/qwikcity/actions.spec.ts

Fixed small typos in qwik-city documentation and one unit test under qwik-city.

docs: fixed small typos in qwik-city documentation.

---

starters/features/pandacss/.vscode/settings.json
starters/features/pandacss/package.json
starters/features/pandacss/panda.config.ts
starters/features/pandacss/postcss.config.js
starters/features/pandacss/src/global.css
starters/features/pandacss/src/routes/pandacss/index.tsx

```
pnpm qwik add pandacss
```
- Install deps
- Add and autorun script
- Create config files
- Update global.css
https://twitter.com/thesegunadebayo/status/1669732623994834946

feat: pandacss integration

---

packages/docs/src/routes/examples/apps/introduction/runtime-less/app.tsx

Toggling the background color on button click.
<!--
While clicking on the button multiple times, the user should get to know that the button is getting clicked repeatedly. Toggling the background color felt like the right way. But wanted to ask you guys first. I am new to Open source contributions. Apologies if I did anything wrong. 
- [ x ] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [ x ] I have performed a self-review of my own code.

Update app.tsx in runtime-less example

---

packages/qwik-city/runtime/src/router-outlet-component.tsx

fix: missing component in layout

---

packages/qwik-city/middleware/request-handler/request-event.ts

fix: regression when navigating to /

---

packages/qwik-city/runtime/src/qwik-city-component.tsx

Improves reliability of `scrollState` slightly by committing state on `visibilitychange`, which can occur in certain circumstances where refresh, navigation, or app switch, occurs before the 200ms scroll debounce.
Blocks Chromium 102+ for now because calling `replaceState` during this stage of lifecycle will prevent the bfcache from saving the page, this will be fixed with the Navigation API.

fix: save scrollState on visibilitychange

---

packages/docs/src/routes/docs/integrations/panda-css/index.mdx
packages/docs/src/routes/docs/menu.md

docs: add panda css

---

packages/docs/src/routes/docs/labs/typed-routes/index.mdx
packages/docs/src/routes/docs/menu.md

docs(labs): add typed routes

---

scripts/qwik-save-artifacts.ts

chore: fix saving of artifacts to build

---

.github/workflows/ci.yml

chore(labs): fix distribution build

---

packages/qwik-react/src/react/qwikify.tsx
packages/qwik/src/core/container/container.ts
packages/qwik/src/core/container/pause.ts
packages/qwik/src/core/container/resume.ts
packages/qwik/src/core/container/serializers.ts
packages/qwik/src/core/examples.tsx
packages/qwik/src/core/qrl/qrl-class.ts
packages/qwik/src/core/readme.md
packages/qwik/src/core/render/dom/notify-render.ts
packages/qwik/src/core/render/dom/render.unit.tsx
packages/qwik/src/core/render/dom/visitor.ts
packages/qwik/src/core/state/common.ts
packages/qwik/src/core/state/context.ts
packages/qwik/src/core/state/signal.ts
packages/qwik/src/core/use/use-resource.ts
packages/qwik/src/core/use/use-task.ts

While going over the Qwik source code, I noticed some function names that might be clearer if they were renamed
So this PR will have several commits with suggestions for renaming, feel free to comment on any of the proposals if you don't agree or think about a better name than what I found.

Internal renaming suggestions

---

.github/workflows/ci.yml
packages/qwik-labs/src/qwik-types/public-api.ts

fix(labs): encodeencodeURIComponent for params

---

packages/docs/src/routes/docs/(qwik)/advanced/custom-build-dir/index.mdx
packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx
packages/docs/src/routes/docs/(qwik)/advanced/library/index.mdx
packages/docs/src/routes/docs/(qwik)/advanced/optimizer/index.mdx
packages/docs/src/routes/docs/(qwik)/advanced/prefetching/index.mdx
packages/docs/src/routes/docs/(qwik)/advanced/qwikloader/index.mdx
packages/docs/src/routes/docs/(qwik)/concepts/progressive/index.mdx
packages/docs/src/routes/docs/(qwik)/concepts/reactivity/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/sitemaps/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/static-assets/index.mdx

This PR covers slight changes to the documentation grammar/structure, hopefully providing more clarity and comprehension for consumers as well as fixing any typos.
I made these changes whilst reviewing both sections in-depth. I initially wanted to gain more clarity on QRL's, symbols, and the Qwikloader, and thought I might as well try to improve the documentation while I'm at it!
If you think that any of these could be improved as well don't hesitate to give feedback / make any further changes!

docs(advanced & concepts docs improvements): clarity / structure changes

---

packages/docs/src/routes/api/qwik-city/api.json
packages/docs/src/routes/api/qwik-city/index.md
packages/qwik-city/runtime/src/api.md
packages/qwik-city/runtime/src/link-component.tsx

https://github.com/BuilderIO/qwik/pull/4488#issuecomment-1591221473

Add replaceState to link component

---

.github/workflows/ci.yml
packages/qwik-labs/src/qwik-types/public-api.ts

chore(labs): copy build artifacts into the build git repo

---

.github/workflows/ci.yml
packages/qwik-labs/package.json

chore(labs): include package.json in full build

---

packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx

Fixed a few typos on the Qwik City homepage.

docs: fix typos on Qwik City home

---

packages/docs/src/components/header/header.tsx

docs header: add shop link

---

packages/docs/src/routes/docs/(qwikcity)/project-structure/index.mdx

This PR adds some documentation for the new command utility announced in Qwik 1.2
If there is anything that's not consistent with the utility, or the verbage/examples need to change don't be afraid to let me know!

docs(utilities): adding documentation for the `new` cli command 

---

packages/docs/src/routes/docs/deployments/aws-lambda/index.mdx
packages/docs/src/routes/docs/menu.md
pnpm-lock.yaml

- [x ] Docs / tests / types / typos

docs: aws lambda documentation

---

packages/qwik-city/buildtime/vite/image-jsx.ts
packages/qwik-dom/lib/Element.js

fix: unit test jsx image

---

packages/docs/src/routes/(shop)/shop.css
packages/docs/src/routes/(shop)/shop/shop-header.tsx

Fix issue with z-index and truncate the article title to prevent CLS

docs css: fix shop cart floating button

---

packages/docs/src/routes/(shop)/shop/shop-cart-rows.tsx
packages/docs/src/routes/(shop)/shop/shop-cart.tsx
packages/docs/src/routes/(shop)/shop/shop-product.tsx

shop: added colors to icons and small changes

---

packages/qwik/src/optimizer/src/plugins/plugin.ts
starters/apps/qwikcity-test/src/routes/issue4679/index.tsx
starters/e2e/qwikcity/actions.spec.ts

fix: inlined signals in library mode

---

packages/qwik/src/optimizer/src/plugins/vite-server.ts

fix: always try relative path for mapped hooks

---

packages/docs/src/routes/api/qwik-city-middleware-node/api.json
packages/docs/src/routes/api/qwik-city-middleware-node/index.md
packages/qwik-city/buildtime/vite/dev-server.ts
packages/qwik-city/middleware/node/api.md
packages/qwik-city/middleware/node/http.ts
packages/qwik-city/middleware/node/index.ts
starters/adapters/cloud-run/src/entry.cloud-run.tsx
starters/adapters/express/src/entry.express.tsx

fix: configurable getOrigin for node servers

---

starters/adapters/deno/src/entry.deno.ts

Fix wrong parameters in [entry.deno.ts](https://github.com/BuilderIO/qwik/blob/main/starters/adapters/deno/src/entry.deno.ts)

fix(entry.deno.ts): fix wrong parameters

---

packages/qwik/src/optimizer/src/plugins/vite-server.ts

fix: PROTOCOL and HOST header are case insensitive

---

packages/qwik/src/core/render/dom/signals.ts
starters/apps/e2e/src/components/attributes/attributes.tsx
starters/e2e/e2e.attributes.spec.ts

fix: clear attribute when undefined

---

packages/docs/src/routes/docs/labs/index.mdx

docs: fixed typo in labs index.mdx

---

packages/qwik-city/buildtime/routing/walk-server-plugins.ts
packages/qwik-city/utils/fs.ts
starters/apps/qwikcity-test/src/components/footer/footer.tsx
starters/apps/qwikcity-test/src/routes/plugin@issue4722.tsx

fix: routes plugins with tsx

---

packages/qwik-labs/src/insights/index.tsx

chore(insights): update the format of data being sent

---

packages/qwik/src/core/qrl/qrl.ts

Pr fix prefetch

---

pnpm-lock.yaml

chore(docs): update to latest qwik

---

packages/insights/src/routes/plugin@db.ts
packages/insights/vite.config.ts

chore(insights): fix broken deploy

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

Add an explination on how and why Qwik uses vDOM.
Extracted from @mhevery's answer on discord: https://discord.com/channels/842438759945601056/842438761287254019/1128678388094226442

docs: add vDOM FAQ

---

packages/docs/src/routes/docs/integrations/image-optimization/index.mdx

The title of the page is currently spelled Intergrations, which should be Integrations
- 1. Reduce confusion when reading docs

Fixed a typo in the title of this page

---

packages/docs/src/routes/docs/integrations/builderio/index.mdx

Fixed a typo in the title of a page
Intergrations -> Integrations

Fixed a typo in the title

---

packages/insights/package.json
packages/insights/src/components/minifest-tile/index.tsx
packages/insights/src/components/symbol-tile/index.tsx
packages/insights/src/db/README.md
packages/insights/src/db/query.ts
packages/insights/src/db/schema.ts
packages/insights/src/db/sql-manifest.ts
packages/insights/src/routes.gen.d.ts
packages/insights/src/routes/api/v1/[publicApiKey]/post/index.tsx
packages/insights/src/routes/app/[publicApiKey]/errors/index.tsx
packages/insights/src/routes/app/[publicApiKey]/layout.tsx
packages/insights/src/routes/app/[publicApiKey]/manifests/index.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/bundles/index.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/edge/index.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/index.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/outgoing/index.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/slow/index.tsx
packages/insights/src/routes/plugin@db.ts
pnpm-lock.yaml

feat(insights): add manifest latency page

---

packages/docs/src/routes/docs/integrations/orama/index.mdx
packages/docs/src/routes/docs/menu.md
starters/features/orama/package.json
starters/features/orama/src/orama/index.ts
starters/features/orama/src/routes/orama/index.tsx

This PR will add the [Orama](https://oramasearch.com/) integration to Qwik

feat: add Orama integration

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

Just some spaces in index.mdx.
Some necessary spaces for better syntax.

docs: some spaces in index.mdx

---

packages/docs/src/routes/tutorial/hooks/use-task/problem/app.tsx
packages/docs/src/routes/tutorial/hooks/use-task/solution/app.tsx
packages/docs/src/routes/tutorial/reactivity/explicit/problem/app.tsx
packages/docs/src/routes/tutorial/reactivity/explicit/solution/app.tsx

docs: update tutorial to use cleanup inside useTaskQRL

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

docs: correct the links for useResource

---

starters/adapters/aws-lambda/adapters/aws-lambda/vite.config.ts
starters/adapters/aws-lambda/package.json

Fixed error at building moment

fix:(adapter): aws fix path of aws-lambda

---

packages/docs/src/routes/docs/(qwikcity)/middleware/index.mdx

Fix endpoints link in middleware section

Fix endpoints link in middleware section

---

packages/docs/src/repl/repl-share-url.ts
packages/docs/src/repl/repl-share-url.unit.ts

This is a continuation of #1954.
Hello world is now just
```
http://localhost:3000/playground/#v=1.1.5&f=G000o4mG5EQDAA
```
and changes don't make the URL much longer.
This is perfect for sharing in Discord.

Playground dictionary compression

---

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx

Under the Synchronous event handling section's NOTE, there were some typo's.

docs: fix typos in events/index.mdx

---

packages/docs/src/routes/docs/(qwikcity)/middleware/index.mdx

docs: fix a typo

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

Improve the documentation on the getting started page to be a bit more consistent throughout. Made improvements while going through the guide.

docs: improve documentation for getting started guide

---

starters/apps/base/.vscode/settings.json

DX: Overwrite Emmet default

---

packages/qwik/src/core/container/pause.ts
starters/apps/e2e/src/components/signals/signals.tsx
starters/e2e/e2e.signals.spec.ts

fix: useComputed with mutable props

---

packages/eslint-plugin-qwik/qwik.unit.ts
packages/eslint-plugin-qwik/src/validLexicalScope.ts
packages/qwik/src/optimizer/src/plugins/plugin.ts

fix: run linter during dev mode

---

packages/docs/src/routes/docs/(qwikcity)/caching/index.mdx

docs: Typo in caching/index.mdx

---

packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx

Fixing grammar mistake in a note

docs: Update components/tasks note regarding useTask$

---

packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx

docs: fix typos in advanced/routing/index.mdx

---

packages/docs/scripts/pages.json

Add a SSG blog built using qwik to the showcase.
The site is statically generated blog, features home page, blog pages, along with home pages for blogs listing all articles, routing on individual pages to next available article and practices good SEO techniques.
Add a SSG blog built using qwik to the showcase hosted at https:// itbusinesshub.com.
-  The site is statically generated blog, and showcases features such as home page, blog pages, individual category pages for blogs listing all articles within the category, routing to next or previous post on individual blog post pages and has implemented good SEO techniques.

docs: add a new blog site powered by qwik

---

packages/docs/scripts/pages.json

Added my website to the showcase list.

docs: add realmof.tech to the showcase

---

starters/adapters/fastify/src/plugins/fastify-qwik.ts

closes #3743, #3925, #4263, #4854
- 1. Fix for the log issues with fastify   #3743 
- 2. Fix for unable to load not found page with fastify adaptor  #3925, #4263, #4854

fix: fastify logging and 404 page loading issues

---

starters/apps/site-with-visual-cms/src/routes/[...index]/index.tsx

fix: typo on Builder Starter

---

packages/docs/src/routes/(ecosystem)/ecosystem/menu-items.tsx

docs(component): fix blog menu icon in ecosystem

---

packages/docs/src/routes/(ecosystem)/media/index.tsx

docs: add ru videos Qwik index.tsx

---

packages/docs/src/routes/(ecosystem)/media/index.tsx
packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx

- closes #4890 
- fixes invalid youtube video

docs: several fixes

---

packages/docs/src/routes/docs/integrations/react/index.mdx

docs: update link to react docs

---

packages/insights/package.json
packages/insights/src/components/symbol-tile/index.tsx
packages/insights/src/db/query.ts
packages/insights/src/db/sql-manifest.ts
packages/insights/src/routes/api/v1/[publicApiKey]/post/error/index.tsx
packages/insights/src/routes/app/[publicApiKey]/errors/index.tsx
pnpm-lock.yaml

chore(insights): update to latest drizzle

---

packages/docs/src/routes/demo/cookbook/modal/index.tsx
packages/docs/src/routes/demo/cookbook/modal/layout.tsx
packages/docs/src/routes/demo/cookbook/modal/popup-example.css
packages/docs/src/routes/demo/cookbook/modal/popup-manager.css
packages/docs/src/routes/demo/cookbook/modal/popup-manager.tsx
packages/docs/src/routes/demo/integration/img/qwik-image/index.tsx
packages/docs/src/routes/docs/(qwikcity)/action/index.mdx
packages/docs/src/routes/docs/(qwikcity)/endpoints/index.mdx
packages/docs/src/routes/docs/(qwikcity)/middleware/index.mdx
packages/docs/src/routes/docs/cookbook/index.mdx
packages/docs/src/routes/docs/cookbook/modal/index.mdx
packages/docs/src/routes/docs/menu.md
packages/qwik/src/core/platform/types.ts

docs: Add modal cookbook example.

---

.github/ISSUE_TEMPLATE/bug.yaml

chore: update bug template

---

.github/ISSUE_TEMPLATE/docs_suggestion.yml

chore: update docs_suggestion issue template

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/docs_suggestion.yml
.github/ISSUE_TEMPLATE/feature.yaml

updated the default github tag for new issues

chore: update issue templates

---

packages/docs/src/components/on-this-page/on-this-page.tsx

docs: correctly generate edit URLs for github

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

"and become productive in for React developers"
changed the sentence to correct the typo and updated grammar for clarity.

Typo in FAQ

---

packages/qwik-auth/src/index.ts

The response from ``await Auth(new Request...) may return the headers 'set-cookie'. When using jwt with token rotation this get's called and subsequently the rotation errors out. This allows the token rotation to work without errors.
**Actual Behaviour**
``await Auth(...)`` gets called returns an updated cookie. Cookie is not set for ``req``.
**Expected Behaviour**
``await Auth(...)`` returns an updated cookie. Cookie is set for ``req``.
- [-] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)

fix(auth): Cookies get updated if session returns Updated Cookies

---

packages/docs/src/routes/(ecosystem)/media/index.tsx
packages/docs/src/routes/(ecosystem)/media/media.css

docs: Improved media, fixed height thumbnails

---

packages/docs/src/components/on-this-page/on-this-page.tsx

chore(docs): fix broken cloudflare build

---

pnpm-lock.yaml

chore(insights): fix build

---

packages/docs/adapters/cloudflare-pages/vite.config.ts

chore(docs): Remove home-page from SSR to improve TTFB metric

---

packages/docs/src/routes/docs/deployments/vercel-edge/index.mdx

docs: Vercel environment variables

---

packages/docs/src/routes/(ecosystem)/media/index.tsx

docs: dynamic alt image

---

packages/docs/src/routes/community/projects/index.mdx

docs: community project update image url

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: Update index.mdx

---

packages/docs/src/components/on-this-page/on-this-page.css
packages/docs/src/components/on-this-page/on-this-page.tsx
packages/docs/src/components/sidebar/sidebar.css
packages/docs/src/components/svgs/alert-icon.tsx

docs: update side bar

---

packages/insights/src/db/query-helpers.ts
packages/insights/src/db/sql-manifest.ts

chore(insights): Remove deprecated InferModel

---

packages/qwik-labs/src-vite/qwik-types/prettify.ts

qwik-labs: fix prettier estree error

---

packages/qwik/src/optimizer/src/plugins/vite.ts

insights: add existsSync check

---

packages/docs/src/routes/demo/component/useId/index.tsx
packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

Add `useId()` documentation and demo component. Closes issue #4120.

Add useId() docs and demo component

---

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

add n8sabes to contributors

---

packages/docs/src/routes/docs/integrations/modular-forms/index.mdx

Fixes a typo / incorrect type in the Modular Forms docs.

Modular Forms: Fix incorrect type in example

---

packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx

Fixes: https://github.com/BuilderIO/qwik/issues/4366
It's not really clear from documentation, how you can define a middleware for `server$` endpoints/functions. This adds a little bit more clarity.

docs: add docs about server$ middleware

---

.github/workflows/ci.yml

chore: add more debug info to build

---

packages/qwik/src/core/container/pause.ts
starters/apps/e2e/src/components/signals/Issue_5001.tsx
starters/apps/e2e/src/entry.ssr.tsx
starters/apps/e2e/src/root.tsx
starters/e2e/e2e.signals.spec.ts

fix(core): correctly handle serialization of Signal of X and naked X

---

packages/qwik/src/optimizer/core/src/parse.rs

fix(core): pass through decorators

---

packages/qwik-city/runtime/src/route-matcher.ts
packages/qwik-city/runtime/src/route-matcher.unit.ts

fix(qwik-city): correct rest route regression

---

packages/insights/vite.config.ts
packages/qwik-labs/src-vite/insights/index.ts
packages/qwik/src/optimizer/src/plugins/vite.ts

fix: QwikInsights path resolution

---

packages/docs/vite.config.ts

docs: add qwikInsights vite plugin

---

packages/docs/package.json
pnpm-lock.yaml

docs: change @builder.io/qwik-labs version

---

packages/docs/package.json
pnpm-lock.yaml

docs: add prettier as devDependencies

---

packages/qwik-city/middleware/node/http.ts

fix(qwik-city): do not write into a closed stream

---

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx

Fix relativeUrl PR to remove CodeSandbox `docs/route-loader/`

Fix the loader document

---

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx

Update the loader document `relativeUrls` for consistency and highlight relevant code.

Loader doc consistency

---

packages/docs/src/routes/demo/cookbook/mediaController/index.tsx
packages/docs/src/routes/docs/cookbook/mediaController/index.mdx

Remove overlooked console.log() from cookbook recipe.

Remove overlooked console.log() from cookbook recipe

---

packages/docs/src/routes/demo/cookbook/mediaController/index.tsx
packages/docs/src/routes/docs/cookbook/mediaController/index.mdx

Update cookbook to stream 1080p video content.

Update cookbook to stream 1080p video content

---

packages/docs/src/routes/tutorial/tutorial-menu.json

fix: remove missing tutorial (#5105)

---

packages/docs/src/routes/tutorial/reactivity/template/index.mdx
packages/docs/src/routes/tutorial/tutorial-menu.json

Correct the title 😅
ref: https://github.com/BuilderIO/qwik/pull/5092#issuecomment-1706229091

docs: fix mismatch title for implicit reactivity tutorial

---

packages/qwik-city/runtime/src/route-matcher.ts
packages/qwik-city/runtime/src/route-matcher.unit.ts

fix(qwikcity): Fix route-matcher regression #5080

---

packages/eslint-plugin-qwik/examples.ts
packages/eslint-plugin-qwik/qwik.unit.ts
packages/eslint-plugin-qwik/src/loaderLocation.ts
packages/eslint-plugin-qwik/src/routes/index.tsx
packages/eslint-plugin-qwik/tsconfig-tests.json

fix(eslint): Support explicit export with loader-location

---

packages/docs/src/repl/repl-options.tsx
packages/docs/src/repl/repl-version.ts
packages/docs/src/repl/repl.tsx
packages/docs/src/repl/types.ts
packages/docs/src/repl/worker/app-bundle-ssr.ts

this allows seeing qwik optimizer debug output

fix v1.2 playground

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

add details and use cases examples for route rewriting to the related docs
Add use case examples to the docs related to route rewriting

docs(qwik-city): Add docs for routes rewriting

---

packages/qwik-city/runtime/src/types.ts
starters/apps/qwikcity-test/src/routes/(common)/actions/issue5065/index.tsx

Issue 5065

---

packages/qwik-city/runtime/src/route-matcher.unit.ts

Issue 5126

---

packages/insights/package.json
pnpm-lock.yaml

chore(insights): upgrade drizzle

---

packages/insights/src/db/query-helpers.ts
packages/insights/src/db/query.ts
packages/insights/src/db/sql-manifest.ts

fix(insight): Correct DB returning too much data error

---

packages/insights/package.json
pnpm-lock.yaml

Revert "chore(insights): upgrade drizzle"

---

packages/docs/src/routes/docs/deployments/aws-lambda/index.mdx
packages/docs/src/routes/docs/deployments/azure-swa/index.mdx
packages/docs/src/routes/docs/deployments/gcp-cloud-run/index.mdx

Simplified and clarified how to deploy qwik to Google Cloud Run, AWS lambda, Azure SWA.

docs: improve descriptions for aws, azure and gcp integrations

---

packages/qwik-city/middleware/request-handler/request-event.ts
packages/qwik-city/runtime/src/head.ts
packages/qwik-city/runtime/src/utils.ts
packages/qwik/src/core/use/use-resource.ts
packages/qwik/src/core/util/promises.ts
packages/qwik/src/optimizer/core/src/parse.rs

Angular integration requires special handling for promises along with TS decorator support. Adding those in order to be able to publish the qwikify-angular package https://github.com/QwikDev/qwik-angular

feat: provide compatibility with angular

---

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx

docs: add routeAction$ caveat

---

packages/insights/src/db/query.ts
packages/insights/src/db/sql-manifest.ts
packages/insights/src/routes/api/v1/[publicApiKey]/bundles/bundles.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/bundles/index.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/edge/index.tsx
packages/insights/src/routes/app/[publicApiKey]/symbols/index.tsx

fix(insight): Limit the size of data retrieved from the database

---

.github/workflows/ci.yml
.github/workflows/housekeeping.yml
.github/workflows/pr.yml

Check PR title and make sure they follow the https://www.conventionalcommits.org/en/v1.0.0/

chore(github-action): added semantic pr title check

---

.github/workflows/pr.yml
package.json

https://github.com/marketplace/actions/semantic-pull-request#work-in-progress-pull-requests

fix(github-action): do not validate draft PRs

---

.github/workflows/pr.yml

This reverts commit 85de4f4d108be094ce7eeaf95a04a4a8a3315791.

fix(github-action): do not validate draft PRs - revert

---

packages/docs/scripts/pages.json

Add www.expobeds.com to the showcase

docs: Add expobeds.com to the showcase

---

starters/features/pandacss/package.json

Updating to the latest @panda/dev package to get features like SVA recipes, bleed patterns and defineUtility method and [more](https://github.com/chakra-ui/panda/blob/main/CHANGELOG.md#090---2023-07-28)

chore: Update 🐼 PandaCSS integration dev dependency

---

packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx

Correct the links to `endpoints` page.

docs(qwik-city): correct the links to endpoints page

---

packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx
packages/docs/src/routes/docs/(qwikcity)/validator/index.mdx
packages/docs/src/routes/docs/menu.md

Add documentation for data validators.
As discussed here: https://discord.com/channels/842438759945601056/1148894383899414538

docs(qwik-city): add validators

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

docs(qwik): Fixed Link

---

packages/qwik-labs/src/qwik-types/public-api.ts

fix(labs): filter out (group layouts)

---

packages/qwik/src/core/container/pause.ts

When serializing a dirty task, it'll be useful to know the exact task that caused the error, to track down the problem faster.

feat(core): added symbol name to error

---

packages/qwik-auth/package.json

chore(qwik-auth): v0.1.2

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: release 1.2.12

---

starters/features/prisma/package.json

This change updates the Prisma versions used for the Prisma integration.

chore: update Prisma versions package.json

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

docs: fix routing page - add missing attributes.

---

packages/insights/src/routes/app/styles.module.css

fix(insights): wrapper style

---

packages/insights/src/components/histogram/index.tsx
packages/insights/src/db/logging.ts
packages/insights/src/db/query-helpers.ts
packages/insights/src/db/query.ts
packages/insights/src/db/sql-routes.ts
packages/insights/src/routes.gen.d.ts
packages/insights/src/routes/api/v1/[publicApiKey]/bundles/strategy/index.tsx
packages/insights/src/routes/app/[publicApiKey]/routes/index.tsx
packages/insights/src/stats/vector.ts
packages/qwik-labs/src-vite/insights/index.ts

feat(insights): return prefetch list per route

---

packages/docs/src/routes/docs/(qwik)/concepts/resumable/index.mdx

docs: Correct image size and CLS in resumable example

---

packages/docs/src/routes/docs/(qwik)/concepts/resumable/index.mdx
packages/docs/src/routes/docs/(qwik)/deprecated-features/index.mdx

docs: fix url for useVisibleTask

---

starters/apps/basic/src/components/starter/next-steps/next-steps.tsx

chore: update file path in next-steps.tsx

---

packages/docs/src/routes/demo/events/preventdefault/index.tsx
packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx
packages/docs/src/routes/docs/integrations/builderio/index.mdx

docs: fix 404 links

---

packages/docs/scripts/pages.json

docs: Add frostytools.com to pages.json

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

Previously, only "Directory-based" was linked. This PR includes "routing" in the link for clarity.

docs: documentation link and text for directory-based routing

---

packages/qwik-labs/package.json
packages/qwik-labs/src/devtools/index.ts
packages/qwik-labs/src/devtools/json.ts
packages/qwik-labs/src/index.ts
packages/qwik-labs/src/root.tsx
packages/qwik/src/core/container/resume.ts

feat(labs): Add json debugging tool

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

Created another version of #5243, taking into consideration gioboa's feedback. You can choose the version you prefer :).
Remember to close either this PR or #5243.

docs(routing): add Link prefetch documentation (alternative)

---

packages/docs/package.json
packages/docs/src/routes/devtools/json/index.tsx
packages/docs/src/routes/docs/labs/devtools/index.mdx
packages/docs/src/routes/docs/menu.md
pnpm-lock.yaml

docs(labs): document devtools/json

---

starters/features/localize/src/entry.ssr.tsx
starters/features/localize/src/routes/[locale]/i18n-utils.ts

fix(starter): localize configuration

---

packages/qwik/src/cli/build/run-build-command.ts

…arn #5104
> If you use Yarn, running the yarn build command while there are (for example) linting issues will prematurely exit the process without printing anything about why it failed.
- 1. If we run `yarn build` and if there is any linting issue then `yarn build` simply get exit with 1 without showing exact issue of linting. To solve that while checking the linting on the build file, I found that the error is not showing properly with `e.stderr` but in the `e.stdout`, we are getting fulll error with description.
So i switched the if condition - 
```diff
- if (e.stderr) {
-        console.log(e.stderr);
} else {
-        console.log(e.e.stderr);
}
+ if (e.stdout) {
+       console.log(e.stdout);
} else {
+        console.log(e.stderr);
}
```

fix: A bug fix #5104

---

packages/docs/src/routes/docs/labs/devtools/index.mdx

docs(labs): update path for devtools to include https

---

packages/qwik-city/middleware/bun/index.ts

fix: Bun adapter polyfill and redirect fix

---

packages/qwik/src/cli/add/update-files.ts

fix: shell script update in README file

---

packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx
packages/docs/src/routes/docs/integrations/authjs/index.mdx

This PR improves [Advanced Routing](https://qwik.builder.io/docs/advanced/routing/) page.
The **Named Layout** section was improved by adding a note that a page can reference the named layout by adding `@<name>` suffix.
Added **The order of execution of `plugin.ts` files** section. I never found the actual code that sorts executes `plugin.ts` files in order that I wrote, so please check it out. What I did is that I just tried couple of combinations in my project and they proved me that.

docs: improve advanced routing documentation

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.2.13

---

packages/docs/src/routes/docs/cookbook/theme-management/index.mdx

docs: fix contributor name

---

packages/qwik/src/core/container/pause.ts
packages/qwik/src/core/container/pause.unit.tsx

fix(core): fix pause logic failing to capture component

---

packages/insights/package.json
pnpm-lock.yaml

chore: rollback drizzle to 0.28.3

---

packages/docs/src/routes/docs/integrations/authjs/index.mdx

Update authjs docs with adding more explanation of the library

docs: update authjs

---

packages/docs/src/routes/docs/(qwikcity)/guides/mdx/index.mdx

docs(guides > mdx > index.mdx): fix syntax error in docs mdx tags example

docs: fix syntax error in mdx tags example

---

packages/docs/package.json
packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx
packages/docs/vite.config.ts
pnpm-lock.yaml

fix: docs Cloudflare build

---

packages/eslint-plugin-qwik/src/useMethodUsage.ts

Convey a stricter restriction from ~~just~~ to ***only*** (examples)

style(eslint): convey a stricter restriction from `just` to `only` (examples)

---

packages/docs/src/routes/docs/labs/typed-routes/index.mdx

Fix small file extension on docs.

chore(docs): Small fix of file to edit

---

packages/docs/src/routes/docs/(qwikcity)/guides/react-cheat-sheet/index.mdx

docs: update React cheat sheet title

---

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/complex-forms/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/content-security-policy/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/menu/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/request-handling/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/sitemaps/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/static-assets/index.mdx
packages/docs/src/routes/docs/(qwikcity)/api/index.mdx
packages/docs/src/routes/docs/(qwikcity)/caching/index.mdx
packages/docs/src/routes/docs/(qwikcity)/endpoints/index.mdx
packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/bundle/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/mdx/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/react-cheat-sheet/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/redirects/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/serialization/index.mdx
packages/docs/src/routes/docs/(qwikcity)/guides/static-site-generation/index.mdx
packages/docs/src/routes/docs/(qwikcity)/html-attributes/index.mdx
packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

docs: improve SEO with descriptions

---

packages/docs/scripts/pages.json
packages/docs/src/routes/(ecosystem)/showcase/generated-pages.json

docs: remove soundy.cloud

---

.vscode/launch.json
packages/qwik-labs/src/devtools/json.ts
scripts/release.ts

chore: clean up release script

---

packages/qwik/package.json
packages/qwik/src/optimizer/src/plugins/vite.ts
pnpm-lock.yaml
scripts/submodule-optimizer.ts
scripts/submodule-server.ts
scripts/util.ts

Reverts BuilderIO/qwik#5312 due to https://github.com/BuilderIO/qwik/issues/5371

revert: refactor(optimizer): remove using resolvePackageData API from Vite

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

docs: update Alex Russell

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json
scripts/release.ts

chore: 1.2.16

---

packages/docs/vite.config.ts
packages/qwik-city/buildtime/vite/plugin.ts
packages/qwik-labs/src-vite/insights/index.ts
packages/qwik/src/optimizer/src/plugins/plugin.ts
packages/qwik/src/optimizer/src/plugins/vite.ts

fix(labs): Better handling and visibility of q-insights.json

---

packages/docs/src/routes/api/qwik-optimizer/api.json
packages/docs/src/routes/api/qwik-optimizer/index.md
packages/qwik/src/optimizer/src/api.md
packages/qwik/src/optimizer/src/plugins/plugin.ts
packages/qwik/src/optimizer/src/types.ts

fix(vite): resolution of nested dependencies

---

packages/insights/src/routes/app/[publicApiKey]/symbols/bundles/index.tsx
packages/insights/src/stats/edges.ts

Increase clustering distance which should result in creation of fewer clusters. Fewer clusters means that less files should be downloaded to the client (each file will have more symbols.) This should improve performance.

fix(insights): improve files per cluster

---

packages/docs/public/robots.txt
packages/docs/src/components/router-head/router-head.tsx

docs: don't index demos; don't duplicate meta descriptions

---

packages/docs/src/routes/404.tsx
packages/docs/src/routes/404/index.tsx

docs: add custom 404 page

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

chore(docs): small improvements to routing/index.mdx

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.2.17

---

packages/insights/package.json
starters/apps/base/.vscode/launch.json

Debugging in Chrome: A Demo App
https://www.loom.com/share/80fe8b4a06354867976e4007f276f4ef

chore(starters): add VSCode debug setting

---

packages/docs/src/routes/docs/integrations/astro/index.mdx
packages/docs/src/routes/docs/integrations/index.mdx
packages/docs/src/routes/docs/menu.md

docs(menu): Add Astro integration to menu

---

packages/docs/src/routes/community/groups/index.mdx

docs: correct broken image

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: fixed small typo

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
packages/docs/src/routes/docs/integrations/authjs/index.mdx

docs: add missing contributors

---

packages/docs/src/routes/api/qwik/index.md

fixed http issue
Changed HTTP to https due to SEO related issues
SEO

fix(docs): improve SEO

---

packages/docs/src/routes/docs/labs/insights/index.mdx

docs: Add link to create new Qwik Insights app as self-serve

---

packages/docs/src/routes/docs/(qwikcity)/middleware/index.mdx
packages/docs/src/routes/tutorial/events/synchronous/solution/app.tsx

fix(docs): typo in qwik city -> middleware page

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.2.18

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.2.19

---

packages/docs/src/routes/docs/integrations/prisma/index.mdx

fix: add example context to docs

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

docs(faq): add link to typescript

---

packages/docs/scripts/pages.json

Hello there :) It's me again, there is 2 more landings that I've built with Qwik and has such a FABOLOUS speed. Thank you all for giving us the chance to use it :) Good work!
https://index.app/beta
https://wiza.co
Love the work you've done so far, I am really happy using Qwik ❤️

docs(showcase): add `index.app` and `wiza.co`

---

packages/qwik-city/middleware/cloudflare-pages/index.ts

fix: revert "fix: remove cf pages stream polyfill"

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.3.0

---

packages/docs/src/routes/community/projects/index.mdx

docs: change image url

---

packages/qwik/package.json
packages/qwik/src/optimizer/src/plugins/vite.ts
pnpm-lock.yaml
scripts/submodule-optimizer.ts
scripts/util.ts

fix: remove dependency on vitefu causing playground failures

---

packages/docs/src/routes/docs/integrations/vitest/index.mdx
packages/eslint-plugin-qwik/package.json

I fixed the link to remove this message in the console

docs: remove console warning

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.3.1

---

packages/docs/src/routes/docs/(qwikcity)/guides/bundle/index.mdx

Adding a notice statement regarding the usage of service worker

chore: Add notice about service worker usage

---

packages/insights/src/routes/app/[publicApiKey]/edit/index.tsx
packages/insights/src/routes/app/add/index.tsx
packages/insights/src/routes/app/index.tsx

fix(insights): form errors

---

packages/docs/src/routes/docs/(qwikcity)/layout/index.mdx

Add import of `Slot` component in the documentation
It is required to import `Slot` in order to compile the application

docs(layout): Add "Slot" import

---

packages/qwik/src/core/container/store.unit.tsx
packages/qwik/src/core/render/sync-qrl.unit.tsx
starters/apps/e2e/src/components/render/render.tsx
starters/apps/e2e/src/components/resuming/sync-qrl.tsx

fix(tests): fix typos

---

packages/docs/src/routes/api/qwik-city/api.json
packages/docs/src/routes/api/qwik-city/index.md
packages/qwik-city/runtime/src/api.md
packages/qwik-city/runtime/src/index.ts
packages/qwik-city/runtime/src/types.ts
packages/qwik/src/core/api.md
packages/qwik/src/core/use/use-core.ts

fix: Correct qwik types

---

packages/docs/src/routes/docs/cookbook/theme-management/index.mdx
packages/docs/src/routes/docs/menu.md

fix(docs): add missing cookbook section

---

packages/qwik/src/core/render/dom/operations.ts
packages/qwik/src/core/render/dom/render.unit.tsx
packages/qwik/src/core/render/dom/visitor.ts
packages/qwik/src/core/render/ssr/render-ssr.ts
packages/qwik/src/core/render/ssr/render-ssr.unit.tsx

Closes #4824
This is a slightly breaking change.

fix: rendering ssr and csr for value=""

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.3.2

---

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx

docs: for accessing the .env variables in serverfull architechture example in express

---

starters/dev-server.ts

The code does not work in the server due to incorrect file path for imports in `Windows` that when running `pnpm serve` it would throw a similar error:
```bash
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must 
be valid file:// URLs. Received protocol 'd:'
```
- Running the development server of Qwik on Windows machines.

fix: fixing running qwik-development-server on windows machine

---

packages/qwik/src/qwikloader.ts

Ver minor variable naming cleanup for readability: The listener is not a QRL, it contains a QRL
N/A

refactor: Clarify var naming qwikloader.ts

---

packages/qwik-city/runtime/src/head.ts

Clarifies a poorly described error.

fix: Clearer error message for `resolveValue` for `head` function

---

starters/apps/basic/src/components/starter/hero/hero.tsx

refactor(starter): add alt attribute in order to improve accessibility

---

packages/insights/netlify.toml

refactor(insights): remove netlify.toml causing confusion

---

packages/docs/src/routes/demo/cookbook/algolia-search/index.tsx
packages/docs/src/routes/docs/cookbook/algolia-search/index.mdx
packages/docs/src/routes/docs/cookbook/index.mdx
packages/docs/src/routes/docs/menu.md

Cookbook: add Algolia working example

feat(cookbook): add Algolia search

---

packages/docs/src/routes/demo/cookbook/algolia-search/index.tsx
packages/docs/src/routes/docs/cookbook/algolia-search/index.mdx

fix(cookbook): change Algolia example

---

CONTRIBUTING.md
flake.lock
flake.nix

This adds support for running `nix develop` and having a reproducible development environment

chore: add Nix build flake environment

---

.envrc
CONTRIBUTING.md
flake.lock
flake.nix

The .envrc is needed for direnv

fix(nix): missing .envrc

---

package.json
packages/docs/src/routes/demo/state/no-serialize/index.tsx
packages/qwik/src/core/render/ssr/render-ssr.ts
starters/apps/e2e/src/components/ref/ref.tsx
starters/e2e/e2e.ref.spec.ts

fix: dynamic refs

---

.vscode/launch.json
packages/qwik-labs/src/qwik-types/public-api.ts

fix(labs): double slash when used with BASE_URL

---

packages/qwik/src/prefetch-service-worker/direct-fetch.ts
packages/qwik/src/prefetch-service-worker/process-message.ts
packages/qwik/src/prefetch-service-worker/setup.ts
packages/qwik/src/prefetch-service-worker/state.ts

fix: prevent race condition

---

packages/docs/src/repl/monaco.tsx

this way, import name completion works (but still not auto adding imports)

fix(repl): give monaco the names of the imports

---

packages/docs/src/routes/demo/cookbook/combine-request-handlers/index.tsx
packages/docs/src/routes/docs/cookbook/combine-request-handlers/index.mdx
packages/docs/src/routes/docs/cookbook/index.mdx
packages/docs/src/routes/docs/menu.md

docs(cookbook): add Combine Request Handlers example

---

starters/features/pandacss/package.json

Overview
Updating to the latest releasesd @panda/dev package.

chore(starters): update 🐼 PandaCSS integration dev dependency 

---

packages/docs/check-qwik-build.ts
packages/docs/package.json
packages/docs/src/repl/bundled.tsx
packages/docs/src/repl/editor.tsx
packages/docs/src/repl/monaco.tsx
packages/docs/src/repl/repl-detail-panel.tsx
packages/docs/src/repl/repl-options.tsx
packages/docs/src/repl/repl-share-url.ts
packages/docs/src/repl/repl-version.ts
packages/docs/src/repl/repl.tsx
packages/docs/src/repl/types.ts
packages/docs/src/repl/worker/repl-constants.ts
packages/docs/src/repl/worker/repl-dependencies.ts
packages/docs/src/repl/worker/repl-plugins.ts
packages/docs/vite.config.ts
packages/qwik/build/index.d.ts
tsconfig-docs.json

- allow using the current qwik version while developing
- remove v= from url if it's the bundled version
- also bundle prettier

feat(repl): use bundled qwik and prettier versions

---

packages/docs/src/repl/worker/repl-server.ts

Add sandbox atttributes to playground iframe for additional security.

fix(docs): Sandbox playground iframe

---

packages/docs/package.json
packages/docs/src/repl/worker/repl-server.ts
packages/docs/src/routes/docs/integrations/astro/index.mdx

docs(astro): update integration doc

---

packages/docs/src/routes/docs/integrations/astro/index.mdx

Had an issue where I was getting errors. Opened an issue, found the fix, and PR for adding it to the doc. https://github.com/BuilderIO/qwik/issues/5716
- 1. User has preact/react integrations too

docs: add note about Astro integrations order importance

---

.eslintignore
packages/qwik/src/prefetch-service-worker/setup.ts
packages/qwik/src/prefetch-service-worker/state.ts

Fixes https://github.com/QwikDev/astro/issues/56
Paired on this with wout, was not able to reproduce the error after the changes made in this PR.

fix: SW cache race condition

---

package.json
packages/create-qwik/package.json
packages/eslint-plugin-qwik/package.json
packages/qwik-city/package.json
packages/qwik/package.json

chore: 1.4.2

---

starters/apps/base/package.json
starters/apps/library/package.json

fix #5773
Changed vite version on starter packages 

chore(vite): downgrade vite version

---

packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx

chore(docs): align indentation

---

starters/features/pandacss/package.json

Overview
Updating to the latest released @panda/dev package.

chore(starters): update 🐼 PandaCSS integration starter dev dependency

---

packages/qwik/src/core/style/scoped-stylesheet.ts
packages/qwik/src/core/style/scoped-stylesheet.unit.ts

fixes #5812
that was a trivial fix :sweat_smile:

fix(scoped styles): @container block

---

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx

docs: fix qwik-nutshell example

---

starters/features/pandacss/package.json

Updating to the latest released @panda/dev package.

chore: Update 🐼 PandaCSS integration dev dependenc

---

packages/docs/src/routes/docs/labs/index.mdx

C.f. https://github.com/BuilderIO/qwik/issues/5803

docs(qwik-labs): npm installation issue

---

packages/docs/src/routes/docs/labs/index.mdx

docs(qwik-labs): fix typo

---

packages/qwik/src/core/render/dom/notify-render.ts
packages/qwik/src/core/state/common.ts
packages/qwik/src/core/state/store.ts
packages/qwik/src/core/use/use-on.ts
packages/qwik/src/core/use/use-task.ts
packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/rendering.unit-util.tsx
packages/qwik/src/core/v2/shared/event-names.ts
packages/qwik/src/core/v2/shared/event-names.unit.tsx
packages/qwik/src/core/v2/shared/scheduler.ts
packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/shared/shared-serialization.unit.ts
packages/qwik/src/core/v2/ssr/render2.ts
packages/qwik/src/core/v2/ssr/ssr-render.ts
packages/qwik/src/core/v2/use-on.unit.tsx
packages/qwik/src/core/v2/use-task.unit.tsx
packages/qwik/src/core/v2/use-visible-task.unit.tsx
packages/qwik/src/core/v2/vdom-diff.unit-util.ts
packages/qwik/src/qwikloader.ts
packages/qwik/src/testing/element-fixture.ts

This PR adds more use visible task tests with fixes for v2

test(use-visible-task): add more use visible task tests

---

package.json

chore: fix vite build

---

packages/docs/src/routes/tutorial/tutorial-content-footer.tsx

Added Reset button to tutorial
https://www.loom.com/share/bb4a5b136c434541aa6409ec60e25e61?sid=e36ab391-9630-40d2-a5a6-eaeded3e4a93
fixes #5860 

docs(tutorial): add reset button

---

packages/qwik/src/core/v2/README.unit.tsx

For those that prefer a video "tutorial" to help for v2 and later improvements.

chore: add around tutorial link to v2 README.unit.tsx

---

packages/docs/src/routes/demo/cookbook/streaming-deferred-loaders/index.tsx
packages/docs/src/routes/docs/cookbook/index.mdx
packages/docs/src/routes/docs/cookbook/streaming-deferred-loaders/index.mdx
packages/docs/src/routes/docs/menu.md

docs: add "Streaming/deferred loaders" cookbook

---

packages/docs/src/routes/(ecosystem)/media/index.tsx

Add link to YouTube video in "Video" section.
Adds a video tutorial to the respective docs page.

docs: Update media page with new YouTube video link

---

packages/docs/src/routes/docs/deployments/deno/index.mdx

docs: add Deno SSR caveat

---

starters/features/builder.io/package.json

fix(feature/builder.io): upgrade deps to support ESM

---

packages/docs/wrangler.toml

chore: Update wrangler.toml with AsyncLocalStorage flag

---

packages/docs/wrangler.toml

chore: Revert: Update wrangler.toml with AsyncLocalStorage flag

---

packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/component.unit.tsx

test(v2): add Parent Child test case 

---

packages/qwik/src/core/use/use-task.ts
packages/qwik/src/core/v2/use-computed.unit.tsx

test(v2): add possible improvements tests

---

packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/ssr/ssr-container.ts
packages/qwik/src/core/v2/ssr/vnode-data.unit.tsx

This PR fixes vnodes ref ids and adds basic tests

test(vnode-data): tests for vnode data refids

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/component.unit.tsx
packages/qwik/src/core/v2/container.unit.tsx
packages/qwik/src/core/v2/projection.unit.tsx
packages/qwik/src/core/v2/shared/types.ts
packages/qwik/src/core/v2/ssr/ssr-container.ts

This PR adds conditional rendering tests and fixes to them for v2

test(v2): add conditional rendering tests

---

packages/qwik/src/core/v2/use-visible-task.unit.tsx

This PR fixes/changes test with promises for visible task

test: change promises test for visible task

---

packages/docs/scripts/pages.json

docs: add new website to showcase

---

packages/qwik/src/core/v2/use-computed.unit.tsx

test: change descriptions

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/ssr/ssr-render.ts
packages/qwik/src/core/v2/use-computed.unit.tsx
packages/qwik/src/core/v2/use-context.unit.tsx
packages/qwik/src/core/v2/use-signal.unit.tsx
packages/qwik/src/core/v2/use-store.unit.tsx

test(v2): add ClassList tests

---

starters/apps/base/vite.config.ts

chore(starters): better externals configuration

---

packages/docs/src/routes/docs/cookbook/debouncer/index.mdx

docs: small changes to the debouncer cookbook

---

packages/qwik/src/core/state/common.ts
packages/qwik/src/core/use/use-task.ts
packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/component.unit.tsx
packages/qwik/src/core/v2/shared/scheduler.ts
packages/qwik/src/core/v2/use-on.unit.tsx
packages/qwik/src/core/v2/use-task.unit.tsx
packages/qwik/src/core/v2/use-visible-task.unit.tsx

test(v2): test for issue #5782

---

packages/qwik/src/core/v2/use-task.unit.tsx

This PR adds test for issue #4332  for v2.

test(v2): test for issue #4332

---

packages/qwik/src/core/v2/use-context.unit.tsx

This PR adds test for issue #4038 

test(v2): test for issue #4038

---

packages/qwik/src/core/v2/render-api.unit.tsx
packages/qwik/src/core/v2/ssr/ssr-container.ts
packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts
packages/qwik/src/core/v2/ssr/ssr-render2.ts
packages/qwik/src/core/v2/ssr/types.ts

feat(v2): add build base option

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/render-api.unit.tsx
packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/ssr/ssr-container.ts
packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts
packages/qwik/src/core/v2/ssr/ssr-render2.ts

feat(v2): static mode impl

---

packages/qwik/src/core/v2/render-api.unit.tsx
packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/ssr/ssr-container.ts
packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts

feat(v2): qwik events impl

---

packages/qwik/src/core/v2/render-api.unit.tsx
packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/ssr/ssr-container.ts
packages/qwik/src/core/v2/ssr/ssr-render2.ts
packages/qwik/src/server/prefetch-implementation.ts

test(v2): qwik funcs and debug tests

---

package.json
packages/qwik/src/server/.eslintrc.cjs
pnpm-lock.yaml

feat(v2): add import eslint rules

---

packages/qwik/src/core/v2/render-api.unit.tsx
packages/qwik/src/core/v2/shared/shared-container.ts
packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts
packages/qwik/src/core/v2/ssr/ssr-types.ts
packages/qwik/src/core/v2/use-styles-scoped.unit.tsx
packages/qwik/src/core/v2/use-styles.unit.tsx
packages/qwik/src/server/v2-ssr-container.ts

feat(v2): handle style body wrapper and qwik loader top position

---

packages/qwik/src/core/v2/client-render.unit.tsx
packages/qwik/src/core/v2/ssr-render.unit.tsx
packages/qwik/src/server/v2-ssr-container.ts
packages/qwik/src/server/v2-tag-nesting.ts

feat(v2): handle self closing elements

---

packages/qwik/src/core/v2/render-api.unit.tsx
packages/qwik/src/server/v2-tag-nesting.ts
packages/qwik/src/server/v2-tag-nesting.unit.ts
starters/apps/e2e/src/components/render/render.tsx
starters/apps/e2e/src/components/slot/slot.tsx

fix(v2): fix svg, math and thead tag nesting

---

packages/docs/src/routes/docs/deployments/cloudflare-pages/index.mdx

When using `npm create qwik@latest` you'll use a later version of nodejs than Cloudflare uses by default.

docs: update Cloudflare Pages Guide

---

packages/docs/src/routes/plugin@builder.io-redirect.ts

docs: correct redirect

---

packages/qwik-city/adapters/shared/vite/index.ts

fixes https://github.com/BuilderIO/qwik/issues/6069

fix: custom origin protocol

---

packages/docs/src/components/header/header.css
packages/docs/src/components/on-this-page/on-this-page.css
packages/docs/src/components/on-this-page/on-this-page.tsx
packages/docs/src/components/sidebar/sidebar.css
packages/docs/src/global.css
packages/docs/src/routes/community/layout.tsx
packages/docs/src/routes/docs/docs.css
packages/docs/src/routes/docs/layout.tsx

fix(layout): revert fix layout for non-default html font-size

---

packages/qwik/src/core/v2/client/dom-container.ts
packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/use-visible-task.unit.tsx

This PR fixes an infinity loop for empty text

fix(v2): fix infinity loop with empty text

---

packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/use-context.unit.tsx

test(v2): change #4038 test

---

packages/qwik/src/core/v2/README.unit.tsx
packages/qwik/src/core/v2/optimizer-output.unit.tsx
packages/qwik/src/core/v2/projection.unit.tsx
packages/qwik/src/core/v2/render-promise.unit.tsx
packages/qwik/src/core/v2/use-computed.unit.tsx
packages/qwik/src/core/v2/use-context.unit.tsx
packages/qwik/src/core/v2/use-on.unit.tsx
packages/qwik/src/core/v2/use-resource.unit.tsx
packages/qwik/src/core/v2/use-signal.unit.tsx
packages/qwik/src/core/v2/use-store.unit.tsx
packages/qwik/src/core/v2/use-styles-scoped.unit.tsx
packages/qwik/src/core/v2/use-styles.unit.tsx
packages/qwik/src/core/v2/use-task.unit.tsx
packages/qwik/src/core/v2/use-visible-task.unit.tsx

test(v2): migrate tests to describe.each

---

packages/qwik/src/prefetch-service-worker/process-message.ts

fix: extra null fetch from SW

---

packages/docs/src/routes/docs/layout.tsx

fix(docs): horizontal scroll issue in docs on mobile

---

packages/docs/src/components/on-this-page/on-this-page.css
packages/docs/src/global.css

fix(docs): solve aside style issue

---

packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/component.unit.tsx
packages/qwik/src/core/v2/vdom-diff.unit-util.ts

This PR fixes a problem with text node rendering

test(v2): add test for rendering text node between nodes

---

packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts
packages/qwik/src/qwikloader.ts
packages/qwik/src/testing/element-fixture.ts

add stoppropagation:<event> attribute like preventdefault:<event>
fixes https://github.com/QwikDev/qwik/issues/5322

feat(qwikloader): stoppropagation

---

.vscode/launch.json
packages/qwik/src/qwikloader.ts

Fixes typo in https://github.com/QwikDev/qwik/pull/6123

fix: replace ev.cancelBubble w/ cancelBubble

---

packages/docs/src/routes/docs/(qwik)/deprecated-features/index.mdx

docs(deprecated-features): routeAction$

---

packages/docs/src/routes/docs/(qwik)/deprecated-features/index.mdx

fix(docs): fix up typo

---

packages/qwik-city/middleware/vercel-edge/index.ts

add Vercel Skew Protection
https://vercel.com/docs/deployments/skew-protection

feat(vercel-edge): add Vercel Skew Protection

---

packages/docs/package.json
pnpm-lock.yaml

feat: update qwik-image version

---

packages/qwik/src/core/v2/client/dom-container.ts
packages/qwik/src/core/v2/client/dom-render.ts
packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/projection.unit.tsx

This PR adds cleanup for unclaimed projections wrapped in components

fix(v2): cleanup unclaimed projections wrapped in components

---

packages/qwik/src/core/v2/component.unit.tsx
packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts

This PR fixes multiple QRLs on event wrapped in array

fix(v2): multiple QRLs on event

---

packages/qwik/src/core/use/use-task.ts

fix(v2): prevent rejected promisses from crashing server

---

packages/qwik/src/core/v2/shared/shared-serialization.ts

This PR add skipping object field serialization with noSerialize

fix(v2): skip object field serialization with noSerialize

---

packages/qwik/src/core/container/pause.ts
packages/qwik/src/core/render/dom/notify-render.ts
packages/qwik/src/core/state/common.ts
packages/qwik/src/core/state/context.ts
packages/qwik/src/core/use/use-on.ts
packages/qwik/src/core/use/use-resource.ts
packages/qwik/src/core/use/use-task.ts
packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/container.unit.tsx
packages/qwik/src/core/v2/shared/component-execution.ts
packages/qwik/src/core/v2/shared/scheduler.ts
packages/qwik/src/core/v2/shared/scheduler.unit.tsx
packages/qwik/src/core/v2/use-visible-task.unit.tsx
starters/e2e/e2e.effect-client.spec.ts

This PR fixes visible task e2e tests

fix(v2): visible task e2e tests fixes

---

packages/qwik/src/core/render/jsx/jsx-runtime.ts
packages/qwik/src/server/v2-ssr-container.ts
packages/qwik/src/server/v2-ssr-render2.ts

fix(v2): don't crash on rendering MDX

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/component.unit.tsx
packages/qwik/src/server/v2-ssr-render2.ts

fix(v2): fix advonce next sibling with retrieve keys

---

packages/qwik/src/core/render/jsx/jsx-runtime.ts
packages/qwik/src/core/v2/client/dom-container.ts
packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/shared/component-execution.ts
starters/apps/e2e/src/components/ref/ref.tsx

This PR fixes the ref e2e test

fix(v2): ref e2e tests fixes

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

docs: Update routing index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx

docs: Update pages index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwikcity)/layout/index.mdx

docs: Update layout index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwikcity)/advanced/menu/index.mdx

docs: Update menu index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwikcity)/api/index.mdx

docs: Update API Reference index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwikcity)/advanced/request-handling/index.mdx

docs: Update request-handling index.mdx capitalize text

---

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx

docs: Update action index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

docs: Update components/overview index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

docs: Update components/date index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwik)/advanced/modules-prefetching/index.mdx

docs: Update advanced modules prefetching index.mdx verbiage

---

package.json
packages/qwik/src/core/state/signal.ts
packages/qwik/src/core/v2/render-api.unit.tsx

This PR fixes a regression related to the signal serialization

fix(v2): change SignalWrapper to SignalDerived

---

packages/qwik/src/core/render/jsx/types/jsx-generated.ts
packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/client/vnode.unit.tsx
packages/qwik/src/core/v2/component.unit.tsx
packages/qwik/src/core/v2/shared/component-execution.ts
packages/qwik/src/core/v2/shared/types.ts
packages/qwik/src/core/v2/ssr/ssr-render-component.ts
packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts
packages/qwik/src/server/qwik-copy.ts
packages/qwik/src/server/v2-ssr-container.ts

This PR adds implementation for textarea value

feat(v2): textarea value

---

packages/docs/src/routes/docs/(qwik)/components/slots/index.mdx

docs: Update components/slots index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwik)/components/rendering/index.mdx

docs: Update components/rendering index.mdx verbiage and phrasing

---

packages/qwik/src/core/use/use-task.ts
packages/qwik/src/core/v2/use-task.unit.tsx
starters/apps/e2e/src/components/exceptions.tsx
starters/apps/e2e/src/entry.ssr.tsx

fix(v2): handle DerivedSignal in useTask.track

---

starters/apps/base/vite.config.ts

fix dupe error only when dupes

fix(vite.config): error only when dupe

---

packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx

docs(routing): plugin

---

packages/docs/src/routes/docs/(qwik)/advanced/vite/index.mdx
packages/docs/src/routes/docs/(qwikcity)/advanced/plugins/index.mdx
packages/docs/src/routes/docs/menu.md
pnpm-lock.yaml

clarify vite plugins and qwik plugins
moving some docs about plugins into its own page. rename vite "plugin" to "vite plugin"

docs(plugin): qwik plugin and vite plugin

---

packages/docs/src/components/sidebar/sidebar.tsx
packages/docs/src/global.css

fix scroll position in docs sidebar
fixes https://github.com/QwikDev/qwik/issues/6233
also fixes feedback from discord

docs(sidebar): save scroll position, wider, and prefetch

---

.github/ISSUE_TEMPLATE/bug.yaml
packages/qwik-city/runtime/src/qwik-city-component.tsx
packages/qwik-city/runtime/src/sw-register.ts
starters/apps/base/src/entry.ssr.tsx
starters/apps/empty/src/routes/index.tsx
starters/apps/site-with-visual-cms/src/entry.ssr.tsx

fixes #6235
fixes https://github.com/QwikDev/qwik/issues/6114

fix(starters/empty): avoid p element gotchas

---

packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx

use the button as shown in the example above 
Fix docs error
line 39 says `<button onClick$={() => console.log('hello')}>Hello Qwik</button>;` so the child should be button

docs: advanced/dollar correct button

---

packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx

docs: Update qwikcity index.mdx verbiage and phrasing

---

packages/qwik/src/core/render/jsx/jsx-runtime.ts
packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/server/v2-ssr-container.ts

fix(v2): incorrect qvnode-data encoding

---

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

docs: Update components/overview index.mdx to add export default

---

packages/docs/src/routes/docs/integrations/authjs/index.mdx

fixes https://github.com/QwikDev/qwik/issues/4715#issuecomment-1620321148
fixes https://github.com/QwikDev/qwik/issues/4607

docs: Update authjs index.mdx add environment vars for node

---

packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx

docs: Update components/tasks index.mdx useVisibleTask$

---

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx

Updating the docs for the environment variables. Adding in the environment variables QwikCity adds by default. Adding some additional clarifying langauge
Expanding the documentation around environment variables.

docs: Environment Variables

---

packages/qwik/src/core/render/ssr/render-ssr.ts
packages/qwik/src/optimizer/src/plugins/click-to-component.html

bypass data-qwik-inspector if dev defined data-qwik-inspector="false"
fixes https://github.com/QwikDev/qwik/issues/5016

fix(data-qwik-inspector): bypass data-qwik-inspector when needed

---

starters/apps/base/src/entry.preview.tsx

fixes https://github.com/QwikDev/qwik/issues/4760

style(base/entry.preview.tsx): comment

---

packages/qwik/src/core/container/pause.ts

fixes https://github.com/QwikDev/qwik/issues/5289

feat(pause): capture errors in tasks

---

packages/qwik/src/optimizer/src/plugins/click-to-component.html

fix https://github.com/QwikDev/qwik/issues/3710

fix(Click-to-Source ): fix windows

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

fixes https://github.com/QwikDev/qwik/issues/3341

docs: Update components/state index.mdx removing store objects

---

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx

fixes https://github.com/QwikDev/qwik/issues/5561#issuecomment-1854639063

docs: Update env-variables index.mdx add docker and fastify note

---

packages/docs/src/components/docsearch/stored-searches.ts
packages/docs/src/components/router-head/theme-script.tsx
packages/docs/src/components/sidebar/sidebar.tsx
packages/docs/src/components/theme-toggle/theme-toggle.tsx

fixes https://github.com/QwikDev/qwik/issues/6264

fix(docs): try-catch local and session storage

---

packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx

docs: Update components/tasks index.mdx add useTask async note

---

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx

docs: Update env-variables index.mdx with lifecycle section

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

fixes https://github.com/QwikDev/qwik/issues/6252

docs: Update routing index.mdx prevent prefetching behavior

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

docs(<Link prefetch>): clarify that prefetch is on by default

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

docs(store): explain arrow function vs regular function gotcha

---

packages/docs/src/routes/docs/(qwikcity)/caching/index.mdx

docs: Update caching index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/(qwikcity)/html-attributes/index.mdx

docs: Update html-attributes index.mdx verbiage and phrasing

---

packages/docs/src/routes/docs/integrations/index.mdx

docs: Update integrations index.mdx

---

packages/docs/src/routes/docs/integrations/bootstrap/index.mdx

docs: Update bootstrap index.mdx verbiage and phrasing

---

starters/e2e/qwikcity/actions.spec.ts

chore: fix Test Typo

---

starters/adapters/aws-lambda/src/entry_aws-lambda.tsx

refactor(aws): handler alias

---

packages/qwik-city/middleware/node/http.ts

fixes https://github.com/QwikDev/qwik/issues/6278

fix(http): ignore http2 headers

---

CONTRIBUTING.md

docs(CONTRIBUTING): spelling fix

---

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx

docs(qwik-nutshell): more code examples for isServer

---

packages/qwik/src/core/container/container.ts
packages/qwik/src/qwikloader.ts

refactor(qwikloader): add types and no handler qerror

---

packages/docs/src/routes/docs/cookbook/algolia-search/index.mdx

Rewrote sentence to use better grammar and to be clearer and more concise.
Rewording and grammar corrections.
- 1. Improves readability.

docs: Grammar correction and rewording

---

packages/docs/src/routes/docs/(qwikcity)/api/index.mdx

A back-and-forth fix
Back and forth fix. Right now it's not looping
1. User wants to go back

docs: Fixing back-and-forth

---

packages/docs/src/routes/api/qwik-city/api.json
packages/docs/src/routes/api/qwik-city/index.md
packages/qwik-city/runtime/src/api.md
packages/qwik-city/runtime/src/qwik-city-component.tsx
packages/qwik-city/runtime/src/types.ts

add support for history for easy back button

feat(RouteNavigate): nav(-1) history support

---

starters/adapters/vercel-edge/vercel.json

feat(vercel): no cache <any>service-worker.js files

---

starters/adapters/cloudflare-pages/public/_headers

feat(cloudflare): no-store <any>service-worker.js

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/tests/render-regression.spec.tsx

fix(v2): properly insert/remove element with key

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/tests/projection.spec.tsx

fix(v2): correct projection cleanup

---

packages/docs/public/repl/~repl-server-host.html
packages/docs/src/root.tsx
packages/insights/src/root.tsx
packages/qwik-city/buildtime/vite/dev-server.ts
packages/qwik-city/middleware/request-handler/error-handler.ts
packages/qwik-city/runtime/src/qwik-city-component.tsx
packages/qwik-labs/src/root.tsx
packages/qwik-react/src/root.tsx
packages/qwik/src/core/render/jsx/types/jsx-generated.ts
packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__issue_476.snap
packages/qwik/src/optimizer/core/src/test.rs
starters/apps/e2e/src/entry.ssr.tsx
starters/apps/empty/src/root.tsx
starters/apps/library/src/root.tsx
starters/apps/perf.prod/src/root.tsx
starters/apps/qwikcity-test/src/root.tsx
starters/apps/site-with-visual-cms/src/root.tsx
starters/apps/starter-partytown-test/src/root.tsx
starters/apps/todo-old-test/src/root.tsx
starters/apps/todo-test/src/root.tsx
starters/features/cypress/cypress/support/component-index.html

more issues and types are wrong

fix: all charSet utf-8 issues

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/shared/types.ts
packages/qwik/src/core/v2/tests/component.spec.tsx

This PR fixes the dangerouslySetInnerHTML prop in varProps

fix(v2): fix dangerouslySetInnerHTML in varProps

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/tests/component.spec.tsx

feat(v2): SkipRender impl

---

packages/docs/wrangler.toml

chore(docs): update cloudflare compatibility flags and date

---

packages/qwik-city/buildtime/build-pages-rewrited.unit.ts
packages/qwik-city/buildtime/build.ts
packages/qwik-city/utils/test-suite.ts
starters/apps/qwikcity-test/src/routes/produkt/index.tsx

fix(qwikcity): duplicated rewrite routes with multiple prefixes

---

contributing/TRIAGE.md

docs(triage.md): fix typos

---

SECURITY.md

Added a security policy and a way for community members to report security issues privately.
Fixes #6203

docs: added SECURITY.md

---

.github/workflows/labeling-issues.yml

made a nicer looking auto message for stale issues

chore: formatted auto comments on issues

---

.github/workflows/ci.yml
packages/qwik/src/core/api.md
starters/e2e/e2e.containers.e2e.ts
starters/e2e/e2e.render.e2e.ts
starters/e2e/e2e.resource.e2e.ts
starters/e2e/e2e.signals.e2e.ts
starters/e2e/e2e.slot.e2e.ts
starters/e2e/e2e.streaming.e2e.ts
starters/e2e/e2e.toggle.e2e.ts
starters/e2e/qwikcity/actions.e2e.ts
starters/e2e/qwikcity/auth.e2e.ts
starters/e2e/qwikcity/locale.e2e.ts
starters/e2e/qwikcity/menu.e2e.ts
starters/e2e/qwikcity/nav.e2e.ts
starters/e2e/qwikcity/page.e2e.ts

This just makes the pipeline green to avoid regressions

chore(v2): make the pipeline green

---

packages/qwik/src/core/api.md
packages/qwik/src/core/util/markers.ts
packages/qwik/src/core/v2/client/dom-container.ts
packages/qwik/src/core/v2/client/process-vnode-data.ts
packages/qwik/src/core/v2/client/process-vnode-data.unit.tsx
packages/qwik/src/core/v2/client/types.ts
packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/shared/vnode-data-types.ts
packages/qwik/src/server/qwik-copy.ts
packages/qwik/src/server/v2-ssr-container.ts
packages/qwik/src/testing/vdom-diff.unit-util.ts

feat(v2): `processVNodeData` can now handle MFEs and foreign SSR content

---

contributing/TRIAGE.md

Added the use case for "community PRs"

docs: update TRIAGE.md

---

packages/create-qwik/src/helpers/jokes.json

feat: add some jokes

---

packages/qwik/src/core/v2/tests/use-context.spec.tsx
packages/qwik/src/server/v2-ssr-container.ts
starters/e2e/e2e.containers.e2e.ts
starters/e2e/qwikcity/actions.e2e.ts
starters/e2e/qwikcity/auth.e2e.ts
starters/e2e/qwikcity/menu.e2e.ts
starters/e2e/qwikcity/nav.e2e.ts

This PR fixes useContext for html wrapper. This is fix for some failing qwikcity e2e tests

fix(v2): useContext for html wrapper

---

package.json
scripts/e2e-cli.ts

chore(v2): easier way of running e2e tests

---

packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx

Small grammar corrections in the qwikcity Pages documentation.
- 1. Grammar corrections

docs: Grammar corrections.

---

packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx

docs(server$): RequestEvent info

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/client/vnode-namespace.ts
packages/qwik/src/core/v2/client/vnode.ts
packages/qwik/src/core/v2/tests/component.spec.tsx

This fixes a svg with content set by dangerouslySetInnerHTML

fix(v2): svg with innerHTML content

---

packages/qwik-auth/package.json

feat(qwik-auth): v0.2.2

---

starters/features/auth/package.json

feat: update Auth.js starter

---

packages/docs/src/components/docsearch/search-box.tsx
packages/docs/src/routes/docs/(qwik)/index.mdx

docs: updating overview

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: update documented minim node version

---

starters/e2e/qwikcity/locale.e2e.ts

Fixes the broken locale e2e test

test: fix locale e2e test

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: fix up playground section

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: improve Posting Data section

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: improve Preview section

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

docs: improve Review section

---

packages/docs/src/routes/docs/(qwikcity)/project-structure/index.mdx

docs: reword for readability

---

packages/docs/src/routes/docs/(qwikcity)/project-structure/index.mdx

docs: improve readability

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

docs: rewording; added punctuation

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

docs: improve vDOM explanation

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

docs: reword; edit run on sentences

---

packages/docs/src/routes/docs/(qwik)/faq/index.mdx

docs: improve faq

---

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

docs: fixed grammar

---

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

docs: added punctuation

---

packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx

docs: punctuation

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

docs: removed we

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

docs: added punctuation; made name plural

---

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx

docs: header change

---

packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx

docs: removed let's; added colon

---

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx

docs: removed we; fixed sentence structure

---

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx

docs: more concise; readability; punctuation

---

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx

docs: removed we; improved syntax

---

packages/docs/src/routes/docs/(qwikcity)/api/index.mdx

docs: (qwikcity/api) removed we; improved sentence structure

---

packages/docs/src/routes/docs/(qwikcity)/env-variables/index.mdx

docs: (qwikcity/env-variables) removed we; punctuation (oxford comma :))

---

packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx

docs: (qwik city/overview) punctuation; removed we; parallelism

---

packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx

docs: (qwikcity/routing) removed we; punctuation; improved readability; grammar

---

packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx

docs: (qwikcity/pages) grammar; typo

---

packages/docs/src/routes/docs/(qwikcity)/layout/index.mdx

docs: (qwikcity/layout) grammar; removed we; removed let's; punctuation

---

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx

docs: (qwikcity/actions) grammar; readability; removed we; punctuation

---

packages/docs/src/routes/docs/(qwikcity)/endpoints/index.mdx

docs: (qwikcity/endpoints) grammar; readability

---

packages/docs/src/routes/docs/(qwikcity)/middleware/index.mdx

docs: (qwikcity/middleware) grammar; typo; readability

---

packages/docs/src/routes/docs/(qwikcity)/caching/index.mdx

docs: (qwikcity/caching) punctuation; removed we; improved syntax

---

packages/qwik/src/optimizer/src/plugins/vite.ts

fix: support Win environment

---

packages/docs/src/routes/docs/(qwik)/concepts/reactivity/index.mdx

docs: (concepts/reactivity) added comma

---

packages/docs/src/routes/docs/(qwik)/concepts/progressive/index.mdx

docs: (concepts/progressive) punctuation; removed we; removed let's

---

packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx

Original link did not work. localhost, however, does work.

docs: update tutorial

---

packages/docs/src/routes/docs/(qwik)/concepts/think-qwik/index.mdx

docs: (concepts/think-qwik) removed we; punctuation; grammar

---

packages/docs/src/routes/docs/(qwik)/concepts/resumable/index.mdx

docs: (concepts/resumable) removed we; readability

---

packages/docs/src/routes/docs/integrations/tauri/index.mdx

I saw that the tauri integrations docs weren't explaining how to set up a tauri app with qwik. I found it to be an extra hurdle to go over to the tauri docs, so I added the docs from the official website to make the process a bit faster.
You want to swiftly set up Tauri. Having the full docs in one place is a bit more efficient than jumping from page to page.

docs: improve Tauri integration

---

packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/tests/use-store.spec.tsx

This fixes setting store value with serialization constant at the start + "unskip" one test which is not failing now

fix(v2): fix setting store value with serialization constant at the start

---

packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx

docs: sw debug mode

---

packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx

docs: improve debug mode docs

---

packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts

feat(vite-imagetools): add fetch priority support

---

packages/qwik-city/buildtime/vite/plugin.ts
packages/qwik-city/buildtime/vite/types.ts

revert: expose MDX transformer and context

---

packages/docs/check-qwik-build.ts
packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
packages/docs/vite.config.mts
packages/qwik/src/core/v2/shared/shared-serialization.ts

This PR fixes some build problems on windows and fixes serializing QRLs

fix(v2): docs build + serialize QRL

---

packages/qwik/src/core/v2/client/vnode-diff.ts
packages/qwik/src/core/v2/tests/projection.spec.tsx
starters/e2e/e2e.slot.e2e.ts

this PR fixes toggling slots in v2

fix(v2): slot toggle fixes

---

packages/docs/src/routes/index.tsx

docs: comment out extra sponsor component

---

packages/docs/src/components/docsearch/doc-search.tsx

docs: fix conflicting ctrl+k shortcut

---

packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx

I deleted redundant bullet points, because without the context of the paragraph before it (which devs might be reading the bullet points after a search), it's not clear that the comparison is done against React anymore.
The line deleted
> For `<input>`, the `onChange` event is called `onInput$` in Qwik.
assumes people are coming from React, where `onChange` is like html's `oninput` . Whereas Qwik's `onChange$` and `onInput$` actually reflect html's `onchange` and `oninput`, respectively 🕺.
Ref: 
https://www.w3schools.com/tags/att_onchange.asp
https://www.w3schools.com/tags/att_oninput.asp
- 2. …

docs(qwik-nutshell): remove onInput$ reference to React onChange

---

.github/CODEOWNERS

Help us prevent accidental API changes to core

chore: add API changes guards

---

packages/docs/package.json
pnpm-lock.yaml

fix: fix up docs build

---

packages/qwik/src/core/components/prefetch.ts
packages/qwik/src/core/components/prefetch.unit.tsx
packages/qwik/src/prefetch-service-worker/process-message.ts
packages/qwik/src/server/prefetch-utils.ts
starters/adapters/fastify/package.json

Here is the test I've done with this code

fix: SW prefetch

---

packages/qwik-city/runtime/src/server-functions.ts

refactor(server$): clean up var names

---

packages/qwik-city/middleware/request-handler/request-handler.ts
packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
packages/qwik-city/runtime/src/routing.ts
packages/qwik-city/runtime/src/server-functions.ts

Clean up the server functions code in Qwik city to make it easier to understand and to debug.
👉 NO PUBLIC API WAS CHANGED IN THIS PR

refactor(city): clean up code

---

packages/qwik/src/optimizer/src/plugins/vite.ts
packages/qwik/src/optimizer/src/plugins/vite.unit.ts

revert: #6522 & #6526

---

packages/qwik/src/core/platform/platform.ts
packages/qwik/src/core/qrl/qrl.unit.ts
packages/qwik/src/optimizer/src/plugins/plugin.ts
packages/qwik/src/optimizer/src/plugins/vite-dev-server.ts
packages/qwik/src/optimizer/src/plugins/vite.ts

dev mode fixes:
- QRL segment import fixes
- move parent build into plugin

fix(dev): qrl import and refactor parent building

---

packages/qwik/src/optimizer/src/plugins/plugin.ts
packages/qwik/src/optimizer/src/plugins/vite-dev-server.ts

prefix qrls that are not under srcDir with /@fs so they won't get rootdir added

fix(dev):  qrl loading for non-srcDir

---

packages/docs/src/routes/docs/(qwikcity)/api/index.mdx

Document how to access current url from within root.tsx Thanks to @shairez.

docs: Document how to access current url from within root.tsx

---

packages/qwik/src/core/components/prefetch.ts

fix: disable PrefetchGraph in dev mode

---

packages/docs/package.json
packages/docs/src/routes/demo/cookbook/leaflet-map/index.tsx
packages/docs/src/routes/docs/integrations/leaflet-map/index.mdx
pnpm-lock.yaml

Added an example of a Leaflet map component, a route, props, and JSON and GeoJSON files to create an initial reactive map.

docs: added an example for creating a dynamic Leaflet map

---

packages/qwik/src/optimizer/src/plugins/plugin.ts

fix: fix up csr mode

---

packages/qwik-city/adapters/cloudflare-pages/vite/index.ts

fix: solve _routes issue with assetsDir

---

packages/qwik/src/core/state/store.ts
packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/tests/use-store.spec.tsx

This PR fixes string deserialization with serialization constant at the start of string

fix(v2): fix string deserialization with serialization constant

---

packages/qwik/src/testing/document.ts

refactor: tiny adjustment for document testing

---

packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts

This PR fixes the qwik inspector in dev mode

fix(v2): qwik inspector

---

README.md

Removes the "made with" part of the logo images

docs: update readme footer logo

---

packages/create-qwik/src/helpers/jokes.json

chore: couldn't handle that joke anymore 😅

---

packages/qwik/src/optimizer/src/plugins/vite.ts

fix: replace chunkFileNames logic

---

packages/qwik/src/optimizer/src/plugins/plugin.ts

when vite is serving, emitFile doesn't work

fix(dev): avoid warning in dev mode

---

.github/workflows/ci.yml

Add cloudflare docs deployment via gh action

feat(v2): docs deployment

---

.github/CODEOWNERS

chore: add guarding to releases

---

packages/qwik/src/core/api.md
packages/qwik/src/core/internal.ts
packages/qwik/src/core/util/flyweight.ts
packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts
packages/qwik/src/server/v2-node.ts

This PR fixes a lot of issues from https://github.com/orgs/QwikDev/projects/1?pane=issue&itemId=70831601

fix(v2): mutating props

---

packages/just-for-checking-changesets/package.json

chore: add missing publishConfig

---

.changeset/config.json

ci: added qwik-labs to changesets ignore

---

.changeset/config.json
.github/workflows/bench.yml.disabled
.github/workflows/ci.yml
package.json
packages/docs/src/routes/docs/integrations/i18n/index.mdx
pnpm-workspace.yaml

the root version is used in several places and is also useful for humans

fix(changesets): version monorepo root

---

packages/qwik/src/core/v2/shared/component-execution.ts
packages/qwik/src/core/v2/tests/use-on.spec.tsx

This PR fixes more edge cases with useOn hook

fix(v2): more useOn fixes

---

packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts

This PR fixes some component rendering edge cases

fix(v2): mutating component props

---

packages/docs/src/routes/docs/labs/typed-routes/index.mdx

docs: Fix quotes in index.mdx

---

.changeset/funny-turtles-visit.md
packages/qwik/src/optimizer/core/src/lib.rs
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_drop_side_effects.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__lib_mode_fn_signal.snap
packages/qwik/src/optimizer/core/src/test.rs

fix(optimizer): don't drop _fnSignal string code in libs

---

.mock_changesets/fake_change.md

you can ignore this PR
it's just for testing purposes

ci: delete mock changeset md

---

.github/workflows/ci.yml

ci: remove disttag log

---

.changeset/config.json
.changeset/heavy-goats-approve.md
.github/workflows/ci.yml
CHANGELOG.md
package.json
pnpm-workspace.yaml
scripts/create-qwik-cli.ts
scripts/release.ts

Starters have "latest" for qwik packages instead of the recent released version
This fixes it

fix: correct version numbers for starter apps

---

.github/workflows/ci.yml
.github/workflows/deploy-docs.yml

this allows PR branches to also get docs previews

chore(ci):  move docs deploy to separate flow

---

.github/workflows/deploy-docs.yml

if at first you don't succeed...

fix(deploy-docs): artifact download

---

packages/qwik-city/buildtime/vite/dev-server.ts
packages/qwik-city/buildtime/vite/plugin.ts
packages/qwik-city/middleware/azure-swa/index.ts
packages/qwik-city/middleware/bun/index.ts
packages/qwik-city/middleware/cloudflare-pages/index.ts
packages/qwik-city/middleware/deno/index.ts
packages/qwik-city/middleware/netlify-edge/index.ts
packages/qwik-city/middleware/node/index.ts
packages/qwik-city/middleware/request-handler/api.md
packages/qwik-city/middleware/request-handler/request-event.ts
packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
packages/qwik-city/middleware/request-handler/types.ts
packages/qwik-city/middleware/vercel-edge/index.ts
packages/qwik-city/runtime/src/server-functions.ts
packages/qwik-city/runtime/src/use-endpoint.ts
packages/qwik-city/static/worker-thread.ts
packages/qwik-worker/src/index.ts
packages/qwik/src/core/api.md
packages/qwik/src/core/index.ts
packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/shared/shared-serialization.unit.ts
packages/qwik/src/core/v2/shared/types.ts

Change the old serialization to the new v2 serialization for the `server$`, actions and loaders

feat(v2): new server$, actions and loaders serialization

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

Update index.mdx : "javascript" to "JavaScript" 

---

packages/docs/src/root.tsx

This reverts commit 42f3940a5c59c519e0d6dffa43e572ca685f36e0.

Revert "chore(docs): use prefetch service worker"

---

package.json
packages/docs/src/repl/repl.tsx
packages/docs/src/repl/worker/app-bundle-client.ts
packages/docs/src/repl/worker/repl-dependencies.ts

fix(repl): version detection

---

packages/docs/src/routes/docs/menu.md

docs: add Core api reference in the the menu

---

packages/docs/src/routes/docs/labs/insights/index.mdx

Link was updated to https://insights.qwik.dev/

fixed insights link

---

GOVERNANCE.md

added governance doc

---

packages/docs/src/routes/api/qwik-city-middleware-request-handler/index.md

fix CDN Cache Control link in docs

---

Makefile
packages/qwik/src/optimizer/core/src/collector.rs
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__ternary_prop.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__transform_qrl_in_regular_prop.snap
packages/qwik/src/optimizer/core/src/test.rs

fix(optimizer): don't count `undefined` as an identifier

---

packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__impure_template_fns.snap
packages/qwik/src/optimizer/core/src/test.rs
packages/qwik/src/optimizer/core/src/transform.rs

fix(optimizer): mark fn`` children as jsx mutable

---

starters/apps/base/gitignore

chore(gitignore): gitignore .env

---

packages/docs/src/routes/docs/(qwikcity)/advanced/sitemaps/index.mdx

- [x ] Docs / tests / types / typos
- [ x] I have ran `pnpm change` and documented my changes
- [x ] I have made corresponding changes to the Qwik docs

docs: add update sitemap documentation for SSR

---

packages/docs/src/entry.ssr.tsx
packages/docs/src/root.tsx

Reverts QwikDev/qwik#6862
cc @maiieul I revert it as requested

Revert "chore: start the experiment with modulepreload on qwik.dev"

---

.changeset/twenty-brooms-speak.md
starters/features/tailwind/package.json

In a separate project, I've been using these current versions and it seems to be working great. It's been a bit tedious to upgrade each time, so though it'd be valuable to update these directly in the starter

refactor: update tailwind starter deps

---

.changeset/moody-squids-listen.md
Makefile
packages/qwik/src/optimizer/core/src/lib.rs
packages/qwik/src/optimizer/core/src/parse.rs
packages/qwik/src/optimizer/core/src/test.rs
packages/qwik/src/optimizer/core/src/transform.rs

this way libraries won't use internal APIs that may break between minor versions

feat(optimizer): don't qwik-transform lib builds

---

package.json
pnpm-lock.yaml

fix: sharp err -> "free(): invalid size"

---

.changeset/curvy-frogs-return.md
.changeset/forty-humans-jump.md
.changeset/moody-squids-listen.md
.changeset/pink-ravens-exist.md
.changeset/popular-dragons-greet.md
.changeset/shaggy-sloths-talk.md
.changeset/stupid-chicken-itch.md
.changeset/twenty-brooms-speak.md

We want to keep the changelog and release messages consistent

improved the changesets messages

---

.github/workflows/deploy-docs.yml
packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx

documenting task() because it's needed and it triggers a docs build

chore(docs): update deploy action + document task()

---

packages/qwik/src/core/v2/shared/shared-serialization.ts
packages/qwik/src/core/v2/signal/v2-signal.ts
packages/qwik/src/core/v2/signal/v2-subscriber.ts

Only WrappedSignal should be a subscriber. Signal and ComputedSingal shoudn't

fix(v2): only wrapped signal as a subscriber

---

packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__impure_template_fns.snap
packages/qwik/src/optimizer/core/src/test.rs
packages/qwik/src/optimizer/core/src/transform.rs

Backported the fix #6847 at v2 to the main.

fix(optimizer): Backported the fix `mark fn`` children as jsx mutable (#6847)` to the main branch

---

packages/create-qwik/src/helpers/jokes.json

chore: fix jokes.json

---

flake.lock
package.json
packages/qwik/src/core/client/dom-container.ts
packages/qwik/src/core/shared/qrl/qrl-class.ts
packages/qwik/src/core/shared/qrl/qrl.unit.ts
packages/qwik/src/core/shared/serialization.md
packages/qwik/src/core/shared/shared-container.ts
packages/qwik/src/core/shared/shared-serialization.ts
packages/qwik/src/core/shared/shared-serialization.unit.ts
packages/qwik/src/core/shared/types.ts
packages/qwik/src/core/shared/utils/markers.ts
packages/qwik/src/core/signal/signal.ts
packages/qwik/src/core/signal/store.ts
packages/qwik/src/core/ssr/ssr-render-jsx.ts
packages/qwik/src/core/ssr/ssr-types.ts
packages/qwik/src/core/tests/container.spec.tsx
packages/qwik/src/core/tests/render-api.spec.tsx
packages/qwik/src/core/tests/use-signal.spec.tsx
packages/qwik/src/core/tests/use-task.spec.tsx
packages/qwik/src/core/use/use-resource.ts
packages/qwik/src/optimizer/src/qwik-binding-map.ts
packages/qwik/src/server/qwik-copy.ts
packages/qwik/src/server/ssr-container.ts
packages/qwik/src/testing/rendering.unit-util.tsx
pnpm-lock.yaml

Goals here are readability, maintainability, performance. Some bugs are preemptively fixed
The previous v2 implementation used inline signaling via unicode characters and ad-hoc parsing.

refactor(v2): serialization

---

packages/docs/src/routes/docs/deployments/cloudflare-pages/index.mdx

add ssg documentation to cloudflare adapter docs

---

packages/docs/src/routes/docs/integrations/image-optimization/index.mdx

docs(image-optimization): explain image vite-imagetools `jsx` query param gotcha

---

packages/qwik/src/core/shared/shared-serialization.ts
packages/qwik/src/core/tests/use-computed.spec.tsx

small missing thing from previous pr

fixup(serdes)

---

packages/qwik-city/src/runtime/src/routing.ts
packages/qwik-city/src/runtime/src/server-functions.ts
packages/qwik-city/src/runtime/src/utils.ts
packages/qwik/src/core/api.md
packages/qwik/src/core/shared/qrl/qrl.unit.ts
packages/qwik/src/core/shared/shared-container.ts
packages/qwik/src/core/shared/shared-serialization.ts
packages/qwik/src/core/shared/shared-serialization.unit.ts
packages/qwik/src/core/shared/types.ts
packages/qwik/src/core/signal/store.ts
packages/qwik/src/core/tests/use-store.spec.tsx
packages/qwik/src/server/ssr-container.ts
packages/qwik/src/testing/rendering.unit-util.tsx

- freeze data shared between server side renders
- don't mutate store target while wrapping in the store proxy

fix(store): don't mutate store target while wrapping in the store proxy

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Update the guidelines now that we'll have only squash and merge merges.
[Rendered](https://github.com/QwikDev/qwik/blob/327eb5b2e8c97a6674f0118bc7faad6719195101/CONTRIBUTING.md)

chore: update contributing guidelines

---

packages/qwik/src/core/api.md
packages/qwik/src/core/debug.ts
packages/qwik/src/core/index.ts
packages/qwik/src/core/ssr/ssr-render-jsx.ts
packages/qwik/src/core/ssr/ssr-types.ts
packages/qwik/src/core/tests/projection.spec.tsx
packages/qwik/src/server/ssr-container.ts
packages/qwik/src/server/ssr-node.ts

fix(slots): get the right component frame while processing slots

---

packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/ssr/ssr-render-component.ts
packages/qwik/src/core/ssr/ssr-render-jsx.ts
packages/qwik/src/core/tests/inline-component.spec.tsx

This fixes inline component rendering

fix(render): fix inline component rendering

---

packages/insights/src/db/query.ts
packages/insights/src/db/sql-manifest.ts
packages/insights/src/db/sql-routes.ts
packages/insights/src/db/sql-user.ts
packages/insights/src/routes/api/v1/[publicApiKey]/post/index.tsx
packages/insights/src/routes/api/v1/[publicApiKey]/post/manifest/index.tsx
packages/insights/src/routes/app/[publicApiKey]/errors/index.tsx
packages/insights/src/routes/app/index.tsx

fix(insights): add query limits to prevent render timeout

---

packages/insights/src/routes/api/v1/[publicApiKey]/post/index.tsx
packages/insights/src/routes/app/[publicApiKey]/errors/index.tsx

fix(insights): fix build

---

README.md

fixed community link in README
fix #6995

fixed community link in README

---

.changeset/lazy-worms-attack.md
.changeset/many-turtles-cough.md
.changeset/ninety-planets-search.md
.changeset/pre.json
.changeset/real-garlics-argue.md
.changeset/shaggy-apes-kneel.md
.changeset/silver-countries-kiss.md
.changeset/thick-dodos-promise.md
.changeset/unlucky-experts-check.md
.github/workflows/ci.yml

This is a preparation PR for V2 alpha release.

Modified prerelease config for v2 alpha

---

packages/qwik/src/core/shared/utils/markers.ts
packages/qwik/src/core/ssr/ssr-render-jsx.ts
packages/qwik/src/core/ssr/ssr-types.ts
packages/qwik/src/core/tests/container.spec.tsx
packages/qwik/src/server/ssr-container.ts

This PR adds nesting error file location
Example:

feat(v2): add nesting error file location

---

packages/docs/src/routes/docs/deployments/cloudflare-pages/index.mdx
packages/docs/src/routes/docs/deployments/netlify-edge/index.mdx

Small PR - Commit e7a91a303e434ea1672c01f6b84384d333e4bb54 moved the middleware sources around. This PR adjusts sources to changes.

docs: update middleware sources references

---

packages/qwik/src/cli/migrate-v2/versions.ts

updated migration version

---

packages/docs/src/routes/docs/(qwikcity)/action/index.mdx

- Docs
Added missing example of how to upload files using actions programmatically

docs: added file upload example

---

packages/docs/public/_redirects
packages/docs/src/routes/docs/cookbook/index.mdx
packages/eslint-plugin-qwik/src/loaderLocation.ts
packages/qwik-city/src/runtime/src/server-functions.ts

fixed a broken link and its references
- [

fixed broken link to re-exporting loaders

---

packages/docs/src/routes/docs/(qwik)/components/events/index.mdx

We've added this feature back in April but it was never documented, this fixes it :)

added missing `stoppropagation` documentation

---

packages/docs/src/routes/docs/(qwik)/concepts/reactivity/index.mdx

- Docs
Updated wrong title on the Reactivity page title

docs: update index.mdx for Reactivity page title

---

packages/docs/src/root.tsx

docs: remove unregister sw script

---

.changeset/changelog-github-custom.cjs
.changeset/changelog-github-custom.ts
.changeset/three-donkeys-admire.md

- Infra
Make the release notes / changelogs a little bit prettier :)

added `chore` and `infra` emojis to changesets

---

packages/docs/src/routes/docs/(qwik)/components/styles/index.mdx

docs: add useStyles$ limitation

---

packages/docs/src/routes/demo/cookbook/drag&drop/advanced/index.tsx
packages/docs/src/routes/demo/cookbook/drag&drop/basic/index.tsx
packages/docs/src/routes/docs/cookbook/drag&drop/index.mdx
packages/docs/src/routes/docs/cookbook/index.mdx
packages/docs/src/routes/docs/menu.md

- Docs 
Contains Cookbook examples for drag & drop. Connected to the issue: https://github.com/QwikDev/qwik/issues/6958

feat(docs): cookbook examples for drag and drop

---

packages/qwik/src/cli/migrate-v2/run-migration.ts

- Infra
Reverted updating `moduleResolution` to `bundler` because the root cause for this issue has been resolved via #7159

revert auto updating moduleResolution

---

.github/workflows/ci.yml

- Bug
- Infra
fixed broken ci code

fixed setting pointing v2 alpha to latest

---

.github/workflows/ci.yml

- Bug
- Infra
Hopefully fixes the tagging issue for v2 latest

fix permissions for tagging v2 with latest

---

packages/docs/src/routes/docs/integrations/authjs/index.mdx

While i was migrating my library i was encountering a issue with the .env file  and the docs were not  aligned with auth.js
<!--
The Qwik Team and Community appreciate all PRs. Thank you for your effort! Not all PRs can be merged, but those that meet the following criteria will be prioritized:
a) Core fixes, and
b) Framework functionality achievable only by the core.
If this PR can be done as a 3rd-Party Community Add-On, we encourage that for quicker adoption.
If you believe your functionality is valuable to the entire Qwik Community, discuss it in the Qwik Discord channels for potential inclusion in the core.
First of all, make sure your PR title is descriptive and matches our commit title guidelines.
Also make sure your PR follows all the guidelines in the …

docs: update auth.js section

---

packages/docs/src/components/header/header.tsx
packages/docs/src/components/router-head/router-head.tsx
packages/docs/src/routes/(blog)/blog/(articles)/qwik-next-leap/index.mdx
packages/docs/src/routes/(blog)/blog/components/articles-grid.tsx
packages/docs/src/routes/(blog)/blog/components/featured-article.tsx
packages/docs/src/routes/(blog)/blog/components/featured-post.tsx
packages/docs/src/routes/(blog)/blog/components/mdx/article-block/article-block.tsx
packages/docs/src/routes/(blog)/blog/components/mdx/article-hero/article-hero.tsx
packages/docs/src/routes/(blog)/blog/components/newsletter.tsx
packages/docs/src/routes/(blog)/blog/icons/clock-icon.tsx
packages/docs/src/routes/(blog)/blog/icons/send-icon.tsx
packages/docs/src/routes/(blog)/blog/index.tsx
packages/docs/src/routes/(blog)/data.ts
packages/docs/src/routes/(blog)/layout.tsx

To limit the number of files and the cognitive weight of a big review, I decided to open a PR for the blog skeleton.
We will iterate on ti later.

feat: add Qwik blog

---

.changeset/brown-ravens-behave.md
packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/tests/attributes.spec.tsx

We should track signal changes for var props as well

fix: updating signal-based var props

---

.changeset/pretty-turtles-design.md
packages/docs/tsconfig.json

fix: a bug about get an error once pnpm run build.full

---

packages/docs/src/routes/docs/integrations/authjs/index.mdx

added docs about the auth in the optimizer include array
Docs 
- [x ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ x] I performed a self-review of my own code
- [x ] I added a changeset with `pnpm change`
- [ x] I made corresponding changes to the Qwik docs
- [ x] I added new tests to cover the fix / functionality

docs: add explanation about the auth in the optimizer

---

packages/docs/src/routes/docs/(qwikcity)/guides/capacitor/index.mdx

- Bug
- Infra
- [√] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [√] I performed a self-review of my own code
- [√] I made corresponding changes to the Qwik docs

Mobile Guide edits, typo fixes, and code improvements

---

.changeset/funny-apricots-learn.md
packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/tests/component.spec.tsx

Previously we were incorrectly creating a new virtual node instead of moving the existing one

fix: moving existing virtual node during vnode diffing

---

.changeset/breezy-suits-notice.md
packages/docs/src/routes/docs/integrations/turso/index.mdx

- Docs
Followup pr to #7211 
Adds more keywords and contributor

docs(starters): update turso docs keywords & contributors

---

packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx

docs: fix up typo

---

starters/features/styled-vanilla-extract/package.json

chore(starter): update vanilla-extract import

---

packages/docs/src/routes/docs/(qwik)/components/state/index.mdx

Fixes a typo noticed while reading the docs.

docs: fix "component" typo

---

.changeset/fuzzy-jobs-compare.md
packages/qwik/src/core/tests/use-store.spec.tsx
packages/qwik/src/optimizer/core/src/inlined_fn.rs
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_colon_props.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_colon_props3.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_block_stmt.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_block_stmt2.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_expr_stmt.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_component_with_event_listeners_inside_loop.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_children.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_div.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_getter_generation.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_issue_33443.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_mutable_children.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_wrapping.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_wrapping2.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_destructure_args.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_mark_props_as_var_props_for_inner_cmp.snap
packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_wrap_object_with_fn_signal.snap
packages/qwik/src/optimizer/core/src/test.rs
packages/qwik/src/optimizer/core/src/transform.rs

Mark component props as var props

fix: component props as var props

---

.changeset/few-mugs-accept.md
packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/tests/ref.spec.tsx
packages/qwik/src/server/ssr-container.ts

Allow null or undefined as ref attribute value

fix: null or undefined as ref attribute value

---

packages/docs/src/routes/(blog)/blog/(articles)/resumable-react-how-to-use-react-inside-qwik/index.mdx
starters/features/cypress/package.json
starters/features/partytown/package.json
starters/features/postcss/package.json
starters/features/prisma/package.json
starters/features/react/package.json
starters/features/storybook/package.json
starters/features/styled-vanilla-extract/package.json
starters/features/turso/package.json
starters/features/vitest/package.json

docs: url fix

---

.changeset/itchy-comics-develop.md
packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/tests/component.spec.tsx

Do not copy flags when inserting a new component. The code is not necessary and it leads to errors

fix: different component rendering with the same key

---

packages/docs/src/routes/docs/integrations/tailwind/index.mdx

docs: tailwind docs improvement

---

packages/qwik/src/core/signal/signal.ts
packages/qwik/src/core/signal/store.ts
packages/qwik/src/core/tests/render-api.spec.tsx
packages/qwik/src/testing/rendering.unit-util.tsx

fix: add signal and store effects to the qrl effects for prefetching

---

.github/workflows/ci.yml
flake.lock
package.json
packages/insights/src/entry.netlify-edge.tsx
packages/insights/vite.config.ts
pnpm-lock.yaml

fix(insights): make the service work again

---

scripts/binding-platform.ts

this is breaking the netlify build

fix(ci): download bindings

---

packages/docs/package.json

- Bug
- Infra
Replaced `the && operator,` which caused issues on Windows, with concurrently to allow the script to run seamlessly **on both Windows and Linux-based systems.**

Dev script fixed for windows machine.

---

packages/docs/package.json
pnpm-lock.yaml

remove unused dependency shikiji

fix: remove unused shikiji

---

packages/qwik-city/src/middleware/request-handler/request-event.ts

fix: cookies in send request handler

---

.changeset/swift-flowers-juggle.md

review https://github.com/QwikDev/qwik/pull/7304#discussion_r1951466537

docs: updated changeset as per review 

---

packages/qwik/src/optimizer/src/plugins/plugin.ts

fix(rollup): prevent over-prefetching

---

.changeset/blue-beans-happen.md
packages/qwik-router/src/runtime/src/server-functions.ts
packages/qwik/src/core/api.md
packages/qwik/src/core/internal.ts
packages/qwik/src/core/shared/jsx/jsx-runtime.ts
packages/qwik/src/core/shared/shared-serialization.ts
packages/qwik/src/core/shared/shared-serialization.unit.ts
packages/qwik/src/core/signal/signal-utils.ts
packages/qwik/src/core/signal/signal.ts
packages/qwik/src/core/signal/signal.unit.tsx
packages/qwik/src/core/tests/container.spec.tsx
starters/apps/qwikrouter-test/src/routes/(common)/loaders/prop/index.tsx
starters/e2e/qwikrouter/loaders.e2e.ts

Fix incorrectly unwrapping WrappedSignal value for routeLoader$ data

fix: using routeLoader$ result as component prop

---

packages/qwik/src/core/client/types.ts
packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/client/vnode.ts
packages/qwik/src/core/debug.ts
packages/qwik/src/core/shared/component.public.ts
packages/qwik/src/core/shared/jsx/jsx-runtime.ts
packages/qwik/src/core/shared/shared-serialization.ts
packages/qwik/src/core/shared/types.ts
packages/qwik/src/core/shared/utils/promises.ts
packages/qwik/src/core/shared/utils/serialize-utils.ts
packages/qwik/src/core/use/use-core.ts
packages/qwik/src/core/use/use-resource.ts
packages/qwik/src/core/use/use-task.ts

Remove not used code + VNodes types fix

chore: cleanup and fix types

---

starters/features/auth/package.json

Hey everyone,
not sure what to label this one as (title)
Small update:
The below instructions are incorrect.
As per docs:
- [x ] I performed a self-review of my own code

chore(starters): correct Auth optimizeDeps instructions

---

vitest.workspace.js

Correceted the vscode vitest config path

fix: vscode vitest error

---

packages/qwik/src/optimizer/src/plugins/plugin.ts
packages/qwik/src/optimizer/src/plugins/plugin.unit.ts
packages/qwik/src/optimizer/src/plugins/rollup.ts
packages/qwik/src/optimizer/src/plugins/vite.ts

Follow-up refactor on https://github.com/QwikDev/qwik/pull/7412
- Bug
- Infra

refactor(rollup): normalizeRollupOutputOptionsObject to accept qwikPlugin as an argument

---

packages/docs/src/routes/docs/(qwikcity)/advanced/request-handling/index.mdx

- "hirarchy" should be "hierarchy"
- "browers" should be "browsers"
- Bug
- Infra

fix(docs): fix up minor typos

---

packages/docs/vite.config.mts

docs: fix repl

---

packages/docs/src/components/docsearch/search-box.tsx

docs: fix current release

---

packages/docs/src/components/docsearch/doc-search.css
packages/docs/src/global.css

Docs site styles
Ciao Gio 
Addressing feedback from Wout that was given in Discord on the docs site.
When using the search functionality on Linux this causes a layout shift (as the scroll bars do not exist) after you click the search icon.
After you click this button (open and close) it will cause the page to "jump".
`scrollbar-gutter: stable;` this addresses the layout shift, by maintaining the space that would have been occupied by the scroll-bar although it is not on the screen.
Although it did create a second issue.
While this gutter maintains the space that would have been taken by the scroll bar, the body background colour is bleeding through the backdrop.
I added the radial gradient to make the backdrop darker.
Before
After:
- [ x] My code follows the [developer guidelines of this …

docs: style improve overflow hidden layout shift

---

Cargo.lock
flake.lock
package.json
packages/docs/src/components/footer/footer.tsx
packages/qwik/src/optimizer/src/plugins/vite.ts
pnpm-lock.yaml

some unrelated fixes from my dynamic preload branch

chore: some fixes

---

.github/workflows/deploy-docs.yml

chore(ci): always deploy docs

---

README.md

these run in the qwikcity-e2e app and vercel is failing, probably due to permissions, and the rest is disabled

chore(README): remove unused badges

---

packages/docs/README.md

- fixed some text duplication
- clarified a statement
- fixed a typo

docs: text deduplication

---

packages/qwik-react/package.json

fix(qwik-react): re-release to provide missing .cjs file

---

packages/docs/src/routes/api/qwik/api.json
packages/docs/src/routes/api/qwik/index.mdx
packages/qwik-city/src/buildtime/markdown/mdx.ts
packages/qwik-city/src/buildtime/markdown/mdx.unit.ts
packages/qwik/src/core/render/jsx/slot.public.ts

fix(mdx): better error when missing component

---

packages/docs/src/routes/docs/(qwik)/advanced/custom-build-dir/index.mdx
packages/docs/src/routes/docs/(qwik)/advanced/vite/index.mdx
packages/docs/src/routes/docs/(qwikrouter)/guides/mdx/index.mdx
packages/docs/src/routes/docs/(qwikrouter)/routing/index.mdx
packages/qwik/src/optimizer/src/manifest.ts
packages/qwik/src/optimizer/src/plugins/bundle-graph.ts
packages/qwik/src/optimizer/src/plugins/plugin.ts
packages/qwik/src/testing/README.md
starters/apps/base/vite.config.mts

the main merge was very complex and the CI didn't run any more

fix(v2): fixup after main merge

---

packages/qwik/src/optimizer/src/manifest.ts
packages/qwik/src/optimizer/src/plugins/plugin.ts

Makes sure the internal QRLs _run and _task are part of the core build and ensures the correct chunk when pointing to these QRLs.

fix(core): find core qrl chunk correctly

---

packages/qwik-city/src/buildtime/vite/get-route-imports.ts

- Bug
The previous code only worked with `debug: true` enabled

fix(qwik-city): 1.14.0 SPA nav without debug=true

---

.changeset/cold-moons-follow.md
packages/qwik/src/core/tests/ref.spec.tsx
packages/qwik/src/server/qwik-types.ts
packages/qwik/src/server/ssr-container.ts

Don't trigger signal effects during ssr render

fix: infinity loop while tracking element ref

---

packages/docs/src/components/code-block/code-block.tsx
packages/docs/src/repl/repl-output-panel.tsx
packages/docs/src/repl/repl-output-segments.tsx
packages/docs/src/repl/repl-output-update.ts
packages/docs/src/repl/repl.css
packages/docs/src/repl/repl.tsx
packages/docs/src/repl/types.ts
packages/docs/src/repl/worker/app-ssr-html.ts
packages/docs/src/repl/worker/app-update.ts
packages/qwik/src/core/client/types.ts
packages/qwik/src/core/client/vnode.ts
packages/qwik/src/core/internal.ts
packages/qwik/src/core/qwik.core.api.md
packages/qwik/src/core/shared/shared-serialization.ts
packages/qwik/src/core/shared/types.ts

feat(docs): add vnode tree & state to html tab

---

packages/qwik-city/src/runtime/src/link-component.tsx

refactor(qwik-city): remove unnecessary handling of onQVisible$

---

.changeset/cold-rice-slide.md
packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/tests/component.spec.tsx

If component has empty props we don't need to compare them

fix: proper empty props diffing

---

README.md
package.json
packages/create-qwik/README.md
packages/docs/package.json
packages/docs/src/components/router-head/vendor.tsx
packages/docs/src/routes/(blog)/blog/(articles)/introducing-qwik-starters/index.mdx
packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx
packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx
packages/docs/src/routes/docs/integrations/partytown/index.mdx
packages/docs/vite.config.mts
packages/qwik-auth/README.md
packages/qwik-city/README.md
packages/qwik-labs/README.md
packages/qwik-react/README.md
pnpm-lock.yaml
starters/apps/library/README.md
starters/apps/starter-partytown-test/package.json
starters/apps/starter-partytown-test/src/components/app/app.tsx
starters/apps/starter-partytown-test/src/root.tsx
starters/features/partytown/package.json
starters/features/partytown/src/components/partytown/partytown.tsx

- Infra
updated to latest partytown

feat: update to latest partytown version

---

.changeset/old-guests-stare.md
packages/qwik/src/core/reactive-primitives/impl/signal.unit.tsx
packages/qwik/src/core/reactive-primitives/impl/wrapped-signal-impl.ts
packages/qwik/src/core/shared/scheduler.ts
packages/qwik/src/core/tests/use-computed.spec.tsx

Subscribe to signals on computed signal recomputation

fix: subscribe to signals on computed signal recomputation

---

.changeset/sweet-stars-melt.md
packages/qwik-city/src/runtime/src/spa-init.ts
packages/qwik/src/server/render.ts

Set correct script type for qwik loader

fix: set correct script type for qwik loader

---

.changeset/swift-peaches-wash.md
package.json
packages/qwik-city/package.json
packages/qwik-labs/package.json
packages/qwik-react/package.json
packages/qwik/package.json
pnpm-lock.yaml
starters/apps/base/package.json
starters/apps/library/package.json

chore: update devDependencies and configurations

---

.changeset/smooth-cups-press.md
packages/qwik-router/src/middleware/request-handler/middleware.request-handler.api.md
packages/qwik-router/src/middleware/request-handler/request-event.ts
packages/qwik-router/src/middleware/request-handler/resolve-request-handlers.ts
starters/apps/qwikrouter-test/src/routes/loaders-serialization/index.tsx
starters/e2e/qwikrouter/loaders.e2e.ts

Call nested route loader if needed
Fixes #7703

fix: nested not serialized loaders

---

packages/qwik/src/optimizer/src/manifest.ts

fix: separate if statements in manifest.ts for bundling edge cases

---

packages/docs/src/routes/docs/integrations/i18n/index.mdx

docs: update link to qwik-specefic instructions

---

.devcontainer/Dockerfile
CONTRIBUTING.md

- Docs 
- Infra
As a first-time contributor, I was having some issues getting the project set up locally. I am on Windows and was using Dev Containers. I eventually have switched to my Mac for better support.
- Update Rust image to 1.88.0 (fixes error trying to set up Rust)
- Update references to Node 22 (Node 18 is not supported anymore for Vite 7), and it matches the `.nvmrc`
- Add tips for Windows users to CONTRIBUTING, and how to workaround an error I ran into on my Mac

fix: Update Dev Container and CONTRIBUTING guidelines

---

.changeset/young-groups-open.md
packages/qwik/src/server/preload-impl.ts
packages/qwik/src/server/render.ts

On Discord there was a report of missing nonces for strict-dynamic https://discord.com/channels/842438759945601056/1401931457714454661

fix(ssr): add nonces for strict-dynamic csp

---

.changeset/small-rocks-relate.md
packages/qwik-city/src/runtime/src/sw-register.ts
packages/qwik/src/core/components/prefetch.ts

fix: service-worker.js and qwik-prefetch-service-worker.js caches removal

---

packages/insights/package.json
pnpm-lock.yaml

chore(insights): remove extra deps 🍰

---

.changeset/tasty-turkeys-stand.md
packages/qwik/src/core/client/vnode-diff.ts
packages/qwik/src/core/tests/component.spec.tsx
packages/qwik/src/server/ssr-container.ts

Don't stringify falsy values for dangerousltSetInnerHTML

fix: handle falsy value for dangerouslySetInnerHTML

---

packages/qwik/src/cli/migrate-v2/update-dependencies.ts

update in migration tool concerning ts-morph

---

.github/workflows/ci.yml
pnpm-lock.yaml

- Infra
Adding this check will minimize the pnpm-lock.yaml file conflicts across PR's and greatly reduce the redundant time spent conflict resolution.

Verify pnpm dedupe

---

packages/docs/src/root.tsx

chore: fix lint error

---

.changeset/wise-worlds-hang.md
packages/qwik/package.json
packages/qwik/src/testing/document.ts
patches/domino@2.1.6.patch
pnpm-lock.yaml
pnpm-workspace.yaml
scripts/submodule-server.ts

Remove the unsupported domino fork and reduces the core package size.
- Bug
- Infra

chore(testing): patch domino to remove qwik-dom  💻

---

packages/docs/src/routes/demo/qwikcity/middleware/layout.tsx

docs: fix middleware example 🍿

---

packages/docs/src/routes/demo/cookbook/detect-img-tag-onload/index.tsx
packages/docs/src/routes/docs/cookbook/detect-img-tag-onload/index.mdx
packages/docs/src/routes/docs/cookbook/index.mdx
packages/docs/src/routes/docs/menu.md

docs: add img tag onLoad cookbook 📌

---

e2e/docs-e2e/tests/Docs/deployments-pages-load.spec.ts
packages/docs/src/routes/docs/deployments/github-pages/index.mdx
packages/docs/src/routes/docs/menu.md

docs: add GitHub Pages deployment 🐺

---

packages/docs/src/routes/docs/labs/insights/index.mdx

docs: insights gotcha

---

e2e/docs-e2e/package.json

made docs-e2e a private package
