QwikDev/qwik

- packages/docs/src/routes/tutorial/projection/basic/index.mdx
Should complete the third task from https://github.com/BuilderIO/qwik/issues/2591
Both `<App>` and `<Panel>` will not be re-render on button click.
> docs: update the basic projection tutorial

- packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
Fix a link to "endpoint" link on [Routing](https://qwik.builder.io/docs/routing/) page. [`/endpoint`](https://qwik.builder.io/docs/endpoint/) does not exist, while [`/endpoints`](https://qwik.builder.io/docs/endpoints/) do.
> docs: fix "Endpoints" link on Qwik City -> Routing page

- packages/docs/src/routes/docs/(qwik)/concepts/reactivity/index.mdx
Should complete the first task from https://github.com/BuilderIO/qwik/issues/2591
`Counter` will not download the rendering function and re-runs the OnRender method.
> docs: update reactivity's counter example

- packages/eslint-plugin-qwik/package.json
Allow higher than 8.45 eslint to be used as a peer dependency, solving #5109
- When using the plugin in a project, one might want the latest eslint to be used
- When using the plugin as part of a package, one might want to allow more than one version of eslint
> chore(eslint-plugin-qwik): change eslint to ^8.45

- packages/docs/src/routes/api/qwik-optimizer/api.json
- packages/docs/src/routes/api/qwik-optimizer/index.md
- packages/qwik/src/optimizer/src/api.md
- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/optimizer/src/types.ts
Closes #5069
The Optimizer inlines styles up to 2e4 bytes. This PR makes that value configurable using:
```
qwikVite({
optimizerOptions: {
inlineStylesUpToBytes: 400,
},
}),
```
Feedback needed:
1. is `inlineStylesUpToBytes` a good enough name?
2. is placing it inside `optimizerOptions` the correct scope?
- 1. Inlining 20k bytes of css might be invalid for certain use cases.
> feat(optimizer): add qwikVite configuration option optimizerOptions.inlineStylesUpToBytes

- packages/docs/src/routes/docs/integrations/authjs/index.mdx
Using pathname is a better example as redirect should almost always only be occurring within the site itself and not outside it, so the origin is unneeded.
> docs(authjs): use pathname in protected route example

- starters/apps/base/.vscode/settings.json
Fix emmet behavior for base
```tsx
// Before
br => <br>
// After
br => <br/>
```
Also applies to `input`, `img`, etc.
> starters: Ensure that VSCode emmet uses JSX syntax for self-closing tags

- packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
- packages/qwik-city/buildtime/build-pages-rewrited.unit.ts
- packages/qwik-city/buildtime/build.ts
- packages/qwik-city/buildtime/markdown/markdown-url.unit.ts
- packages/qwik-city/buildtime/routing/resolve-source-file.unit.ts
- packages/qwik-city/buildtime/types.ts
- packages/qwik-city/utils/fs.unit.ts
- packages/qwik-city/utils/test-suite.ts
Now you can rewrite your urls using the same page component, layout and middlewares. 
You can use a prefix to localize your routes or you can simply rewrite urls without prefix.
- 1. **Translate localized urls with prefix**: for localization purposes you may want to translate your routes from `/products` to `/it/prodotti` or to `/fr/produits` and `/products/product-name` to `/it/prodotti/nome-prodotto` or `/fr/produits/nom-du-produit` without having multiple routes files for each locale but reusing the same page component, layouts, middlewares and so on. parameters name will not be changed so if the routePath is `/products/[slug]` you will receive `product-name`, `nome-prodotto` or `nom-du-produit` as the values for the same `slug` path parameter.
- 2. **Rewrite urls without prefix**: …
> feat: Add route rewriting

- packages/qwik/src/optimizer/src/plugins/plugin.ts
I think this might fix what was wrong with the playground.
The Qwik optimizer transform will create new QRL imports and stores them in memory until they are loaded by rollup/vite.
If a subsequent run tries to load a QRL, it won't be in the transform cache.
This change hopefully loads the code into the cache, but I wasn't able to actually test this.
I also wonder how rollup knows that a QRL  has changed when the source file has changed.
> bug(vite): populate rollup cache after transform

- packages/qwik/src/core/api.md
- packages/qwik/src/core/qrl/qrl-class.ts
- packages/qwik/src/core/qrl/qrl.public.ts
- packages/qwik/src/core/qrl/qrl.unit.ts
- packages/qwik/src/core/readme.md
> feat(qrl): add resolved

- packages/qwik-city/runtime/src/route-matcher.unit.ts
> test(qwik-city): add route-matcher case with two rest params

- packages/qwik-city/adapters/shared/vite/post-build.ts
> fix(qwik-city): Correctly SSG routes even with `trailingSlash: false`

- packages/qwik-city/middleware/request-handler/request-event.ts
- packages/qwik-city/runtime/src/api.md
- packages/qwik-city/runtime/src/types.ts
- starters/apps/qwikcity-test/src/routes/(common)/actions/validated/index.tsx
- Wrap the type of rest `DataValidator`s with `FailReturn` to correct the type if we're using action with `validator$`s.
- Update the tests for `routeAction$` with validators.
Before:
```ts
const action1 = useAction1();
if (action1.value) {
if (action1.value.failed) {
action1.value satisfies { failed: true } & (
| TypedDataValidatorError
| ActionFailedObject
);
} else {
action1.value satisfies ActionSuccessObject | DataValidatorError;  // ❌ DataValidatorError shouldn't be here
}
}
```
After:
```ts
if (action1.value) {
if (action1.value.failed) {
action1.value satisfies { failed: true } & (
| TypedDataValidatorError
| DataValidatorError // ✅ DataValidatorError should be here
| ActionFailedObject
);
} else {
action1.value satisfies ActionSuccessObject;
}
}
```
- 2. Another …
> fix(qwik-city): correct validator failed type

- packages/qwik/src/optimizer/src/plugins/image-size-runtime.html
I have found that the `<img>` tags having src attributes of the blob URL causes errors in order to request the `__image_info` to the image size server.
Obviously there is no way to get the image info of the blob URLs from the server side, I simply ignored if the URL starting with `blob:`.
The blob URL is useful for using images dynamically generated in client side.
> fix: Ignore blob URL on getting image info

- packages/qwik-city/buildtime/build-pages-rewrited.unit.ts
- packages/qwik-city/buildtime/build.ts
The home route is not translated if rewriteRoutes config is provided. 
If there is a prefix in a rewriteRoute item the home page as well needs to be translated.
- Actual: I need to translate the homepage to `/it-IT/` but the corresponding route is not created.
- Expected: If i add a rewriteRoute with the prefix `it-IT` i want the `/it-IT/` route to be created.
> fix(qwik-city): Fix rewrite home route

- packages/docs/src/repl/monaco.tsx
- packages/docs/src/repl/worker/app-bundle-client.ts
- packages/docs/src/repl/worker/repl-plugins.ts
- packages/docs/src/routes/examples/apps/visibility/clock/app.tsx
- packages/docs/src/routes/tutorial/hooks/use-visible-task/solution/app.tsx
This PR replaces `.css` with `.css?inline`.
Replaced `.css` with `.css?inline` and tweaked the REPL so that `.css?inline` is resolved.
The default export of css is deprecated since Vite 4 and will be removed in Vite 5.
This will make vite-ecosystem-ci pass after https://github.com/vitejs/vite/pull/14125 is merged (the PR that removes the deprecated css default export).
> docs: use import .css?inline instead of .css

- packages/qwik-auth/src/index.ts
In Authjs, we cannot return a custom error currently, the only way is to redirect to a certain URL with the error being injected in the search params. So when we try setting `location` header, it can be missed since when Authjs gives the error it overwrites that `location` header with the CallbackRouteError URL which is not useful for a product or a website.
In this PR, we try checking if we're overwriting what's in the response or no. So we skip it if the header is already there which gives control over the redirecting ability of qwik instead of it being handled by Authjs.
- 1. Making Redirecting by the `location` property possible in Qwik in the `authorize` function of the Credentials provider of Authjs
> fix(qwik-auth): don't overwrite response headers in qwik auth

- packages/qwik-city/middleware/node/http.ts
Check if the response is already destroyed similar to checking if the response is closed.
PR https://github.com/BuilderIO/qwik/pull/5074 fixed some of the `Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed` errors but sometimes `closed` is undefined and `destroyed` is true.
If checking for `destroyed`, I don't know if that makes checking for `closed` redundant so I kept the `closed` check.
> fix(qwik-city): do not write into a destroyed stream

- packages/qwik-auth/src/index.ts
In PKCE OAuth authentication @auth/core sets two cookies (callback url and pkce code_verifier), but the second one was failing because of the condition added in #5180, which checked to see if the header already existed. This may be fine for most headers, but not for 'set-cookie' headers, in which multiple are allowed.
> fix(qwik-auth): allow multiple set-cookie headers

- packages/docs/src/routes/docs/(qwikcity)/project-structure/index.mdx
- starters/templates/barrel/component/index.tsx.template
- starters/templates/barrel/markdown/index.md.template
- starters/templates/barrel/mdx/index.mdx.template
- starters/templates/barrel/route/index.tsx.template
This PR aims to implement the `barrel` template as suggested in the issue https://github.com/BuilderIO/qwik/issues/4933.
An example of usage is:
```bash
qwik new MyComponent --barrel
```
The output of this example would be the generation of the file `MyComponent/index.tsx` in the `src/components` folder.
> feat(cli): add barrel template to `new` command

- packages/docs/scripts/pages.json
I don't know you're still adding showcase items but, one of my works has been published and it is built with Qwik. If it is possible, I would like to see it in showcase too :)
https://dimension.dev/
Thank you for all your hard work in Qwik, it is godly!
> docs: add `dimension.dev` to showcase

- packages/qwik/src/core/container/serializers.ts
fix #5207, fix #4786
Fixes serialization of an empty set or map
```ts
const setData = useComputed$(
() =>  new Set<string>()
);
```
```ts
const mapData = useComputed$(
() =>  new Map<string, string>()
);
```
> fix(serializers): fix for serialization of an empty set or map

- packages/qwik/src/core/state/context.ts
> refactor: remove extraneous isElement call

- packages/docs/src/components/on-this-page/on-this-page.tsx
When try to use "edit this page" on deprecated feature page, the link was broken
Before
After
> docs: fix edit this page for deprecated features

- starters/adapters/firebase/firebase.json
Related to https://github.com/BuilderIO/qwik/issues/5205
A configuration was added to firebase to include the dist folder, since at the moment of publishing it gave error in the service worker, see issue for more information.
> chore: update firebase starter to contemplate dist folder

- packages/qwik/src/optimizer/src/plugins/vite-server.ts
If I start a Qwik app and use `curl` to make a GET request to the home page, Qwik returns a 404.
```
❯ curl -vv http://localhost:5173
*   Trying 127.0.0.1:5173...
* connect to 127.0.0.1 port 5173 failed: Connection refused
*   Trying [::1]:5173...
* Connected to localhost (::1) port 5173 (#0)
> GET / HTTP/1.1
> Host: localhost:5173
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Origin: *
< cache-control: max-age=5, stale-while-revalidate=604800
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 139
< Date: Thu, 28 Sep 2023 13:53:22 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"> …
```
> fix: should SSR render if accept header includes */*

- packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
- packages/qwik/src/core/use/use-context.ts
- starters/apps/e2e/src/components/context/context.tsx
This allows `useContext()` within the same component that already ran `useContextProvider()`.
This is useful for terseness, code reuse, and it eliminates an element of surprise.
> feat(core): Allow useContext in same elem as provider

- packages/docs/package.json
- packages/docs/src/routes/demo/integration/modular-forms/index.tsx
- packages/docs/src/routes/docs/(qwik)/components/events/index.mdx
- packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
- packages/docs/src/routes/docs/cookbook/mediaController/index.mdx
- packages/docs/src/routes/docs/cookbook/portal/index.mdx
- packages/docs/src/routes/docs/integrations/modular-forms/index.mdx
- pnpm-lock.yaml
I added Valibot to the Modular Forms integration guide and synced the CodeSandbox code in the docs with the demo code.
As the author of both libraries, I prefer to use Valibot with Modular Forms because of the smaller bundle size.
> docs(integrations): add valibot to modular forms guide

- packages/docs/src/routes/docs/(qwikcity)/guides/static-site-generation/index.mdx
This PR aims to correct the documentation for SSG, specifically to suggest running build instead of preview.
This PR updates the SSG documentation to replace the recommendation of using the preview command with the build command for generating static pages. This change is important to highlight because the preview command currently does not generate any HTML static files, whereas the build command does. This ensures developers are fully aware of what each command will yield.
- Clarity: The documentation should accurately guide the developer in generating static pages, which is achieved by using build.
- Avoiding Confusion: Mentioning that preview does not generate HTML static files clarifies its limitations.
> docs: Update SSG documentation to run build instead of preview

- starters/features/localize/src/entry.ssr.tsx
I changed the lang of the container attributes to serverData.locale with fallback en-us
Just added the container attribute for locale
> fix(starter): localize container attribute

- packages/docs/src/routes/docs/(qwik)/components/state/index.mdx
This PR includes a modification to improve the rendering of a list in the code. It adds a 'key' prop to each list item to enhance Qwik's performance and prevent potential issues with list item reordering. The 'key' is generated based on the item's index.
**Motivation:**
- The change enhances Qwik performance when rendering the list.
- It ensures that each list item has a unique identifier, which is important for Qwik's reconciliation process when items are added, removed, or reordered.
**Dependencies:**
None.
- 1. Improved rendering performance of lists.
- 2. Ensured that list items have unique identifiers for efficient Qwik updates.
> docs(state): Add 'key' prop to list items

- packages/docs/src/routes/docs/integrations/authjs/index.mdx
I had an issue when I removed `onRequest` export because my IDE told me that it was unused. Then, I spent a couple of hours trying to figure out how to handle routes that were coming to `/api/auth/callback/[provider]`. This PR adds a note not to remove `onRequest` export.
Add a note to keep `onRequest` export when using `serverAuth$`
> docs: add note about `onRequest` middleware exported from `serverAuth$`

- packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx
docs: Documentation clarity change on reference about no on-mount hook.
Hello Qwik team! I was studying Tasks and Lifecycles and found the following line confusing and hard to understand: `"There is not an specific "on-mount" hook in Qwik because ..."`
I rephrased it to: "`Qwik does not have a specific "on-mount" hook because useTask$() without track() effectively behaves like a mount hook.`" I think it is more succinct and clearer to understand. Hope you see what I mean. 
Thank you for creating such an amazing thing!
-- Not applicable.
> docs: updated phrasing for clarity

- .devcontainer/Dockerfile
- CONTRIBUTING.md
fixes #5218
The dev container Dockerfile was failing, this PR fixes that
The nightly version of Rust in the Dockerfile was causing some of the cargo install to fail, also the Dockerfile was set such that pnpm store and node_modules was getting created in the same directory, hence pnpm install was failing in the Dockerfile. 
The fix was to update the Rust version to LTS and setting the directory for pnpm store in Dockerfile.
Now the dev container vscode plugin as well as manual docker dev env setup will run successfully.
> fix: Pr local dev docker

- packages/qwik/src/core/container/pause.ts
- packages/qwik/src/core/use/use-context.ts
It's unused + undocumented + makes '_' as a contextId not work
Fixes #5257
> refactor(core): remove useContextBoundary

- packages/qwik-city/runtime/src/server-functions.ts
> fix(qwik-city): ensure `server$` has correct `this` on server-side

- packages/docs/src/routes/docs/integrations/i18n/index.mdx
@mhevery I made a new version of deepl-localize to take `message-` prefix into account.
I added the information about a package I wrote to automatically $localize with one of the best translation platforms out there
> docs(localization): auto-translation

- packages/docs/src/routes/tutorial/projection/basic/index.mdx
This PR fixes grammatical issues with Basic Projection Tutorial
> fix: grammatical issue with Basic Projection Tutorial

- packages/docs/src/routes/docs/cookbook/index.mdx
Fix link to theme-management route
> docs: fix broken link

- starters/features/storybook/.storybook/preview.tsx
I added missing CSS import to Storybook integration. In my quick test, this seems to fix Tailwind with it.
Closes #5304.
- 1. If Tailwind is installed, it should work now
The assumption here is that `global.css` is defined always. Likely a better fix would check if it's there in the user source and write it conditionally.
I wasn't sure how to test this but it would definitely be good to test if you know how.
> fix: Add a missing CSS import to Storybook

- packages/docs/src/routes/docs/(qwik)/advanced/qrl/index.mdx
I used a descriptive link as that's good for screen readers.
Closes #5305.
> docs: Add a missing link to qrl docs

- packages/docs/src/routes/community/groups/index.mdx
> docs: add moroccan meetup group

- starters/adapters/firebase/src/entry-firebase.tsx
Comment in firebase entry file was incorrectly referencing `Netlify` instead of `Firebase`
> fix(comment): Updated firebase entry comments to reference Firebase correctly

- packages/docs/src/routes/examples/apps/partial/hackernews-index/app.tsx
- starters/apps/e2e/src/components/watch/watch.tsx
Small fix to types in the examples to not be marked as errors in the Repl editor (see on the live examples [page](https://qwik.builder.io/examples/reactivity/task/)).
| Before | After |
|--------|--------|
| <img width="300" alt="image" src="https://github.com/BuilderIO/qwik/assets/1355455/4845d406-5d89-4e45-a0d5-a338a37adbea"> | <img width="300" alt="image" src="https://github.com/BuilderIO/qwik/assets/1355455/bd0ece6c-a473-4255-aff9-e67443c9475d"> |
> docs: fix component types in examples

- starters/features/pandacss/package.json
I fixed the [issue](https://github.com/chakra-ui/panda/issues/1507) in pandacss, now we just need to bump the Qwik starter package – for any future users 😃
> fix: Bump pandacss version to a Qwik compatible one

- packages/qwik/src/optimizer/src/plugins/vite-server.ts
As per bug #5325 `@builder.io/qwik/build` is a special url that should not ssr render. #5234 introduced new logic on `shouldSsrRender` that causes it to ssr render, which breaks things.
fix #5325 
This PR adds a new conditional to `shouldSsrRender` similar to the existing ones for `vite-ping`, `html-proxy` and `__open-in-editor` for `@builder.io/qwik/build` that fixes the issue.
As per #5325, the library starter template throws an error when interacting with any client side code on v1.2.13
> fix: @builder.io/qwik/build should not SSR render

- packages/qwik-city/adapters/vercel-edge/vite/index.ts
- packages/qwik-labs/src-vite/insights/index.ts
I'm using qwik-nx which makes use of outDir for both client/server outputs. qwikInsights doesn't yet support it so the file ends up in a different location. Also, the manifest is assumed to exist within dist which isn't true with a qwik-nx project.
Adds support for outDir, which qwikVite already supports.
- 1. To customise the outDir, which is useful in projects that are generated by qwik-nx where you can have multiple apps.
**patches/@builder.io+qwik-labs+0.0.1.patch:**
```
diff --git a/node_modules/@builder.io/qwik-labs/vite/insights/index.d.ts b/node_modules/@builder.io/qwik-labs/vite/insights/index.d.ts
index …
```
> feat: add outDir support to qwikInsights

- packages/qwik-city/adapters/vercel-edge/vite/index.ts
- packages/qwik/src/cli/run.ts
When using the interactive CLI mode, the build preview option was in the help commands list but wasn't working, selecting it would return you back to the interactive help.
The `build preview` option wasn't working as the command runner expects the task to be named `build` with preview being an extra argument.
Initially considered adding it as a special case to the `runCommand` switch statement, but this fix is actually better as it will work more consistently if other two word commands are added, and it prevents unexpected behaviour. 
For instance, without the fix, if you run `qwik preview` (unrecognized command) and when the interactive help shows up you select the production build option it would still run a preview build as the args are inherited from your initial commands.
> fix(cli): set args on interactive cli

- packages/qwik-city/adapters/shared/vite/index.ts
- packages/qwik-city/buildtime/vite/plugin.ts
Currently [Qwik in vite-ecosystem-ci](https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6583609019/job/17886921273#step:8:929) is failing in the build step as Vite 5 has removed the `ssr.format` option. This PR fixes it by adding `@ts-ignore` so it works in both Vite 4 and Vite 5.
There are a few more PRs coming to Vite 5, and being able to make Qwik green allows us to anticipate potential breaking changes better.
> chore: ts-ignore vite 5 types issue

- packages/docs/src/components/code-sandbox/index.tsx
- packages/docs/src/components/docsearch/doc-search.tsx
- packages/docs/src/components/docsearch/search-box.tsx
- packages/docs/src/components/router-head/router-head.tsx
- packages/docs/src/components/sidebar/sidebar.tsx
- packages/docs/src/routes/docs/layout.tsx
> chore(docs): remove warnings

- packages/qwik/src/optimizer/src/plugins/vite.ts
> feat(vite): allow disabling dev SSR server in vite

- packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
- packages/qwik-city/middleware/request-handler/resolve-request-handlers.unit.ts
> fix: action redirect accidentally stripped searchparams

- packages/qwik-city/middleware/cloudflare-pages/index.ts
Removes the CF pages `TextEncoderStream` polyfill, not needed anymore since CF implemented the standard API as documented in this blog post https://blog.cloudflare.com/standards-compliant-workers-api/
fix #3269 
fix #3449
I've marked this as a bug since the polyfill had bugs as documented in issue #3269, the native API fixes this as well as other potential problems
Have tested that the native implementation works without any other code changes in both wrangler (miniflare) and a production environment.
> fix: remove cf pages stream polyfill

- packages/qwik/src/cli/utils/templates.ts
in windows path split with \,which makes parseTemplatePath does not work.
qwik new does not work in windows
> fix(cli): parseTemplatePath doesn't work in windows

- packages/docs/src/routes/api/qwik-optimizer/api.json
- packages/docs/src/routes/api/qwik-optimizer/index.md
- packages/qwik-city/buildtime/vite/plugin.ts
- packages/qwik-labs/src-vite/insights/index.ts
- packages/qwik/src/optimizer/src/api.md
- packages/qwik/src/optimizer/src/plugins/vite.ts
Solves my issue with using qwikInsights within an NX repository: https://github.com/BuilderIO/qwik/issues/5337
- Fixed directory creation not being recursive and q-insights.json failing to be created until it's already created
- Added usage of clientOutDir within qwikVite plugin when reading the q-insights.json file
- 1. If you use something like qwik-nx where you have multiple apps, you'll have a different directory structure for where your code goes and currently we just assume everything is directly within /dist
> chore(qwik-insights): use clientOutDir if provided

- packages/qwik/src/optimizer/src/plugins/plugin.ts
> fix(qwik): Incorrect module reference in inlinedQrl

- packages/docs/src/routes/docs/(qwik)/faq/index.mdx
adding the fact that Qwik is an Alex Russell Approved javascript framework
> docs: Alex Russell Approved javascript framework

- CONTINUOUS_BUILD.md
- scripts/qwik-save-artifacts.ts
> chore: improved README.md for build artifacts

- packages/qwik-city/middleware/request-handler/request-event.ts
The `parseBody` qwik-city method on `Request` is cloning the request stream unnecessarily. This PR changes it to use the original `Request` object instead.
qwik-city provides a `parseBody` method on `Request` which checks the headers for certain parseable content-types and returns the data if it can parse it. The `parseBody` is a wrapper around `parseRequest` that caches the returned data (so a second call to `parseBody` won't parse it again)
`parseRequest` currently clones the request object, which is wasteful and raises a warning under some platforms (like Cloudflare) as only this new stream gets read (and only if the content type is parseable)
`parseBody` seems to be the main way the framework reads the request body when needed and is itself safe to call multiple times, so this change …
> fix(qwik-city): parseBody should not clone Request

- packages/qwik-city/package.json
- packages/qwik/package.json
- pnpm-lock.yaml
- scripts/validate-build.ts
As documented in #5038, we cannot start a Qwik app in a Yarn 3 or 4 workspace with PnP because some dependencies are not properly declared in both `qwik` and `qwik-city`.
The changes in this PR are simply to make the dependencies explicit or to make them as an acutal dependency instead of just a dev-dependency.
Close #5038.
<details>
<summary>For reference: here are the places I found in the code requiring each dependency.</summary>
* Qwik
* Vite
* `packages/qwik/src/optimizer/src/plugins/eslint-plugin.ts`
* `packages/qwik/src/optimizer/src/plugins/vite-server.ts`
* `packages/qwik/src/optimizer/src/plugins/vite-utils.ts`
* `packages/qwik/src/optimizer/src/plugins/image-size-server.ts`
* `packages/qwik/src/optimizer/src/plugins/rollup.ts`
* …
> fix: Yarn 3/4 PnP compatibility

- .vscode/launch.json
- packages/qwik/src/optimizer/src/plugins/vite.ts
The log now includes file location and code snippet.
> fix(qwik): Improve logging of vite plugin

- packages/qwik/src/core/state/context.ts
- packages/qwik/src/core/use/use-context.ts
- starters/apps/e2e/src/components/context/context.tsx
- starters/e2e/e2e.context.spec.ts
the parentCtx attribute was optimized to point directly to parents with `$contexts$` defined, but that broke pausing which needs the immediate parent.
Fixes #5356
> fix(core): parent component lookup during pause

- CONTRIBUTING.md
- package.json
- scripts/index.ts
Add package.json `docs.dev` & `docs.preview` scripts to improve the DX for contributors. Having to cd manually in packages/docs had me writing root commands in the wrong folder. This can be a bit frustrating and I think `dev` and `preview` commands are common enough that this should slightly improve the DX for contributors.
For those that are used to the workflow, `cd packages/docs && pnpm start` will keep working.
> refactor(package.json): add docs.dev & docs.preview

- packages/qwik-labs/src-vite/insights/index.ts
Was trying to use the insight fixes from 1.2.17 but was getting an error that the path doesn't yet exist before it writes the q-insights.json to it:
```
qwikInsight(): Fetched latest Qwik Insight data into: dist/apps/myapp/client/q-insights.json
[Error: ENOENT: no such file or directory, open '/Projects/myproject/dist/apps/myapp/client/q-insights.json'] { ... }
```
This makes sure that the same path used later exists, using the same relative path logic
- 1. I'm using qwik-nx with multiple apps in a single repository and the pathing is weird because it has to go back a couple of directories first:
```
qwikVite({
client: {
outDir: '../../dist/apps/myapp/client',
},
ssr: {
outDir: '../../dist/apps/myapp/server',
},
tsconfigFileNames: ['tsconfig.app.json'],
}),
qwikInsights({
outDir: …
```
> fix(insight): use relative path

- packages/docs/src/routes/docs/integrations/astro/index.mdx
> docs(integrations): astro integration docs

- packages/docs/src/routes/docs/integrations/astro/index.mdx
Fix JSON formatting, add an example file path
> docs(astro): Qwik + Astro doc improvements

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/component/component.public.ts
- packages/qwik/src/core/component/component.unit.tsx
…on to PropFnInterface
fix #4946
Added a condition to PropFunctionProps to prevent it from transforming standalone `undefined`, `null`, `never`, into PropFnInterface<unknown[], unknown>.
This mostly fixes ts issues with <input> tags and similar self-closing tags which have a `children: undefined` attribute mismatching the component$ children prop as explained in #4946, but it could also prevent issues with other props that are of the form `prop: null` or `prop: never`.
Let's define a sample object
```tsx
type SampleObject = {
numProp: number | undefined;
strProp: string | null;
boolProp: boolean | never;
nullProp: null;
undefinedProp: undefined;
neverProp: never;
anyProp: any;
unknownProp: unknown;
funcProp: (x: number, y: string) => boolean;
};
```
And apply the PropFunctionProps …
> fix(propfunctionprops): prevent 'undefined', 'null', 'never' conversion to PropFnInterface

- scripts/api.ts
This provides the correct type when importing an svg file as a jsx component.
> fix(qwik-city): better type for svg?jsx imports

- packages/docs/src/routes/docs/integrations/authjs/index.mdx
- packages/docs/vite.config.ts
- packages/insights/vite.config.ts
- starters/apps/base/vite.config.ts
Component Link in client side navigation, returns cached data in dev mode
Screw default seems to be 31536000
Before click Link component
After click Link component
> fix: cache max-age vite.config for dev mode

- packages/qwik/src/cli/new/run-new-command.ts
This fixes the `qwik new` command to:
- preserve `CamelCased` components
- wrong `/route/newRoute` console.success
- mdx route creation provided with `.mdx` created wrong route
Improves/fixes:
1. Enhanced the `toPascal` and `toSlug` functions to better accommodate varying casings. For instance, if we input `new-component` as the name, it will correctly transform it into `NewComponent`. However, if we provide `NewComponent`, the default behavior (or no change) is expected, but currently, it converts it to `Newcomponent`. (Ref: #5282)
2. When generating an MDX route and supplying it with a `.mdx` extension, the resulting route appears as `/route/pagex`. The issue arises as `!(nameAnswer as string).startsWith('/')` is false if we already provide it starting `/`. This fails to differentiate …
> fix(cli): casing for component and mdx route creation

- packages/qwik/src/core/render/dom/render.unit.tsx
- packages/qwik/src/core/render/execute-component.ts
- packages/qwik/src/core/util/unitless_number.ts
This PR adds support for auto-addition of 'px' to CSS properties so that unitless numbers can also be passed to CSS properties under style prop.
Ref: #5419 
With this change, we will automatically add 'px' to unitless numbers provided under the style prop.
```jsx
<h1 style={{ fontSize: 50 }}> Hello World </h1>
```
this resolves to `font-size: 50px`.
I've referred and taken inspiration from React-DOM's implementation, reference attached below:
- https://github.com/facebook/react/blob/432b9f1d9729aaea010730d546bda89b9842eaa1/packages/react-dom-bindings/src/client/CSSPropertyOperations.js#L90
- Referred to [this](https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/shared/isUnitlessNumber.js) for getting all CSS properties that support numbers and don't require units. …
> feat(core): auto px addition to css properties for unitless numbers

- starters/features/bootstrap/src/routes/bootstrap/spinners/index.tsx
Pass the missing props for Spinner component in Bootstrap starter
As the `growing` props is missing in the bootstrap starter template `Spinner` component it is causing the issue in production build while testing after adding the bootstrap.
- The dev build works and the spinners are appering as expected
- But the production build fails without the `growing` props
> fix: Pass the missing props for Spinner component

- packages/docs/src/routes/tutorial/events/synchronous/solution/app.tsx
Updates the tutorial example for synchronous events with using the cleanup function instead of returning a function.
> fix: Wrap function in cleanup function instead of returning it

- packages/docs/src/routes/docs/(qwikcity)/validator/index.mdx
- packages/docs/src/routes/tutorial/events/synchronous/solution/app.tsx
> fix(docs): typo in qwikcity -> Validator docs

- packages/docs/src/routes/community/projects/index.mdx
I have added [`ionic-qwik`](https://github.com/juergenie/ionic-qwik) to the community projects on the docs page. It's a third-party wrapper for `@ionic/core`.
> docs: Add Component library `ionic-qwik` to community projects on docs.

- packages/docs/src/routes/docs/(qwikcity)/guides/static-site-generation/index.mdx
> docs(ssg): fix shell command

- packages/docs/src/routes/api/qwik/index.md
- packages/docs/src/routes/docs/integrations/authjs/index.mdx
Update documentation to add a Credentials example for Auth.js
Add Credentials example in documentation for Auth.js integrations because seems many people have trouble with it.
> docs(auth.js): add credentials example

- packages/docs/src/routes/docs/(qwik)/advanced/eslint/index.mdx
- packages/eslint-plugin-qwik/index.ts
- packages/eslint-plugin-qwik/qwik.unit.ts
- packages/eslint-plugin-qwik/src/noUseVisibleTask.ts
We did a pair programming PR
Co-authored-by: Matteo Pietro Dazzi <ilteoood@users.noreply.github.com>
Co-authored-by: Pasquale De Lucia <pasquale.delucia96@gmail.com>
Co-authored-by: Gloria Giannascoli <gloriag-dev@users.noreply.github.com>
Co-authored-by: pietrodev07 <pietrodev07@users.noreply.github.com>
> feat: add qwik/no-use-visible-task eslint rule

- packages/qwik/src/optimizer/src/plugins/vite.ts
I have few apps where Qwik Insights is not necessary, every build I have this message in my terminal.
Please let's remove this extra log.
> chore(insights): remove unnecessary log

- .vscode/launch.json
- packages/qwik/src/core/container/render.unit.tsx
- packages/qwik/src/core/render/dom/notify-render.ts
- packages/qwik/src/core/render/dom/operations.ts
- packages/qwik/src/core/render/dom/render-dom.ts
- packages/qwik/src/core/render/dom/signals.ts
- packages/qwik/src/core/render/dom/visitor.ts
- packages/qwik/src/core/render/ssr/render-ssr.ts
- packages/qwik/src/core/state/common.ts
- packages/qwik/src/core/util/element.ts
- starters/apps/qwikcity-test/src/components/breadcrumbs/breadcrumbs.tsx
> fix(core): Support JSX in signals

- packages/docs/src/routes/docs/(qwik)/faq/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx
I think this is one of the biggest misconceptions in Qwik and thought could be made clearer. I tried to keep things logical and removed unnecessary references.
> docs(FAQ): - lazy-loading on user interaction & speculative module fetching

- packages/docs/src/routes/docs/(qwik)/faq/index.mdx
Sorry for the typos in my last PR #5488. I re-read the whole thing and made some slight changes for better clarity. Thanks @intellix for pointing out the typos.
> docs(faq): fix typos and improve the wording of some sentences

- packages/docs/public/_redirects
- packages/docs/src/components/on-this-page/on-this-page.tsx
- packages/docs/src/routes/docs/(qwik)/advanced/modules-prefetching/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
- packages/docs/src/routes/docs/integrations/astro/index.mdx
- packages/docs/src/routes/docs/menu.md
Someone on the discord had a hard time finding the documentation for `<Link prefetch>`, so I tried to make the distinction clearer in the docs.
I'm not sure this really helps the algolia algorithm as I couldn't figure out how to test it in development (looks like it's using the current build output even in development). But at least, the docs will make the distinction clearer.
> docs: make the distinction between module-prefetching and <Link prefetch>

- packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
Sorry, my last PR #5485 introduced a small bug in the docs @zanettin.
I checked that everything's working properly again with `pnpm docs.preview` this time.
> fix(docs): mdx interpreting title as component

- packages/qwik-city/buildtime/vite/image-jsx.ts
- packages/qwik-city/buildtime/vite/image-jsx.unit.ts
- packages/qwik-city/buildtime/vite/types.ts
Enable the prefixIds SVGO plugin by default, while still allowing customization. This is a follow up on https://github.com/BuilderIO/qwik/pull/5407. Here's a discussion on why it makes sense when optimizing SVG files for the web: https://github.com/svg/svgo/issues/674.
> fix(qwik-city): prefix ids of SVGs based on their path when loaded as qwik nodes

- packages/qwik-city/middleware/cloudflare-pages/index.ts
As discussed in #5400, the previous patch to remove the CF Pages Stream polyfill was causing trouble for people with older pages apps as Cloudflare does not make new APIs available by default, they instead preserve backwards compatibility by making it opt-in – so it was only working correctly for apps less than a year old.
This patch checks whether the TextEncoderStream class is available before replacing it, preferring the native version if so, but keeps the polyfill for backwards compatibility
> fix: cf pages polyfill only if needed

- packages/docs/src/routes/docs/(qwikcity)/api/index.mdx
- packages/docs/src/routes/docs/integrations/vitest/index.mdx
Added a short description w/ example for the QwikCityMockProvider as it seems to be an undocumented feature (not visible on website)
- 1. As a developer I would like to write tests that use Components with QwikCity. I would like to not need to create my own QC context or mocks
- [omit] Added new tests to cover the fix / functionality
> docs: add QwikCityMockProvider explanation

- packages/qwik/src/optimizer/src/plugins/vite-server.ts
Adding a cypress dev server prefix to the regexp of `shouldSsrRender` function
Cypress tries to load vite assets using a slightly different path than we usually have: it adds  `/__cypress/src` prefix so we end up having paths like `/__cypress/src/@vite/client` . This is not caught by the VITE_PUBLIC_PATH regex part here https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/optimizer/src/plugins/vite-server.ts#L291 because it checks for the /@vite/ part to be at the beginning of the url's pathname.
> fix(qwik): handle cypress dev server path

- packages/docs/src/routes/docs/integrations/i18n/index.mdx
- starters/features/localize/package.json
I changed the file pathes in the docs to match the real ones and also added a prei18n-extract script to make sure the build is running before the extract. I guess a lot of users will miss that one.
> fix(localization-starter): update docs and add script

- packages/qwik-city/package.json
- pnpm-lock.yaml
Updates the vite-imagetools in the qwik-city package. This contains a newer verison of Sharp underneath that resolves an issue of using Qwik with Deno:
- https://github.com/denoland/deno/issues/20612
> chore(qwik-city): bump vite-imagetools ^5 -> ^6

- starters/apps/base/package.json
Fix the following warning after vite was upgraded to v5.x in qwik v.1.3.0:
Adding `type: module` to the `package.json` of the base app starter.
> chore(starters): add type module to package.json 

- packages/qwik/src/core/container/container.ts
- packages/qwik/src/core/container/pause.ts
- packages/qwik/src/core/qrl/qrl.ts
dedupe sync$ functions
ensure sync$ functions are only included once
> fix(qrl.ts): dedupe sync$

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/render/jsx/types/jsx-qwik-events.ts
Not all replacement events were correct. Also, the event.target is the starting target and not the current target, so the old events had incorrect types on the target when bubbling.
> fix: better deprecation notice on qwikevents

- packages/qwik/src/optimizer/src/plugins/eslint-plugin.ts
Closed #5555 #5460
With this PR, priority is given to the configuration that eslint can load from the project.
if it is invalid or does not exist `eslintConfig.parser === null` then we fallback to the one we have always used.
> fix: use existing local .eslintrc configuration

- packages/eslint-plugin-qwik/tests/valid-lexical-scope/valid-component-prop-function.tsx
- packages/qwik/src/core/api.md
- packages/qwik/src/core/qrl/qrl.public.ts
- packages/qwik/src/core/render/jsx/types/jsx-node.ts
> refactor(qwik): add `__qwik_serializable__` brand to types

- packages/eslint-plugin-qwik/index.ts
If it's in 'recommended' I think it should be in 'strict'. We shouldn't make it 'error' though, since visible tasks have valid use cases.
> chore(eslint-plugin-qwik): add 'qwik/no-use-visible-task': 'warn' to strict

- packages/qwik-city/runtime/src/server-functions.unit.ts
- packages/qwik-city/runtime/src/types.ts
- packages/qwik/src/core/api.md
- packages/qwik/src/core/qrl/qrl-class.ts
- packages/qwik/src/core/qrl/qrl.public.ts
> fix: `server$` and AbortSignal types

- .github/workflows/ci.yml
- packages/qwik/src/core/api.md
- packages/qwik/src/core/qrl/qrl-class.ts
- packages/qwik/src/core/qrl/qrl.public.ts
> fix(qwik): restore bivarience hack

- packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx
- packages/eslint-plugin-qwik/src/noUseVisibleTask.ts
Reduced the eslint warning message for noUseVisibleTask as this warning can add up a lot of noise when it comes many times at once (especially codebases that are transitioning to 1.3).
Most other warnings are rather small, so I made it consistent with the other warnings.
I added the corresponding documentation. On their IDE, users can click on the qwik/no-use-visible-task link when hovering the warning. On the console, the warning redirects to where this happens in the IDE.
I believe this would result in less frustration, especially since useVisibleTask$ is sometimes unavoidable.
> docs(usevisibletask$): reduce eslint noUseVisibleTask message + transfer to docs

- packages/qwik-city/runtime/src/qwik-city-component.tsx
- packages/qwik-city/runtime/src/scroll-restoration.ts
Fixes: https://github.com/BuilderIO/qwik/issues/5537
- 1. Restore the scroll position to 0 if the navigation caused by an action (navType=from) and the URL has changed, that means action triggered a redirect.
> fix(qwik-city): Scroll Position doesn't reset to 0 when it was triggered by an Action.

- packages/docs/src/routes/docs/cookbook/portal/index.mdx
This PR updates the portal cookbook section with the problems we've solved in Qwik UI. We hope it'll provide a better experience for those trying to build UI with Qwik.
> docs: update portal cookbook with solved problems

- packages/qwik-city/middleware/bun/index.ts
Fixes this error when using `req.env` with Bun (e.g. for qwik-auth):
```
TypeError: req.env.get is not a function. (In 'req.env.get("AUTH_SECRET")', 'req.env.get' is undefined)
```
> fix: Bun integration env.get is undefined

- starters/features/tailwind/tailwind.config.js
When adding the tailwind integration with `1.3.1`, we get the following error:
```
node:internal/process/promises:289
triggerUncaughtException(err, true /* fromPromise */);
^
[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /Volumes/Primary/Code/eatess/cruncho-landing): [ReferenceError] module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Volumes/Primary/Code/eatess/cruncho-landing/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and …
```
> fix(tailwind starter): switch from cjs to esm to support vite 5

- packages/insights/src/routes/api/v1/[publicApiKey]/post/index.tsx
Nothing related to features or bugs. It is just a coding enhancement. making sure Single Source of Truth.
> refactor(insights): improve consistency 

- starters/apps/basic/src/components/starter/next-steps/next-steps.tsx
Added ALT/Option for clearer instruction for the Mac users
The onboarding is awsome! 
I just added a little help for the Mac users
- 1. When a Mac user sees `ALT`, they might not know that it referes to the Option key.
> docs: improve getting started steps

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/container/pause.ts
- packages/qwik/src/core/container/resume.ts
- packages/qwik/src/core/container/serializers.ts
- packages/qwik/src/core/render/README.md
- packages/qwik/src/core/render/dom/notify-render.ts
- packages/qwik/src/core/render/dom/visitor.ts
- packages/qwik/src/core/render/execute-component.ts
- packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts
- packages/qwik/src/core/render/ssr/render-ssr.ts
- packages/qwik/src/core/render/types.ts
- packages/qwik/src/core/state/common.ts
- packages/qwik/src/core/state/context.ts
- packages/qwik/src/core/state/listeners.ts
- packages/qwik/src/core/state/signal.ts
- packages/qwik/src/core/use/use-context.ts
- packages/qwik/src/core/use/use-resource.ts
- packages/qwik/src/core/util/element.ts
- packages/qwik/src/core/util/types.ts
- starters/apps/e2e/src/components/slot/slot.tsx
- starters/e2e/e2e.slot.spec.ts
Fixes #5506 
By removing the `slotParent` in #5263, the container pause couldn't correctly determine the listener activation graph, so some subscriptions were left out.
This PR ensures that slot contexts are considered for subscriptions by storing the original parent for slotted components.
Also includes some internal type improvements and comments. Please don't squash when merging.
> fix(ssr): slot subscribers

- packages/docs/src/routes/demo/cookbook/nav-link/example/index.tsx
- packages/docs/src/routes/demo/cookbook/nav-link/index.tsx
- packages/docs/src/routes/docs/cookbook/index.mdx
- packages/docs/src/routes/docs/cookbook/nav-link/index.mdx
- packages/docs/src/routes/docs/menu.md
The NavLink component enhances navigation by getting isPending and isActive status to styling your links
When building navigation in Qwik, you may want to know when a link is active or pending navigation. The standard <a> and <Link> components don't provide this.
The NavLink component enhances navigation links by adding:
- **Active Status** - Apply a class when the link matches the current location. 
- **Pending Status** - Apply a class during navigation when linking to the target location.
- 1. navbar
- 2. sidebar
> docs: create NavLink cookbook example

- starters/features/tailwind/.prettierrc.js
When trying to format files using prettier it fails because the qwik project by default has `type: module` defined in the package.json file
Thanks to @dmitry-stepanenko for helping me find the issue
> fix(tailwind): fix prettier config type

- packages/qwik/src/core/render/execute-component.ts
- packages/qwik/src/core/render/execute-component.unit.ts
This PR fixes an extra space being added to the element's class attribute. For example, in my app, I usually have an extra space:
This PR has two commits:
- the first commit adds a lot of tests for `serializeClass` and `serializeClassWithHost` functions;
- the second commit fixes an issue described in the image above.
The first commit will fail test `serializeClassWithHost -> should serialize context with empty $scopeIds$` without a fix from a second commit because expected value is `'bar bar-baz baz-bar'`, but actual value was `' bar bar-baz baz-bar'`. It is fixed with the second commit and the expected values matches actual value.
This is minor and an extra space in the string won't harm anything, but it was still an easy fix.
> fix: remove unnecessary whitespace when handling classes

- packages/qwik/src/cli/add/run-add-interactive.ts
The ability to add `--skipConfirmation=true` to the `add` command in qwik cli.
It's good for other CLI tools that reuses the `qwik add` command to install integrations (like the qwik-ui cli for example)
> feat: add `skipConfirmation` to cli add command

- packages/create-qwik/src/helpers/jokes.json
I ran `npm create qwik` and got greeted with this:
Not sure where y'all are sourcing your jokes from, but you might want to do a review. For now, I'm just removing this one.
Because it's not funny, it's abhorrent.
> fix(cli): Update jokes.json

- packages/docs/src/routes/demo/cookbook/nav-link/index.tsx
- packages/docs/src/routes/docs/cookbook/nav-link/index.mdx
change placement of {...props} to not overwrite class when active with default classes  also, add a section to make Navlink work when you're adding class and activeClass at the same time
> docs: change placement of {...props}  and add section

- packages/docs/src/routes/docs/(qwikcity)/guides/static-site-generation/index.mdx
The current command for building static site is
```
npm run build
```
It should be 
```
npm run build.server
```
Right?
Updated index.md file for the SSG docs
> docs: Update build command in Static Site Generation (SSG) Overview docs

- starters/apps/base/vite.config.ts
Added proper type for the return type of the vite config closure. It helps when customizing the config.
Typescript type improvement for starter for vite config.
> fix(starter): add vite plugin type

- packages/qwik-react/package.json
- packages/qwik-react/src/react/slot.ts
- packages/qwik-react/src/react/types.ts
This PR adds aliases for the directives so that they can be used in `.astro` files.
But, it can also be used in other places where packages might have `client:*` directives that conflict.
> feat(qwik-react): directive aliases for Astro and other package conflicts

- packages/docs/src/routes/docs/deployments/node/index.mdx
Simple change to the docs based on behavior I found in the CLI
Docs currently mention that `createQwikCity` exists in `/src/entry.[server].tsx`, but actual behavior is in `/src/entry.preview.tsx`
I'm not sure about some of the other references in the rest of the page.
> docs: fix entry file name

- packages/qwik-labs/src/qwik-types/public-api.ts
https://github.com/BuilderIO/qwik/issues/5417
support the base in [untypedAppUrl](https://github.com/BuilderIO/qwik/blob/eaf939fda440f5bf75e8bf16d0b4df176001a56f/packages/qwik-labs/src/qwik-types/public-api.ts#L2).
If a base URL is specified in the base field of vite.config, the return value of untypedAppUrl is prefixed with the base URL.
If baseURL is not set, no prefix is given to the path returned.
> feat(labs): Support base prefix in untypedAppUrl

- packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/qwikcity/index.mdx
- starters/apps/basic/package.json
- starters/apps/empty/package.json
- starters/apps/library/package.json
- starters/apps/site-with-visual-cms/package.json
Following the conversation from Discord ([message](https://discord.com/channels/842438759945601056/842438761287254019/1178146319353794622)) it is not entirely clear how one initializes a Qwik City projects, compared to a pure Qwik project.
So, the docs are improved by connecting the two sections - the one for running the CLI tool to bootstrap a project, and a Qwik City section.
Additional changes include additional "tags" to started templates to clearly help distinguish what type of app it's being made, by adding `(Qwik City)` or `(Qwik)` tag next to it.
I'm happy to reconsider any of these changes.
> style(starter templates): updates to starter templates names

- packages/docs/.prettierignore
- starters/apps/base/.prettierignore
Removing dist directoring duplicated value
> chore: Remove duplicated dist directory from .prettierignore

- packages/docs/src/routes/docs/integrations/og-img/index.mdx
- packages/docs/src/routes/docs/menu.md
I added an integration guide for my new package `og-img`.
> I was unfortunately unable to launch the docs website locally on my computer. I therefore recommend checking the page once before the merge.
> docs: add og-img integration guide

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/component/component.public.ts
- packages/qwik/src/core/index.ts
- packages/qwik/src/core/render/dom/render-dom.ts
- packages/qwik/src/core/render/jsx/types/jsx-node.ts
- packages/qwik/src/core/render/jsx/types/jsx-qwik.ts
- packages/qwik/src/core/render/jsx/types/jsx-types.unit.tsx
- packages/qwik/src/jsx-runtime/api.md
- scripts/api.ts
FunctionComponent now handles QRLs, PropsOf is more robust, and the JSX namespace doesn't duplicate all the types any more.
> chore: improve FunctionComponent

- packages/qwik/src/core/container/pause.ts
Prevents XSS by escaping all scripts in `qwik/json` before inserting into DOM.
Previous implementation of "escapeText" function was case sensitive so it was possible to inject XSS via URL when using different cases for script tag (e.g. "scRipt"). The new implementation takes case of case sensitiveness so it prevents XSS injection.
> fix: improve escapeText replace

- packages/qwik/src/optimizer/core/src/props_destructuring.rs
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap
it was converting `{foo: bar = 123, ...rest}` into `rest = omit(props, ['bar'])` instead of `rest = omit(props, ['foo'])`
> fix(optimizer): use correct prop in omit

- packages/docs/src/routes/docs/cookbook/nav-link/index.mdx
Fix typos for TailwinCss --> TailwindCss and like--> link in end section of docs
> docs: fix typos for nav link cookbook 

- .vscode/launch.json
- packages/qwik/src/core/container/resume.ts
- packages/qwik/src/qwikloader.ts
- packages/qwik/src/server/render.ts
It's a follow up PR for https://github.com/BuilderIO/qwik/pull/5689 to prevent XSS injection on server side as well.
Improves `escapeText` and `unescapeText` replace to prevent `XSS`.
> fix: improve escapeText and unescapeText replace to prevent XSS

- package.json
- packages/docs/package.json
- packages/insights/package.json
- packages/qwik-city/package.json
- packages/qwik-labs/package.json
- pnpm-lock.yaml
we don't need a specific version, and in the next major release we'll remove it
> chore: allow any undici version

- packages/docs/scripts/pages.json
The PR adds Blueagle's Profolio & Blog to the sites showcase in the documentation website.
The PR adds Blueagle's Profolio & Blog to the sites showcase in the documentation website.
No specific use case. Only documentation update.
> docs(showcase): add Blueagle's Profolio & Blog

- packages/docs/src/routes/docs/(qwikcity)/guides/react-cheat-sheet/index.mdx
Not a huge change, but I noticed the Props example uses useStore and changes a signal value before explaining what useStore is and how signal values are changed.
I think that swapping the order makes the flow more natural and easier to understand.
> docs: move props example after local state and useStore explanation

- packages/docs/src/routes/docs/integrations/storybook/index.mdx
Added a few examples to the Storybook documentation. Included an example of using <QwikCityMockProvider> as this is required when using QwikCity.
re #5684
Requested in #5684 to make it a little more clear that when using QwikCity in Storybook the \<QwikCityMockProvider\> must be used. Also included a simple component story for clarity.
> docs: add Storybook Examples

- packages/docs/src/components/builder-content/index.tsx
- packages/docs/src/repl/monaco.tsx
- packages/docs/src/repl/repl-version.ts
- packages/docs/src/routes/api/qwik-city/api.json
- packages/docs/src/routes/api/qwik-city/index.md
- packages/docs/src/routes/api/qwik-testing/api.json
- packages/docs/src/routes/api/qwik-testing/index.md
- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/docs/src/routes/demo/cookbook/portal/portal-provider.tsx
- packages/docs/src/routes/demo/resumability/index.tsx
- packages/docs/src/routes/examples/[...id]/examples.css
- packages/docs/src/routes/playground/playground.css
- packages/qwik-city/runtime/src/api.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/container/render.unit.tsx
- packages/qwik/src/core/render/dom/render.public.ts
- packages/qwik/src/core/render/jsx/factory.ts
- packages/qwik/src/core/render/jsx/types/jsx-qwik.ts
- packages/qwik/src/core/render/jsx/types/jsx-types.unit.tsx
- packages/qwik/src/core/render/ssr/render-ssr.ts
- packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
- packages/qwik/src/core/use/use-resource.ts
- packages/qwik/src/testing/api.md
- packages/qwik/src/testing/library.ts
- starters/apps/e2e/src/components/render/render.tsx
- correct JSX.Element so it accepts JSXOutput
- also correct render functions
- bonus repl fixes on mobile
slightly breaking, so should probably be released as at least minor.
> fix(types): JSX.Element is JSXOutput

- packages/docs/src/routes/docs/cookbook/algolia-search/index.mdx
- packages/docs/src/routes/docs/cookbook/glob-import/index.mdx
- packages/docs/src/routes/docs/cookbook/mediaController/index.mdx
- packages/docs/src/routes/docs/cookbook/portals/index.mdx
- packages/docs/src/routes/docs/cookbook/re-exporting-loaders/index.mdx
- packages/docs/src/routes/docs/cookbook/sync-events/index.mdx
- packages/docs/src/routes/docs/integrations/react/index.mdx
While I was wandering through the docs, I have noticed that some documentation cookbooks examples have broken urls.
https://github.com/BuilderIO/qwik/assets/12732872/d4eedcbf-ac13-4269-a7d7-981cbcfa3e15
Some broken urls for documentations examples
No broken urls for documentations examples
> docs: fixed CodeSandbox/CodeFile src paths to match github files

- packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
- packages/docs/src/routes/docs/(qwik)/components/rendering/index.mdx
- packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/advanced/complex-forms/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/layout/index.mdx
- packages/docs/src/routes/docs/cookbook/index.mdx
- packages/docs/src/routes/docs/cookbook/node-docker-deploy/index.mdx
- packages/docs/src/routes/docs/cookbook/portals/index.mdx
- packages/docs/src/routes/docs/cookbook/re-exporting-loaders/index.mdx
- packages/docs/src/routes/docs/cookbook/theme-management/index.mdx
- packages/docs/src/routes/docs/deployments/static/index.mdx
- packages/docs/src/routes/docs/integrations/bootstrap/index.mdx
- packages/docs/src/routes/docs/integrations/builderio/index.mdx
- packages/docs/src/routes/docs/integrations/icons/index.mdx
- packages/docs/src/routes/docs/integrations/image-optimization/index.mdx
- packages/docs/src/routes/docs/integrations/og-img/index.mdx
- packages/docs/src/routes/docs/integrations/prisma/index.mdx
- packages/docs/src/routes/docs/integrations/supabase/index.mdx
As described with the commit message, with this pull request I'm requesting to add some misspelled words I have found while I was reading the documentation.
> docs: Fixed various typos (or misspelled words) in documentation files

- packages/docs/src/routes/docs/(qwikcity)/project-structure/index.mdx
Update the typo by removing "can" from the text.
There's a typo in the content of document titled "Project Structure".\
Removed "can" from the content to make it correct sentence.
> fix(docs): grammar in "Project Structure" page

- packages/qwik-auth/src/index.ts
https://github.com/BuilderIO/qwik/pull/5194 introduced functionality to set multiple cookies.
With fetch setting multiple cookies via the set-cookie key is not supported though.
The testing was limited to the PCKE cookie, which passed as that cookie is last in the list coming from auth.js.
Other cookies like next-auth.callback-url would come earlier and would have been discarded by the later cookie.
I am not sure, if we should handle pre-existing values for set-cookies?
Instead of setting cookies directly, instead collect them and then create a semicolon seperated string.
> fix: multiple cookies in qwik-auth

- packages/docs/package.json
- pnpm-lock.yaml
With #5705 a lot of dependencies have been updated, including `rehype-pretty-code` in `packages/docs` from version `^0.10.1` to `^0.12.3`.
This introduces a bug in the highlight of many code snippets in the docs, for example:
Context page: https://qwik.builder.io/docs/components/context/
Rendering page: https://qwik.builder.io/docs/components/rendering/
The most updated version without this issue seems to be `0.11.0` (tested on local). If we do not need any particular feature in version 0.12 we should probably go back there.
> docs: fix code highlight by downgrading rehype-pretty-code

- packages/docs/src/repl/repl.tsx
- packages/docs/src/repl/worker/repl-server.ts
Messages in the playground weren't validating the origin of the message. This can be dangerous in some contexts.
> fix(docs): Validate origin on postmessage

- packages/qwik/src/optimizer/src/plugins/vite.ts
This PR adds the ability to filter out files from the optimizer with a predicate function. It can be useful if you're using multiple frameworks alongside Qwik, and gives the ability to customize what files get passed into `qwikVite`.
Without this PR, other JSX frameworks do not work with Qwik, this is something we thought previously was not necessary, but it is 😅 
I am currently using the build artifact in the Astro integration so that `@astrojs/react` can work alongside Qwik.
> feat(vite): new file filter option

- packages/qwik/src/core/render/dom/notify-render.ts
- packages/qwik/src/core/render/execute-component.ts
- starters/apps/e2e/src/components/computed/computed.tsx
- starters/e2e/e2e.computed.spec.ts
Fixes #5738.
The problem is that dirty tasks never run again, whereas on the client they are run on the next tick.
This PR makes executeComponent rerun tasks during SSR until they are no longer dirty.
> fix(ssr): dirty tasks

- packages/docs/.gitignore
- packages/docs/check-qwik-build.ts
- packages/docs/package.json
- packages/docs/src/repl/bundled.tsx
- packages/docs/src/repl/editor.tsx
- packages/docs/src/repl/monaco.tsx
- packages/docs/src/repl/qwikFiles.tsx
- packages/docs/src/repl/repl-detail-panel.tsx
- packages/docs/src/repl/repl-options.tsx
- packages/docs/src/repl/repl-share-url.ts
- packages/docs/src/repl/repl-version.ts
- packages/docs/src/repl/repl.tsx
- packages/docs/src/repl/types.ts
- packages/docs/src/repl/worker/repl-constants.ts
- packages/docs/src/repl/worker/repl-dependencies.ts
- packages/docs/src/repl/worker/repl-plugins.ts
- packages/docs/vite.config.ts
This serves the local qwik build to the REPL so that it enables easy testing of new features and eventually it enables running the docs offline (for airplane developmen), although that still needs extra work for rollup, terser and monaco.
It also includes prebuild checks to make `docs.dev` work on a fresh checkout.
> feat(repl): use bundled qwik and prettier versions

- packages/qwik/src/prefetch-service-worker/direct-fetch.ts
- packages/qwik/src/prefetch-service-worker/index.unit.tsx
- packages/qwik/src/prefetch-service-worker/state.ts
This also works around the minifier renaming properties in the class but not the ones that are initializers.
> fix(sw-prefetch): clone on reuse

- starters/apps/basic/src/routes/styles.css
Adjust padding over the hero section.  Fix #5786
I adjusted the boilerplate overlay to ensure it fits seamlessly with the hero section.
> fix(starter): adjust padding for 768px devices

- packages/qwik-city/buildtime/vite/plugin.ts
- packages/qwik/src/optimizer/src/plugins/rollup.ts
This reverts commit d2380feb80a221c0376d1754838cc24376baab06 and fixes the relative qwik-city imports by co-locating entry and chunks.
The previous fix broke deploys because the build contained the build path.
Fixes #5774
> fix(qwik-city): fix import ./@qwik-city files in prod

- packages/docs/src/routes/plugin@builder.io-redirect.ts
This redirect has been placed here because of security vulnerabilities on the builder.io domain.
- Because of Qwik REPL is is possible to write arbitrary code that runs on a builder.io subdomain with qwik.builder.io/repl
- This opens vulnerabilities around XSS, cookie jacking, because builder.io uses cross-subdomain cookies
- Move the qwik.builder.io/repl of the qwik.builder.io domain to the qwik.dev domain.
- Place a 308 redirect here to ensure that all requests to the builder.io domain are redirected to the qwik.dev domain.
> docs: Redirect all requests from builder.io to the qwik.dev domain.

- packages/docs/src/routes/api/qwik-city/api.json
- packages/docs/src/routes/api/qwik-city/index.md
- packages/docs/src/routes/docs/(qwikcity)/api/index.mdx
- packages/qwik-city/runtime/src/api.md
- packages/qwik-city/runtime/src/qwik-city-component.tsx
While trying to run a Cypress e2e test based on a storybook, I've challenged an issue due to the thrown error of the `goto` function not implemented in `QwikCityMockProvider`.
In order to tackle, I've moved the error to a warning. On top of that I've added an optional prop that allows users to pass a custom goto function.
> feat(QwikCityMockProvider): add optional goto prop

- packages/qwik/src/core/container/container.ts
During SSR, reactivity on refs will cause dirty tasks, and besides, refs are used to interact with the DOM, which is not possible with the MockElements.
Example script that has dirty tasks without this fix:
```tsx
import { component$, useTask$, useSignal, useVisibleTask$ } from '@builder.io/qwik';
export default component$(() => {
const ref = useSignal<Element>()
useTask$(({track}) => {
console.log(`task runs, ref is ${track(ref) ? '':'un'}defined`)
})
useVisibleTask$(({track}) => {
console.log(`visibleTask runs, ref is ${track(ref) ? '':'un'}defined`)
})
return <p ref={ref}>Hello Qwik</p>;
});
```
[playground](https://qwik.dev/playground/#f=Q0o0JoaW2BKNDrySBLMg9TCYiVzQUZy0IOEELL6AwYSo7l1zUkEZxU5DkwuoBl5ba1RD695auH6ICbDqPqEEqE6hqDSvWAdsJrB8UakGa9EAcjUV7BXU1RWsFNRL89Rrgc4Cll0pCZpAU2pBBHoZTt …
> fix(core): assign refs without reactivity during SSR

- packages/docs/src/routes/docs/integrations/vitest/index.mdx
Very minor typo fixes in the docs.
N/A
> fix(docs): correct minor typos

- .github/workflows/ci.yml
hopefully this makes the tests more stable
> chore: ci e2e: single worker and longer timeout

- packages/qwik-city/runtime/src/link-component.tsx
- packages/qwik-city/runtime/src/use-endpoint.ts
Fixes: https://github.com/BuilderIO/qwik/issues/5474
This PR fixes the bug by adding a flag to the `loadClientData` function, and update `handlePrefetch` in link-component to use the flag to indicate that the call is intended to just prefetch not actual navigation, So in-case the route does occur unexpected error or doesn't exist it shouldn't redirect to the page.
> fix(link): Prefetch redirects to error pages. Fixes #5474

- packages/docs/src/routes/tutorial/reactivity/resource/solution/app.tsx
Restored dynamic input reactivity in the `useResource$()` tutorial by updating the `onInput$` handler to properly reflect changes. Previously, updates to the `github.org` input did not refresh repository data due to static value assignment, preventing the expected reactive behavior.
- [] I have performed a self-review of my own code
> fix: Fix input reactivity in `useResource$()` tutorial

- packages/docs/src/routes/docs/integrations/astro/index.mdx
The Astro page included some broken Markdown that rendered parts of the markdown source as a code block. This PR fixes that.
- [N/A] I have made corresponding changes to the documentation
> docs: Fix broken Markdown on Astro Docs page

- packages/docs/src/routes/docs/(qwikcity)/advanced/speculative-module-fetching/index.mdx
I tested in a fresh qwik app and speculative module fetching appears to be working in preview.
To verify, just install a qwik starter project with the flower and todos. On the home page click on the + button of the counter on a fresh page and you'll see that the signal code is being retrieved from the service worker.
> docs(speculative-module-fetching): remove that it doesn't work in preview because it does

- packages/qwik-city/buildtime/vite/dev-server.ts
> fix(qwik-city): don't cache errors

- packages/qwik/src/cli/utils/utils.ts
create-qwik
This PR is fixing a minor issue
I created a new project using `npx create-qwik@latest` and tried to run `npm run dev`. Although I had Node.js v16 and the `package.json` in the generated project specified that the appropriate version is `>=15.0.0`, I encountered an error because `sharp` does not support this version.
> fix(create-qwik): update engine version in package.json for generated projects

- packages/docs/src/routes/api/qwik-server/api.json
- packages/docs/src/routes/api/qwik-server/index.md
- packages/qwik/package.json
- packages/qwik/src/core/container/pause.ts
- packages/qwik/src/core/container/store.unit.tsx
- packages/qwik/src/core/render/dom/visitor.ts
- packages/qwik/src/qwikloader.ts
- packages/qwik/src/server/api.md
- packages/qwik/src/server/render.ts
- packages/qwik/src/server/scripts.ts
- packages/qwik/src/server/types.ts
- scripts/submodule-qwikloader.ts
- starters/apps/e2e/src/entry.ssr.tsx
- only run once in the browser
- qEvents is no longer used
- qwikloader.optimize.js is the same as regular, remove
- some tricks to allow smaller code after minify
- remove @vite-ignore comment
> fix(qwik-loader): run only once + better minify

- packages/qwik-labs/src-vite/qwik-types/generator.ts
Fix the problem when using Dynamic route segments, qwik-types cannot generate correct routes.gen.d.ts
Test Passed:
- 1. part.startsWith('[') will not intersect with part.startsWith('...')
> fix(routing): generate correct routes.gen.d.ts for dynamic segments

- packages/eslint-plugin-qwik/src/validLexicalScope.ts
Allow the `JSXNode` to serialize.
Even though there is the `JSXNodeSerializer`, the eslint has been warning when you use the `JSXNode` across the `$` sign.
This PR solves this issue.
Fixes #5864
> fix(eslint): Allow JSXNode to serialize

- packages/docs/src/routes/docs/deployments/deno/index.mdx
- packages/qwik-city/middleware/deno/api.md
- packages/qwik-city/middleware/deno/index.ts
- starters/adapters/deno/README.md
- starters/adapters/deno/package.json
- starters/adapters/deno/src/entry.deno.ts
This pull request updates the codebase to use the recommended [`Deno.serve`](https://deno.land/api?s=Deno.serve) API for creating HTTP servers, replacing the deprecated [`serve`](https://deno.land/std@0.217.0/http/mod.ts?s=serve) function from the Deno standard library.
```ts
// Before:
import { serve } from "https://deno.land/std@0.192.0/http/server.ts";
serve(/* ... */);
// After:
Deno.serve(/* ... */);
```
You can find the `Deno.serve` signature [here](https://github.com/denoland/deno/blob/v1.41.0/cli/tsc/dts/lib.deno.ns.d.ts#L6496-L6499).
I also replace the docs URL for Deno servers. The former redirects to the latter.
```diff
- https://deno.com/manual/examples/http_server
+ https://docs.deno.com/runtime/tutorials/http_server
```
The [latest `serve` …
> fix(deno): replace deprecated Deno server module with `Deno.serve`

- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
Bump GH action versions to remove this warn
> chore: bump versions of GH actions

- .devcontainer/Dockerfile
fix #5891
Docker build was failing from one of `wasm-pack`'s dependencies requiring a newer version of `rustc` than was provided by the container. I passed the `--locked` flag to the `cargo install` command so that the rust packages use their `cargo.lock` files if available to ensure more reproducible builds.
Note: Another possible fix for #5891 is to upgrade the container's rust toolchain version to >= v1.74 in the docker container. I chose not to use this solution since I'm not familiar with the rust toolchain and I could not determine the possible side effects of upgrading the toolchain version which could possibly contain breaking changes.
Docker is convenient for creating reproducible builds and streamlining the contribution process. This fix allows Docker to be used again and in a …
> fix(docker): fix Docker build failing

- packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
Adds a missing import in [part 5 of the  Getting started tutorial](https://qwik.dev/docs/getting-started/#5-tasks-and-invoking-server-code).
> docs: Add missing server$ import in Getting started example

- packages/docs/src/components/sidebar/sidebar.css
- packages/docs/src/components/sidebar/sidebar.tsx
switched the updated indicator to be on the right of the a tag text, as on desktop it is not visible due to the small sidebar width
vs
> chore(docs): change indicator side from left to the right

- packages/docs/vite.config.ts
> chore: Update vite.config.ts to externalize `async_hooks`

- packages/docs/src/components/sidebar/sidebar.css
sorry in my last pr i removed margin left by mistake when trying to fix my original mistake
this caused the updated indicator to be super to the left of the link text in desktop, and in mobile its almost not visible in some screens.
apologise for the wasteful prs (i didnt know if i can update my previous pr any further as it got merged)
> chore(docs): updated indicator in docs not appearing in mobile sidebar

- packages/qwik/src/core/error/error.ts
Very cute little hack that uses the line number to point to the error code.
I moved the codes below the strings so the starting line number stays fixed.
> feat(core): direct url to errors in prod

- packages/qwik/src/core/use/use-task.ts
- packages/qwik/src/core/v2/use-store.unit.tsx
- packages/qwik/src/testing/element-fixture.ts
Adds utility class for triggering fake timers and test case for #5597 for v2.
> test(use-store): add set interval test for 5597 issue

- packages/docs/src/repl/bundled.tsx
- packages/docs/src/repl/monaco.tsx
- packages/docs/src/repl/repl-detail-panel.tsx
- packages/docs/src/repl/repl-version.ts
- packages/docs/src/repl/repl.tsx
- packages/qwik/src/core/component/component.unit.tsx
client-side code was being run on the server, and cloudflare doesn't support blobUrls, nor should it. This change reduces the server js by 3MB as well.
> fix: docs site deploy

- packages/qwik-city/middleware/cloudflare-pages/index.ts
This reverts commit 1995753ff587d9938dcc08515ca64693a805d14f.
Somehow, this causes cloudflare not to honor Cache-Control headers. The answers do not have the cache-hit header.
Fixes #5947
> fix(cloudflare): cache-control ignored by cf (#3679)"

- packages/qwik-city/runtime/src/spa-shim.ts
spa-shim.ts does not respect q:base attribute when importing script
In a subpath, for example http://localhost:3000/blog/
It will import the script from http://localhost:3000/blog/eg.js
Not from http://localhost:3000/build/eg.js
Just a mistype maybe
> fix(qwik-city): spa-shim.ts import scripts from wrong path

- packages/docs/src/routes/demo/cookbook/debouncer/index.tsx
- packages/docs/src/routes/docs/cookbook/debouncer/index.mdx
- packages/docs/src/routes/docs/cookbook/index.mdx
- packages/docs/src/routes/docs/menu.md
- [√] Docs / tests / types / typos
Add denouncer recipe to the cookbook
Writing a debouncer in Qwik does not follow the standard patterns used in other frameworks and results in unnecessary developer effort to figure it out.
- [√] My code follows the [developer guidelines of this project](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md)
- [√] I have performed a self-review of my own code
- [√] I have made corresponding changes to the documentation
Special thanks to @KenAKAFrosty.
> docs: Add debouncer recipe to cookbook

- packages/docs/src/routes/(ecosystem)/showcase/index.tsx
> docs: run linter 🧽

- packages/insights/src/stats/edges.ts
> chore: fix typo in edges.ts

- packages/qwik/src/prefetch-service-worker/direct-fetch.ts
- packages/qwik/src/prefetch-service-worker/process-message.ts
- packages/qwik/src/prefetch-service-worker/state.ts
This fix will solve this edge case error. 
With:
- empty browser cache
- no active service worker
sometimes the variable `$cache$` is null when that code is evaluated.
This code could be the problem https://github.com/BuilderIO/qwik/blob/157f7b01df22448638f7cc55546a051aa4eea5f0/packages/qwik/src/prefetch-service-worker/setup.ts#L42
> fix: prevent SW exception

- packages/qwik/src/core/v2/render-api.unit.tsx
- packages/qwik/src/core/v2/ssr/ssr-container.ts
- packages/qwik/src/core/v2/ssr/ssr-render2.ts
- packages/qwik/src/server/types.ts
- packages/qwik/src/server/utils.ts
This PR adds render and snapshot timing
> feat(v2): add render and snapshot timing

- packages/qwik/src/core/v2/render-api.unit.tsx
- packages/qwik/src/core/v2/ssr/ssr-container.ts
- packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts
- packages/qwik/src/core/v2/ssr/ssr-render2.ts
- packages/qwik/src/core/v2/ssr/types.ts
This PR adds tests and impl for locale, containerTagName, containerAttributes, serverData, manifest hash attribute and version option.
> feat(v2): add more renderToString2 tests

- packages/qwik/src/core/container/container.ts
- packages/qwik/src/core/v2/render-api.unit.tsx
- packages/qwik/src/core/v2/shared/shared-serialization.ts
- packages/qwik/src/core/v2/ssr/ssr-container.ts
- packages/qwik/src/core/v2/ssr/ssr-render2.ts
- packages/qwik/src/core/v2/ssr/types.ts
- packages/qwik/src/server/prefetch-implementation.ts
- packages/qwik/src/server/prefetch-strategy.ts
- packages/qwik/src/server/render.ts
This PR adds prefetch strategy option handling and partial snapshot result
> feat(v2): prefetch strategy option and partial snapshot result

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/render/dom/visitor.ts
- packages/qwik/src/core/render/jsx/jsx-runtime.ts
- packages/qwik/src/core/render/ssr/render-ssr.ts
- packages/qwik/src/optimizer/core/src/is_immutable.rs
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_class_name.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_cmp.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_complext_children.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_derived_signals_div.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_getter_generation.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_immutable_analysis.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_input_bind.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_jsx_listeners.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_spread_jsx.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_strip_client_code.snap
- packages/qwik/src/optimizer/core/src/test.rs
- packages/qwik/src/optimizer/core/src/transform.rs
- packages/qwik/src/optimizer/core/src/words.rs
- starters/e2e/e2e.render.spec.ts
- be agnostic towards className
- fix `{...props}` overriding
- re-fixes #3622
- properly fixes #3481
- Fixes #5292
- makes @PatrickJS happy about the className
It works by, when a component has spread props (`dynamic_component` is `true`), putting all props in the mutable props and tagging them as immutable by also setting their key in the immutable props to _IMMUTABLE.
Then, in SSR and DOM, the visitors are changed to give precedence to immutable props when both mutable and immutable are defined.
> fix(core): spread props, className

- starters/features/pandacss/package.json
Updating to the latest released @panda/dev package.
[PandaCSS Change log](https://github.com/chakra-ui/panda/blob/main/CHANGELOG.md#0360---2024-03-19) 👈 
> chore(starters): update 🐼 PandaCSS integration starter dev dependency

- README.md
- Remove Vercel Server badge
- Add Vercel Serverless badge
- Add Vercel Edge budge
As mentioned Overview.
> docs: Fix README badges

- packages/docs/src/routes/tutorial/events/preventdefault/index.mdx
In tutorial : adding missing comma to improve reading
Adding a comma to make the sentence more readable.
Before : For some events browsers have default behavior.
After : For some events, browsers have default behavior.
> docs: improve readability

- starters/adapters/node-server/src/entry.node-server.tsx
The current Node server starts silently without any indication of what's going on. Adding a log with the PORT information makes it easier to test locally and doesn't really hurt prod.
Adds a callback after the server `.listen()` function runs to log where the app is running.
> feat: Log PORT info at startup in entry.node-server.tsx

- starters/adapters/node-server/README.md
The current docs report the default Node server running at port 8080, when in fact, it's 3004. Alternatively, we could change 3004 to 8080.
> docs: Update README.md to use correct default PORT

- packages/docs/src/repl/worker/repl-plugins.ts
- packages/qwik-city/buildtime/vite/dev-server.ts
- packages/qwik/src/optimizer/src/plugins/vite-server.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
Less and Styles did not work with development server, because these extensions were missing.
- Less and Stylus should work in development.
> fix: less and stylus support in development

- packages/docs/src/routes/docs/(qwikcity)/pages/index.mdx
- Added instructions for inserting scripts into the <head> section.
- Included guidelines for adding Google Structured Data, beneficial for SEO.
I and a few other people I know have had difficulty adding script and schema to the head of the page. So I created this pull request to add documentation, helping to save time for future developers.
> docs: add Google Structured Data example

- packages/docs/src/routes/docs/(qwikcity)/middleware/index.mdx
The example code for the send() function in the middleware documentation was wrong.
- Documentation should be correct
> docs: improve example in middleware doc

- packages/qwik/src/core/v2/component.unit.tsx
- packages/qwik/src/core/v2/use-signal.unit.tsx
- packages/qwik/src/core/v2/vdom-diff.unit-util.ts
This adds new vitest matcher `toMatchDOM`.
Example usage:
for vDOM:
```tsx
<Component>
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
<circle cx="10" cy="10" r="50" />
</svg>
</Component>
```
we can now also compare the HTML:
```tsx
await expect(container.document.body).toMatchDOM(`
<svg viewbox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" q:key="0">
<circle cx="10" cy="10" r="50"></circle>
</svg>
`);
```
> test(v2): toMatchDOM matcher

- starters/README.md
- starters/features/builder.io/package.json
- starters/features/builder.io/src/components/gauge/gauge.module.css
- starters/features/builder.io/src/components/gauge/index.tsx
- starters/features/builder.io/src/routes/[...index]/index.tsx
This PR upgrades the version of qwik sdk as well as qwik dev tools to their latest in builder_io integration starters. This also fixes couple of issues:
- Uses latest SDK functions (fetchOneEntry, Content)
- Fixes the Counter component by adding the missing Gauge component
https://www.loom.com/share/de19fe84f7fb400f9566b95f77a2738c
- 1. Unblocks user to smoothly onboard using the builder.io integration
> fix(starters): use latest qwik sdk in starters and fixes

- packages/docs/src/components/router-head/router-head.tsx
- packages/docs/src/routes/layout.tsx
The previous implementation used useSignals and useTask$ unnecessarily, which could cause delays in generating the Open Graph (OG) image URL and result in blank OG previews when shared. This pull request introduces an OGImage object that efficiently handles the dynamic OG image generation, leading to faster generation of the image URL and improved performance in creating OG previews.
> fix(Docs): Social media OG image URL generation update

- packages/docs/src/components/header/header.css
- packages/docs/src/components/on-this-page/on-this-page.css
- packages/docs/src/components/on-this-page/on-this-page.tsx
- packages/docs/src/components/sidebar/sidebar.css
- packages/docs/src/global.css
- packages/docs/src/routes/community/layout.tsx
- packages/docs/src/routes/docs/docs.css
- packages/docs/src/routes/docs/layout.tsx
Make layout work independent of browser font-size setting.
See #5853
> fix(layout): fix layout for non-default html font-size 

- packages/qwik-city/static/main-thread.ts
fixes https://github.com/BuilderIO/qwik/issues/6069
> fix: valid protocol error

- packages/qwik/src/qwikloader.ts
> fix: make the event listener on the window to use the capture option

- packages/qwik/src/optimizer/src/plugins/image-size-server.ts
fix #6089
Image resizing optimization is done using the `image-size` dependency. There was a case missing to handle AVIF image types/extensions, which caused the optimizer server to return a `500` to `GET` requests to a `__image-info` endpoint.
There should be no errors when AVIF images are being served on a page (during development).
> fix(optimizer): add support for AVIF images

- packages/qwik/src/optimizer/src/plugins/image-size-server.ts
> fix(pipeline): apply linter 🧽

- packages/docs/src/components/on-this-page/on-this-page.css
- packages/docs/src/routes/docs/docs.css
- packages/docs/src/routes/docs/layout.tsx
Re-add OnThisPage for docs pages (removed by mistake).
See https://github.com/BuilderIO/qwik/pull/6073#issuecomment-2041116199 and following discussion.
@shairez 
I replaced your fix for horizontal scrolling on mobile with `min-w-48` on `.docs-container` to mitigate possible issues on larger screens as well. Unfortunately, I didn't figure out why the code fragments messed up the `min-content` value in the first place.
> docs: re-add OnThisPage for docs pages

- packages/qwik-city/buildtime/build.ts
- starters/apps/qwikcity-test/src/routes/issue5665/projects/index.tsx
- starters/dev-server.ts
Fixes https://github.com/BuilderIO/qwik/issues/5665. As the `rewriteRoutes` were pushed at the end of the `routes` array at build time, when the `loadRoute` (runtime) got called and iterate through all the routes, the `matchRoute` function matched any dynamic or catchAll route first (because they were before).
- [-] Added new tests to cover the fix / functionality ---> Not necessary?
> fix(#5665): rewritten routes get ignored by dynamic and catchAll routes

- starters/adapters/express/package.json
express  <4.19.2
Severity: moderate
Express.js Open Redirect in malformed URLs - https://github.com/advisories/GHSA-rv95-896h-c2vc fix available via `npm audit fix --force`
Will install express@4.19.2, which is outside the stated dependency range node_modules/express
1 moderate severity vulnerability
To address all issues, run:
npm audit fix --force
> fix(starter/express): Update package.json

- packages/qwik/src/qwikloader.ts
sync$ may not be async function and e.stopPropagation() won't work unless it's fired immediately
fixes https://github.com/QwikDev/qwik/issues/5322
used this repo with the fix in a custom qwik loader
https://github.com/PatrickJS/bug-qwik-loader-stopPropagation
> fix(qwikloader): stopPropagation for any async handlers

- packages/docs/src/routes/examples/apps/examples-menu.json
Removed an extra word in runtime-less app description in docs package
> docs(examples/apps): fixing a typo in runtime-less app description

- packages/docs/src/routes/docs/(qwik)/faq/index.mdx
Updated grammar in Docs.
1) Even and Cache are unnecessarily capitalized
2) The 's is not necessary in reference to a plural noun's possession. Depending on the intent of a plural or singular browsers, it is either browsers' or browser's
> docs: correct spelling/grammar

- packages/qwik/src/core/use/use-task.ts
- packages/qwik/src/core/v2/use-computed.unit.tsx
> fix(v2): correct handling of async code loading with use-computed

- packages/docs/src/routes/docs/(qwikcity)/project-structure/index.mdx
> docs: Update project-structure index.mdx verbiage and phrasing

- packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
> docs: Update server index.mdx verbiage and phrasing

- packages/docs/src/routes/docs/(qwikcity)/advanced/routing/index.mdx
> docs: Update advanced/routing index.mdx verbiage and phrasing

- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/vite-server.ts
This PR aims to enhance the support for custom entry points in the Vite configuration in library mode, enabling developers to specify custom entry points and facilitating the creation of libraries with custom submodules. By extending the capability of Vite configuration, this enhancement provides flexibility and empowers developers to tailor their projects more effectively.
This PR modifies the code to allow for custom entry points in the Vite configuration (library mode). It includes updates to handle custom entry points provided in the Vite config file. This enhancement aims to address the need for developers to create libraries with custom submodules by providing a more flexible configuration option.
The primary use cases for this enhancement include:
1. **Custom Entry Points:** …
> fix(plugin/optimizer): 🐛 Enhance support for custom entry points in Vite config

- packages/qwik/src/optimizer/src/qwik-binding-map.ts
- starters/apps/base/qwik.env.d.ts
- starters/apps/base/tsconfig.json
Closes #6059
It's been about a month since [this](https://github.com/QwikDev/qwik/pull/6059) PR was opened and to this point I doubt that it is going somewhere, so I decided to take over and fix this issue, using the same solution I have proposed [here](https://github.com/QwikDev/qwik/pull/6059#discussion_r1543971400), and I was able to verify it is working.
My [previous](https://github.com/QwikDev/qwik/pull/5942) attempt to fix types for Bun turned out to be incomplete, so this PR fixes the issue. Here's a brief list of changes:
As I said before, the `types` field narrows the list of the sources where TypeScript will look for typings for global scope, so I don't think it would be a good fit when there's many other typings that can be needed from `node_modules/@types`. In our case, we …
> fix(starters): Fix vite types referencing in base starter

- packages/docs/src/routes/docs/(qwik)/deprecated-features/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx
A lot of developers are used to simply using if(typeof window !== 'undefined'). I tried to improve the docs on why are isServer/isBrowser needed.
> docs(isBrowser/isServer): explain why those helpers are useful

- packages/docs/src/routes/docs/(qwik)/components/tasks/index.mdx
> docs: Update components/tasks index.mdx verbiage and phrasing

- packages/qwik/src/core/v2/client/vnode-diff.ts
- packages/qwik/src/core/v2/component.unit.tsx
- packages/qwik/src/core/v2/shared/component-execution.ts
This PR fixes component rerender with the same key and different props
> fix(v2): component rerender with the same key and different props

- packages/docs/src/routes/docs/(qwik)/components/context/index.mdx
> docs: Update components/context index.mdx verbiage

- packages/docs/src/routes/docs/deployments/static/index.mdx
add missing import in https://qwik.dev/docs/deployments/static/
add missing import in https://qwik.dev/docs/deployments/static/
N/A
> docs: add missing import

- starters/apps/base/vite.config.ts
this is caused by having duplicate deps in both devDeps and deps
fixes #6226
> fix(vite.config): Duplicate Export

- packages/docs/src/routes/docs/(qwik)/components/styles/index.mdx
> docs: Update components/styles index.mdx verbiage and phrasing

- packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx
add a clarification to denote the 2 files
Small clarification to denote one file from the other (as the on file has a ts title="chunk..." and the other does not so for a moment there it looks like there's a missing file)
> docs: advanced dollar

- packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
> docs: Update getting-started index.mdx to add export default

- packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
> docs: Update server index.mdx define server inside onclick

- packages/qwik-city/middleware/node/http.ts
when refreshing the page mid-stream or when a user changes view and disrupts server$ we may see this error
fixes https://github.com/QwikDev/qwik/issues/5028
fixes https://github.com/QwikDev/qwik/issues/4805
> fix(http): ignore ERR_HTTP2_INVALID_STREAM

- starters/apps/base/vite.config.ts
The commented SSR configuration in vite.config.ts intended to enhance server code bundling for production builds by including all development dependencies and excluding specified production dependencies to optimize the server bundling.
This has led to consumers adding packages in the wrong location, and as a result these packages do not work in production.
This PR comments out that code, and labels it as an advanced config for when you understand which dependencies should be consumed either as a dependency, or dev dependency.
In the future, I believe we should uncomment this code by default, but only when better error handling is present, as it was difficult to debug. For example, a CLI message that tells us whether the wrong dependency was bundled or not.
For more context see: …
> revert: starter vite config server bundle optimizations

- packages/docs/src/routes/docs/integrations/i18n/index.mdx
> docs: Update i18n index.mdx verbiage and phrasing

- packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
- packages/docs/src/routes/docs/labs/typed-routes/index.mdx
Adding the setup and usage instructions for how to use the Declarative Routing package inside QwikCity. Also adding a link to the Typed Routes section inside of the standard Routing page
Adding the setup and usage instructions for how to use the Declarative Routing package inside QwikCity
- 1. User would like to use declarative (typesafe) routing inside QwikCity
> docs(routes / typed-routes): add Declarative Routing

- packages/qwik/src/qwikloader.ts
fixes https://github.com/QwikDev/qwik/issues/3716
> feat(qwikloader): emit error

- packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
The examples were wrong, because <Slot/> was missing
> docs(polymorphism): changed hi to slot

- packages/docs/src/routes/docs/cookbook/sync-events/index.mdx
In the event that people might find the sync$() docs when attempting to find out how to do `preventDefault`, I have added a note before the example with a redirect to the preventDefault documentation
In the event that people might find the sync$() docs when attempting to find out how to do `preventDefault`, I have added a note before the example with a redirect to the preventDefault documentation
> docs(sync$): adding note pointing to preventDefault docs

- packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
> docs: server$ wording and link

- packages/qwik-city/utils/fs.ts
> fix: SSG ignoring the index page when trailingSlash is false

- packages/docs/src/routes/docs/integrations/partytown/index.mdx
This update enhances the Qwik application's integration with Google Analytics via Partytown by ensuring the `gtag` function is exposed for use in components, enabling the sending of custom events directly from the component level.
Key changes:
1. Updated the Partytown script configuration to expose `gtag` globally, allowing for direct invocation in component logic.
2. Added the complete Google Analytics integration script as recommended by Google, ensuring comprehensive tracking capabilities.
3. Documented this integration pattern to assist others in setting up Google Analytics with Partytown in Qwik applications, addressing a common challenge found during implementation.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. …
> docs: Document exposing gtag for custom events in Qwik Partytown setup

- packages/qwik-city/middleware/bun/index.ts
Closes #5929
The implementation of bun adapter implemented in #5129 has also introduced a polyfill for [TextEncoderStream](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoderStream). While the adapter itself works, this polyfill introduced a bug, caused on attempt to close a response stream (see #5929 for more info). This PR fixes this issue by rewriting the polyfill based on this comment: https://github.com/QwikDev/qwik/issues/5929#issuecomment-2108951045
> fix(bun): Rewrite TextEncoderStream polyfill implementation for Bun middleware

- package.json
- packages/insights/src/db/query.ts
- packages/insights/src/routes/plugin@auth.ts
> fix(insights): lower limit to prevent timeouts

- packages/qwik-city/buildtime/context.ts
- packages/qwik/src/core/components/prefetch.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/server/utils.ts
- starters/features/localize/src/routes/[locale]/i18n-utils.ts
@mhevery not sure if this should go in only v2 because it might be slightly breaking.
> fix(qwik-city): enforce / on base paths

- packages/docs/src/routes/docs/(qwikcity)/api/index.mdx
This pull request adds a documentation about how to "Go Back" using `useNavigate` and `useLocation`
> docs: added going back example

- packages/docs/src/routes/docs/(qwikcity)/api/index.mdx
Updated for better readability and understanding.
- 1. Easier for users to read and understand
> docs: Wording and grammar corrections

- packages/docs/src/routes/docs/(qwikcity)/advanced/request-handling/index.mdx
@PatrickJS asked me on Discord to add this ^^
> docs: alternative cookie delete

- starters/apps/base/vite.config.ts
Update vite.config file to throw an Error if qwik packages are in dependencies
> feat(starters): error if qwik packages aren't together 

- packages/docs/src/routes/docs/cookbook/portals/index.mdx
replaces link with one provided by Jack Shelton
fixes https://github.com/QwikDev/qwik/issues/6329
Replace dead link with live link provided by Jack Shelton.
> docs: fixes broken link

- packages/docs/src/routes/docs/(qwikcity)/action/index.mdx
Rewrote the routeAction$() section to be more concise and to provide better reader understanding. Made minor grammar improvements.
- 1. Improves readability and reader understanding.
> docs: Improved readability

- packages/qwik-city/runtime/src/route-matcher.ts
- packages/qwik-city/runtime/src/route-matcher.unit.ts
- [*] Feature / enhancement
For recursive matching of catchall routes, there was an artificial recursion watchdog limiter (set to 5). So, a route like
/[...catchall]/a/b/c/d/e wouldn't work if catchall didn't have a value (for example: /a/b/c/d/e would fail).
To fix this, we just check if there are any chances for the route to still match instead of stopping at the X amount of time.
- [*] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [*] I have performed a self-review of my own code
- [*] Added new tests to cover the fix / functionality
> fix(qwik-city): Removed artificial recursive limiter from recursive path matching

- packages/qwik/src/core/qrl/qrl-class.ts
- packages/qwik/src/core/v2/shared/shared-serialization.ts
> refactor(qrlToString): v2 SyncQRLInternal type

- packages/qwik-city/runtime/src/server-functions.ts
when server$ lambda blows up the content type changes.
this is needed for debugging
> fix(server$): return content type changes

- packages/docs/src/routes/api/qwik-city-middleware-request-handler/api.json
- packages/docs/src/routes/api/qwik-city-middleware-request-handler/index.md
- packages/qwik-city/middleware/request-handler/api.md
- packages/qwik-city/middleware/request-handler/cookie.ts
- packages/qwik-city/middleware/request-handler/cookie.unit.ts
- packages/qwik-city/middleware/request-handler/types.ts
Qwik-city lacks ability to append cookie headers to response. See https://developer.mozilla.org/en-US/docs/Web/API/Headers/append
In some cases it's valuable to be able to append cookies with the same name but different options.
```
MY_COOKIE=my_value; Expires=Mon, 28 May 2024 09:00:00 GMT; Path=/; Domain=my.domain.com
MY_COOKIE=my_value; Expires=Mon, 29 May 2024 10:00:00 GMT; Path=/account/; Domain=another.my.domain.com
MY_COOKIE=my_value; Expires=Mon, 30 May 2024 11:00:00 GMT; Path=/api/; Domain=.my.domain.com
```
> feat(qwik-city): append cookie headers to response

- packages/qwik/src/core/readme.md
Mentions to avoid using a try/catch statement in useResource and why.
Until I removed the `try/catch` statement in `useResource$`, `Resource` was not providing an accurate `onRejected` status.
> docs: Updates useResource description in readme.md

- starters/apps/basic/src/root.tsx
fixes https://github.com/QwikDev/qwik/issues/6352
> fix(starters): unicode problem

- packages/insights/src/components/avatar/index.tsx
> fix(insights): fix up CSS class

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/index.ts
- packages/qwik/src/core/render/jsx/jsx-runtime.ts
- packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
- packages/qwik/src/core/v2/client/vnode-diff.ts
- packages/qwik/src/optimizer/core/src/transform.rs
- starters/apps/e2e/src/components/render/render.tsx
- starters/e2e/e2e.render.e2e.ts
This PR removes the HTMLFragment component. It is not needed.
> fix(v2): delete HTMLFragment

- .npmrc
In `package.json` the `packageManager` option is set to a specific version which makes it harder to work with. 
By disabling the strict check but enabling the `engine-strict` check we still verify that pnpm has the right minimum version but not limit newer pnpm versions.
> chore: disabled strict check on package manager

- packages/docs/public/repl/~repl-server-host.html
- packages/docs/src/root.tsx
- packages/insights/src/root.tsx
- packages/qwik-city/buildtime/vite/dev-server.ts
- packages/qwik-city/middleware/request-handler/error-handler.ts
- packages/qwik-city/runtime/src/qwik-city-component.tsx
- packages/qwik-labs/src/root.tsx
- packages/qwik-react/src/root.tsx
- packages/qwik/src/core/container/index.html
- packages/qwik/src/core/render/jsx/types/jsx-generated.ts
- packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__issue_476.snap
- packages/qwik/src/optimizer/core/src/test.rs
- starters/apps/basic/src/root.tsx
- starters/apps/e2e/src/entry.ssr.tsx
- starters/apps/empty/src/root.tsx
- starters/apps/library/src/root.tsx
- starters/apps/perf.prod/src/root.tsx
- starters/apps/qwikcity-test/src/root.tsx
- starters/apps/site-with-visual-cms/src/root.tsx
- starters/apps/starter-partytown-test/src/root.tsx
- starters/apps/todo-old-test/src/root.tsx
- starters/apps/todo-test/src/root.tsx
- starters/features/cypress/cypress/support/component-index.html
fix utf-8 lowercase
> The default character encoding used in HTML5 is UTF-8. This means if you include <!DOCTYPE html> at the top of your HTML file (which declares that it's an HTML5 file), it'll automatically use UTF-8 unless specified otherwise.
> Most browsers use UTF-8 by default if no character encoding is specified. But because that's not guaranteed, it's better to just include a character encoding specification using the <meta> tag in your HTML file.
> fix: utf-8 lowercase

- packages/qwik-city/middleware/bun/index.ts
- packages/qwik-city/middleware/cloudflare-pages/index.ts
- packages/qwik-city/middleware/request-handler/api.md
- packages/qwik-city/middleware/request-handler/index.ts
- packages/qwik-city/middleware/request-handler/polyfill.ts
revert TextEncoderStream for cloudflare
> chore: use old cf TextEncoderStream

- packages/eslint-plugin-qwik/src/loaderLocation.ts
fix #6361
See related issue: https://github.com/QwikDev/qwik/issues/6361
I suppose we could also update the related doc, but I'm not sure that's necessary.
ESLint is triggering an `invalidLoaderLocation` warning when loaders are located in a `.jsx` file instead of `.tsx`.
Loaders should be considered valid in `.jsx` files as well.
> fix(eslint-plugin-qwik): allow loaders in routes with JSX extension

- packages/docs/src/routes/docs/deployments/vercel-edge/index.mdx
The aim of pull request is to add a new section on vercel deployment page to explain how to deploy Qwik app with drizzle adapter on vercel endge.
- Devs might get some confusing errors during deployment and this would be quite helpful
> docs: drizzle vercel edge section

- .github/workflows/closing-issues.yml
- .github/workflows/labeling-issues.yml
- CONTRIBUTING.md
- contributing/TRIAGE.md
Added a "Triage Process" guide
Plus added 2 ci workflows - 
1. Auto closing stale issues that needs reproduction or missing info and haven't got any response for 14 days
2. Adding a comment on "missing info" and "needs reproduction" labeled issues to notify it will be automatically be closed after 14 days.
> docs: added traiging process and github actions

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/use/use-store.public.ts
Changes are made in JSDoc, API json and API docs.
In #3678 the `useStore` is made recursive by default. The JSDoc and API description for the `deep` property of `UseStoreOptions` were not yet updated to match this.
The conflicting docs can be confusing as it insinuates that deep reactivity still has to be enabled manually. Especially the outdated JSDoc makes for a confusing IntelliSense in code editors.
> docs: update docs for `deep` property of `useStore` to match the new default

- packages/create-qwik/src/helpers/jokes.json
- packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
Rewrote the server$() section to be more concise and easier to read.
- 1. Improves conciseness and readability
> docs: Improved conciseness and readability

- packages/create-qwik/src/helpers/jokes.json
- packages/qwik/src/core/use/use-resource.ts
Duplicates the text changes that were approved for the core readme in this PR: https://github.com/QwikDev/qwik/pull/6354/files
Catching an error in `useResource$` will prevent `<Resource />` from getting the `onRejected` state.
> docs: Update use-resource.ts

- packages/docs/src/routes/api/qwik-city/api.json
- packages/docs/src/routes/api/qwik-city/index.md
- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik-city/runtime/src/api.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/index.ts
- packages/qwik/src/core/state/signal.ts
- packages/qwik/src/core/use/use-core.ts
- packages/qwik/src/core/use/use-signal.ts
- packages/qwik/src/core/use/use-task.ts
- packages/qwik/src/core/util/implicit_dollar.ts
- starters/apps/e2e/src/components/signals/signals.tsx
- starters/e2e/e2e.signals.spec.ts
This adds the following APIs:
- `useConstant(value)`: stores a fixed value for the lifetime of the component
- `createSignal(value)`: same as useSignal but can be called a variable amount of times and always returns a new Signal
- `createComputed$(cb)`: same as createSignal but for computed signals
Note that the create* API calls still need to run within the component context. This is only available inside the render function and the useConst callback.
Perhaps we should also make the context available inside tasks, as long as we forbid calling hooks (by forbidding useSequentialContext).
Example:
```tsx
const signals = useConstant(() => {
const arr: (Signal<number> | string)[] = [];
for (let i = 0; i < 10; i++) {
arr.push(createSignal(0));
arr.push(", ");
}
return arr;
});
const doubles = …
```
> feat(core): useConstant, createSignal, createComputed$

- packages/qwik-auth/src/index.ts
> fix(qwik-auth): define `basePath` option

- packages/docs/src/components/footer/footer.tsx
- packages/docs/src/components/header/header.tsx
- packages/docs/src/components/svgs/discord-logo.tsx
- packages/docs/src/components/svgs/qwik-logo.tsx
- packages/docs/tailwind.config.js
> docs: site footer + banner changes

- packages/docs/src/components/docsearch/search-box.tsx
- packages/docs/src/routes/docs/(qwik)/index.mdx
Also changed the wording of the search input since Qwik GPT has been disabled
> docs: improve clarity in docs overview

- packages/docs/src/routes/docs/menu.md
typo. When you go to the overview, it says "Components".
> docs: heading change

- packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx
> docs: punctuation, run on sentence fix

- packages/docs/src/routes/docs/(qwik)/components/state/index.mdx
> docs: added punctuation

- packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
> docs: (qwikcity/server$) grammar; punctuation; readability

- packages/docs/src/routes/docs/(qwikcity)/guides/best-practices/index.mdx
Added another best practices that avoids subscribing inside the component$ function.
> docs: added reactivity best practice

- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/optimizer/src/plugins/vite.unit.ts
> feat: use assetsDir in the qwikVite plugin

- packages/qwik-city/buildtime/vite/plugin.ts
- packages/qwik-city/buildtime/vite/types.ts
Helps with integrations that want to use the already configured MDX transformer, by simply accessing the plugin's API. Additionally, exposes the build context so that any other transformer could use it.
While building a Vite plugin that uses MDX transformations, I ran into the complexity where I was using imports to get the transformed state. Ideally, I do not want to set up an alternative MDX transformer and just let the project define one. The basic import transformation works when retrieving content, albeit for more complex features, like breaking the markdown files into blocks, edit files and save them, I would need a deeper integration.
1. Split MDX content into blocks to inject any additional content in-between blocks like references, ads, summaries and allow …
> feat(qwik-city): expose MDX transformer and context

- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/optimizer/src/plugins/vite.unit.ts
I'm using `qwikVite` to bundle my library. Because my setup requires multiple output files per format, I've tried to use the `rollupOptions.output` field to achieve this:
```js
{
build: {
lib: {
entry: './src/index.ts',
},
rollupOptions: {
output: [
{
format: 'es',
entryFileNames: 'index.esm.js',
},
{
format: 'es',
entryFileNames: 'index.mjs',
},
{
format: 'cjs',
entryFileNames: 'index.cjs.js',
},
{
format: 'cjs',
entryFileNames: 'index.cjs',
},
],
},
}
}
```
This did work but always created one additional output file which I didn't specify in the config. That happens because the `qwikVite` plugin is not handling output arrays correctly.
The possibility to achieve multiple outputs for library authors.
> feat(qwikVite): add possibility to define multiple outputs

- packages/docs/src/routes/docs/labs/index.mdx
- packages/docs/src/routes/docs/labs/typed-routes/index.mdx
I changed the references to install directly from GitHub to the right repository
Currently working on a local version without turso and stumbled across this little doc problem.
> docs(insights): location change to qwikdev

- packages/qwik/src/server/v2-ssr-container.ts
During a session with @mhevery and @shairez,
we looked at the SSR container class,
@mhevery explained what `tagNesting` means and I found this as something that is not intuitive so went ahead and opened this PR to add some context to it.
> docs(v2/ssr-container): add context to tag nesting property

- packages/qwik/src/core/v2/client/vnode-diff.ts
- packages/qwik/src/core/v2/client/vnode-namespace.ts
- packages/qwik/src/core/v2/client/vnode.ts
- packages/qwik/src/core/v2/ssr/ssr-render-jsx.ts
- packages/qwik/src/core/v2/ssr/ssr-types.ts
- packages/qwik/src/server/v2-ssr-container.ts
- packages/qwik/src/server/v2-ssr-render2.ts
- packages/qwik/src/server/v2-tag-nesting.ts
- starters/apps/e2e/src/components/streaming/streaming.tsx
- starters/e2e/e2e.streaming.e2e.ts
this PR fixes the streaming tests + some refactoring
> fix(v2): fix streaming tests

- packages/qwik-city/runtime/src/router-outlet-component.tsx
- packages/qwik-city/runtime/src/spa-init.ts
- packages/qwik-city/runtime/src/spa-shim.ts
- packages/qwik/src/core/components/prefetch.ts
- packages/qwik/src/core/components/prefetch.unit.tsx
- packages/qwik/src/core/container/container.ts
- packages/qwik/src/core/container/pause.ts
- packages/qwik/src/core/container/resume.ts
- packages/qwik/src/core/qrl/qrl-class.ts
- packages/qwik/src/core/render/ssr/render-ssr.ts
- packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
- packages/qwik/src/core/util/markers.ts
- packages/qwik/src/qwikloader.ts
- packages/qwik/src/server/prefetch-implementation.ts
- packages/qwik/src/server/prefetch-utils.ts
- packages/qwik/src/server/render.ts
- packages/qwik/src/testing/element-fixture.ts
`currentScript` is not available in shadow dom. For this reason we can't use it. This change removes all references to `currentScript`
The biggest change is that the `qFuncs` are no longer written to the container element but rather to the document. Because there is only one document the `qFuncs` property now includes the `container` `q:manifest-hash` to distinguish between different containers.
> refactor: remove references to `currentScript`

- packages/docs/src/repl/repl-options.tsx
- packages/docs/src/repl/repl-output-modules.tsx
- packages/docs/src/repl/repl-output-symbols.tsx
- packages/docs/src/repl/repl-output-update.ts
- packages/docs/src/repl/repl.css
- packages/docs/src/repl/types.ts
- packages/docs/src/repl/worker/repl-server.ts
- click to file works again
- don't duplicate code DOM elements
- in mobile, put file paths at the top
And most notably:
- store now deeply updates so that code changes update the output
> fix(repl): code display in repl output

- packages/docs/src/routes/demo/integration/modular-forms/index.tsx
- packages/docs/src/routes/docs/integrations/modular-forms/index.mdx
I was trying to implement modular forms like on [docs](https://qwik.dev/docs/integrations/modular-forms/#modular-forms) but when I installed `valibot` ^0.32.0 found there is no exported type `Input` (I think it's outdated).
When I looked in `valibot` docs they use `InferOutput` instead.
> fix(docs): update valibot snippet

- packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts
- packages/qwik/src/qwikloader.ts
- starters/apps/e2e/src/components/containers/container.tsx
- starters/e2e/e2e.containers.spec.ts
feat(core): Add support to shadow DOM for QwikLoader.
Shadow DOM can be used to isolate an application. The isolation also
includes:
- Events don't bubble across shadow boundaries.
- QuerySelector doesn't cross shadow boundaries.
QwikLoader relies on both event bubbling and querySelector to process
events such as `on:click` and dispatch such as `on-window:resize`.
To enable QwikLoader to work with shadow DOM, it is necessary to tell
qwikloader that when it is registering an event listener, as well as
performing querySelector, it should do so not just on document but also
inside the shadow DOM. To do that it is the responsibility of the
developer to tell qwikloader about the shadow DOM roots.
CONSTRAINTS:
The qwikloader applications `q:container` must be fully inside the
shadow root. (i.e. …
> feat(core): Add support to shadow DOM for QwikLoader.

- starters/adapters/fastify/package.json
Moved fastify to dependencies section
Fastify should be under dependencies. Here the issue:
https://github.com/QwikDev/qwik/issues/5795
> fix: moved Fastify packages to dependencies section

- packages/qwik-city/runtime/src/spa-init.ts
- packages/qwik-city/runtime/src/spa-shim.ts
- packages/qwik/src/core/qrl/qrl.ts
- packages/qwik/src/core/qrl/qrl.unit.ts
- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/vite-dev-server.ts
Qwik city preloaded spa-init.ts but that didn't include the parent info so it gave a harmless error.
Also, qrl paths with + turned into spaces, which broke loading
> fix(qrl): correct qrl loading in vite dev mode

- packages/qwik/src/core/qrl/qrl-class.ts
- packages/qwik/src/core/qrl/qrl.unit.ts
- now you can call the result of `.resolve()` (and `.resolved`) directly
- avoids wrapping QRL functions that don't use lexical scope
- moves symbol load event to resolve(), only when it needed to get it externally
> feat(qrl): wrap resolved funcs for scope

- packages/docs/src/routes/docs/(qwik)/components/state/index.mdx
Will help people to use qwik's best practices and save them time
> docs(state): add guidance on signals as props

- packages/qwik/src/optimizer/core/src/entry_strategy.rs
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_default_export.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_manual_chunks.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_qwik_sdk_inline.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_use_server_mount.snap
- packages/qwik/src/optimizer/core/src/transform.rs
...by adding the original filename.
This way multiple files in the same directory with the same component name won't cause problems.
> fix(optimizer): make component entries more unique

- .github/workflows/ci.yml
without this, it was using a copy of the previous release
> fix(build): put optimizer in pr.new builds

- packages/qwik/src/server/v2-ssr-container.ts
During a session with @mhevery and @shairez,
@mhevery said that the `Container` prefix is redundant and a bit confusing.
Therefore I created this PR to remove it.
> refactor(v2/ssr-container): rename ContainerElementFrame to ElementFrame

- packages/qwik/src/core/use/use-sequential-scope.ts
- packages/qwik/src/core/util/markers.ts
- packages/qwik/src/core/v2/client/dom-container.ts
- packages/qwik/src/core/v2/client/process-vnode-data.ts
- packages/qwik/src/core/v2/client/vnode.ts
- packages/qwik/src/core/v2/shared/component-execution.ts
- packages/qwik/src/core/v2/shared/vnode-data-types.ts
- packages/qwik/src/server/qwik-copy.ts
- packages/qwik/src/server/v2-ssr-container.ts
This PR fixes vnode separators and `missing refElement` error in the docs
> fix(v2): fix vnode separators

- packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx
Small grammar fix in the $ symbol section about the optimizer.
- 1. Improves readability
> docs: small grammar change

- .github/workflows/labeling-issues.yml
> chore: improve needs reproduction message

- packages/qwik/src/optimizer/src/plugins/vite-dev-server.ts
`/` gets prepended due to the request and parentPath already has `/`
> fix(dev): path to outside-project files

- packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx
Updated the RouteLoader$ section with small grammar corrections.
- 1. Improves readability
> docs: Small grammatical corrections

- starters/apps/base/vite.config.ts
> docs(starts): fix typo depencies

- packages/qwik/src/server/prefetch-implementation.ts
- packages/qwik/src/server/v2-ssr-container.ts
This PR removes the use of tag nesting as it doesn't work for production. This fixes the "missing child" error in production build.
> fix(v2): do not use tag nesting for production build

- packages/qwik/src/core/v2/shared/scheduler.ts
- starters/e2e/e2e.toggle.e2e.ts
This is a fix for a toggle e2e test
Instead of throwing an error we will show a warning now
> fix: show a warning instead of an error for rerunning tasks on a different host

- packages/docs/src/routes/docs/(qwik)/advanced/dollar/index.mdx
Fixed the capitalization of Optimizer
> docs: Fixed capitalization on "Optimizer"

- packages/qwik/src/core/v2/client/vnode-diff.ts
- packages/qwik/src/core/v2/client/vnode-diff.unit.tsx
- packages/qwik/src/core/v2/shared/types.ts
- packages/qwik/src/core/v2/tests/component.spec.tsx
- packages/qwik/src/qwikloader.ts
This PR fixes attribute toggling and CSR event registration
> fix(v2): attribute setting and CSR event registration

- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/prefetch-service-worker/direct-fetch.ts
- packages/qwik/src/prefetch-service-worker/process-message.ts
> fix: improve new SW logic

- packages/docs/src/repl/worker/app-bundle-client.ts
- packages/docs/src/routes/api/qwik-optimizer/api.json
- packages/docs/src/routes/api/qwik-optimizer/index.md
- packages/docs/src/routes/docs/(qwikcity)/advanced/content-security-policy/index.mdx
- packages/qwik-city/buildtime/vite/dev-server.ts
- packages/qwik-react/package.json
- packages/qwik-react/src/vite.ts
- packages/qwik/src/optimizer/src/api.md
- packages/qwik/src/optimizer/src/index.ts
- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/vite-dev-server.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- starters/apps/empty/src/root.tsx
- starters/apps/playground/src/root.tsx
- fixes nx monorepo path lookup in dev mode
- fix vite prefix for css etc
- fix qrl segment path encoding for windows in dev mode
- only pass parent filename since path is always the same
- simplify resolveId path handling
- change starter to only add service worker in production
- add base url to manifest
> fix(dev): vite base and qrl segment fixes

- packages/qwik/src/core/state/store.ts
- packages/qwik/src/core/v2/tests/use-store.spec.tsx
This PR fixes deep store update
> fix(v2): deep store update

- starters/features/partytown/src/components/partytown/partytown.tsx
In a typescript project the partytown starter will lead to lint warnings.
> fix(partytown-starter): using type import

- .changeset/lucky-dolphins-grab.md
- .changeset/rich-hairs-worry.md
- packages/qwik-city/buildtime/vite/dev-server.ts
- packages/qwik-city/buildtime/vite/plugin.ts
- packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts
- packages/qwik-city/middleware/request-handler/resolve-request-handlers.unit.ts
- packages/qwik-city/runtime/src/qwik-city-component.tsx
- scripts/build.ts
- starters/apps/qwikcity-test/src/routes/issue6660/index.tsx
- starters/e2e/qwikcity/nav.spec.ts
Followup for #6410 and #6687
Fixes #6660
Fixes #6677
> fix(qwik-city): strip internal parameters for compare

- .changeset/two-tips-protect.md
- .eslintignore
- .github/workflows/ci.yml
- .prettierignore
- packages/docs/.gitignore
- packages/docs/check-qwik-build.ts
- packages/docs/package.json
- packages/docs/src/components/docsearch/result.tsx
- packages/docs/src/routes/docs/(qwikcity)/routing/index.mdx
- packages/docs/vite.config-repl-sw.mts
- packages/qwik-city/buildtime/vite/dev-server.ts
- allow HMR for `entry.ts` routes in dev
- speed up dev docs build by only building `repl-sw.js`, and only when needed
- speed up search results by doing SPA navigation
> fix(dev): docs.dev playground + small things

- packages/qwik/src/core/use/use-on.ts
- packages/qwik/src/core/use/use-sequential-scope.ts
- packages/qwik/src/core/util/markers.ts
- packages/qwik/src/core/v2/client/dom-container.ts
- packages/qwik/src/core/v2/shared/component-execution.ts
- packages/qwik/src/core/v2/tests/use-on.spec.tsx
This PR fixes few edge cases for the `useOn` hook
> fix(v2): use on events fixes

- packages/qwik/src/core/util/markers.ts
- packages/qwik/src/core/v2/client/process-vnode-data.ts
- packages/qwik/src/core/v2/client/process-vnode-data.unit.tsx
- packages/qwik/src/core/v2/client/vnode.ts
- packages/qwik/src/core/v2/shared/vnode-data-types.ts
- packages/qwik/src/server/v2-ssr-container.ts
This PR adds the `q-ignore` and the `q-container-island` comments.
Example:
```html
<div>interactive content 1</div>
...(ignored)
<button on:click="...">some interactive island</button>
...(ignored)
<div>interactive content 2</div>
```
> feat(v2): q-ignore and q-container-island implementation

- .github/workflows/ci.yml
- package.json
Changesets create a root CHANGELOG and it is not needed
> ci: delete root useless CHANGELOG 😊

- .gitignore
- CHANGELOG.md
Changesets will run over the root CHANGELOG
So I created an index for all of the sub packages changelogs and added it to gitignore so it wouldn't get run over by changesets.
> chore: make root CHANGELOG permanent

- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/optimizer/src/plugins/vite.unit.ts
Fixes #6620 and retains #6452. Successor of #6643.
> fix(qwikVite): multiple outputs logic

- .changeset/nasty-files-fail.md
- packages/qwik-city/src/runtime/src/use-endpoint.ts
When using capacitor, the "browser" is on capacitor://localhost or http://localhost, and
when route loading is proxied, the return URL origin is not the same as the current
origin. This prompted qwik-city to reload the page.
Now, this is only done when the request was actually redirected.
> fix(qwik-city): redirect route loads when sane

- .github/workflows/ci.yml
- scripts/release.ts
This PR reverts the default "version setting" behavior to add the `dev-timestamp` suffix to the packages' version number.
But, if the CI identifies that the latest "push" (merge) removed the md files from the `.changesets` folder, and there are no other .md files there, it'll set the `disttag` to `latest`.
This will make sure Qwik doesn't add the `dev-timestamp` suffix but instead leave it intact
> ci: made changesets work with dist tag

- package.json
- pnpm-lock.yaml
The end of all CI linting errors
Every local pnpm install will also install a pre-commit hook that will run `pretty-quick --staged` which will fix prettier errors only for staged files.
oh happy days!  🎉
> chore: added pretty-quick and a pre-commit hook

- .changeset/sour-papayas-travel.md
- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/vite.unit.ts
- starters/dev-server.ts
Right now, if `rollupOptions.output.assetFilenames` is not defined, assets will be output as `build/q-[hash].ext`.
This PR changes that default setting to `assets/[hash].[ext]`.
The reasoning is that for post-processing like `$localize` that copies the build files into `/build/[locale]/`, it makes no sense to have to copy `.css` files and others, especially since all css files will be automatically added to the head and so you'll get a per-language copy of the css file.
This is a slightly breaking change, in case some custom scripting is expecting all files to live under `/build`. (Seems unlikely though)
> feat(vite-plugin): set assets path in build to /assets

- .changeset/ninety-weeks-enjoy.md
- packages/qwik/src/optimizer/core/src/clean_side_effects.rs
- packages/qwik/src/optimizer/core/src/code_move.rs
- packages/qwik/src/optimizer/core/src/lib.rs
- packages/qwik/src/optimizer/core/src/parse.rs
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_11.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_default_export.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_drop_side_effects.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_explicit_ext_no_transpile.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_fix_dynamic_import.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_manual_chunks.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_qwik_sdk_inline.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_use_server_mount.snap
- packages/qwik/src/optimizer/core/src/transform.rs
- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/vite-dev-server.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
This makes the Qwik rollup plugin behave like a normal plugin, and speeds up dev startup.
- removes entry creating from optimizer
- adds manualChunks option that tells Rollup which chunks to put together
- removes building at buildStart so other plugins can transform before the segment splitting
> fix(optimizer): let the bundler handle entries

- .changeset/silver-readers-appear.md
- scripts/create-qwik-cli.ts
- scripts/util.ts
- scripts/validate-cli.ts
When creating a library via the CLI, it creates the wrong Qwik version in `devDependencies`
This fixes it and adds a test to make sure this bug won't come back.
(In the future we are planning a more robust testing system for qwik starters tests)
> fixed library starter wrong Qwik version

- packages/docs/src/routes/docs/(qwikcity)/action/index.mdx
The documentation says `superDefine` but no such function exists. The author probably meant to say `superRefine`.
- Idk, typos are bad.
> docs: change superDefine to superRefine

- .changeset/polite-feet-greet.md
- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
The `fileFilter` option to `qwikVite()` now always allows `*.qwik.{m,c,}.js` files so that QRLs in libraries can be processed.
> fix(vite): don't filter out qwik library files

- CONTRIBUTING.md
Just fixing a contributing docs issue (I believe it to be just a copy-paste mistake)
> docs(contributing): fix Qwik React indicated instead of Qwik Labs

- starters/features/storybook/package.json
Current   cli version of  `npx qwik add storybook` will run into 
the pr update the  starter to a healthy version 
here a stackblitz with  the said version 
https://stackblitz.com/edit/github-sy5fgo-s1yms4?file=storyboard%2FREADME.md
- [x ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
> fix(starter): update CLI version of storybook

- .changeset/wicked-foxes-behave.md
- starters/apps/library/vite.config.ts
Adds preserve modules to the library starters. It also makes the entryname apparent in the build, otherwise you would have:
`index.qwik2.mjs` and so forth.
> feat: add preserve modules to lib starter

- packages/docs/src/routes/docs/(qwikcity)/api/index.mdx
Add info about Link prefetching, which may result with too many requests.
IMO. Link prefetch behaviour should be by default use 'js' and hover/onload should be option on production.
> docs: add info about Link prefetch option

- package.json
Vite has an ecosystem ci which fails for Qwik.
This should fix it
> fixed build for vite ecosystem ci

- packages/qwik/src/optimizer/src/plugins/vite.ts
Bug in either vite or how we handle the transform of `?raw`. Prevents `?raw` imports from being transformed w/ qwikVite
> fix: qwikVite transforming id's with ?raw

- packages/docs/src/entry.ssr.tsx
- packages/docs/src/root.tsx
> chore: start modulepreload experiment

- packages/qwik-city/src/middleware/request-handler/resolve-request-handlers.ts
The search engine should update the URLs and for this we would have to declare them as 301 and not as 302 as is currently the case.
> fix(request-handler) change from 302 to 301

- .changeset/flat-pans-crash.md
- packages/docs/src/routes/demo/state/counter-store-deep/index.tsx
- packages/docs/src/routes/docs/(qwik)/components/state/index.mdx
Fixed typo in order to avoid the following situation:
> docs: fix typo in using useStore()

- .changeset/popular-dragons-greet.md
- .github/workflows/ci.yml
It took us a few hours of debugging to realize that our new version doesn't have a `.eslintrc.cjs` file because there [was a hidden breaking change](https://github.com/actions/upload-artifact/issues/602) introduced in a minor version of `upload-artifact`
Plus this PR fixes a typo in one of the changeset files
> Fixed CI not uploading dot files

- packages/docs/src/routes/docs/integrations/authjs/index.mdx
I noticed that the links to the environment variables docs in the [documentation](https://qwik.dev/docs/integrations/authjs/) were broken (I think it still linked to an old route). I've gone ahead to update it.
> docs: fix up env links in auth.js section

- packages/docs/src/routes/docs/(qwikcity)/guides/redirects/index.mdx
> Managing multiple redirects in Qwik

- packages/docs/src/routes/docs/(qwik)/concepts/think-qwik/index.mdx
Just a silly little fix to reword this section, as currently it reads as if Qwik is part of the problem, rather than the solution!
> fix(docs): improve wording in problem oultine section

- .changeset/tender-files-press.md
- packages/qwik/src/core/error/error.ts
- packages/qwik/src/core/render/execute-component.ts
- packages/qwik/src/core/render/execute-component.unit.ts
It is completely valid to write a code like this:
```tsx
export const cmp = component$(() => {
const style = {
hasOwnProperty: () => false,
foo: () => {
return 'bar';
},
color: 'red',
};
return <a style={style} href="/some-link">Link</a>;
});
```
This gets serialized to DOM like this:
To prove this wrong, I added some tests for `stringifyStyle` function that converts whatever it gets from user to a usable string value that later gets stored to DOM. Without this fix, tests `"should ignore object methods"` and `"should stringify object with custom hasOwnProperty method"` would fail.
Side note: since I wanted to add a lot of other tests for `stringifyStyle` (and `setValueForStyle` as well), I noticed that error with code [`QError_stringifyClassOrStyle`](https://github.com/QwikDev/qwik/blob/ba …
> fix: do not serialize methods of objects passed to styles

- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/shared/component-execution.ts
- packages/qwik/src/core/shared/jsx/jsx-runtime.ts
- packages/qwik/src/core/ssr/ssr-render-jsx.ts
- packages/qwik/src/server/ssr-container.ts
- do not use `.props` during rendering - this  creates component-level subscription
- don't use regexp for checking attribute name during ssr
> refactor(v2): reduce subsriptions count, dont use regexp for attribute checking

- .changeset/thick-dodos-promise.md
- packages/qwik/src/cli/utils/run-build-command.ts
Sometimes when running build (especially when using the static adapter), if there was a lint error it looked like the cli doesn't properly exit the process. 
This fixes it so it always comes back to the terminal command line after errors.
> fixed cli build "hangs"

- .changeset/shaggy-apes-kneel.md
- .changeset/silver-countries-kiss.md
- packages/qwik-city/src/runtime/src/router-outlet-component.tsx
- packages/qwik/src/core/qrl/qrl.public.ts
- packages/qwik/src/core/qrl/qrl.ts
It's not super minified, but it's better than before.
For example, qwik.dev had this in the sync funcs script tag:
```tsx
() => {
((window1, history1) => {
var _a3;
if (!window1._qcs && history1.scrollRestoration === "manual") {
window1._qcs = true;
const scrollState = (_a3 = history1.state) == null ? void 0 : _a3._qCityScroll;
if (scrollState) window1.scrollTo(scrollState.x, scrollState.y);
document.dispatchEvent(new Event("qcinit"));
}
})(window, history)})
```
which was copied verbatim with spacing.
Now it will be without spaces.
> fix(sync$): serialize "minified" function

- packages/docs/src/entry.ssr.tsx
- packages/docs/src/root.tsx
The docs site wasn't updated when I made the first modulepreload experiment PR. So we have to run the experiment until October ~20 to be sure we have all the data running on pagespeed for 28 days.
> chore: update modulepreload experiment date

- packages/insights/.gitignore
- packages/insights/package.json
- packages/insights/src/db/query-helpers.ts
- packages/insights/src/db/query.ts
- packages/insights/src/routes/api/v1/[publicApiKey]/post/index.tsx
- packages/qwik-labs/package.json
- packages/qwik-labs/src/insights/index.tsx
- packages/qwik-labs/vite.config.mts
- pnpm-lock.yaml
zod was being built into the library, and the script wasn't minified and was actually broken because fn.toString() didn't include a helper that rollup injected
> fix(insights): minify ping script and externalize zod

- packages/docs/src/routes/docs/(qwik)/advanced/eslint/index.mdx
- packages/docs/src/routes/docs/(qwikcity)/server$/index.mdx
Fixes https://qwik.dev/docs/server$/#server  and  https://qwik.dev/docs/advanced/eslint/#unused-server
as described in the documentation:
When defining and calling `server$()` inside an `onClick$¡, be aware that this can lead to potential errors. To avoid them, make sure the handlers have `$¡ wrapped around them.
Don't do this
`onClick$={() => server$(() => // some server code!)}`
Do this
`onClick$={$(() => server$(() => // some server code!))}`
> docs: fix server$ example

- packages/docs/src/routes/docs/(qwik)/components/state/index.mdx
- packages/qwik/src/core/shared/shared-serialization.ts
- packages/qwik/src/core/tests/use-computed.spec.tsx
This makes sure that noSerialize values get rebuilt on the client at first use
> fix(ComputedSignal): noSerialize marks invalid for serdes

- .changeset/lazy-worms-attack.md
- .changeset/real-garlics-argue.md
- packages/qwik-city/src/buildtime/markdown/mdx.ts
- packages/qwik-city/src/buildtime/markdown/mdx.unit.ts
This PR has fixes for two things:
1. I noticed that the link scripts in the `package.json` were broken since the relative path was incorrect.
2. A fix for https://github.com/QwikDev/qwik/issues/6844.
> fix: correctly handle MDX layouts

- packages/qwik/src/core/shared/shared-serialization.ts
- starters/apps/e2e/src/components/computed/computed.tsx
- starters/e2e/e2e.computed.e2e.ts
System throws an error with qrl promise when the qrl is not resolved. To prevent that we should early resolve computed qrl while computed deserialization
> fix(signals): should early resolve computed qrl

- packages/docs/src/components/docsearch/results-screen.tsx
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/tests/component.spec.tsx
Fix component rendering by marking a host as not deleted if we schedule it to rerender. We could mark it before during cleanup, but now we found it and want to reuse it, so we need to mark it as not deleted.
> fix(render): fix component rendering

- packages/docs/src/routes/docs/(qwik)/concepts/think-qwik/index.mdx
- Docs
The original text wrongly implied that Qwik's tools increase JavaScript, which goes against what Qwik is all about. I reworded it to clarify that the issue applies to general tools, not Qwik's.
> docs: clarify wording

- packages/qwik/src/core/shared/shared-serialization.ts
- packages/qwik/src/qwikloader.ts
- starters/apps/e2e/src/components/computed/computed.tsx
- starters/e2e/e2e.computed.e2e.ts
When we are executing the `computedIfNeeded` function we can throw a promise (a qrl) if the qrl is not resolved, then we should retry execution of it.
This is a workaround until a complex fix will be implemented.
> fix(computed): retry qrl execution on throwing promise

- .changeset/config.json
- .changeset/rotten-weeks-tickle.md
- packages/qwik/src/core/shared/utils/promises.ts
- packages/qwik/src/core/signal/signal.ts
- packages/qwik/src/core/tests/use-computed.spec.tsx
> fix: should not trigger effects if computed value is not changed

- packages/qwik/src/core/tests/projection.spec.tsx
- packages/qwik/src/server/ssr-container.ts
Allow promises in the q:template while emitting unclaimed projections.
fixes #7000
> fix: allow promises in the q:template

- packages/docs/src/routes/docs/cookbook/debouncer/index.mdx
- Docs
- Replaces `any` type with inferred type. `debounce` now knows its type arguments and knows that it loses its return type.
- Replaces unnecessary `Number` conversion.
- `setTimeout` incorrectly returns `NodeJS.Timeout`, because TypeScript assumes it is running on a Node server; but `window.setTimeout` correctly returns `number`, because TypeScript infers it is running in the browser.
> Update debouncer type accuracy

- package.json
- packages/qwik/package.json
- scripts/submodule-cli.ts
To have the bin `qwik` working during installs, the file it points to from package.json must exist.
We already had a perpetual script in the qwik package but it got ignored at some point.
> fix(build): always have qwik binary available

- packages/qwik/src/optimizer/core/src/lib.rs
- packages/qwik/src/optimizer/core/src/parse.rs
- packages/qwik/src/optimizer/core/src/rename_imports.rs
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__rename_builder_io.snap
- packages/qwik/src/optimizer/core/src/test.rs
The vite aliases don't help because they happen after the transform, and Qwik needs to know exactly what's importing what.
> fix(core): rename old packages during transform

- .changeset/gentle-adults-compare.md
- packages/qwik/src/core/render/jsx/types/jsx-generated.ts
> fix(jsx): textarea type should accept text children

- .changeset/ninety-planets-search.md
- packages/qwik-labs/package.json
- packages/qwik-react/package.json
- packages/qwik/package.json
`vite` is now a peer dependency of `qwik`, `qwik-city`, `qwik-react` and `qwik-labs`, so that there can be no duplicate imports. This should not have consequences, since all apps also directly depend on `vite`.
- Infra
> added vite as peer to qwik-react and qwik-labs

- packages/qwik/src/core/use/use-task.ts
- Infra
When devs see warnings, they aren't used to see the word `Error` in it. 
So I removed it so devs won't think that they're app is broken or something
> reduce the fear level of the warning of useComputed async

- .changeset/rude-camels-hang.md
- packages/eslint-plugin-qwik/package.json
- pnpm-lock.yaml
> fix(eslint-plugin): specify the runtime dependency

- .changeset/moaning-master-chief.md
- packages/qwik-city/src/middleware/request-handler/request-event.ts
- Bug (kinda)
Currently, it is impossible to define a Cache-Control header using the `request.cacheControl` on any method that takes a request event other than success (HTTP 200). Looks like qwik-city, internally, deletes whatever is defined.
I am not entirely sure about the `error()` and `fail()` handlers, which are also forcing the removal of the header. I'd say that engineers could potentially decide to cache 404s, for example, and the framework should not enforce this kind of rules. However, I am not sure about this premise for 4xx or 5xx.
Redirects (HTTP 301, HTTP 302, HTTP 307, HTTP 308, at least) should be totally configurable by software engineers.
> fix: solve issue with Cache-Control header deletion

- packages/qwik/src/core/shared/component.public.ts
- packages/qwik/src/core/tests/inline-component.spec.tsx
This PR fixes calling a component as a function by returning a jsxSplit with correct props inside component
> fix: calling component as a function

- .changeset/config.json
- .github/workflows/ci.yml
- CONTRIBUTING.md
- Infra
We want to make sure that we release only versions that have been tested by our "alpha testers" team.
Currently, releasing from `main` is problematic, because PRs might get merged between the time we got a 👍 from the testers but before we release, meaing bugs can creep in. 
Having a pure `upcoming` release branch, where everything is being tested from allows us to release fully tested and more stable versions. 
The new flow will be: 
1. PRs are merged into `main`
2. `main` is periodically merged into `upcoming`
3. A new `Versions` PR is getting created automatically by changesets against the `upcoming` branch (instead of `main`).
4. When we are ready to cut a release, we ask the alpha testers to test the `pkg.pr.new` version from the `upcoming` branch.
5. After we get the approval …
> Changed release from `main` to `upcoming` branch

- packages/docs/src/routes/docs/integrations/image-optimization/index.mdx
Typo in image path example (double ?): `'[IMAGE_PATH]??w=24&h=24&jsx';` -> `'[IMAGE_PATH]?w=24&h=24&jsx';`
> docs: typo in image path example

- .changeset/proud-carrots-grab.md
- packages/qwik/src/core/state/store.ts
- Bug
the code should be self explanatory
add the missing store subscription for `prop in store` cases
the fix is tested in local dev env. I haven't contributed to qwik for some time, so please notify me if this PR needs improvement, I'll change accordingly
> fix store subscription for `prop in store` cases

- .changeset/three-donkeys-admire.md
- packages/qwik-city/src/runtime/src/server-functions.ts
- Bug
Server functions only throw errors in the browser with 500 status code errors.
For errors that are greater than 500, such as a 504, the server functions will return the text which means you are unable to correctly catch and handle the errors.
> fix: server$ not throwing for errors above 500

- packages/qwik/src/core/shared/qrl/qrl-class.ts
- packages/qwik/src/core/shared/shared-serialization.ts
- packages/qwik/src/core/signal/flags.ts
- packages/qwik/src/core/signal/signal.ts
- Infra
This PR should make the complicated code of `createQrl` a little bit easier to follow.
Renamed the `invokeFn` as it doesn't really mean what you think it means... 
and sorted the functions based on their order of their invocation, so it'll reduce the "scroll fatigue" caused by scrolling down and up multiple times just in order to follow the complicated timeline as if it was the movie pulp fiction o something... 😅
> cleaned the `createQrl` code

- starters/apps/base/src/entry.preview.tsx
I created a new app with `create qwik@2.0.0-alpha.1` and I found a missing import
> chore(v2 starter): add missing import

- .changeset/twenty-paws-argue.md
- packages/qwik/src/qwikloader.ts
- starters/apps/e2e/src/components/events/events.tsx
- starters/e2e/e2e.events.spec.ts
- Bug
This fixes the implementation of `stoppropagation:`
> fix stoppropagation

- packages/docs/src/routes/docs/(qwik)/components/events/index.mdx
> fixed typo in events doc

- packages/docs/src/routes/docs/cookbook/theme-management/index.mdx
- Docs
Previous version of this set the theme to light if no theme was found in local storage. Updated version checks for preferences and sets accordingly.
That is: if nothing saved in local storage and prefers dark mode, local storage is set to dark etc....
-  [x] Tested locally and seems to work just fine on a new qwik app.
> chore: improve theme-management cookbook

- .github/workflows/ci.yml
- Infra
Currently the npm tag `latest` is stuck on `alpha.0`, this temporary fix should make sure it always sets the latest release to `latest` as well.
We should delete / change this once V2 is officially released.
> fix v2 `latest` tag

- packages/insights/drizzle/0017_pink_maestro.sql
- packages/insights/drizzle/0018_heavy_toad.sql
- packages/insights/drizzle/0019_known_satana.sql
- packages/insights/drizzle/meta/0017_snapshot.json
- packages/insights/drizzle/meta/0018_snapshot.json
- packages/insights/drizzle/meta/0019_snapshot.json
- packages/insights/drizzle/meta/_journal.json
- packages/insights/src/db/schema.ts
> chore(insights): add more indexes to spped up DB

- packages/docs/src/routes/docs/cookbook/nav-link/index.mdx
- Docs
activeClass is an optional prop (string)
If isActive is true but no activeClass provided "undefined" would be passed in as a class
if isActive is true and activeClass is true (non-empty string) then add activeClass to link
> docs: improve NavLink cookbook

- .changeset/friendly-gorillas-walk.md
- packages/qwik-router/package.json
- packages/qwik/package.json
- Bug
Actually fixes #7130
Now migrating from V1 with `moduleResolution: "node"` in the `tscofnig.json` won't break typescript.
> fix migrating from V1 with module resolution "node'

- .changeset/twenty-goats-flow.md
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/tests/projection.spec.tsx
Before we ignored children if they were equal to null or undefined. We should only ignore them if we don't have old projection slots and the children are null
closes #7147
> fix: replacing projection content with null or undefined

- .changeset/thirty-ravens-draw.md
- packages/qwik/src/core/tests/use-store.spec.tsx
- packages/qwik/src/optimizer/core/src/props_destructuring.rs
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_colon_props2.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_colon_props3.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_block_stmt.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_block_stmt2.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__destructure_args_inline_cmp_expr_stmt.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_8.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_lightweight_functional.snap
- packages/qwik/src/optimizer/core/src/test.rs
Convert destructured props for an inline component to single prop
> fix: destructured props for inline components

- .changeset/sour-beans-hope.md
- packages/docs/src/routes/docs/(qwikcity)/guides/capacitor/index.mdx
- packages/docs/src/routes/docs/menu.md
> mobile guide

- .changeset/serious-pandas-joke.md
- packages/docs/src/routes/docs/integrations/turso/index.mdx
- starters/features/turso/src/utils/turso.ts
- Bug
- Docs
Starting with a fresh turso integration, while working with a local sqlite db file the following error occured:
```
Internal server error: URL_SCHEME_NOT_SUPPORTED: The client that uses Web standard APIs supports only "libsql:", "wss:", "ws:", "https:" and "http:" URLs, got "file:". For more information, please read https://github.com/libsql/libsql-client-ts#supported-urls
```
Looking at the corresponding section in the [turso docs](https://docs.turso.tech/sdk/ts/reference#local-development) shows the import of `createClient` must not be from `@libsql/client/web` since then it does not support file based urls.
This pr updates the import inside the turso starter and expands the note inside the docs explaining the issue.
> fix(starters): update turso createClient import, update turso docs note

- packages/docs/public/_redirects
https://qwik.dev/docs/env-variables/#environment-variables
this point to 404 
add an entry in the _redirect 
Docs fix env redirect
> chore: update _redirect to remove a 404

- packages/docs/src/routes/docs/(qwikcity)/advanced/complex-forms/index.mdx
Grammatical error correction in doc.
- Bug
- Infra
> docs: grammatical error correction

- .changeset/forty-garlics-train.md
- .changeset/friendly-sloths-return.md
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/shared/shared-serialization.ts
- packages/qwik/src/core/signal/signal-subscriber.ts
- packages/qwik/src/core/signal/signal.ts
- packages/qwik/src/core/signal/store.ts
- packages/qwik/src/core/tests/projection.spec.tsx
- packages/qwik/src/core/tests/use-resource.spec.tsx
- packages/qwik/src/core/tests/use-store.spec.tsx
- packages/qwik/src/core/tests/use-styles-scoped.spec.tsx
- packages/qwik/src/core/use/use-resource.ts
- packages/qwik/src/core/use/use-task.ts
- packages/qwik/src/server/ssr-container.ts
- Cleanup store effects on VNode destory etc.
- Serialize all projection siblings. Previously we only added the `SERIALIZE` flag, which is a bug, because we did not serialize component props that were siblings of the projection
- Run resource functions within invoke context
> fix: store effects cleanup & projection siblings serialization

- packages/docs/src/routes/docs/(qwik)/getting-started/index.mdx
Docs
The link to zod validation is incorrect
> docs: fix bad link to zod validation

- .changeset/purple-melons-invent.md
- packages/qwik/src/core/tests/use-context.spec.tsx
- packages/qwik/src/server/ssr-node.ts
Fix a problem with slot prop for ssr. Empty arrays should be considered as empty content.
> fix: find correct context after rendering empty array

- .changeset/long-jobs-whisper.md
- packages/qwik-city/src/buildtime/markdown/mdx.ts
- packages/qwik-city/src/buildtime/markdown/mdx.unit.ts
- Bug
For some reason,  the Qwik UI docs didn't render with version 1.10.0 because they are based on mdx.
Apparently #6845 broke it.
But this seems to fix it.
Couldn't setup a breaking test for this one (it happens only in dev mode, and the CLI e2e passed with my attempt to break it). 
It also seems like this is solved in V2, so this will be a quick (qwik) fix until V2 is released and then we'll dig into it more.
> fix mdx not rendering

- .changeset/cold-dogs-hunt.md
- packages/qwik/src/optimizer/src/plugins/image-size-runtime.html
`computedStyleMap` is not supported on Firefox
> fix: remove usage of computedStyleMap

- packages/docs/src/routes/docs/(qwik)/components/styles/index.mdx
- Docs 
Hi Everyone.
Little bit of background on this PR.
In Discord the question was raised "what does the star icon represent when inspecting the DOM?"
See link: [https://discord.com/channels/842438759945601056/1326121240074780722](https://discord.com/channels/842438759945601056/1326121240074780722)
This emoji is in the process of being updated from start to a lightening bolt.
See PR: #7248 
I have tried to update the docs to futureproof this change by not referencing the specific emoji.
But may need to update this after the release in which the icon has changed.
Also as a note: there is a star reference in the docs that will need to be updated after the icon has changed.
Quote:
".list.⭐️8vzca0-0 > *:nth-child(3)"
Have a great day everyone.
> docs: clarify use of emojis in useStylesScoped$

- .changeset/shaggy-poems-appear.md
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/client/vnode.unit.tsx
- packages/qwik/src/core/shared/error/error.ts
- packages/qwik/src/core/shared/scheduler-document-position.spec.ts
- packages/qwik/src/core/shared/scheduler-document-position.ts
- packages/qwik/src/core/shared/scheduler.ts
Log a warning instead of throwing an error for server host mismatch error
> feat: log a warning instead of throwing an error for server host mismatch error

- packages/qwik/src/core/state/store.ts
- starters/apps/qwikcity-test/src/routes/issue7254/index.tsx
- starters/e2e/qwikcity/resource.spec.ts
Fix issue: https://github.com/QwikDev/qwik/issues/7254
https://github.com/user-attachments/assets/80ff265a-0cbf-49b7-850c-8adea4bcbd81
> fix: :zap: Fix proxy

- .changeset/breezy-lizards-dress.md
- packages/qwik-city/src/buildtime/markdown/mdx.ts
- packages/qwik-city/src/buildtime/markdown/mdx.unit.ts
- Bug
This PR fixes MDX content to support passing props, including the `components` prop that allows using custom components within MDX content.
> fix(mdx): support passing props to MDX content

- .changeset/bright-experts-sip.md
- .github/workflows/ci.yml
- packages/docs/src/routes/docs/integrations/tailwind/index.mdx
- starters/features/tailwind/.vscode/settings.json
- starters/features/tailwind/package.json
- starters/features/tailwind/postcss.config.cjs
- starters/features/tailwind/src/global.css
- starters/features/tailwind/tailwind.config.js
> tailwind v4

- .changeset/sharp-apples-relate.md
- packages/qwik/src/core/shared/shared-serialization.ts
- packages/qwik/src/core/use/use-core.ts
- starters/apps/qwikrouter-test/src/routes/issue7260/index.tsx
- starters/e2e/qwikrouter/server.e2e.ts
Fix issue #7260 skipping the vNode serialization from server$
> Fix vNode serialization issue on server$

- .changeset/six-games-float.md
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_not_wrap_fn.snap
- packages/qwik/src/optimizer/core/src/test.rs
- packages/qwik/src/optimizer/core/src/transform.rs
Do not convert attribute value function call to _fnSignal. This way it will create component-level subscription like in v1 and should work after resuming the application
> fix: don't wrap and serialize functions that are attribute values

- .changeset/tidy-years-smile.md
- packages/qwik/src/server/prefetch-utils.ts
- Bug
A bug was accidently which caused the QwikCity service worker not to fetch some of the bundles for event handler and that caused latency on user interactions.
This PR  fixes it and should help improving the speed of Qwik.
> fix: qwikcity sw SSR prefetching

- .changeset/warm-camels-remain.md
- packages/qwik/package.json
- packages/qwik/public.d.ts
Expose `_serialize`, `_deserialize` & `_getContextElement` to make the `createWorker$` from RFC works with v2
Expose `OnVisibleTaskOptions` because it was missing
> Expose missing types & fix package.json internal expose uri

- scripts/binding-platform.ts
this makes sure that recent optimizer changes are used when not building the optimizer
> fix(core dev): copy optimizer from CI build if dev

- .changeset/maiieul-manual-changeset.md
- packages/docs/src/routes/docs/(qwik)/advanced/vite/index.mdx
- packages/qwik/src/optimizer/src/plugins/rollup.ts
To be able to debug production-only bugs more easily, instead of checking each `q-[hash]` manually to figure out what code it refers to.
> feat(qwikVite): show build/[name].js output in preview with debug mode

- packages/docs/src/routes/docs/integrations/authjs/index.mdx
- Docs
Ciao Gio (it's usually Gio that reviews these)
As per discussion with Ian in Discord.
There are other references to `redirectTo` on this page.
But from my testing this morning the below is still valid,
So not every refence to `redirectTo` needed to be adjusted.
```html
<Form action={signOut}>
<input type="hidden" name="redirectTo" value="/signedout" />
<button>Sign Out</button>
</Form>
```
Link to Discord Chat below:
[https://discord.com/channels/842438759945601056/1334857616295333909](https://discord.com/channels/842438759945601056/1334857616295333909)
- [x ] I performed a self-review of my own code
- [x ] I made corresponding changes to the Qwik docs
> docs: improve Auth.js integration page

- .github/workflows/ci.yml
- package.json
this fixes the problems caused by https://github.com/nodejs/corepack/issues/612
We no longer rely on corepack to get the correct pnpm version, and we hope that `pnpm/action-setup@v4` will do the right thing.
> fix(ci): make pnpm work again

- .changeset/long-shirts-thank.md
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/client/vnode-namespace.ts
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/tests/render-namespace.spec.tsx
In some cases vNodes didn't have the correct flags for the namespace
> fix: create svg nested children with correct namespace

- packages/qwik/src/cli/migrate-v2/run-migration.ts
- packages/qwik/src/cli/migrate-v2/update-dependencies.ts
- packages/qwik/src/cli/types.ts
> fix(qwik): handle additional use cases in migrate-v2

- starters/adapters/fastify/src/plugins/fastify-qwik.ts
Currently, Fastify/Qwik can not parse body on `onPost` requests due to the following exception:
`SyntaxError: Unexpected end of JSON input`
By removing the default content type parsers seems to let Fastify+Qwik handle the request body as expected.
> fix: Remove all default content type fastify parsers

- .changeset/maiieul-manual-changeset-2.md
- packages/qwik/src/optimizer/src/plugins/plugin.ts
> fix(rollup): improve manualChunks logic to minimize over-prefetching

- .changeset/five-shoes-deny.md
- .changeset/tasty-penguins-ring.md
- packages/qwik/src/core/client/dom-container.ts
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/client/vnode.unit.tsx
- packages/qwik/src/core/shared/utils/markers.ts
- packages/qwik/src/core/shared/utils/prop.ts
- packages/qwik/src/core/shared/vnode-data-types.ts
- packages/qwik/src/core/ssr/ssr-render-jsx.ts
- packages/qwik/src/core/tests/projection.spec.tsx
- packages/qwik/src/server/qwik-copy.ts
- packages/qwik/src/server/ssr-container.ts
- packages/qwik/src/testing/element-fixture.ts
Qwik reuses content projections. Imagine an edge case:
```tsx
const Child = component$(() => {
return <h1>Some title</h1>;
});
const Parent = component$((props) => {
{props.toggle && <Slot />}
{!props.toggle && (
<>
<Slot />
</>
)}
});
const Cmp = component$(() => {
const toggle = useSignal(true);
return <>
<button onClick$={() => toggle.value = !toggle.value}>toggle</button>
<Parent toggle={toggle.value}>
<Child />
</Parent>
</>;
});
```
We render `Child` inside `Parent`, but `Parent` has multiple default slots. At the time of button click the node is already projected, but VIRTUAL structure has been changed. This means real DOM element parent is the same for both projections. In next steps we will insert the projection at the end of the DOM parent. However we will find existing …
> fix: reusing the same projection

- .changeset/mean-parents-buy.md
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/tests/inline-component.spec.tsx
Replacing an inline component with component$ didn't always work, because keys are unique only for single file. If the key was the same at the same place for diferent component types (and different components) the component was not rerendered
> fix: replace inline component with component$ with the same key

- packages/qwik/src/optimizer/src/plugins/plugin.ts
- Bug
- Docs
- Actually removed manual chunks for core and qwik-city. After further analysis, I think it's more robust to let rollup do it's job here. For example it bundles the `isServer` from @builder.io/build properly on its own.
- Only return sanitizedPath for `.(tsx|jsx)` is enough to prevent over-prefetching on qwik-ui.
- We could simply return `id` instead of sanitizedPath, but keeping it for convenience for now for `debug: true`. I'll see in a follow-up PR if I can remove that too.
> fix(docs repl): let rollup handle more chunks

- package.json
- packages/docs/check-qwik-build.ts
- packages/docs/package.json
- packages/eslint-plugin-qwik/qwik.unit.ts
- Bug
Hey everyone,
Unfortunately the below PR did not fully fix the issue on Windows.
[https://github.com/QwikDev/qwik/pull/7301](https://github.com/QwikDev/qwik/pull/7301)
There were 2 underlying issues.
1) the cd to packages/docs in the root package.json did not work. packages/docs the "/" did not work on windows. 
-> moved to pnpm -c
2) in file: check-qwik-build.ts the dirname variable on windows began with a "/" (forward slash)
This would cause the check to fail on Windows as the directory was incorrect -> this has been resolved
3) revert the dev script in packages/docs package.json
The use of concurrently is no longer needed for Windows support as this has been resolved in step 2 above.
This has been tested on the below Operating Systems:
System:
OS: Windows 11 10.0.26100
OS: Linux …
> Fix: Windows Docs.dev script

- .changeset/proud-kangaroos-boil.md
- packages/qwik/src/core/client/vnode.ts
We should always call the `toLowerCase` fn on node names, because they are always uppercased
> fix: finding vnodes on interaction

- .changeset/pole-comfort-active.md
- packages/docs/src/routes/docs/integrations/tailwind-v3/index.mdx
- packages/docs/src/routes/docs/integrations/tailwind/index.mdx
- starters/README.md
- starters/features/tailwind-v3/.vscode/settings.json
- starters/features/tailwind-v3/package.json
- starters/features/tailwind-v3/postcss.config.cjs
- starters/features/tailwind-v3/src/global.css
- starters/features/tailwind-v3/tailwind.config.js
- starters/features/tailwind/package.json
Some projects might not be able to use tailwind v4 yet. qwik-ui/styled hasn't been updated for tailwind v4 yet. I think even after updating to tailwind v4, we should keep a qwik-ui subdomain live for tailwind v3 for some time.
> feat(cli): add ability to keep using tailwind v3

- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/optimizer/src/plugins/vite.unit.ts
- Bug
- Infra
Because manualChunks should only be responsible for telling rollup to not bundle certain chunks together, not to specifically name certain chunks. Naming through the outputOptions ensures we don't interfere with Rollup's bundling unnecessarily.
> refactor(rollup): move build mode + debug:true chunk names logic out of manualChunks

- .changeset/giant-lobsters-sip.md
- packages/eslint-plugin-qwik/README.md
- packages/eslint-plugin-qwik/index.ts
- packages/eslint-plugin-qwik/package.json
- enhancement
- Bug
This PR fixes the `ConfigError: Config (unnamed): Key "plugins": Key "qwik": Expected an object.` error when using ESLint 9 flat configs with `qwikEslint9Plugin`. The issue was related to circular references in the plugin configuration.
Key changes:
- Fixed plugin configuration using getter functions following [the official typescript-eslint pattern](https://github.com/typescript-eslint/examples/blob/2d41579035a27a048f105cab2b0780a4ff52f2cd/packages/eslint-plugin-example-typed-linting/src/index.ts)
- Added proper TypeScript typings with `TSESLint` types
- Enhanced type safety with `as const satisfies` assertions
- Significantly expanded documentation with installation instructions, configuration examples, and comprehensive rule documentation
> fix(eslint-plugin-qwik): fix ESLint 9 compatibility, enhance README 

- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/client/vnode-diff.unit.tsx
- packages/qwik/src/core/tests/component.spec.tsx
- packages/qwik/src/testing/vdom-diff.unit-util.ts
- starters/apps/e2e/src/components/attributes/attributes.tsx
- starters/apps/e2e/src/components/context/context.tsx
- starters/e2e/e2e.attributes.e2e.ts
- starters/e2e/e2e.context.e2e.ts
Remove vSiblings logic, they are no longer needed. Replace them with a Map for keyed nodes and with an array for non-keyed nodes to speed up diffing
> chore: refactor vSiblings

- package.json
- scripts/build-clean.ts
- Bug
Hey everyeone:
Another PR just to improve the compatibility of the package.json for Windows.
This has been tested on the below Operating Systems:
OS: Windows 11 10.0.26100
OS: Linux 6.8 Linux Mint 22.1 (Xia)
Summary:
1) build.clean: 
this was moved to a tsx approach `rm rf` doesn't work on Windows OS.
this requires a `pnpm install` but should be fine as a build would also be required.
2) docs.preview: 
the `cd packages/docs && pnpm preview` style commands do not work on Windows.
moved to `PNPM -C` for cross platform support.
As a note:
`link.dist` &&`"link.dist.yarn":` &&  `"link.dist.npm":` currently do not work cross platform,
But they do not appear to be frequently needed. 
I think this is the last one of these PR's for a while as visual check confirms all other commands should …
> chore (package.json) :improve windows support

- packages/docs/src/routes/api/qwik-testing/api.json
- packages/docs/src/routes/api/qwik-testing/index.md
- packages/qwik/src/core/client/process-vnode-data.unit.tsx
- packages/qwik/src/core/client/vnode-diff.unit.tsx
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/tests/attributes.spec.tsx
- packages/qwik/src/core/tests/component.spec.tsx
- packages/qwik/src/core/tests/projection.spec.tsx
- packages/qwik/src/core/tests/render-namespace.spec.tsx
- packages/qwik/src/core/tests/ssr-render.spec.tsx
- packages/qwik/src/testing/api.md
- packages/qwik/src/testing/html.ts
- packages/qwik/src/testing/jsx.ts
- packages/qwik/src/testing/vdom-diff.unit-util.ts
`toMatchDOM` matcher did not work correctly for comparing attributes. Refactored all matcher code and replaced it with string comparison done by vitest. Now the messages are nicer.
> chore: toMatchDOM fix and refactor

- .changeset/wicked-pets-chew.md
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/client/vnode.unit.tsx
After ssr it, we get ie. "0123" as one text node, then we materialize 4 fragements with one letter in each.
We should get:
```tsx
<>0</><>1</><>2</><>3</>
```
but this also means that every vnode right after materializing will point to the same shared textnode "0123". Of course we need to split it to separate text nodes, and this should be done at time of removing. In this case we did it to late, when virtual parent didn't have connections to siblings.
> fix: removing text node from shared text node

- .changeset/fair-cameras-boil.md
- packages/qwik/src/core/api.md
- packages/qwik/src/core/client/dom-container.ts
- packages/qwik/src/core/client/types.ts
- packages/qwik/src/core/shared/shared-container.ts
- packages/qwik/src/core/shared/types.ts
- packages/qwik/src/core/ssr/ssr-types.ts
- packages/qwik/src/core/tests/use-id.spec.tsx
- packages/qwik/src/core/use/use-id.ts
- packages/qwik/src/server/prefetch-implementation.ts
- packages/qwik/src/server/ssr-container.ts
Use build base for client side generated ID and convert first char to letter if it is statring from number, because CSS selectors can't start with number
> fix: change client side generated ID to start with build base

- .changeset/tall-paint-help.md
- packages/qwik-city/src/middleware/request-handler/request-event.ts
- Bug
This is what qwik-city/qwik-router consumers can perform:
However the `Response` object is lost because on the `send` event, when performing any kind of redirect (code > 300 && < 400), qwik-city is returning a new RedirectMessage instead.
> fix: Write Response object in the send request event even on redirects

- .changeset/cyan-bottles-speak.md
- .changeset/tame-glasses-explain.md
- packages/qwik/src/core/client/dom-container.ts
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/client/vnode.unit.tsx
- packages/qwik/src/core/tests/error-handling.spec.tsx
- create error overlay correctly using vnode transformations
- fix inserting node edge case and prevent referencing vnode to self
- add a lot of `insertBefore` tests
> fix: inserting new node edge case and creating error overlay

- packages/docs/src/routes/(ecosystem)/ecosystem.css
- packages/docs/src/routes/(ecosystem)/ecosystem/index.tsx
- Styles - workaround
Ciao Gio
The Grid on the ecosystem page has broken for desktop view
https://qwik.dev/ecosystem/
This seems to be a tailwindcss v4.0.12 issue
Issue seems to be that the css  is not valid due to the `,` separator in the below image
Current page layout:
I did add a comment in the CSS hoping someone will see it in the future.
- [x ] I performed a self-review of my own code
> docs: update ecosystem style

- packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx
A misspelling. routeLoader$s is the correct plural form of routeLoader$.
- [*] I made corresponding changes to the Qwik docs
> docs: improve route-loader page

- packages/docs/src/components/docsearch/doc-search-modal.tsx
-docs
Ciao Gio,
`Bug: when you go to qwik.dev and then CLICK search and type "usesignal" and then CLICK on the result, then scrolling doesn't work any more`
This is originating from Qwik UI Modal in Single Page Applications
Package below is adding the overflow hidden - but not removing it, after clicking the link.
`name: body-scroll-lock-upgrade`
The links in the results  are `<Link>` (from Qwik) and not `<a> `
So this will just manually remove the overflow hidden from the body for now.
I'll have a look into fixing it within Qwik UI,  but just adding this pull request so that the search works as expected for now.
- [x ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x ] I performed a self-review of my own code
> docs:force remove body overflow-hidden when search closes

- packages/docs/src/routes/docs/(qwikcity)/guides/qwik-nutshell/index.mdx
missing expression in an if condition
- [* ] I made corresponding changes to the Qwik docs
> docs: fix up typo

- .changeset/kind-bees-grin.md
- packages/docs/src/routes/docs/cookbook/nav-link/index.mdx
current code results in unexpected behavior when `props.class` was an array. Updated to:
`class={[props.class, isActive && activeClass ? activeClass : ""]}`
ensuring proper class concatenation and maintaining Tailwind's expected behavior.
This fixes styling inconsistencies and improves component reliability.
> docs(cookbook): update class handling

- packages/docs/src/routes/docs/(qwikcity)/guides/bundle/index.mdx
fixed 3 typos
Fixed some typos.
- [* ] I made corresponding changes to the Qwik docs
> docs: fix up some typos

- packages/docs/src/repl/repl-output-modules.tsx
For some reason TS fails on this perfectly valid code
```
packages/docs/src/repl/repl-output-modules.tsx:58:44 - error TS18048: 'o.shorten' is possibly 'undefined'.
58                   <button onClick$={() => (o.shorten.value = !o.shorten.value)}>
~~~~~~~~~
packages/docs/src/repl/repl-output-modules.tsx:58:63 - error TS18048: 'o.shorten' is possibly 'undefined'.
58                   <button onClick$={() => (o.shorten.value = !o.shorten.value)}>
~~~~~~~~~
Found 2 errors in the same file, starting at: packages/docs/src/repl/repl-output-modules.tsx:58
❌  Error: Command failed with exit code 2: tsc -p packages/docs/tsconfig.json
at makeError (file:///home/wmertens/Projects/qwik/node_modules/.pnpm/execa@8.0.1/node_modules/execa/lib/error.js:60:11)
at handlePromise …
```
> fix: build.full fails because of TS confusion

- packages/docs/src/entry.ssr.tsx
- packages/qwik/package.json
- packages/qwik/src/core/preloader/bundle-graph.ts
- packages/qwik/src/core/preloader/queue.ts
- packages/qwik/src/core/preloader/types.ts
- packages/qwik/src/server/prefetch-strategy.ts
- pnpm-lock.yaml
- scripts/submodule-preloader.ts
- require rollup with facade fix
- fix preloader minification
- when 100% sure add unlimited preload links and have the browser figure it out
- for docs, allow tweaking the preloader with query parameters. They are the same as in opts.prefetchStrategy.implementation, but `debug` is `preloadDebug`. For example, https://wmertens-fixes.qwik-8nx.pages.dev/?preloadDebug&maxPreload=0 to turn off initial preload links
> chore: some small fixes

- .changeset/eighty-ligers-wink.md
- packages/qwik/src/core/tests/use-resource.spec.tsx
- packages/qwik/src/core/use/use-resource.ts
Handle initial undefined value for resource. The initial value is undefined because we delegate execution of it to the scheduler
> fix: correctly handle initial resource state

- .changeset/sweet-hairs-remember.md
- packages/qwik/src/core/shared/qrl/qrl-class.ts
- starters/apps/e2e/src/components/qrl/qrl.tsx
- starters/apps/e2e/src/root.tsx
- starters/e2e/e2e.qrl.e2e.ts
fixes #7442
feat(qrl): add e2e test and retry logic for QRL resolution
Add a new e2e test to verify QRL behavior without uncaught promises. Introduce retry logic for QRL resolution to handle potential promise retries, ensuring robustness in asynchronous operations.
- Bug
- Infra
> fix: retry computed qrl execution when not ready

- packages/qwik/src/core/shared/shared-serialization.ts
- packages/qwik/src/core/shared/shared-serialization.unit.ts
Wrapped signals are always based on other values
- if they dont change we dont need value
- if they change we recompute anyway
- if we call `.value` on it - just compute value
> chore: don't serialize wrapped signal value

- package.json
- packages/docs/package.json
- packages/docs/vite.config.ts
- packages/insights/package.json
- packages/insights/vite.config.ts
- packages/qwik-react/package.json
- packages/qwik-router/package.json
- packages/qwik/package.json
- packages/qwik/src/core/shared/shared-serialization.ts
- packages/qwik/src/core/shared/shared-serialization.unit.ts
- packages/qwik/src/core/tests/container.spec.tsx
- patches/@auth__qwik.patch
- pnpm-lock.yaml
this fails because of @auth/qwik importing server stuff on the client. Waiting for  https://github.com/nextauthjs/next-auth/pull/12723 to be merged
> chore: vite 6 (just upgrade, no env)

- packages/docs/scripts/showcase.js
lcp and inp are core web vitals but were missing.
the display already shows them, this makes it so the page info stores them.
> feat(showcase): add lcp,inp,ttfb

- .changeset/wet-bobcats-decide.md
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/tests/projection.spec.tsx
Fixing insertBefore function for inserting text nodes from shared text node
> fix: inflating text nodes from single shared text node

- packages/docs/src/routes/docs/(qwikcity)/re-exporting-loaders/index.mdx
> docs: fixed some typos

- .changeset/unlucky-olives-knock.md
- packages/docs/src/repl/worker/repl-request-handler.ts
- packages/qwik/src/core/client/types.ts
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/client/vnode-diff.unit.tsx
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/testing/platform.ts
Signal and promise virtual wrapper should not rerender, we should use the same one. Those wrappers don't have keys, so we should handle that case and check keys only for comparing actual fragments
> fix: signal wrapper should not rerender

- packages/docs/src/routes/docs/integrations/supabase/index.mdx
Grammar issue in the Supabase Integration doc page. Usage of 'this' with plural subject _values_. Should be 'these' instead.
> docs: fix grammar issue in Supabase Integration page

- .changeset/good-tables-rush.md
- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.md
- packages/qwik/src/core/core.api.md
- packages/qwik/src/core/index.ts
- packages/qwik/src/core/reactive-primitives/impl/computed-signal-impl.ts
- packages/qwik/src/core/shared/error/error.ts
- packages/qwik/src/core/ssr/ssr-render-jsx.ts
- packages/qwik/src/core/tests/use-computed.spec.tsx
- packages/qwik/src/core/use/use-computed.ts
This allows async operations in useComputed$ in a predictable way, so deprecating it in v1 is not necessary
> feat: allow async operations in useComputed$ hook

- starters/features/styled-vanilla-extract/package.json
- Bug
@wmertens 
Hey Wout 
Sorry for the tag, but I think this is your integration, so would appreciate your input here.
Small update:
seems `@vanilla-extract/vite-plugin` was missing from the devDependencies  which would cause `error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vanilla-extract/vite-plugin' ` 
I did link the CLI globally and just updating the devDependencies seems to have fixed the issue with the `/styled-flower/` route without any adjustments.
I'll leave it as a draft for now, let me know what you think.
- [ x] I performed a self-review of my own code
> fix(starters): styled vanilla extract update devDependncies

- .vscode/launch.json
- packages/qwik-city/src/buildtime/vite/get-route-imports.ts
- packages/qwik-city/src/buildtime/vite/get-route-imports.unit.ts
- Bug
Fixes the Link prefetching in preloader-test
bonus: adds a config in launch.json for one click debugging of preloader-test app
> fix(qwik): preloader & SPA Link nav

- packages/docs/src/components/sidebar/sidebar.tsx
- packages/docs/src/routes/community/layout.tsx
- packages/docs/src/routes/docs/layout.tsx
This reverts commit eea117b5b159f37de93034c47de931d48f79e01c.
Using a server$ blocks SPA Link nav and is visibly slow on 4G/3G
> Revert "perf(docs): only load sidebar paths once"

- packages/qwik/package.json
removed warnings due to improper order of default and min
> removed build warnings due to improper order of default and min

- .changeset/easy-boxes-win.md
- packages/create-qwik/src/helpers/logAppCreated.ts
- Bug
Currently, when creating a new qwik app using deno, the cli output shows 'next steps' as 'deno start'. This is incorrect, as deno needs the keyword 'task' by default. Corrected to 'deno task start'. This fixes bug #7520
> Create Qwik - Next Steps Deno Corrected - Bug #7520

- .changeset/thick-trams-pay.md
- packages/qwik-city/src/runtime/src/link-component.tsx
- packages/qwik-city/src/runtime/src/utils.ts
- packages/qwik-city/src/runtime/src/utils.unit.ts
- Bug
SPA would previously only prefetch the visible Link components on first page load. Subsequent navigation wouldn't prefetch and would therefore include a delay when clicked.
Also the first route to be loaded would never be prefetched again (e.g. /home -> /about wouldn't prefetch /home anymore, even though the routeLoaders might return updated data). This PR also fixes that.
> fix(qwik-city): SPA link prefetching on subsequent navigations

- packages/docs/public/_headers
order matters when matching multiple times
> fix(docs): correct cloudflare _headers

- packages/qwik/src/server/preload-impl.ts
I just learned that async scripts can be run earlier than their DOM order, so let's use that.
> perf(preloader): start preloading slightly earlier

- .changeset/witty-spoons-hug.md
- packages/qwik-city/src/runtime/src/link-component.tsx
- starters/apps/preloader-test/src/routes/counters/index.tsx
- starters/apps/preloader-test/src/routes/hidden/index.tsx
- starters/apps/preloader-test/src/routes/layout.tsx
- starters/apps/preloader-test/vite.config.ts
- Bug
the `onQVisible$` would only be fired once on first SPA load. Now it is fired on all subsequent route changes with the Link component.
> fix(qwik-city): Link onQVisible$ handling

- packages/docs/public/_headers
The semicolon is necessary :roll_eyes:
> chore(docs): fix cache control headers

- .changeset/fancy-eagles-guess.md
- e2e/qwik-cli-e2e/tests/serve.spec.ts
- e2e/qwik-cli-e2e/utils/index.ts
- e2e/qwik-cli-e2e/utils/setup.ts
- e2e/qwik-cli-e2e/vite.config.ts
- packages/qwik/src/cli/utils/utils.ts
- starters/apps/base/package.json
- starters/apps/library/package.json
- starters/apps/playground/src/routes/layout.tsx
The `globals` package was missing from the starters package.json, so that's fixed. 
Plus, we've added a cli test that prevents this type of bugs to re-appear later on
> Fix cli test

- .changeset/pretty-trees-check.md
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/tests/component.spec.tsx
If we've found the correct component and props are the same don't rerender it
> fix: ensure components are only rendered when necessary

- .changeset/olive-yaks-prove.md
- packages/qwik/src/core/reactive-primitives/internal-api.ts
- packages/qwik/src/core/shared/shared-serialization.unit.ts
- packages/qwik/src/core/tests/component.spec.tsx
- packages/qwik/src/core/tests/inline-component.spec.tsx
- packages/qwik/src/core/tests/projection.spec.tsx
- packages/qwik/src/core/tests/render-namespace.spec.tsx
- packages/qwik/src/core/tests/use-context.spec.tsx
- packages/qwik/src/core/tests/use-store.spec.tsx
Static/const objects should not be wrapped with WrappedSignal, they are static and cannot change
> fix: don't wrap static objects with signal

- packages/docs/src/routes/docs/cookbook/debouncer/index.mdx
This PR addresses a TypeScript error related to the use of readonly tuple types in conjunction with QRL.
Using a readonly tuple type A extends readonly unknown[] caused the following TypeScript diagnostic when invoking a QRL:
```txt
Argument of type '[...A]' is not assignable to parameter of type 'QrlArgs<(...args: A) => R>'. [2345]
```
This appears to be a type compatibility issue between the readonly tuple spread ([...A]) and the expected QrlArgs type in the QRL function signature. It's possible there's an edge case or mismatch in how QrlArgs<(...args: A) => R> resolves in the presence of readonly tuples, or perhaps recent TypeScript updates introduced stricter rules around readonly spreads.
The fix involves removing the readonly modifier from the generic …
> docs: fix up cookbook debounce typing

- packages/qwik/src/core/state/common.ts
the error is not helpful and it's nicer to just check and ignore
> chore(noSerialize): don't console when bad value

- .changeset/quick-moons-show.md
- packages/qwik/src/core/tests/container.spec.tsx
- packages/qwik/src/server/ssr-node.spec.ts
- packages/qwik/src/server/ssr-node.ts
- packages/qwik/src/server/vnode-data.ts
When SsrNode props were equal to EMPTY_PROPS object, then after setting prop they were not updated in vnode data.
> fix: correctly serialize vnode props in production mode

- .changeset/bright-cows-sell.md
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/tests/use-styles.spec.tsx
We should skip style node when it is before a text node
> fix: resuming a component using styles and a text node

- .changeset/cyan-walls-sing.md
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/shared/component-execution.ts
- packages/qwik/src/core/shared/scheduler.ts
- packages/qwik/src/core/tests/component.spec.tsx
- starters/apps/e2e/src/components/render/render.tsx
- starters/e2e/e2e.render.e2e.ts
- starters/e2e/e2e.signals.e2e.ts
- reuse the same instance of props when they changed. We need that, because some qrls could use props instance as a capture ref
- compare qrl hashes in chore comparator
> fix: reuse the same props instance when props are changing

- .changeset/fancy-nights-chew.md
- packages/qwik/src/optimizer/src/plugins/vite-error.ts
- Bug
Removes the backdrop-filter/blur when an error appears. In the event that you have multiple error overlays, it causes my Super Computer (M4 Max) to absolutely crawl. 
Closes https://github.com/QwikDev/qwik/issues/7675
> fix(optimizer): remove backdrop-filter from vite-error-overlay for perf

- packages/docs/src/routes/docs/(qwikcity)/middleware/index.mdx
set the "text/event-stream" for the content-type in the headers
added the headers configs required for the event streaming to work as expected
- [*] I made corresponding changes to the Qwik docs
> fixed an issue with the example for the "getWritableStream()" method

- .changeset/dark-experts-scream.md
- packages/qwik/src/optimizer/src/platform.ts
* Bug
When building a Qwik project using **Deno**, the process fails because the Vite `build.outDir` is resolved to an **absolute path** (`/dist`) rather than a relative one. This happens because the optimizer currently sets `cwd()` to `'/'` by default for platforms other than Node.js and Bun ([source](https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/optimizer/src/platform.ts#L26)).
This causes Deno to attempt writing to the system root directory, which typically fails with a permission error (`EACCES`). This does not occur in Node or Bun environments, where `cwd()` resolves to `process.cwd()`.
In this PR, we fix the issue by using `Deno.cwd()` as the default `cwd()` value when the runtime environment is Deno.
It’s also worth noting that this `cwd()` is used to compute the …
> 🐛 fix(#7697): use correct working directory for Deno environment

- .changeset/better-shrimps-sin.md
- packages/qwik-router/src/runtime/src/spa-init.ts
- packages/qwik/src/core/tests/render-api.spec.tsx
- packages/qwik/src/server/ssr-container.ts
For some reason sometimes addEventListener was calling qwik-loader function instead of native one
> fix: adding popstate and scroll event for SPA navigation

- .changeset/open-beds-grab.md
- packages/qwik/src/core/client/vnode-diff.ts
- packages/qwik/src/core/client/vnode-namespace.ts
- packages/qwik/src/core/shared/utils/markers.ts
- packages/qwik/src/core/tests/render-namespace.spec.tsx
few SVG attributes can have different namespaces
> fix: render SVG attributes with correct namespace

- packages/qwik/package.json
- packages/qwik/src/optimizer/src/manifest.ts
- packages/qwik/src/optimizer/src/plugins/plugin.ts
- scripts/submodule-preloader.ts
- Bug
Certain environements can't use preloader.mjs (e.g. jest 29 and below). So until we decide to officially not support cjs anymore, we need to also output the preloader as `.cjs`.
> fix: qwikloader.cjs missing in non esm environments

- .changeset/heavy-maps-wash.md
- e2e/adapters-e2e/src/routes/loaders/index.tsx
- e2e/adapters-e2e/src/routes/loaders/subpage/index.tsx
- e2e/adapters-e2e/tests/express.spec.ts
- packages/qwik-router/src/runtime/src/server-functions.ts
- packages/qwik/src/core/internal.ts
- packages/qwik/src/core/qwik.core.api.md
- packages/qwik/src/core/use/use-context.ts
We should not use $$ varaibles cross-packages, because they can be minified
> fix: getting invoke context for loaders in production

- packages/qwik/src/optimizer/src/plugins/plugin.ts
- Bug
`invalidateModule` is used for HMR in Vite `handleHotUpdate` hook. It was added in https://github.com/QwikDev/qwik/commit/a69de93ef5d2ebf1ae3a92c18879fafcb3d86cbd in an attempt to make sure that QRLs also get updated on parent changes.
The problem is that this causes cypress component tests (CCTs) to be 10x slower, eventually leading to CCTs startup timing out with a "Error: Code(5): You can render over a existing q:container. Skipping render()." message.
I tried many possible combinations of updating the child, the parent, the jsx, the useVisibleTask, the useTask, the QRL outside of the component... I haven't been able to trigger a case where the `invalidateModule` in the `transform` hook with the optimizer would ever run.
What seems to happen is that the `handleHotUpdate` hook …
> fix: invalidate module in createQwikPlugin slows down cypress component tests

- .changeset/every-socks-beg.md
- packages/qwik-city/src/buildtime/build-layout.unit.ts
- packages/qwik-city/src/runtime/src/qwik-city-component.tsx
- starters/apps/qwikcity-test/src/routes/issue-route-with-search-params-and-action-redirect-without-search-params/action-redirect-without-search-params-target/index.tsx
- starters/apps/qwikcity-test/src/routes/issue-route-with-search-params-and-action-redirect-without-search-params/action-redirect-without-search-params/index.tsx
- starters/apps/qwikcity-test/src/routes/issue7732/a/index.tsx
- starters/apps/qwikcity-test/src/routes/issue7732/b/index.tsx
- starters/apps/qwikcity-test/src/routes/issue7732/c/index.tsx
- starters/apps/qwikcity-test/src/routes/issue7732/layout.tsx
- starters/e2e/qwikcity/nav.spec.ts
- Bug
Fixes https://github.com/QwikDev/qwik/issues/7732
> fix(qwik-city): link/useNavigate query params override thrown redirect's in loader/middleware

- packages/eslint-plugin-qwik/src/validLexicalScope.ts
- Bug
[valid-lexical-scope](https://github.com/QwikDev/qwik/blob/7bb5229c187a7b0c92e37ed4a8f9d6c97bab8026/packages/eslint-plugin-qwik/src/validLexicalScope.ts#L31) rule currently allows extra properties to be passed in options object, which should not be allowed. This makes it easier for typos in rule options to go unnoticed.
This PR simply disallows extra properties in this rule's schema.
> fix: disallow extra properties in rule options

- .changeset/angry-boats-lose.md
- packages/docs/src/routes/docs/cookbook/view-transition/index.mdx
- packages/qwik-router/src/runtime/src/qwik-router-component.tsx
- Bug
Change the name of the view transition type in the default CSS style to prevent default view transition between pages
> fix(view-transition): rename qwik-router-spa to qwik-navigation

- .changeset/tiny-cows-pick.md
- packages/qwik/src/core/shared/component-execution.ts
- packages/qwik/src/core/shared/utils/types.ts
- packages/qwik/src/core/tests/use-on.spec.tsx
- packages/qwik/src/core/tests/use-visible-task.spec.tsx
Correctly handle a case where only primitve value is returned from component
> fix: use on events for headless components

- packages/docs/src/routes/docs/integrations/postcss/index.mdx
- starters/features/postcss/postcss.config.js
- Bug
I created a project using the `npm create` Qwik City starter.
Then, after following the PostCSS integration guide, trying to run `npm start` will throw an error:
```
[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /demo): [ReferenceError] module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '\demo\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: module is not defined in ES module scope
```
- fix(postcss): update `postcss.config.js` to ESM syntax
- docs(postcss): update PostCSS integration docs to reflect ESM config
> fix(postcss): use ESM syntax for postcss.config.js

- .changeset/flat-hounds-burn.md
- packages/docs/src/routes/api/qwik-router/api.json
- packages/docs/src/routes/api/qwik-router/index.mdx
- packages/docs/src/routes/docs/(qwikrouter)/api/index.mdx
- packages/qwik-router/src/runtime/src/document-head-tags-component.tsx
- packages/qwik-router/src/runtime/src/head.ts
- packages/qwik-router/src/runtime/src/index.ts
- packages/qwik-router/src/runtime/src/qwik-router.runtime.api.md
- packages/qwik-router/src/runtime/src/types.ts
- starters/apps/empty/src/components/router-head/router-head.tsx
- starters/apps/empty/src/root.tsx
- starters/apps/playground/src/components/router-head/router-head.tsx
- starters/apps/playground/src/root.tsx
- starters/apps/qwikrouter-test/src/components/router-head/router-head.tsx
This component renders the head tags from `head` exports correctly, including the scripts that were added later.
This reduces mistakes and makes the starters cleaner.
Furthermore, the styles and scripts types now allow setting props directly, which is like meta and links.
> feat: <DocumentHeadTags />

- packages/docs/src/repl/repl.tsx
Fix up this issue in the repl
```
Error: No URL given for dep: @builder.io/qwik/dist/preloader.mjs at m
(https://xxxx.dev/repl/repl-sw.js:1:286)
at Object.load (https://xxxx.dev/repl/repl-sw.js:1:3475)
at eval (eval at w (https://xxxx.dev/repl/repl-sw.js:1:626),
<anonymous>:12:372180)
```
> docs: fix up repl issue 🥗

- .changeset/early-eels-listen.md
- packages/qwik-city/src/runtime/src/sw-register.ts
- packages/qwik/src/core/components/prefetch.ts
- Bug
The service-workers components were not unregistering.
I checked that this works for both on a small repro.
> fix: service-worker.js and qwik-prefetch-service-worker.js unregistering

- packages/qwik/src/optimizer/src/manifest.ts
- packages/qwik/src/optimizer/src/plugins/plugin.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/optimizer/src/plugins/vite.unit.ts
I overrode vite with rolldown-vite and then fixed the types. It doesn't manage to build docs though, but at least the types won't impede progress.
> fix(build): make types rolldown-vite compatible

- .changeset/solid-olives-know.md
- packages/qwik/src/core/internal.ts
- packages/qwik/src/core/qwik.core.api.md
- packages/qwik/src/core/shared/jsx/jsx-runtime.ts
- packages/qwik/src/core/tests/attributes.spec.tsx
- packages/qwik/src/core/tests/component.spec.tsx
- packages/qwik/src/core/tests/use-task.spec.tsx
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_jsx.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_props_optimization.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__example_spread_jsx.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_destructure_args.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop2.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop3.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop4.snap
- packages/qwik/src/optimizer/core/src/snapshots/qwik_core__test__should_split_spread_props_with_additional_prop5.snap
- packages/qwik/src/optimizer/core/src/test.rs
- packages/qwik/src/optimizer/core/src/transform.rs
- packages/qwik/src/optimizer/core/src/words.rs
- starters/e2e/e2e.render.e2e.ts
Spread props caused calling get trap for every props property. It means propsproxy will unwrap signals and pass flat value instead. Now we are using new _getVarProps, _getConstProps functions to direct get props object instead of using proxy
> fix: reactivity after spreading props

- packages/qwik/src/optimizer/src/plugins/plugin.ts
- starters/e2e/qwikcity/nav.spec.ts
when overriding vite with npm:rolldown-vite, dev mode hangs
thanks to @sapphi-red
> fix(vite): deadlock in rolldown-vite

- packages/docs/src/components/code-block/code-block.tsx
- packages/qwik/src/optimizer/src/manifest.ts
- packages/qwik/src/optimizer/src/plugins/plugin.ts
make it possible to run docs with rolldown-vite
However, editor still breaks on Prism missing from imports
> fix(rolldown): some fixes for rolldown-vite

- packages/docs/src/components/code-block/code-block.tsx
with this change, everything seems to work when you use rolldown-vite instead of vite.
The previous code was triggering a [bug in rolldown](https://github.com/rolldown/rolldown/issues/5731) and this way is cleaner anyway.
> chore(docs): cleaner prism importing for rolldown

- .changeset/sixty-rockets-clean.md
- packages/qwik-city/src/runtime/src/client-navigate.ts
- packages/qwik-city/src/runtime/src/link-component.tsx
- packages/qwik-city/src/runtime/src/use-endpoint.ts
- Bug
Fixes https://github.com/QwikDev/qwik/issues/7834 to some extent. There are still bundling issues leading to over-prefetching on click left.
This speeds up SPA Link navigation by preloading the next route bundles on click.
> feat(qwik-city): Link SPA – preload route bundles with max probability on click

- .changeset/hot-buses-strive.md
- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
> fix: hoisted transitive imports mess up the bundle-graph static imports graph

- packages/create-qwik/src/run-create-interactive-cli.ts
> fix(create): clean up tmp folder before exit 😸

- .changeset/thin-horses-bake.md
- packages/qwik-city/src/buildtime/runtime-generation/generate-service-worker.ts
- packages/qwik-city/src/buildtime/vite/plugin.ts
- packages/qwik-city/src/runtime/src/sw-component.tsx
- packages/qwik-city/src/runtime/src/sw-register.ts
Close https://github.com/QwikDev/qwik/issues/7856
- Bug
Now custom service-worker implementation will keep working, while projects that removed their service-worker.ts files will unregister their service-worker.js and related cache.
> fix(qwik-city): custom service-worker.ts code is also being unregistered

- .changeset/mean-tires-cover.md
- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.mdx
- packages/qwik/src/core/qwik.core.api.md
- packages/qwik/src/core/reactive-primitives/signal.public.ts
- packages/qwik/src/core/tests/use-async-computed.spec.tsx
- packages/qwik/src/testing/rendering.unit-util.tsx
Expose (hidden until now) `loading` and `error` fields of async computed signal
> feat: expose loading and error fields of async computed signal

- .changeset/twelve-words-jump.md
- packages/qwik/src/core/preloader/preloader.unit.ts
- packages/qwik/src/core/preloader/queue.ts
It's better to have this value be constant, otherwise it is hard for the developer to control it. 
Also increased the ssrPreloads limit (before bundle-graph is loaded) to 5 since 2 seems like it can create a lot of waterfalls no? (I didn't benchmark this ^^)
> refactor: set maxIdlePreloads to be constant over time

- .changeset/shy-shirts-glow.md
- packages/qwik/src/core/client/dom-container.ts
- packages/qwik/src/core/client/vnode.ts
- packages/qwik/src/core/tests/projection.spec.tsx
Find the correct parent dom element from projected content
> fix: finding parent dom element from projected content

- .changeset/lemon-dingos-dance.md
- packages/docs/src/repl/worker/repl-dependencies.ts
- packages/docs/vite.config.ts
- packages/qwik-router/src/ssg/worker-thread.ts
- packages/qwik/src/core/index.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- packages/qwik/src/optimizer/src/plugins/vite.unit.ts
- starters/dev-server.ts
- starters/e2e/e2e.use-id.e2e.ts
v2 version of #7109 with vendorRoots removal, but not throwing
> chore: warn when importing core twice

- .changeset/curvy-glasses-wash.md
- packages/qwik-city/src/middleware/request-handler/resolve-request-handlers.ts
Previously, two CSRF middlewares were added for lax-proto requests: one at the beginning and one at the end. This change replaces them with a single middleware placed at the beginning. Non-lax-proto cases remain unchanged.
- Bug
fix behaviour of checkOrigin: "lax-proto" in createQwikCity
> fix: compare URLs without protocols with checkOrigin: lax-proto 

- packages/docs/src/routes/api/qwik/api.json
- packages/docs/src/routes/api/qwik/index.mdx
- packages/qwik/src/core/index.ts
- packages/qwik/src/core/qwik.core.api.md
- packages/qwik/src/core/shared/jsx/utils.public.ts
- packages/qwik/src/core/ssr/ssr-render-jsx.ts
- packages/qwik/src/core/tests/ssr-render.spec.tsx
Adding test for ssrstream together with ssrraw
> test: add ssrstream with ssrraw unit test

- .changeset/ten-emus-jog.md
- packages/docs/src/routes/playground/parser/html/index.tsx
- packages/qwik/src/core/client/process-vnode-data.ts
- packages/qwik/src/core/client/process-vnode-data.unit.tsx
- packages/qwik/src/testing/document.ts
Pass first child of shadow root's as container. In other case the tree walker returns the same container element for nextNode function.
> fix: resuming nested container in shadow root

- .changeset/some-oranges-open.md
- .github/workflows/ci.yml
- package.json
this is a continuation of previos PR https://github.com/QwikDev/qwik/pull/7950 (forgot to add test runs to ci)
add test runs to ci
> ci: add qwik react e2e tests run to ci

- .changeset/fifty-dots-wonder.md
- packages/qwik-city/src/adapters/shared/vite/index.ts
Implement a workaround to address the issue where the SSG process hangs after completion by forcibly exiting the process after a delay.
> fix(qwik-city): force exit on SSG hang

- packages/docs/src/routes/examples/apps/partial/hackernews-index/app.tsx
- packages/docs/src/routes/examples/apps/reactivity/counter/app.tsx
- packages/docs/src/routes/examples/apps/reactivity/task/app.tsx
- packages/qwik/src/core/render/ssr/render-ssr.ts
- packages/qwik/src/core/render/ssr/render-ssr.unit.tsx
use signals in the playground examples, and a possible fix for old safari mobile clients
fixes #7140
> Small things

- packages/docs/src/repl/ui/monaco.tsx
- packages/qwik/src/core/render/jsx/types/jsx-types.unit.tsx
Without this we get type errors on style objects
> fix(repl): CSS types

- .changeset/clean-bears-cough.md
- package.json
- packages/qwik/package.json
- packages/qwik/src/optimizer/src/plugins/rollup.ts
- packages/qwik/src/optimizer/src/plugins/utils.ts
- packages/qwik/src/optimizer/src/plugins/vite.ts
- pnpm-lock.yaml
- Bug
Fixes #7882
Installs Rollup 4.52 and marks it as a peer dep. Warns the developers that they should update to get the new `output.onlyExplicitManualChunks` feature working on their project.
The first bundle won't get non specified dependencies merged into its manualChunk anymore. This reduces over-preloading for that bundle and cache invalidation.
See https://github.com/rollup/rollup/pull/6087 for more info on `onlyExplicitManualChunks`.
We can remove this code when we'll update qwik to Rollup 5.
> fix: over-preloading due to inaccurate bundle-graph static import graph

- .changeset/some-emus-fly.md
- packages/docs/src/routes/docs/(qwikrouter)/pages/index.mdx
- packages/qwik-router/src/runtime/src/head.ts
- packages/qwik-router/src/runtime/src/head.unit.ts
The current way of merging head objects is surprising, like #7868.
This PR changes it to merge objects in the unsurprising order, but keep merging functions in the original order.
> feat(router): [breaking] change head merge order

- .changeset/pre.json
- e2e/docs-e2e/package.json
This fixes the release automation that was broken by trying to release a private package. 
Note for next time (for PR reviewers) - notice that there's no version for private packages.
> fix: removed version from docs-e2e

- .changeset/config.json
- .changeset/real-chefs-teach.md
- Bug
- Infra
qwik-react was in the ignore list of changesets, making it impossible to select in the changeset menu when generating a new change. 
This fixes it and also redo the changeset from #7865 to make sure the qwik-react package gets properly released with the new updates.
> removed qwik-react from changesets ignore

- .github/workflows/ci.yml
EDIT - Hmm actually the windows tests have started working again... keeping draft for a bit
> fix(ci): use windows-2022 instead of latest

- packages/docs/src/routes/api/qwik-city-middleware-node/index.mdx
Close #8018
- Docs
- getOrigin is an optional function on QwikCityNodeRequestOptions that returns the public origin (scheme + host + optional port) for an incoming request. The middleware uses this origin to resolve relative URLs and to validate request origins (CSRF checks).
- Addressing the open issue #8018 
- *[x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ *] I performed a self-review of my own code
- [* ] I made corresponding changes to the Qwik docs
> docs: add getOrigin callback
